import { type AppActionType } from '#/utils/handlerContract';

// Generated from the AppAction discriminated union. This runtime allowlist is
// the serialized Command boundary's exact top-level argument contract.
export const versionedCommandArgumentKeys: Readonly<Record<AppActionType, readonly string[]>> = {
    addAdjustmentRegion: [
        'blend',
        'endBeat',
        'expectedLayer',
        'expectedTracks',
        'fadeInBeats',
        'fadeOutBeats',
        'layerId',
        'regionId',
        'sourceRegionId',
        'sourceSection',
        'startBeat',
        'targetSection',
    ],
    addAutomationLane: ['laneId', 'parameterId', 'parameterName', 'trackId'],
    addAutomationPoint: ['beat', 'cp1', 'cp2', 'curve', 'laneId', 'pointId', 'stairSteps', 'tension', 'value'],
    addChordEvent: ['beat', 'duration', 'eventId', 'quality', 'root'],
    addClip: [
        'assetHash',
        'audioBufferId',
        'audioOffsetBeats',
        'color',
        'endBeat',
        'fadeInBeats',
        'fadeOutBeats',
        'followAction',
        'gain',
        'id',
        'isGhost',
        'locked',
        'loopEnabled',
        'loopLength',
        'midiOffsetBeats',
        'muted',
        'name',
        'startBeat',
        'stretchMode',
        'stretchRatio',
        'trackId',
        'type',
    ],
    addCvOutput: ['channel', 'name', 'type'],
    addDevice: ['afterDeviceId', 'deviceId', 'deviceType', 'expectedDeviceIds', 'expectedFrozen', 'trackId'],
    addMarker: ['beat', 'color', 'markerId', 'name'],
    addNotes: ['clipId', 'notes'],
    addSection: ['color', 'endBeat', 'name', 'sectionId', 'startBeat'],
    addSend: ['busId', 'expectedAbsent', 'level', 'preFader', 'trackId'],
    addSidechainRoute: ['gain', 'routeId', 'sourceTrackId', 'targetDeviceId', 'targetParameterId', 'targetTrackId'],
    addTimeSignatureChange: ['beat', 'denominator', 'numerator'],
    addTrack: ['color', 'id', 'initialAlternativeId', 'kind', 'name', 'select'],
    analyzeMix: [],
    applyGroove: ['amount', 'clipId', 'grooveId'],
    armTrack: [
        'armed',
        'expectedMidiInputOwnerId',
        'expectedMidiInputTrackId',
        'midiInputOwnerId',
        'midiInputTrackId',
        'trackId',
    ],
    arpeggiate: [
        'addedNotes',
        'clipId',
        'clipName',
        'expectedClipLocked',
        'expectedNotes',
        'expectedTrackFrozen',
        'expectedTrackId',
        'gate',
        'octaves',
        'pattern',
        'rate',
        'trackName',
    ],
    assignGrooveTemplate: ['amount', 'consumerId', 'consumerType', 'templateId'],
    assignToVca: ['trackId', 'vcaGroupId'],
    audioToMidi: ['clipId', 'mode', 'sensitivity', 'trackId'],
    autoFixMix: [],
    automateSendRange: [
        'busId',
        'busName',
        'endBeat',
        'expectedSection',
        'expectedSends',
        'reductionDb',
        'sectionId',
        'sectionName',
        'startBeat',
        'trackIds',
    ],
    automateSendRanges: [
        'busId',
        'busName',
        'expectedTimeSignature',
        'expectedTracks',
        'ranges',
        'sectionIds',
        'tailBars',
        'targetLevelDb',
        'trackIds',
    ],
    automateTrackGainRange: [
        'endBeat',
        'expectedSection',
        'expectedTracks',
        'gainDb',
        'sectionId',
        'sectionName',
        'startBeat',
        'trackIds',
    ],
    autoOrganizeProject: ['tracks'],
    bounceInPlace: ['trackId'],
    bounceSelection: ['endBeat', 'startBeat', 'trackId'],
    bounceToNewTrack: ['trackId'],
    bypassDevice: ['bypassed', 'deviceId'],
    captureScratchPad: [],
    clearAllMidiMappings: [],
    clearChordTrack: [],
    clearMidiOutput: ['trackId'],
    clearScratchPad: [],
    clearSolos: [],
    closeElasticEditor: [],
    closeMixer: [],
    commitPitchEdit: ['clipId', 'contour', 'segments'],
    commitScratchPad: [],
    compareToReference: [],
    completeMidi: ['bars', 'clipId', 'direction'],
    connectPush: ['model'],
    consolidateAllTracks: [],
    consolidateSelection: ['endBeat', 'startBeat', 'trackId'],
    copyClip: [],
    copyMidiArticulations: [
        'expectedSourceClipLocked',
        'expectedSourceNotes',
        'expectedTargetClipLocked',
        'expectedTargetNotes',
        'expectedTrackFrozen',
        'notePairs',
        'sourceClipId',
        'targetClipId',
        'trackId',
    ],
    createAdjustmentLayer: ['effectType', 'layerId', 'name'],
    createBus: [
        'busId',
        'color',
        'expectedAbsentTrackNames',
        'expectedTrackOutputs',
        'initialAlternativeId',
        'initialGain',
        'name',
    ],
    createCollabSession: ['name'],
    createCompGroup: ['name', 'trackIds'],
    createDrumPreviewBranches: [
        'candidateCount',
        'candidates',
        'createdAt',
        'expectedBranchState',
        'expectedDocuments',
        'expectedSourceBranchId',
        'expectedSourceHeads',
        'hiHat',
        'kick',
        'ownerId',
        'sectionEndBeat',
        'sectionId',
        'sectionName',
        'sectionStartBeat',
        'snare',
        'varyingRoles',
    ],
    createFolder: ['name'],
    createGrooveTemplate: ['id', 'name', 'provenance', 'slots', 'subdivision'],
    createPatternInstance: ['sourceClipId', 'startBeat', 'targetTrackId'],
    createProjectFromTemplate: ['templateId'],
    createProjectVersion: ['description', 'label'],
    createTrackAlternative: ['alternativeId', 'duplicateActive', 'name', 'trackId'],
    createVcaGroup: ['name', 'trackIds', 'vcaGroupId'],
    createVersionBranch: ['name'],
    crossfadeClips: ['clipAId', 'clipBId', 'durationBeats'],
    cutClip: [],
    deleteDrumPreviewBranches: ['branches', 'expectedSourceBranchId', 'ownerId'],
    deleteGrooveTemplate: ['templateId'],
    deleteMacro: ['macroId'],
    deleteTime: ['endBeat', 'startBeat'],
    deleteTrackAlternative: ['alternativeId', 'fallbackAlternativeId', 'trackId'],
    deleteTrackTemplate: ['templateId'],
    detachPatternInstance: ['clipId'],
    detectKey: ['clipId'],
    detectSongStructure: ['trackId'],
    detectTempo: ['clipId'],
    detectTransients: ['clipId', 'sensitivity'],
    disableMpe: [],
    disableTrack: ['disabled', 'trackId'],
    discardCreatedTrack: ['generatedMidiStateGuard', 'trackId'],
    discardDuplicatedClip: ['clipId', 'generatedMidiStateGuard'],
    discardImportedStemSet: ['folderId', 'guards', 'stemTrackIds'],
    disconnectPush: [],
    duplicateClip: ['clipId', 'targetClipId'],
    duplicateClipToNextBar: ['clipId', 'targetClipId'],
    duplicateTimeRange: ['endBeat', 'startBeat'],
    duplicateTrack: ['select', 'targetTrackId', 'trackId'],
    elasticAddMarker: ['clipId', 'localBeat'],
    elasticRemoveMarker: ['markerId'],
    elasticSetSensitivity: ['sensitivity'],
    elasticSetTool: ['tool'],
    elasticToggleMarkerLock: ['markerId'],
    enableMpe: [],
    enableWarping: ['clipId'],
    exportDawProject: [],
    exportMidi: ['clipId'],
    exportProject: [],
    extractGroove: ['clipId', 'proposal', 'sourceName', 'sourceRevision', 'subdivision', 'templateId'],
    fitClipToBeats: ['clipId', 'targetBeats'],
    flattenTrack: ['trackId'],
    foldTrack: ['folded', 'trackId'],
    freezeTrack: ['trackId'],
    generateAllTransitions: [],
    generateAudio: ['durationSeconds', 'prompt', 'trackId'],
    generateBassline: ['clipId', 'style', 'trackId'],
    generateChordProgression: ['bars', 'key', 'scale', 'seed', 'startBeat', 'style', 'trackId', 'voicing'],
    generateDrumPattern: ['bars', 'density', 'seed', 'startBeat', 'style', 'trackId'],
    generateFill: ['atBeat', 'durationBeats', 'style'],
    generateMelody: ['bars', 'density', 'key', 'octave', 'scale', 'seed', 'startBeat', 'style', 'trackId'],
    getLatencyReport: [],
    getMentorTips: [],
    glueClips: ['clipIds', 'expected', 'replacement', 'targetClipId'],
    groupTracks: ['name', 'trackIds'],
    hideTrack: ['hidden', 'trackId'],
    humanizeNotes: ['amount', 'clipId', 'seed', 'velocityAmount'],
    importAudioFile: [],
    importDawProject: [],
    importMidiFile: [],
    importStemSet: [
        'folderAlternativeId',
        'folderColor',
        'folderId',
        'groupName',
        'projectTempo',
        'selectionId',
        'stems',
    ],
    insertTime: ['atBeat', 'durationBeats'],
    invertAutomation: ['laneId'],
    invertNotes: ['clipId'],
    joinCollabSession: ['inviteString', 'peerName'],
    labelUndoBranch: ['label', 'nodeId'],
    leaveCollabSession: [],
    loadExternalPlugin: ['pluginId', 'trackId'],
    loadPreset: ['presetId', 'trackId'],
    loadRaveModel: ['modelId'],
    loadTrackTemplate: ['templateId'],
    lockClip: ['clipId', 'expectedLocked', 'locked'],
    moveAdjustmentRegion: ['endBeat', 'regionId', 'startBeat'],
    moveChordEvent: ['beat', 'eventId'],
    moveClip: ['clipId', 'startBeat', 'trackId'],
    muteClip: ['clipId', 'expectedMuted', 'muted'],
    muteTrack: ['expectedMuted', 'muted', 'trackId'],
    newProject: [],
    nextSetlistItem: [],
    normalizeClip: ['clipId', 'mode', 'targetDb'],
    nudgeClip: ['beats', 'clipId'],
    openElasticEditor: ['clipId'],
    openMixer: [],
    openPreferencesDialog: [],
    pasteClip: [],
    playMacro: ['macroId'],
    previousSetlistItem: [],
    quantizeAutomation: ['gridSize', 'laneId'],
    quantizeNoteLengths: ['clipId', 'gridSize'],
    quantizeNotes: ['clipId', 'gridSize', 'strength', 'swing'],
    quantizeTransients: ['clipId'],
    redo: [],
    removeAdjustmentLayer: ['layerId'],
    removeAdjustmentRegion: ['expectedRegion', 'expectedTracks', 'layerId', 'regionId'],
    removeAllTracks: [],
    removeAutomationLane: ['laneId'],
    removeAutomationPoint: ['laneId', 'pointId', 'pointIndex'],
    removeChordEvent: ['eventId'],
    removeClip: ['clipId'],
    removeDevice: ['deviceId', 'expectedDeviceIds', 'expectedTrackId'],
    removeFromVca: ['trackId'],
    removeMarker: ['markerId'],
    removeRenderedProjectSections: ['jobs', 'sectionIds'],
    removeSection: ['sectionId'],
    removeSend: ['busId', 'expectedLevel', 'expectedPreFader', 'trackId'],
    removeSendAutomationRange: [
        'busId',
        'busName',
        'endBeat',
        'expectedSection',
        'expectedSends',
        'reductionDb',
        'sectionId',
        'sectionName',
        'startBeat',
        'trackIds',
    ],
    removeSendAutomationRanges: [
        'busId',
        'busName',
        'expectedTimeSignature',
        'expectedTracks',
        'ranges',
        'sectionIds',
        'tailBars',
        'targetLevelDb',
        'trackIds',
    ],
    removeShortMidiOverlaps: [
        'clipId',
        'clipName',
        'expectedClipLocked',
        'expectedNotes',
        'expectedTempo',
        'expectedTrackFrozen',
        'expectedTrackId',
        'maximumOverlapMs',
        'trackName',
    ],
    removeSidechainRoute: ['gain', 'routeId', 'sourceTrackId', 'targetDeviceId', 'targetParameterId', 'targetTrackId'],
    removeTimeSignatureChange: ['beat'],
    removeTrack: [
        'expectedAlternativeClipIds',
        'expectedClipIds',
        'expectedKind',
        'expectedMuted',
        'expectedVcaGroupId',
        'expectedVcaMembershipGroupIds',
        'trackId',
    ],
    removeTrackGainAutomationRange: [
        'endBeat',
        'expectedSection',
        'expectedTracks',
        'gainDb',
        'sectionId',
        'sectionName',
        'startBeat',
        'trackIds',
    ],
    renameClip: ['clipId', 'name'],
    renameGrooveTemplate: ['name', 'templateId'],
    renameMacro: ['macroId', 'name'],
    renameSection: ['name', 'sectionId'],
    renameTrack: ['name', 'trackId'],
    renameTrackAlternative: ['alternativeId', 'name', 'trackId'],
    renderProjectSections: ['jobs', 'sectionIds'],
    reorderTrack: ['newIndex', 'trackId'],
    replayGeneratedMidi: ['operation'],
    restoreAdjustmentLayerMutation: ['expectedLayersFingerprint', 'freezeTransitions', 'layers'],
    restoreAutomationLanePoints: ['expectedPoints', 'laneId', 'points'],
    restoreChordTrackState: ['expected', 'replacement'],
    restoreClip: [
        'clipId',
        'clipSnapshot',
        'midiCcSnapshot',
        'midiNotesSnapshot',
        'midiPitchBendSnapshot',
        'ripplePlan',
        'trackId',
    ],
    restoreClipFileId: ['clipId', 'fileId'],
    restoreClipGlueState: ['expected', 'replacement'],
    restoreClipLoop: ['clipId', 'expected', 'replacement'],
    restoreClipLoopLength: ['clipId', 'expected', 'replacement'],
    restoreClipPlacement: ['clipId', 'expected', 'replacement'],
    restoreClipSplitState: ['clipId', 'expected', 'replacement', 'rightClipId'],
    restoreClipStretchState: ['clipId', 'expected', 'replacement'],
    restoreCrossfadeClips: ['clipAId', 'clipBId', 'expected', 'replacement'],
    restoreDeletedGrooveTemplate: ['assignments', 'template', 'templateIndex'],
    restoreDevice: ['batchRestoreDevices', 'deviceIndex', 'deviceSnapshot', 'expectedDeviceIds', 'trackId'],
    restoreGrooveAssignment: ['assignment', 'consumerId', 'consumerType', 'expectedAssignment'],
    restoreGrooveTemplateName: ['expectedName', 'name', 'templateId'],
    restoreLegacyVcaState: ['groupGains', 'groupMemberships', 'groupRows', 'trackMemberships'],
    restoreLoopRegion: ['isLooping', 'loopEnd', 'loopStart'],
    restoreMasterGain: ['expectedPercent', 'replacementPercent'],
    restoreMidiClipNotes: [
        'allowMissingExpectedEmpty',
        'articulationReplayGuard',
        'clipId',
        'expectedNotes',
        'noteTransformReplayGuard',
        'notes',
    ],
    restoreProjectVersion: ['versionId'],
    restorePunchRegion: ['expected', 'replacement'],
    restoreSoloSafe: ['expected', 'replacement', 'trackId'],
    restoreTrack: [
        'automationLaneSnapshots',
        'batchRestoreTracks',
        'incomingModulationMappingSnapshots',
        'midiCcByClipId',
        'midiNotesByClipId',
        'midiPitchBendByClipId',
        'ownedModulatorSnapshots',
        'routingPatches',
        'sidechainRouteSnapshots',
        'takeLaneSnapshots',
        'trackGain',
        'trackId',
        'trackIndex',
        'trackKind',
        'trackName',
        'trackParentId',
        'trackSnapshot',
        'wasSelected',
    ],
    restoreTrackSoloStates: ['expected', 'replacement'],
    retrogradeNotes: ['clipId'],
    reverseAutomation: ['laneId'],
    reverseClip: ['clipId'],
    savePreset: ['category', 'name', 'trackId'],
    saveProject: [],
    saveTrackTemplate: ['category', 'name', 'trackId'],
    scaleAllVelocities: ['clipId', 'factor'],
    scaleAutomation: ['anchor', 'factor', 'laneId'],
    scaleVelocities: ['clipId', 'curve', 'maxVelocity', 'minVelocity'],
    scanPlugins: [],
    searchSamples: ['query'],
    seekPlayhead: ['beat'],
    selectTrack: ['trackId'],
    setAllVelocities: ['clipId', 'velocity'],
    setAutomationLaneEnabled: ['enabled', 'laneId'],
    setAutomationMode: ['expectedMode', 'mode', 'trackId'],
    setClipColor: ['clipId', 'color', 'expectedColor'],
    setClipFade: ['clipId', 'expectedFadeInBeats', 'expectedFadeOutBeats', 'fadeInBeats', 'fadeOutBeats'],
    setClipGain: ['clipId', 'gain'],
    setClipLoop: ['clipId', 'enabled'],
    setClipLoopLength: ['clipId', 'loopLength'],
    setClipStretchMode: ['clipId', 'mode'],
    setClipStretchRatio: ['clipId', 'ratio'],
    setControlSurface: ['protocol'],
    setCountInBars: ['bars'],
    setDeviceParameter: [
        'deleteParameter',
        'deviceId',
        'expectedDeviceIds',
        'expectedDeviceType',
        'expectedTrackFrozen',
        'expectedTrackId',
        'expectedValue',
        'expectedValuePresent',
        'paramId',
        'value',
    ],
    setDeviceState: ['deviceId', 'state'],
    setEditingTool: ['tool'],
    setExternalPluginState: ['deviceId', 'stateChunk'],
    setLayerAffectedTracks: ['layerId', 'trackIds'],
    setLayerFades: ['fadeInBeats', 'fadeOutBeats', 'regionId'],
    setLayerInsertionIndex: ['insertionIndex', 'layerId'],
    setLayerMix: ['layerId', 'mix'],
    setLayerParameter: ['layerId', 'paramName', 'value'],
    setLoopEnabled: ['enabled'],
    setLoopRegion: ['endBeat', 'startBeat'],
    setMarkerColor: ['color', 'markerId'],
    setMarqueeSelection: ['selection'],
    setMasterGain: ['gain'],
    setMetronomeEnabled: ['enabled'],
    setMetronomeVolume: ['volume'],
    setMidiOutput: ['destinationTrackId', 'trackId'],
    setPlayback: ['playing'],
    setPreRollBars: ['bars'],
    setProductionBrief: ['brief', 'expectedRevision'],
    setPunchEnabled: ['enabled', 'expectedEnabled'],
    setPunchIn: ['beat'],
    setPunchOut: ['beat'],
    setRaveBlend: ['blend'],
    setSend: ['busId', 'expectedLevel', 'expectedPreFader', 'level', 'trackId'],
    setSnapValue: ['value'],
    setSoloSafe: ['soloSafe', 'trackId'],
    setTempo: ['bpm', 'tempoChangeId'],
    setTimeSignature: ['denominator', 'numerator'],
    setTrackColor: ['color', 'trackId'],
    setTrackGain: ['expectedGain', 'gain', 'trackId'],
    setTrackHeight: ['height', 'trackId'],
    setTrackInput: ['inputId', 'trackId'],
    setTrackNotes: ['notes', 'trackId'],
    setTrackOutput: ['expectedOutputId', 'outputId', 'trackId'],
    setTrackPan: ['expectedPan', 'pan', 'trackId'],
    setVcaGain: ['gain', 'vcaGroupId'],
    setWarpAlgorithm: ['algorithm', 'clipId'],
    setWarpPitchShift: ['clipId', 'semitones'],
    setWorkspaceMode: ['mode'],
    soloTrack: ['soloed', 'trackId'],
    splitClip: ['beat', 'clipId', 'resolvedBeat', 'rightClipId', 'targetNoteIds'],
    startMacroRecording: [],
    stemSeparate: ['clipId', 'stems'],
    stopMacroRecording: ['name'],
    stopPlayback: [],
    stretchAutomation: ['anchorBeat', 'factor', 'laneId'],
    stripSilence: ['clipId', 'minDuration', 'threshold'],
    switchMonitor: ['monitorId'],
    switchTrackAlternative: ['alternativeId', 'trackId'],
    thinAutomation: ['laneId', 'tolerance'],
    toggleAdjustmentLayer: ['layerId'],
    toggleChatPanel: [],
    toggleChordTrack: ['enabled'],
    toggleControlRoomDim: [],
    toggleControlRoomMono: [],
    toggleCountIn: [],
    toggleInspector: [],
    toggleLoop: [],
    toggleLoopRecord: ['slotId'],
    toggleMetronome: [],
    toggleNodeView: [],
    togglePlayback: [],
    togglePreRoll: [],
    togglePunch: [],
    togglePunchRecording: [],
    toggleRecording: [],
    toggleScratchPad: [],
    toggleSidebar: [],
    toggleSoloSafe: ['trackId'],
    toggleUndoTree: [],
    transposeNotes: ['clipId', 'semitones'],
    triggerScene: ['column'],
    trimClipEnd: ['clipId', 'newEndBeat'],
    trimClipStart: ['clipId', 'newStartBeat'],
    undo: [],
    unfreezeTrack: ['trackId'],
    ungroupTracks: ['groupId'],
    updateChordEvent: ['duration', 'eventId', 'quality', 'root'],
    variationMidi: ['amount', 'clipId'],
    zoomToFit: [],
    zoomToSelection: [],
    zoomTracksVertical: ['delta'],
};
