[workspace]
members = [
    "crates/daw-core",
    "crates/daw-collab",
    "crates/daw-engine",
    "crates/daw-dsp",
    "crates/daw-io",
    "crates/daw-wasm-decoder",
    "crates/daw-plugin-host",
    "crates/proof-chamber",
    "crates/scoring",
    "src-tauri"
]
resolver = "2"

[profile.release]
opt-level = 3
lto = false
codegen-units = 16
split-debuginfo = "unpacked"
