// @ts-check
// Standalone ESLint config for Sourdaw — React 19 + Compiler, TypeScript, Tailwind v4.
// Cherry-picked from @frontify/eslint-config-{basic,react}, with broken plugins removed
// and rules tuned for a DAW application.

import eslint from '@eslint/js';
import eslintPluginReact from '@eslint-react/eslint-plugin';
import eslintPluginComments from '@eslint-community/eslint-plugin-eslint-comments/configs';
import eslintPluginStylistic from '@stylistic/eslint-plugin';
import { defineConfig } from 'eslint/config';
import eslintPluginJsxA11yX from 'eslint-plugin-jsx-a11y-x';
import eslintPluginPrettierRecommended from 'eslint-plugin-prettier/recommended';
import eslintPluginPromise from 'eslint-plugin-promise';
import eslintPluginReactHooks from 'eslint-plugin-react-hooks';
import eslintPluginUnicorn from 'eslint-plugin-unicorn';
import globals from 'globals';
import tseslint from 'typescript-eslint';

export default defineConfig(
    // ─── Base configs ────────────────────────────────────────────────────────
    eslint.configs.recommended,
    tseslint.configs.recommendedTypeChecked,
    eslintPluginPromise.configs['flat/recommended'],
    eslintPluginComments.recommended,

    // ─── React 19 + Compiler ─────────────────────────────────────────────────
    eslintPluginJsxA11yX.flatConfigs.recommended,
    eslintPluginReact.configs['recommended-type-checked'],
    eslintPluginReactHooks.configs.flat['recommended-latest'],

    // ─── Ignores ─────────────────────────────────────────────────────────────
    {
        ignores: [
            'build/',
            'dist/',
            'node_modules/',
            'public/',
            'coverage/',
            'storybook-static/',
            'src/routeTree.gen.ts', // Auto-generated by TanStack Router
            '**/*.md',
        ],
    },

    // ─── Global settings ─────────────────────────────────────────────────────
    {
        linterOptions: {
            reportUnusedDisableDirectives: true,
        },
        plugins: {
            unicorn: eslintPluginUnicorn,
            '@stylistic': eslintPluginStylistic,
        },
        languageOptions: {
            ecmaVersion: 'latest',
            sourceType: 'module',
            globals: {
                ...globals.browser,
            },
            parserOptions: {
                projectService: true,
                ecmaFeatures: { jsx: true },
            },
        },
        settings: {
            react: { version: 'detect' },
        },
    },

    // ─── All JS/TS files ─────────────────────────────────────────────────────
    {
        files: ['**/*.{js,jsx,ts,tsx,mts,cts}'],
        rules: {
            // ── Code style (enforced by @stylistic or base) ──────────────────
            '@stylistic/linebreak-style': ['error', 'unix'],
            '@stylistic/eol-last': ['error', 'always'],
            '@stylistic/spaced-comment': [
                'error',
                'always',
                {
                    line: { markers: ['/'], exceptions: ['/', '#'] },
                    block: { markers: ['!'], exceptions: ['*'], balanced: true },
                },
            ],
            'prefer-template': 'error',
            'no-var': 'error',
            eqeqeq: 'error',
            'no-eval': 'error',
            'no-extra-bind': 'error',
            curly: ['error', 'all'],
            semi: ['error', 'always'],
            quotes: ['error', 'single', { avoidEscape: true }],
            'block-scoped-var': 'error',
            'array-callback-return': 'error',
            'object-shorthand': ['error', 'always', { ignoreConstructors: false, avoidQuotes: true }],
            'no-case-declarations': 'error',
            'no-void': ['warn', { allowAsStatement: true }],
            'no-invalid-this': 'error',
            'require-await': 'off',
            'max-statements-per-line': ['error', { max: 1 }],
            'prefer-exponentiation-operator': 'error',
            'prefer-rest-params': 'error',
            'prefer-spread': 'error',
            'no-debugger': 'error',
            'no-constant-condition': 'warn',
            'prefer-const': ['error', { destructuring: 'all', ignoreReadBeforeAssign: true }],
            'no-unreachable': 'error',
            'no-unused-labels': 'error',
            'no-useless-computed-key': 'error',
            'no-useless-concat': 'error',
            'no-useless-escape': 'error',
            'no-useless-rename': ['error', { ignoreDestructuring: false, ignoreImport: false, ignoreExport: false }],
            'no-undef': 'off', // TypeScript handles this

            // ── Unicorn (selective) ──────────────────────────────────────────
            'unicorn/error-message': 'error',
            'unicorn/escape-case': 'error',
            'unicorn/no-instanceof-array': 'error',
            'unicorn/number-literal-case': 'error',
            'unicorn/prefer-array-find': 'error',
            'unicorn/prefer-default-parameters': 'error',
            'unicorn/prefer-includes': 'error',
            'unicorn/prefer-string-starts-ends-with': 'error',
            'unicorn/prefer-string-replace-all': 'error',
            'unicorn/prefer-dom-node-text-content': 'warn',
            'unicorn/prefer-type-error': 'error',
            'unicorn/throw-new-error': 'error',
            'unicorn/no-array-for-each': 'error',
            'unicorn/explicit-length-check': 'error',
            'unicorn/no-new-array': 'error',
            'unicorn/no-useless-length-check': 'error',
            'unicorn/catch-error-name': 'error',

            // ── Promise ──────────────────────────────────────────────────────
            'promise/param-names': 'error',
            'promise/always-return': 'warn',
            'promise/catch-or-return': 'warn',
        },
    },

    // ─── TypeScript files ────────────────────────────────────────────────────
    {
        files: ['**/*.{ts,tsx,mts,cts}'],
        rules: {
            'no-unused-vars': 'off',
            '@typescript-eslint/no-unused-vars': ['error', { argsIgnorePattern: '^_', varsIgnorePattern: '^_' }],
            'no-dupe-class-members': 'off',
            '@typescript-eslint/no-dupe-class-members': 'error',
            '@typescript-eslint/no-explicit-any': 'warn',
            'no-implied-eval': 'off',
            '@typescript-eslint/no-implied-eval': 'error',
            'dot-notation': 'off',
            '@typescript-eslint/dot-notation': ['error', { allowKeywords: true }],
            '@typescript-eslint/await-thenable': 'error',
            '@typescript-eslint/no-for-in-array': 'error',
            '@typescript-eslint/no-unnecessary-type-assertion': 'error',
            '@typescript-eslint/no-unsafe-argument': 'warn',
            '@typescript-eslint/no-unsafe-assignment': 'warn',
            '@typescript-eslint/no-unsafe-call': 'warn',
            '@typescript-eslint/no-unsafe-member-access': 'warn',
            '@typescript-eslint/no-unsafe-return': 'warn',
            'require-await': 'off',
            '@typescript-eslint/require-await': 'warn',
            '@typescript-eslint/restrict-plus-operands': 'error',
            '@typescript-eslint/restrict-template-expressions': [
                'warn',
                {
                    allowAny: false,
                    allowBoolean: true,
                    allowNullish: false,
                    allowNumber: true,
                    allowRegExp: true,
                },
            ],
            '@typescript-eslint/unbound-method': 'off',
            '@typescript-eslint/consistent-type-imports': [
                'warn',
                { prefer: 'type-imports', fixStyle: 'inline-type-imports' },
            ],
            '@typescript-eslint/no-misused-promises': ['warn', { checksVoidReturn: { attributes: false } }],
            '@typescript-eslint/no-floating-promises': 'warn',
            '@typescript-eslint/prefer-promise-reject-errors': 'warn',
        },
    },

    // ─── React components (JSX) ──────────────────────────────────────────────
    {
        files: ['**/*.{tsx,jsx}'],
        rules: {
            'jsx-quotes': ['error', 'prefer-double'],

            // Children manipulation is fine for DAW components (e.g. slot patterns)
            '@eslint-react/no-children-for-each': 'off',
            '@eslint-react/no-children-count': 'off',
            '@eslint-react/no-children-map': 'off',
            '@eslint-react/no-children-to-array': 'off',

            // React 19: no forwardRef needed (ref is a regular prop)
            '@eslint-react/no-forward-ref': 'error',

            // Naming conventions
            '@eslint-react/naming-convention/context-name': 'error',

            // DAW UX: autoFocus is intentional for inline editors, command palette, tempo fields, etc.
            'jsx-a11y-x/no-autofocus': 'off',

            // DAW surfaces: canvas, SVG lanes, and track headers have legitimate interactions
            'jsx-a11y-x/no-noninteractive-element-interactions': 'off',

            // DAW uses <label> for presentational parameter names (mixer knobs, sliders).
            // These are visual labels, not form labels. Warn to track but don't block.
            'jsx-a11y-x/label-has-associated-control': [
                'warn',
                {
                    controlComponents: ['Slider', 'Select', 'Switch', 'Input', 'Knob', 'Checkbox', 'SelectTrigger'],
                    depth: 3,
                },
            ],

            // DAW interactive surfaces may not have focusable equivalents.
            'jsx-a11y-x/interactive-supports-focus': 'warn',

            // DAW has many interactive surfaces (track headers, mixer strips, automation lanes)
            // where full keyboard equivalents are complex. Warn instead of error.
            'jsx-a11y-x/click-events-have-key-events': 'warn',
            'jsx-a11y-x/no-static-element-interactions': 'warn',

            // DAW transport/track controls use aria-pressed on various roles.
            'jsx-a11y-x/role-supports-aria-props': 'warn',

            // React Compiler purity rules — DAW canvas/WebGL/automation components
            // legitimately read refs during render to measure DOM dimensions (e.g.
            // containerRef.current.clientWidth for pixel-per-beat calculations).
            // These are valid patterns that React Compiler can't optimize but are
            // necessary for real-time renderer surfaces.
            'react-hooks/refs': 'warn',
            'react-hooks/purity': 'warn',
            '@eslint-react/purity': 'warn',

            // setState in sync effects is common for derived state from store subscriptions
            // and layout measurements in DAW panels. Warn to track but don't block.
            'react-hooks/set-state-in-effect': 'warn',
            '@eslint-react/set-state-in-effect': 'warn',

            // IIFEs in JSX are used for inline complex rendering in mixer/inspector panels.
            '@eslint-react/unsupported-syntax': 'warn',

            // No default React import (jsx-transform handles it)
            'no-restricted-syntax': [
                'error',
                {
                    selector:
                        "ImportDeclaration[source.value='react'] :matches(ImportDefaultSpecifier, ImportNamespaceSpecifier)",
                    message:
                        'Default React import not allowed since we use the TypeScript jsx-transform. If you need a global type that collides with a React named export (such as `MouseEvent`), use `globalThis.MouseEvent`.',
                },
            ],
        },
    },

    // ─── Business-layer conventions ──────────────────────────────────────────
    // Prefer function declarations over const arrow functions in non-presentation code.
    {
        files: [
            'src/**/useCases/**/*.ts',
            'src/**/repositories/**/*.ts',
            'src/**/transformers/**/*.ts',
            'src/**/models/**/*.ts',
            'src/**/stores/**/*.ts',
            'src/**/events/**/*.ts',
            'src/helpers/**/*.ts',
        ],
        rules: {
            'func-style': ['warn', 'declaration', { allowArrowFunctions: false }],
        },
    },

    // ─── Project-specific restrictions ───────────────────────────────────────
    {
        files: ['**/*.{ts,tsx,mts,cts}'],
        ignores: [
            '**/*.spec.{ts,tsx}',
            // Storage implementations — they ARE the abstraction layer
            'src/helpers/Store/Storage/LocalStorageStorage.ts',
            'src/helpers/Store/Storage/SessionStorageStorage.ts',
            // Repositories/stores that implement persistence directly
            'src/modules/DevTools/repositories/devToolsStorageRepository.ts',
            'src/modules/Project/repositories/projectRepository.ts',
            'src/modules/Project/useCases/recentProjects.ts',
            'src/modules/Command/stores/undoStore.ts',
        ],
        rules: {
            'no-restricted-syntax': [
                'warn',
                {
                    selector: "CallExpression[callee.object.name='localStorage']",
                    message: 'Do not use `localStorage` directly, use the `Store` with `LocalStorageStorage` instead',
                },
                {
                    selector:
                        "CallExpression[callee.object.object.name='window'][callee.object.property.name='localStorage']",
                    message: 'Do not use `localStorage` directly, use the `Store` with `LocalStorageStorage` instead',
                },
                {
                    selector: "CallExpression[callee.object.name='sessionStorage']",
                    message:
                        'Do not use `sessionStorage` directly, use the `Store` with `SessionStorageStorage` instead',
                },
                {
                    selector:
                        "CallExpression[callee.object.object.name='window'][callee.object.property.name='sessionStorage']",
                    message:
                        'Do not use `sessionStorage` directly, use the `Store` with `SessionStorageStorage` instead',
                },
            ],
        },
    },

    // ─── Test files ──────────────────────────────────────────────────────────
    {
        files: ['**/*.spec.{ts,tsx}', '**/*.test.{ts,tsx}'],
        rules: {
            '@eslint-react/no-unnecessary-use-prefix': 'off',
            '@eslint-react/no-missing-context-display-name': 'off',
            '@eslint-react/no-create-ref': 'off',
            '@eslint-react/no-unstable-context-value': 'off',
            'jsx-a11y-x/no-static-element-interactions': 'off',
            'jsx-a11y-x/click-events-have-key-events': 'off',
            '@typescript-eslint/unbound-method': 'off',
        },
    },

    // ─── d.ts files ──────────────────────────────────────────────────────────
    {
        files: ['**/*.d.ts'],
        extends: [tseslint.configs.disableTypeChecked],
    },

    // ─── Prettier (must be last) ─────────────────────────────────────────────
    eslintPluginPrettierRecommended,
    {
        files: ['**/*.{ts,tsx,mts,cts}'],
        rules: {
            curly: ['error', 'all'], // Override Prettier's curly brace preference
        },
    }
);
