import supersawUnisonDsp from './dsp/supersaw-unison.dsp?raw';
import { registerFaustDSP } from './registerFaustDSP';

export function registerSupersawUnison(): void {
    registerFaustDSP(
        'Supersaw Unison',
        supersawUnisonDsp,
        [
            {
                address: '/supersaw/lfo_rate',
                label: 'LFO Rate',
                min: 0.1,
                max: 20,
                defaultValue: 5,
                step: 0.1,
                type: 'hslider',
            },
            {
                address: '/supersaw/lfo_depth',
                label: 'LFO Depth',
                min: 0,
                max: 1,
                defaultValue: 0,
                step: 0.01,
                type: 'hslider',
            },
            {
                address: '/supersaw/detune',
                label: 'Detune (cents)',
                min: 0,
                max: 100,
                defaultValue: 15,
                step: 0.1,
                type: 'hslider',
            },
            {
                address: '/supersaw/center_mix',
                label: 'Center Mix',
                min: 0,
                max: 1,
                defaultValue: 0.7,
                step: 0.01,
                type: 'hslider',
            },
            {
                address: '/supersaw/cutoff',
                label: 'Cutoff',
                min: 100,
                max: 20000,
                defaultValue: 6000,
                step: 1,
                type: 'hslider',
                scaling: 'log',
            },
            {
                address: '/supersaw/resonance',
                label: 'Resonance',
                min: 0,
                max: 0.99,
                defaultValue: 0.3,
                step: 0.01,
                type: 'hslider',
            },
            {
                address: '/synth/attack',
                label: 'Attack',
                min: 0.001,
                max: 5,
                defaultValue: 0.01,
                step: 0.001,
                type: 'hslider',
                scaling: 'log',
            },
            {
                address: '/synth/decay',
                label: 'Decay',
                min: 0.01,
                max: 5,
                defaultValue: 0.3,
                step: 0.01,
                type: 'hslider',
                scaling: 'log',
            },
            {
                address: '/synth/sustain',
                label: 'Sustain',
                min: 0,
                max: 1,
                defaultValue: 0.8,
                step: 0.01,
                type: 'hslider',
            },
            {
                address: '/synth/release',
                label: 'Release',
                min: 0.01,
                max: 10,
                defaultValue: 0.5,
                step: 0.01,
                type: 'hslider',
                scaling: 'log',
            },
            {
                address: '/supersaw/freq',
                label: 'Freq',
                min: 20,
                max: 12000,
                defaultValue: 440,
                step: 0.01,
                type: 'hslider',
            },
            {
                address: '/supersaw/gate',
                label: 'Gate',
                min: 0,
                max: 1,
                defaultValue: 0,
                step: 1,
                type: 'button',
            },
        ],
        true
    );
}
