/**
 * Toaster factory kit presets — bread-themed drum kits.
 */

import { type ToasterKit, createDefaultKit, createDefaultPad } from '../models/ToasterKit';

export type ToasterKitPreset = {
    id: string;
    name: string;
    description: string;
    tags: string[];
    kit: ToasterKit;
};

function kit(id: string, name: string, desc: string, tags: string[], overrides: Partial<ToasterKit>): ToasterKitPreset {
    return {
        id,
        name,
        description: desc,
        tags: ['toaster', ...tags],
        kit: { ...createDefaultKit(), name, ...overrides },
    };
}

export const TOASTER_PRESETS: ToasterKitPreset[] = [
    kit('init', 'Blank Flour', 'Empty 16-pad kit — start from scratch', ['init'], {}),
    kit('808-classic', 'Sourdough 808', 'Classic TR-808 electronic kit', ['808', 'classic', 'electronic', 'hip-hop'], {
        pads: [
            {
                ...createDefaultPad(0),
                name: 'Kick',
                engineType: 'kick-808',
            },
            { ...createDefaultPad(1), name: 'Snare', engineType: 'snare-808' },
            { ...createDefaultPad(2), name: 'CH', engineType: 'hihat-closed', chokeGroup: 1, decay: 0.2 },
            { ...createDefaultPad(3), name: 'OH', engineType: 'hihat-open', chokeGroup: 1, decay: 0.7 },
            { ...createDefaultPad(4), name: 'Clap', engineType: 'clap' },
            { ...createDefaultPad(5), name: 'Rim', engineType: 'rimshot' },
            { ...createDefaultPad(6), name: 'Lo Tom', engineType: 'tom', tune: -6 },
            { ...createDefaultPad(7), name: 'Mid Tom', engineType: 'tom', tune: 0 },
            { ...createDefaultPad(8), name: 'Hi Tom', engineType: 'tom', tune: 6 },
            { ...createDefaultPad(9), name: 'Cowbell', engineType: 'cowbell' },
            { ...createDefaultPad(10), name: 'Clave', engineType: 'clave' },
            { ...createDefaultPad(11), name: 'Maracas', engineType: 'shaker' },
            { ...createDefaultPad(12), name: 'Conga L', engineType: 'perc-generic', tune: -3 },
            { ...createDefaultPad(13), name: 'Conga H', engineType: 'perc-generic', tune: 3 },
            { ...createDefaultPad(14), name: 'Perc 1', engineType: 'perc-generic' },
            { ...createDefaultPad(15), name: 'Perc 2', engineType: 'perc-generic' },
        ],
    }),
    kit('909-punchy', 'Rye 909', 'Punchy TR-909 kit — house/techno staple', ['909', 'house', 'techno'], {
        pads: [
            { ...createDefaultPad(0), name: 'Kick', engineType: 'kick-909' },
            { ...createDefaultPad(1), name: 'Snare', engineType: 'snare-analog', tone: 0.6 },
            { ...createDefaultPad(2), name: 'CH', engineType: 'hihat-closed', chokeGroup: 1 },
            { ...createDefaultPad(3), name: 'OH', engineType: 'hihat-open', chokeGroup: 1 },
            { ...createDefaultPad(4), name: 'Clap', engineType: 'clap' },
            { ...createDefaultPad(5), name: 'Ride', engineType: 'cymbal', decay: 0.8 },
            { ...createDefaultPad(6), name: 'Lo Tom', engineType: 'tom', tune: -5 },
            { ...createDefaultPad(7), name: 'Mid Tom', engineType: 'tom' },
            { ...createDefaultPad(8), name: 'Hi Tom', engineType: 'tom', tune: 5 },
            { ...createDefaultPad(9), name: 'Crash', engineType: 'cymbal', decay: 0.9 },
            ...Array.from({ length: 6 }, (_, index) => createDefaultPad(10 + index)),
        ],
    }),
    kit('trap-heavy', 'Trap Dough', 'Heavy trap kit — deep 808 + crispy hats', ['trap', 'hip-hop', 'modern'], {
        pads: [
            { ...createDefaultPad(0), name: 'Deep 808', engineType: 'kick-808', tune: -3, decay: 0.8, drive: 2 },
            { ...createDefaultPad(1), name: 'Trap Snare', engineType: 'snare-analog', tone: 0.7 },
            { ...createDefaultPad(2), name: 'CH', engineType: 'hihat-closed', chokeGroup: 1, tone: 0.8, decay: 0.15 },
            { ...createDefaultPad(3), name: 'OH', engineType: 'hihat-open', chokeGroup: 1, decay: 0.5 },
            { ...createDefaultPad(4), name: 'Clap', engineType: 'clap' },
            { ...createDefaultPad(5), name: 'Snap', engineType: 'rimshot', tone: 0.9 },
            ...Array.from({ length: 10 }, (_, index) => createDefaultPad(6 + index)),
        ],
    }),
    kit('lofi-crust', 'Crusty Lo-Fi', 'Lo-fi hip-hop kit — dusty, warm, nostalgic', ['lofi', 'hip-hop', 'vintage'], {
        pads: [
            { ...createDefaultPad(0), name: 'Dusty Kick', engineType: 'kick-analog', drive: 3, tone: 0.3 },
            { ...createDefaultPad(1), name: 'Vinyl Snare', engineType: 'snare-analog', tone: 0.4 },
            {
                ...createDefaultPad(2),
                name: 'Soft CH',
                engineType: 'hihat-closed',
                chokeGroup: 1,
                volume: 0.6,
                tone: 0.3,
            },
            { ...createDefaultPad(3), name: 'Loose OH', engineType: 'hihat-open', chokeGroup: 1, volume: 0.5 },
            { ...createDefaultPad(4), name: 'Rim', engineType: 'rimshot', volume: 0.5 },
            { ...createDefaultPad(5), name: 'Shaker', engineType: 'shaker', volume: 0.4 },
            ...Array.from({ length: 10 }, (_, index) => createDefaultPad(6 + index)),
        ],
        reverbMix: 0.25,
        swing: 0.3,
    }),
    kit('minimal-techno', 'Minimal Rye', 'Stripped-down techno kit', ['techno', 'minimal', 'electronic'], {
        pads: [
            { ...createDefaultPad(0), name: 'Kick', engineType: 'kick-analog', decay: 0.3 },
            { ...createDefaultPad(1), name: 'Clap', engineType: 'clap', sendReverb: 0.3 },
            { ...createDefaultPad(2), name: 'CH', engineType: 'hihat-closed', chokeGroup: 1, decay: 0.1 },
            { ...createDefaultPad(3), name: 'OH', engineType: 'hihat-open', chokeGroup: 1, decay: 0.4 },
            { ...createDefaultPad(4), name: 'Rim', engineType: 'rimshot' },
            { ...createDefaultPad(5), name: 'Perc', engineType: 'perc-generic', sendDelay: 0.2 },
            ...Array.from({ length: 10 }, (_, index) => createDefaultPad(6 + index)),
        ],
    }),
    kit('dnb-roller', 'DnB Roller', 'Drum & bass kit — fast breaks + deep sub', ['dnb', 'jungle', 'breakbeat'], {
        pads: [
            { ...createDefaultPad(0), name: 'Sub Kick', engineType: 'kick-808', tune: -5, decay: 0.6, drive: 1 },
            { ...createDefaultPad(1), name: 'Snare', engineType: 'snare-analog', tone: 0.7, decay: 0.3 },
            { ...createDefaultPad(2), name: 'CH', engineType: 'hihat-closed', chokeGroup: 1, decay: 0.1 },
            { ...createDefaultPad(3), name: 'OH', engineType: 'hihat-open', chokeGroup: 1, decay: 0.3 },
            { ...createDefaultPad(4), name: 'Break Snare', engineType: 'snare-808', tone: 0.8 },
            { ...createDefaultPad(5), name: 'Ride', engineType: 'cymbal', decay: 0.5 },
            ...Array.from({ length: 10 }, (_, index) => createDefaultPad(6 + index)),
        ],
        swing: 0.1,
    }),
    kit(
        'house-classic',
        'House Bread',
        'Classic house kit — four-on-the-floor foundation',
        ['house', 'dance', 'classic'],
        {
            pads: [
                { ...createDefaultPad(0), name: 'House Kick', engineType: 'kick-909', decay: 0.35 },
                { ...createDefaultPad(1), name: 'Clap', engineType: 'clap', sendReverb: 0.3 },
                {
                    ...createDefaultPad(2),
                    name: 'CH',
                    engineType: 'hihat-closed',
                    chokeGroup: 1,
                    decay: 0.15,
                    volume: 0.7,
                },
                {
                    ...createDefaultPad(3),
                    name: 'OH',
                    engineType: 'hihat-open',
                    chokeGroup: 1,
                    decay: 0.4,
                    volume: 0.6,
                },
                { ...createDefaultPad(4), name: 'Shaker', engineType: 'shaker', volume: 0.5 },
                { ...createDefaultPad(5), name: 'Perc', engineType: 'perc-generic', sendDelay: 0.15 },
                ...Array.from({ length: 10 }, (_, index) => createDefaultPad(6 + index)),
            ],
            swing: 0.15,
        }
    ),
    kit(
        'industrial',
        'Iron Loaf',
        'Industrial kit — harsh, metallic, aggressive',
        ['industrial', 'noise', 'aggressive'],
        {
            pads: [
                { ...createDefaultPad(0), name: 'Metal Kick', engineType: 'kick-analog', drive: 6, tone: 0.7 },
                { ...createDefaultPad(1), name: 'Noise Snare', engineType: 'snare-analog', tone: 0.9, drive: 4 },
                { ...createDefaultPad(2), name: 'Metal CH', engineType: 'hihat-closed', chokeGroup: 1, tone: 0.9 },
                { ...createDefaultPad(3), name: 'Crash', engineType: 'cymbal', decay: 0.7 },
                { ...createDefaultPad(4), name: 'Clang', engineType: 'cowbell', drive: 3 },
                { ...createDefaultPad(5), name: 'Rim', engineType: 'rimshot', drive: 2 },
                ...Array.from({ length: 10 }, (_, index) => createDefaultPad(6 + index)),
            ],
        }
    ),
    kit(
        'ambient-perc',
        'Ambient Crumb',
        'Ambient percussion — soft, spacious, textural',
        ['ambient', 'downtempo', 'atmospheric'],
        {
            pads: [
                {
                    ...createDefaultPad(0),
                    name: 'Soft Kick',
                    engineType: 'kick-analog',
                    decay: 0.2,
                    tone: 0.3,
                    volume: 0.6,
                },
                { ...createDefaultPad(1), name: 'Brush', engineType: 'shaker', volume: 0.4 },
                {
                    ...createDefaultPad(2),
                    name: 'Soft CH',
                    engineType: 'hihat-closed',
                    chokeGroup: 1,
                    volume: 0.4,
                    tone: 0.3,
                },
                {
                    ...createDefaultPad(3),
                    name: 'Shimmer',
                    engineType: 'cymbal',
                    decay: 0.9,
                    volume: 0.3,
                    sendReverb: 0.5,
                },
                { ...createDefaultPad(4), name: 'Click', engineType: 'rimshot', volume: 0.4, sendDelay: 0.3 },
                {
                    ...createDefaultPad(5),
                    name: 'Texture',
                    engineType: 'perc-generic',
                    sendReverb: 0.4,
                    sendDelay: 0.2,
                },
                ...Array.from({ length: 10 }, (_, index) => createDefaultPad(6 + index)),
            ],
            reverbMix: 0.4,
            reverbDecay: 0.8,
            delayMix: 0.2,
            delayTime: 500,
            delayFeedback: 0.4,
        }
    ),
    kit(
        'reggaeton',
        'Dembow Dough',
        'Reggaeton/dembow kit — punchy with characteristic rhythm',
        ['reggaeton', 'latin', 'urban'],
        {
            pads: [
                { ...createDefaultPad(0), name: 'Dembow Kick', engineType: 'kick-808', decay: 0.3, drive: 1.5 },
                { ...createDefaultPad(1), name: 'Snare', engineType: 'snare-808', tone: 0.6 },
                { ...createDefaultPad(2), name: 'CH', engineType: 'hihat-closed', chokeGroup: 1, decay: 0.12 },
                { ...createDefaultPad(3), name: 'OH', engineType: 'hihat-open', chokeGroup: 1, decay: 0.35 },
                { ...createDefaultPad(4), name: 'Clap', engineType: 'clap', sendReverb: 0.2 },
                { ...createDefaultPad(5), name: 'Perc', engineType: 'perc-generic' },
                ...Array.from({ length: 10 }, (_, index) => createDefaultPad(6 + index)),
            ],
        }
    ),
    kit('acoustic-bread', 'Sourdough Acoustic', 'Acoustic drum kit emulation', ['acoustic', 'natural', 'live'], {
        pads: [
            { ...createDefaultPad(0), name: 'Kick', engineType: 'kick-analog', decay: 0.3, tone: 0.4 },
            { ...createDefaultPad(1), name: 'Snare', engineType: 'snare-analog', tone: 0.5 },
            { ...createDefaultPad(2), name: 'CH', engineType: 'hihat-closed', chokeGroup: 1, tone: 0.5, decay: 0.15 },
            { ...createDefaultPad(3), name: 'OH', engineType: 'hihat-open', chokeGroup: 1, tone: 0.5, decay: 0.6 },
            { ...createDefaultPad(4), name: 'Cross Stick', engineType: 'rimshot' },
            { ...createDefaultPad(5), name: 'Ride', engineType: 'cymbal', decay: 0.8 },
            { ...createDefaultPad(6), name: 'Floor Tom', engineType: 'tom', tune: -7 },
            { ...createDefaultPad(7), name: 'Rack Tom', engineType: 'tom', tune: 2 },
            { ...createDefaultPad(8), name: 'Crash', engineType: 'cymbal', decay: 0.9, sendReverb: 0.3 },
            ...Array.from({ length: 7 }, (_, index) => createDefaultPad(9 + index)),
        ],
        reverbMix: 0.3,
        reverbDecay: 0.6,
    }),
    kit(
        'world-perc',
        'World Grain',
        'World percussion — modal synthesis tabla, bongo, woodblock',
        ['world', 'ethnic', 'percussion'],
        {
            pads: [
                { ...createDefaultPad(0), name: 'Tabla', engineType: 'modal-tabla' },
                { ...createDefaultPad(1), name: 'Bongo Hi', engineType: 'modal-bongo', tune: 3 },
                { ...createDefaultPad(2), name: 'Bongo Lo', engineType: 'modal-bongo', tune: -3 },
                { ...createDefaultPad(3), name: 'Woodblock', engineType: 'modal-woodblock' },
                { ...createDefaultPad(4), name: 'Metal', engineType: 'modal-metal' },
                { ...createDefaultPad(5), name: 'Shaker', engineType: 'shaker' },
                { ...createDefaultPad(6), name: 'Clave', engineType: 'clave' },
                { ...createDefaultPad(7), name: 'Cowbell', engineType: 'cowbell' },
                { ...createDefaultPad(8), name: 'Tom Lo', engineType: 'tom', tune: -5 },
                { ...createDefaultPad(9), name: 'Tom Hi', engineType: 'tom', tune: 5 },
                ...Array.from({ length: 6 }, (_, index) => createDefaultPad(10 + index)),
            ],
            reverbMix: 0.25,
        }
    ),
    kit('edm-festival', 'Festival Loaf', 'EDM/festival kit — big room drops', ['edm', 'festival', 'bigroom'], {
        pads: [
            { ...createDefaultPad(0), name: 'Big Kick', engineType: 'kick-909', drive: 2, decay: 0.4 },
            { ...createDefaultPad(1), name: 'Clap', engineType: 'clap', sendReverb: 0.4 },
            { ...createDefaultPad(2), name: 'CH', engineType: 'hihat-closed', chokeGroup: 1, tone: 0.8 },
            { ...createDefaultPad(3), name: 'OH', engineType: 'hihat-open', chokeGroup: 1 },
            { ...createDefaultPad(4), name: 'Snare', engineType: 'snare-analog', tone: 0.7 },
            { ...createDefaultPad(5), name: 'Impact', engineType: 'cymbal', decay: 0.9, sendReverb: 0.5 },
            ...Array.from({ length: 10 }, (_, index) => createDefaultPad(6 + index)),
        ],
        reverbMix: 0.3,
        reverbDecay: 0.7,
    }),
    kit(
        'psytrance-mycelium',
        'Mycelial Pulse',
        'Tight psychedelic trance kit — focused low end, controlled air, and spatial percussion',
        ['psytrance', 'trance', 'psychedelic'],
        {
            pads: [
                {
                    ...createDefaultPad(0),
                    name: 'Kick',
                    engineType: 'kick-909',
                    volume: 1,
                    tune: -1,
                    decay: 0.24,
                    filterCutoff: 12_000,
                    filterResonance: 0.7,
                    sendReverb: 0,
                },
                {
                    ...createDefaultPad(1),
                    name: 'Snare',
                    engineType: 'snare-808',
                    volume: 0.68,
                    pan: -0.04,
                    decay: 0.34,
                    tone: 0.62,
                    filterCutoff: 14_000,
                    sendReverb: 0.04,
                },
                {
                    ...createDefaultPad(2),
                    name: 'Closed HH',
                    engineType: 'hihat-closed',
                    chokeGroup: 1,
                    volume: 0.42,
                    pan: 0.16,
                    decay: 0.1,
                    tone: 0.58,
                    filterCutoff: 10_500,
                    sendReverb: 0.01,
                },
                {
                    ...createDefaultPad(3),
                    name: 'Open HH',
                    engineType: 'hihat-open',
                    chokeGroup: 1,
                    volume: 0.46,
                    pan: -0.16,
                    decay: 0.34,
                    tone: 0.55,
                    filterCutoff: 12_000,
                    sendReverb: 0.02,
                },
                {
                    ...createDefaultPad(4),
                    name: 'Clap',
                    engineType: 'clap',
                    volume: 0.52,
                    pan: 0.08,
                    decay: 0.28,
                    filterCutoff: 11_000,
                    sendReverb: 0.08,
                },
                {
                    ...createDefaultPad(5),
                    name: 'Rim',
                    engineType: 'rimshot',
                    volume: 0.34,
                    pan: -0.3,
                    decay: 0.18,
                    tone: 0.6,
                    filterCutoff: 9_000,
                    sendReverb: 0.03,
                    sendDelay: 0.04,
                },
                {
                    ...createDefaultPad(6),
                    name: 'Low Tom',
                    engineType: 'tom-808-low',
                    volume: 0.52,
                    pan: -0.26,
                    tune: -2,
                    decay: 0.32,
                    tone: 0.42,
                    filterCutoff: 9_000,
                    sendReverb: 0.05,
                },
                {
                    ...createDefaultPad(7),
                    name: 'Mid Tom',
                    engineType: 'tom-808-mid',
                    volume: 0.48,
                    decay: 0.28,
                    tone: 0.48,
                    filterCutoff: 10_000,
                    sendReverb: 0.05,
                },
                {
                    ...createDefaultPad(8),
                    name: 'Hi Tom',
                    engineType: 'tom-808-high',
                    volume: 0.44,
                    pan: 0.26,
                    tune: 2,
                    decay: 0.24,
                    tone: 0.54,
                    filterCutoff: 11_000,
                    sendReverb: 0.05,
                },
                {
                    ...createDefaultPad(9),
                    name: 'Crash',
                    engineType: 'cymbal',
                    volume: 0.38,
                    pan: -0.34,
                    decay: 0.55,
                    tone: 0.42,
                    filterCutoff: 10_000,
                    sendReverb: 0.08,
                },
                {
                    ...createDefaultPad(10),
                    name: 'Ride',
                    engineType: 'cymbal',
                    volume: 0.34,
                    pan: 0.34,
                    decay: 0.42,
                    filterCutoff: 11_500,
                    sendReverb: 0.05,
                },
                {
                    ...createDefaultPad(11),
                    name: 'Cowbell',
                    engineType: 'cowbell',
                    volume: 0.28,
                    pan: 0.22,
                    decay: 0.22,
                    filterCutoff: 8_500,
                    sendReverb: 0.03,
                    sendDelay: 0.05,
                },
                {
                    ...createDefaultPad(12),
                    name: 'Clave',
                    engineType: 'clave',
                    volume: 0.3,
                    pan: -0.2,
                    decay: 0.18,
                    filterCutoff: 7_500,
                    sendReverb: 0.02,
                    sendDelay: 0.04,
                },
                {
                    ...createDefaultPad(13),
                    name: 'Shaker',
                    engineType: 'shaker',
                    volume: 0.26,
                    pan: 0.3,
                    decay: 0.12,
                    tone: 0.45,
                    filterCutoff: 9_000,
                    sendReverb: 0.02,
                },
                {
                    ...createDefaultPad(14),
                    name: 'Perc 1',
                    engineType: 'perc-generic',
                    volume: 0.36,
                    pan: -0.38,
                    tune: -5,
                    decay: 0.24,
                    tone: 0.42,
                    drive: 0.4,
                    filterCutoff: 8_000,
                    sendReverb: 0.03,
                    sendDelay: 0.07,
                },
                {
                    ...createDefaultPad(15),
                    name: 'Perc 2',
                    engineType: 'perc-generic',
                    volume: 0.32,
                    pan: 0.38,
                    tune: 4,
                    decay: 0.18,
                    tone: 0.58,
                    drive: 0.3,
                    filterCutoff: 10_000,
                    sendReverb: 0.03,
                    sendDelay: 0.05,
                },
            ],
            swing: 0.04,
            masterGain: 0.9,
            reverbMix: 0.08,
            reverbDecay: 0.55,
            delayTime: 312.5,
            delayFeedback: 0.28,
            delayMix: 0.02,
        }
    ),
    kit('jazz-brush', 'Jazz Crouton', 'Jazz brushes kit — soft, swinging, intimate', ['jazz', 'brush', 'acoustic'], {
        pads: [
            { ...createDefaultPad(0), name: 'Kick', engineType: 'kick-analog', decay: 0.2, tone: 0.3, volume: 0.6 },
            { ...createDefaultPad(1), name: 'Brush', engineType: 'shaker', volume: 0.5, tone: 0.4 },
            { ...createDefaultPad(2), name: 'CH', engineType: 'hihat-closed', chokeGroup: 1, volume: 0.5, tone: 0.4 },
            { ...createDefaultPad(3), name: 'OH', engineType: 'hihat-open', chokeGroup: 1, volume: 0.4 },
            { ...createDefaultPad(4), name: 'Cross Stick', engineType: 'rimshot', volume: 0.5 },
            { ...createDefaultPad(5), name: 'Ride', engineType: 'cymbal', decay: 0.7, volume: 0.5 },
            ...Array.from({ length: 10 }, (_, index) => createDefaultPad(6 + index)),
        ],
        reverbMix: 0.3,
        reverbDecay: 0.6,
        swing: 0.25,
    }),
    kit(
        'sp1200-crunch',
        'SP-Twelve Crust',
        '12-bit SP-1200 crunch — golden era hip-hop',
        ['sp1200', 'lofi', 'hip-hop', 'vintage'],
        {
            pads: [
                { ...createDefaultPad(0), name: 'Dusty Kick', engineType: 'kick-808', tune: -2, drive: 1.5 },
                { ...createDefaultPad(1), name: 'Crunch Snare', engineType: 'snare-808', drive: 2 },
                { ...createDefaultPad(2), name: 'Lo-Fi CH', engineType: 'hihat-closed', chokeGroup: 1, tone: 0.3 },
                { ...createDefaultPad(3), name: 'Lo-Fi OH', engineType: 'hihat-open', chokeGroup: 1, tone: 0.3 },
                { ...createDefaultPad(4), name: 'Clap', engineType: 'clap' },
                { ...createDefaultPad(5), name: 'Rim', engineType: 'rimshot' },
                ...Array.from({ length: 10 }, (_, index) => createDefaultPad(6 + index)),
            ],
            lofiBits: 12,
            lofiRate: 26040,
            lofiMix: 0.7,
            swing: 0.2,
        }
    ),
    kit(
        'cinematic-perc',
        'Cinematic Crumb',
        'Cinematic percussion — big, spatial, epic',
        ['cinematic', 'film', 'epic'],
        {
            pads: [
                {
                    ...createDefaultPad(0),
                    name: 'Epic Hit',
                    engineType: 'kick-analog',
                    decay: 0.6,
                    drive: 3,
                    sendReverb: 0.5,
                },
                { ...createDefaultPad(1), name: 'Taiko', engineType: 'modal-tabla', tune: -5, sendReverb: 0.4 },
                { ...createDefaultPad(2), name: 'Metal', engineType: 'modal-metal', sendReverb: 0.5, sendDelay: 0.2 },
                { ...createDefaultPad(3), name: 'Impact', engineType: 'cymbal', decay: 0.9, sendReverb: 0.6 },
                { ...createDefaultPad(4), name: 'Snap', engineType: 'rimshot', sendReverb: 0.3 },
                { ...createDefaultPad(5), name: 'Texture', engineType: 'shaker', volume: 0.4, sendReverb: 0.4 },
                ...Array.from({ length: 10 }, (_, index) => createDefaultPad(6 + index)),
            ],
            reverbMix: 0.4,
            reverbDecay: 0.8,
        }
    ),
    kit('garage-2step', 'Garage Crouton', 'UK garage / 2-step kit — skippy, shuffled', ['garage', '2step', 'uk'], {
        pads: [
            { ...createDefaultPad(0), name: 'Kick', engineType: 'kick-909', decay: 0.25 },
            { ...createDefaultPad(1), name: 'Snare', engineType: 'snare-analog', tone: 0.6 },
            { ...createDefaultPad(2), name: 'CH', engineType: 'hihat-closed', chokeGroup: 1, decay: 0.1, tone: 0.7 },
            { ...createDefaultPad(3), name: 'OH', engineType: 'hihat-open', chokeGroup: 1, decay: 0.3 },
            { ...createDefaultPad(4), name: 'Clap', engineType: 'clap', sendReverb: 0.25 },
            { ...createDefaultPad(5), name: 'Perc', engineType: 'perc-generic', sendDelay: 0.15 },
            ...Array.from({ length: 10 }, (_, index) => createDefaultPad(6 + index)),
        ],
        swing: 0.3,
        reverbMix: 0.2,
    }),
    kit('afrobeat', 'Afro Flour', 'Afrobeat percussion — polyrhythmic, layered', ['afrobeat', 'african', 'world'], {
        pads: [
            { ...createDefaultPad(0), name: 'Kick', engineType: 'kick-analog', decay: 0.25, tone: 0.4 },
            { ...createDefaultPad(1), name: 'Snare', engineType: 'snare-analog', tone: 0.5 },
            { ...createDefaultPad(2), name: 'CH', engineType: 'hihat-closed', chokeGroup: 1 },
            { ...createDefaultPad(3), name: 'OH', engineType: 'hihat-open', chokeGroup: 1 },
            { ...createDefaultPad(4), name: 'Conga Hi', engineType: 'modal-bongo', tune: 3 },
            { ...createDefaultPad(5), name: 'Conga Lo', engineType: 'modal-bongo', tune: -3 },
            { ...createDefaultPad(6), name: 'Shekere', engineType: 'shaker' },
            { ...createDefaultPad(7), name: 'Bell', engineType: 'cowbell' },
            { ...createDefaultPad(8), name: 'Clave', engineType: 'clave' },
            { ...createDefaultPad(9), name: 'Woodblock', engineType: 'modal-woodblock' },
            ...Array.from({ length: 6 }, (_, index) => createDefaultPad(10 + index)),
        ],
        reverbMix: 0.2,
    }),
    kit(
        'fm-metallic',
        'Metallic Grain',
        'FM percussion — bells, clangs, metallic textures',
        ['fm', 'metallic', 'experimental'],
        {
            pads: [
                { ...createDefaultPad(0), name: 'FM Kick', engineType: 'kick-808', drive: 2 },
                {
                    ...createDefaultPad(1),
                    name: 'FM Snare',
                    engineType: 'fm-perc',
                    tune: 5,
                    engineParams: { mod_ratio: 2.3, mod_amount: 3, feedback: 0.2 },
                },
                {
                    ...createDefaultPad(2),
                    name: 'FM Hat',
                    engineType: 'fm-perc',
                    tune: 12,
                    decay: 0.15,
                    engineParams: { mod_ratio: 7.1, mod_amount: 5, feedback: 0.5 },
                },
                {
                    ...createDefaultPad(3),
                    name: 'FM Bell',
                    engineType: 'fm-perc',
                    tune: 8,
                    decay: 0.7,
                    engineParams: { mod_ratio: 3.5, mod_amount: 2, feedback: 0.1 },
                },
                {
                    ...createDefaultPad(4),
                    name: 'FM Clang',
                    engineType: 'fm-perc',
                    tune: -3,
                    engineParams: { mod_ratio: 5.7, mod_amount: 4, feedback: 0.4 },
                },
                {
                    ...createDefaultPad(5),
                    name: 'FM Zap',
                    engineType: 'fm-perc',
                    tune: 0,
                    decay: 0.1,
                    engineParams: { mod_ratio: 1, mod_amount: 6, feedback: 0.7 },
                },
                ...Array.from({ length: 10 }, (_, index) => createDefaultPad(6 + index)),
            ],
            reverbMix: 0.3,
            delayMix: 0.15,
            delayTime: 300,
        }
    ),
    kit(
        'glitch-bread',
        'Glitch Crumb',
        'Glitch/IDM kit — broken, stuttered, experimental',
        ['glitch', 'idm', 'experimental'],
        {
            pads: [
                { ...createDefaultPad(0), name: 'Broken Kick', engineType: 'kick-analog', drive: 5, tune: -8 },
                { ...createDefaultPad(1), name: 'Noise Hit', engineType: 'snare-analog', tone: 0.9, drive: 4 },
                {
                    ...createDefaultPad(2),
                    name: 'Glitch CH',
                    engineType: 'fm-perc',
                    tune: 15,
                    decay: 0.05,
                    engineParams: { mod_ratio: 11, mod_amount: 7, feedback: 0.6 },
                },
                {
                    ...createDefaultPad(3),
                    name: 'Zap',
                    engineType: 'fm-perc',
                    decay: 0.08,
                    engineParams: { mod_ratio: 1, mod_amount: 8, feedback: 0.8 },
                },
                { ...createDefaultPad(4), name: 'Click', engineType: 'rimshot', drive: 3 },
                { ...createDefaultPad(5), name: 'Texture', engineType: 'shaker', tone: 0.9 },
                ...Array.from({ length: 10 }, (_, index) => createDefaultPad(6 + index)),
            ],
            lofiBits: 10,
            lofiRate: 22050,
            lofiMix: 0.3,
        }
    ),
    kit('latin-bread', 'Latin Loaf', 'Latin percussion — salsa, bossa, samba rhythms', ['latin', 'salsa', 'bossa'], {
        pads: [
            { ...createDefaultPad(0), name: 'Kick', engineType: 'kick-analog', decay: 0.2, tone: 0.4 },
            { ...createDefaultPad(1), name: 'Snare', engineType: 'snare-analog', tone: 0.5 },
            { ...createDefaultPad(2), name: 'CH', engineType: 'hihat-closed', chokeGroup: 1 },
            { ...createDefaultPad(3), name: 'OH', engineType: 'hihat-open', chokeGroup: 1 },
            { ...createDefaultPad(4), name: 'Conga Hi', engineType: 'modal-bongo', tune: 4 },
            { ...createDefaultPad(5), name: 'Conga Lo', engineType: 'modal-bongo', tune: -2 },
            { ...createDefaultPad(6), name: 'Timbale', engineType: 'modal-metal', tune: 8 },
            { ...createDefaultPad(7), name: 'Guiro', engineType: 'shaker' },
            { ...createDefaultPad(8), name: 'Clave', engineType: 'clave' },
            { ...createDefaultPad(9), name: 'Cowbell', engineType: 'cowbell' },
            {
                ...createDefaultPad(10),
                name: 'Agogo',
                engineType: 'fm-perc',
                tune: 10,
                decay: 0.3,
                engineParams: { mod_ratio: 2.8, mod_amount: 1.5 },
            },
            { ...createDefaultPad(11), name: 'Cabasa', engineType: 'shaker', tone: 0.7 },
            ...Array.from({ length: 4 }, (_, index) => createDefaultPad(12 + index)),
        ],
        reverbMix: 0.15,
    }),
];
