export { scheduleNote, getSynthParamsFromDevices, scheduleNoteOffline } from './builtinSynth';
export { addCvOutput } from './cvGate/cvOutputOperations/addCvOutput';
export { removeCvOutput } from './cvGate/cvOutputOperations/removeCvOutput';
export { setCvValue } from './cvGate/cvOutputOperations/setCvValue';
export { setVoltageStandard } from './cvGate/cvOutputOperations/setVoltageStandard';
export { setClockDivision } from './cvGate/cvOutputOperations/setClockDivision';
export { scheduleKitNote } from './drumKitSynth';
export { getDrumKitDefByIndex } from './drumSynthEngine/kitDefinitions/getDrumKitDefByIndex';
export { scheduleDrumKitNote } from './drumSynthEngine/kitDefinitions/scheduleDrumKitNote';
export { registerProSynthInstruments } from './proSynthInstruments';
