import { type PluginDescriptor } from '../DeviceParameterTypes';

/** Built-in instrument plugin descriptors (Synth, Drum Kit). */
export const BUILTIN_INSTRUMENT_DESCRIPTORS: PluginDescriptor[] = [
    {
        id: 'builtin-synth',
        name: 'Synth',
        vendor: 'Sourdaw',
        format: 'builtin',
        category: 'instrument',
        hasCustomUI: false,
        // Amp-envelope release keeps the voice sounding past the last note. The
        // synth variants inherit this declaration and override the value.
        tail: { kind: 'decaySeconds', parameterId: 'release', defaultSeconds: 0.3 },
        parameters: [
            {
                id: 'waveform',
                deviceId: 'builtin-synth',
                name: 'Waveform',
                type: 'choice',
                value: 2,
                defaultValue: 2,
                minValue: 0,
                maxValue: 3,
                unit: '',
                choices: ['Sine', 'Triangle', 'Sawtooth', 'Square'],
                automatable: false,
                hasAutomation: false,
            },
            {
                id: 'attack',
                deviceId: 'builtin-synth',
                name: 'Attack',
                type: 'float',
                value: 0.01,
                defaultValue: 0.01,
                minValue: 0.001,
                maxValue: 2,
                unit: 's',
                automatable: true,
                hasAutomation: false,
                scaling: 'log',
            },
            {
                id: 'decay',
                deviceId: 'builtin-synth',
                name: 'Decay',
                type: 'float',
                value: 0.2,
                defaultValue: 0.2,
                minValue: 0.001,
                maxValue: 2,
                unit: 's',
                automatable: true,
                hasAutomation: false,
                scaling: 'log',
            },
            {
                id: 'sustain',
                deviceId: 'builtin-synth',
                name: 'Sustain',
                type: 'float',
                value: 0.7,
                defaultValue: 0.7,
                minValue: 0,
                maxValue: 1,
                unit: '',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'release',
                deviceId: 'builtin-synth',
                name: 'Release',
                type: 'float',
                value: 0.3,
                defaultValue: 0.3,
                minValue: 0.001,
                maxValue: 5,
                unit: 's',
                automatable: true,
                hasAutomation: false,
                scaling: 'log',
            },
            {
                id: 'filterCutoff',
                deviceId: 'builtin-synth',
                name: 'Filter Cutoff',
                type: 'float',
                value: 5000,
                defaultValue: 5000,
                minValue: 20,
                maxValue: 20000,
                unit: 'Hz',
                automatable: true,
                hasAutomation: false,
                scaling: 'log',
            },
            {
                id: 'filterResonance',
                deviceId: 'builtin-synth',
                name: 'Filter Resonance',
                type: 'float',
                value: 1,
                defaultValue: 1,
                // `scheduleBuiltinSynthNote` assigns this to a
                // `BiquadFilterNode.Q`, and its own MPE-slide branch computes
                // `(slide / 127) * 20` — 0 at rest. The engine already produces
                // the value 0.1 claimed to forbid, and `factory-bass-sub` ships
                // `filterResonance: 0` for a deliberately unresonant sub.
                minValue: 0,
                maxValue: 20,
                unit: '',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'filterType',
                deviceId: 'builtin-synth',
                name: 'Filter Type',
                type: 'choice',
                value: 0,
                defaultValue: 0,
                minValue: 0,
                maxValue: 2,
                unit: '',
                choices: ['Lowpass', 'Highpass', 'Bandpass'],
                automatable: false,
                hasAutomation: false,
            },
            {
                id: 'filterEnvAmount',
                deviceId: 'builtin-synth',
                name: 'Filter Env',
                type: 'float',
                value: 0,
                defaultValue: 0,
                minValue: 0,
                maxValue: 10000,
                unit: 'Hz',
                automatable: true,
                hasAutomation: false,
                scaling: 'log',
            },
            {
                id: 'detune',
                deviceId: 'builtin-synth',
                name: 'Detune',
                type: 'float',
                value: 0,
                defaultValue: 0,
                minValue: -100,
                maxValue: 100,
                unit: 'cents',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'gain',
                deviceId: 'builtin-synth',
                name: 'Gain',
                type: 'float',
                value: 0.3,
                defaultValue: 0.3,
                minValue: 0,
                maxValue: 1,
                unit: '',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'osc2Waveform',
                deviceId: 'builtin-synth',
                name: 'Osc 2 Wave',
                type: 'choice',
                value: 2,
                defaultValue: 2,
                minValue: 0,
                maxValue: 3,
                unit: '',
                choices: ['Sine', 'Triangle', 'Sawtooth', 'Square'],
                automatable: false,
                hasAutomation: false,
            },
            {
                id: 'osc2Detune',
                deviceId: 'builtin-synth',
                name: 'Osc 2 Detune',
                type: 'float',
                value: 0,
                defaultValue: 0,
                minValue: -1200,
                maxValue: 1200,
                unit: 'cents',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'osc2Mix',
                deviceId: 'builtin-synth',
                name: 'Osc 2 Mix',
                type: 'float',
                value: 0,
                defaultValue: 0,
                minValue: 0,
                maxValue: 1,
                unit: '',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'subOscLevel',
                deviceId: 'builtin-synth',
                name: 'Sub-Osc Level',
                type: 'float',
                value: 0,
                defaultValue: 0,
                minValue: 0,
                maxValue: 1,
                unit: '',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'noiseLevel',
                deviceId: 'builtin-synth',
                name: 'Noise Level',
                type: 'float',
                value: 0,
                defaultValue: 0,
                minValue: 0,
                maxValue: 1,
                unit: '',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'vibratoRate',
                deviceId: 'builtin-synth',
                name: 'Vibrato Rate',
                type: 'float',
                value: 0,
                defaultValue: 0,
                minValue: 0,
                maxValue: 10,
                unit: 'Hz',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'vibratoDepth',
                deviceId: 'builtin-synth',
                name: 'Vibrato Depth',
                type: 'float',
                value: 0,
                defaultValue: 0,
                minValue: 0,
                maxValue: 50,
                unit: 'cents',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'stereoSpread',
                deviceId: 'builtin-synth',
                name: 'Stereo Spread',
                type: 'float',
                value: 0,
                defaultValue: 0,
                minValue: 0,
                maxValue: 1,
                unit: '',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'vibratoDelay',
                deviceId: 'builtin-synth',
                name: 'Vibrato Delay',
                type: 'float',
                value: 0.3,
                defaultValue: 0.3,
                minValue: 0,
                maxValue: 2,
                unit: 's',
                automatable: false,
                hasAutomation: false,
            },
            {
                id: 'filterVelocitySensitivity',
                deviceId: 'builtin-synth',
                name: 'Filter Velocity',
                type: 'float',
                value: 0,
                defaultValue: 0,
                minValue: 0,
                maxValue: 1,
                unit: '',
                automatable: false,
                hasAutomation: false,
            },
        ],
    },
    {
        id: 'builtin-drum-kit',
        name: 'Drum Kit',
        vendor: 'Sourdaw',
        format: 'builtin',
        category: 'instrument',
        hasCustomUI: false,
        parameters: [
            {
                id: 'kit',
                deviceId: 'builtin-drum-kit',
                name: 'Kit',
                type: 'choice',
                value: 0,
                defaultValue: 0,
                minValue: 0,
                maxValue: 5,
                unit: '',
                choices: ['808 Kit', 'Analog Kit', 'Electronic Kit', 'Acoustic Kit', 'Lo-fi Vinyl', 'Trap'],
                automatable: false,
                hasAutomation: false,
            },
            {
                id: 'gain',
                deviceId: 'builtin-drum-kit',
                name: 'Gain',
                type: 'float',
                value: 0.8,
                defaultValue: 0.8,
                minValue: 0,
                maxValue: 1,
                unit: '',
                automatable: true,
                hasAutomation: false,
            },
        ],
    },
    // ─── Native DSP (Rust/WASM) ─────────────────────────────────────────
];
