import { type PluginDescriptor } from '../DeviceParameterTypes';

/** Built-in effect plugin descriptors (EQ, Compressor, Reverb, Delay, etc.) */
export const BUILTIN_EFFECT_DESCRIPTORS: PluginDescriptor[] = [
    {
        id: 'builtin-eq',
        name: 'EQ',
        vendor: 'Sourdaw',
        format: 'builtin',
        category: 'effect',
        hasCustomUI: false,
        platform: 'both',
        parameters: [
            {
                id: 'eq-low-gain',
                deviceId: 'builtin-eq',
                name: 'Low Gain',
                type: 'float',
                value: 0,
                defaultValue: 0,
                minValue: -24,
                maxValue: 24,
                unit: 'dB',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'eq-low-freq',
                deviceId: 'builtin-eq',
                name: 'Low Freq',
                type: 'float',
                value: 100,
                defaultValue: 100,
                minValue: 20,
                maxValue: 500,
                unit: 'Hz',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'eq-low-q',
                deviceId: 'builtin-eq',
                name: 'Low Q',
                type: 'float',
                value: 1,
                defaultValue: 1,
                minValue: 0.1,
                maxValue: 10,
                unit: '',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'eq-mid-gain',
                deviceId: 'builtin-eq',
                name: 'Mid Gain',
                type: 'float',
                value: 0,
                defaultValue: 0,
                minValue: -24,
                maxValue: 24,
                unit: 'dB',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'eq-mid-freq',
                deviceId: 'builtin-eq',
                name: 'Mid Freq',
                type: 'float',
                value: 1000,
                defaultValue: 1000,
                minValue: 200,
                maxValue: 8000,
                unit: 'Hz',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'eq-mid-q',
                deviceId: 'builtin-eq',
                name: 'Mid Q',
                type: 'float',
                value: 1,
                defaultValue: 1,
                minValue: 0.1,
                maxValue: 10,
                unit: '',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'eq-high-gain',
                deviceId: 'builtin-eq',
                name: 'High Gain',
                type: 'float',
                value: 0,
                defaultValue: 0,
                minValue: -24,
                maxValue: 24,
                unit: 'dB',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'eq-high-freq',
                deviceId: 'builtin-eq',
                name: 'High Freq',
                type: 'float',
                value: 8000,
                defaultValue: 8000,
                minValue: 2000,
                maxValue: 20000,
                unit: 'Hz',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'eq-high-q',
                deviceId: 'builtin-eq',
                name: 'High Q',
                type: 'float',
                value: 1,
                defaultValue: 1,
                minValue: 0.1,
                maxValue: 10,
                unit: '',
                automatable: true,
                hasAutomation: false,
            },
        ],
    },
    {
        id: 'builtin-compressor',
        name: 'Compressor',
        vendor: 'Sourdaw',
        format: 'builtin',
        category: 'effect',
        hasCustomUI: false,
        platform: 'both',
        parameters: [
            {
                id: 'comp-threshold',
                deviceId: 'builtin-compressor',
                name: 'Threshold',
                type: 'float',
                value: -20,
                defaultValue: -20,
                minValue: -60,
                maxValue: 0,
                unit: 'dB',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'comp-ratio',
                deviceId: 'builtin-compressor',
                name: 'Ratio',
                type: 'float',
                value: 4,
                defaultValue: 4,
                minValue: 1,
                maxValue: 20,
                unit: ':1',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'comp-attack',
                deviceId: 'builtin-compressor',
                name: 'Attack',
                type: 'float',
                value: 10,
                defaultValue: 10,
                minValue: 0.1,
                maxValue: 100,
                unit: 'ms',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'comp-release',
                deviceId: 'builtin-compressor',
                name: 'Release',
                type: 'float',
                value: 100,
                defaultValue: 100,
                minValue: 10,
                maxValue: 1000,
                unit: 'ms',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'comp-knee',
                deviceId: 'builtin-compressor',
                name: 'Knee',
                type: 'float',
                value: 6,
                defaultValue: 6,
                minValue: 0,
                maxValue: 30,
                unit: 'dB',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'comp-makeup',
                deviceId: 'builtin-compressor',
                name: 'Makeup',
                type: 'float',
                value: 0,
                defaultValue: 0,
                minValue: 0,
                maxValue: 30,
                unit: 'dB',
                automatable: true,
                hasAutomation: false,
            },
        ],
    },
    {
        id: 'builtin-reverb',
        name: 'Reverb',
        vendor: 'Sourdaw',
        format: 'builtin',
        category: 'effect',
        hasCustomUI: false,
        platform: 'both',
        // The audible tail is the impulse response, which `createReverb` bakes at a
        // fixed `sampleRate * 2` — exactly 2 s — when the node is built.
        //
        // It deliberately does NOT read `rev-decay`. That knob reaches no audio
        // node: `applyReverbParams` has no `rev-decay` branch, a boundary pinned by
        // `applyReverbParams.spec.ts` ("does not consume rev-decay") and documented
        // at `AdjustmentBusNode.ts:44-49`. Declaring the tail from it made every
        // export reserve or truncate on a number the user cannot hear — "Ambient
        // Wash" (`rev-decay: 8`) bought 8 s of dead air, "Tight Room" (0.4) cut the
        // real 2 s tail short.
        //
        // Deriving seconds from `rev-decay` anyway would be inventing a conversion
        // for a dead control. If real decay support lands (Architecture-decision
        // #1), wire the DSP first and change this declaration in the same commit.
        // Pre-delay is genuinely honoured, so it still counts.
        tail: { kind: 'fixed', seconds: 2, predelayMsParameterId: 'rev-predelay' },
        parameters: [
            {
                id: 'rev-size',
                deviceId: 'builtin-reverb',
                name: 'Size',
                type: 'float',
                value: 0.5,
                defaultValue: 0.5,
                minValue: 0,
                maxValue: 1,
                unit: '',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'rev-decay',
                deviceId: 'builtin-reverb',
                name: 'Decay',
                type: 'float',
                value: 2,
                defaultValue: 2,
                minValue: 0.1,
                maxValue: 20,
                unit: 's',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'rev-damping',
                deviceId: 'builtin-reverb',
                name: 'Damping',
                type: 'float',
                value: 0.5,
                defaultValue: 0.5,
                minValue: 0,
                maxValue: 1,
                unit: '',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'rev-predelay',
                deviceId: 'builtin-reverb',
                name: 'Pre-Delay',
                type: 'float',
                value: 10,
                defaultValue: 10,
                minValue: 0,
                maxValue: 200,
                unit: 'ms',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'rev-lowcut',
                deviceId: 'builtin-reverb',
                name: 'Low Cut',
                type: 'float',
                value: 80,
                defaultValue: 80,
                minValue: 20,
                maxValue: 2000,
                unit: 'Hz',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'rev-mix',
                deviceId: 'builtin-reverb',
                name: 'Dry/Wet',
                type: 'float',
                value: 0.3,
                defaultValue: 0.3,
                minValue: 0,
                maxValue: 1,
                unit: '',
                automatable: true,
                hasAutomation: false,
            },
        ],
    },
    {
        id: 'builtin-delay',
        name: 'Delay',
        vendor: 'Sourdaw',
        format: 'builtin',
        category: 'effect',
        hasCustomUI: false,
        platform: 'both',
        tail: {
            kind: 'feedbackLoop',
            feedbackParameterId: 'delay-feedback',
            defaultFeedback: 0.4,
            maxFeedback: 0.95,
            loopParameterId: 'delay-time',
            loopUnit: 'ms',
            defaultLoopSeconds: 0.25,
        },
        parameters: [
            {
                id: 'delay-time',
                deviceId: 'builtin-delay',
                name: 'Time',
                type: 'float',
                value: 250,
                defaultValue: 250,
                minValue: 1,
                maxValue: 2000,
                unit: 'ms',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'delay-feedback',
                deviceId: 'builtin-delay',
                name: 'Feedback',
                type: 'float',
                value: 0.4,
                defaultValue: 0.4,
                minValue: 0,
                maxValue: 0.95,
                unit: '',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'delay-lowcut',
                deviceId: 'builtin-delay',
                name: 'Low Cut',
                type: 'float',
                value: 80,
                defaultValue: 80,
                minValue: 20,
                maxValue: 2000,
                unit: 'Hz',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'delay-highcut',
                deviceId: 'builtin-delay',
                name: 'High Cut',
                type: 'float',
                value: 12000,
                defaultValue: 12000,
                minValue: 1000,
                maxValue: 20000,
                unit: 'Hz',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'delay-mix',
                deviceId: 'builtin-delay',
                name: 'Dry/Wet',
                type: 'float',
                value: 0.3,
                defaultValue: 0.3,
                minValue: 0,
                maxValue: 1,
                unit: '',
                automatable: true,
                hasAutomation: false,
            },
        ],
    },
    {
        id: 'builtin-gain',
        name: 'Gain',
        vendor: 'Sourdaw',
        format: 'builtin',
        category: 'utility',
        hasCustomUI: false,
        platform: 'both',
        parameters: [
            {
                id: 'gain-level',
                deviceId: 'builtin-gain',
                name: 'Gain',
                type: 'float',
                value: 0,
                defaultValue: 0,
                minValue: -60,
                maxValue: 24,
                unit: 'dB',
                automatable: true,
                hasAutomation: false,
            },
        ],
    },
    {
        id: 'builtin-sidechain-compressor',
        name: 'Sidechain Compressor',
        vendor: 'Sourdaw',
        format: 'builtin',
        category: 'effect',
        hasCustomUI: false,
        parameters: [
            {
                id: 'sc-comp-threshold',
                deviceId: 'builtin-sidechain-compressor',
                name: 'Threshold',
                type: 'float',
                value: -20,
                defaultValue: -20,
                minValue: -60,
                maxValue: 0,
                unit: 'dB',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'sc-comp-ratio',
                deviceId: 'builtin-sidechain-compressor',
                name: 'Ratio',
                type: 'float',
                value: 4,
                defaultValue: 4,
                minValue: 1,
                maxValue: 20,
                unit: ':1',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'sc-comp-attack',
                deviceId: 'builtin-sidechain-compressor',
                name: 'Attack',
                type: 'float',
                value: 10,
                defaultValue: 10,
                minValue: 1,
                maxValue: 100,
                unit: 'ms',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'sc-comp-release',
                deviceId: 'builtin-sidechain-compressor',
                name: 'Release',
                type: 'float',
                value: 100,
                defaultValue: 100,
                minValue: 10,
                maxValue: 1000,
                unit: 'ms',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'sc-comp-makeup',
                deviceId: 'builtin-sidechain-compressor',
                name: 'Makeup',
                type: 'float',
                value: 0,
                defaultValue: 0,
                minValue: 0,
                maxValue: 30,
                unit: 'dB',
                automatable: true,
                hasAutomation: false,
            },
        ],
    },
    {
        id: 'builtin-chorus',
        name: 'Chorus',
        vendor: 'Sourdaw',
        format: 'builtin',
        category: 'effect',
        hasCustomUI: false,
        parameters: [
            {
                id: 'chorus-rate',
                deviceId: 'builtin-chorus',
                name: 'Rate',
                type: 'float',
                value: 1.5,
                defaultValue: 1.5,
                minValue: 0.1,
                maxValue: 10,
                unit: 'Hz',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'chorus-depth',
                deviceId: 'builtin-chorus',
                name: 'Depth',
                type: 'float',
                value: 5,
                defaultValue: 5,
                minValue: 0,
                maxValue: 20,
                unit: 'ms',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'chorus-feedback',
                deviceId: 'builtin-chorus',
                name: 'Feedback',
                type: 'float',
                value: 0.2,
                defaultValue: 0.2,
                minValue: 0,
                maxValue: 0.9,
                unit: '',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'chorus-mix',
                deviceId: 'builtin-chorus',
                name: 'Dry/Wet',
                type: 'float',
                value: 0.5,
                defaultValue: 0.5,
                minValue: 0,
                maxValue: 1,
                unit: '',
                automatable: true,
                hasAutomation: false,
            },
        ],
    },
    {
        id: 'builtin-phaser',
        name: 'Phaser',
        vendor: 'Sourdaw',
        format: 'builtin',
        category: 'effect',
        hasCustomUI: false,
        parameters: [
            {
                id: 'phaser-rate',
                deviceId: 'builtin-phaser',
                name: 'Rate',
                type: 'float',
                value: 0.5,
                defaultValue: 0.5,
                // `applyPhaserParams` assigns this to the sweep
                // `OscillatorNode.frequency`, which accepts any rate down to a
                // stopped LFO at 0 Hz; the old 0.1 was the knob's floor, and it
                // sat above values this repo already ships (Nebula Drift's
                // 0.05/0.06 and an 0.08 automation point, `synth-pad-dark-drone`'s
                // 0.05). Kept as `uiMinValue` so the knob still bottoms out
                // somewhere useful.
                minValue: 0,
                maxValue: 10,
                uiMinValue: 0.1,
                unit: 'Hz',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'phaser-depth',
                deviceId: 'builtin-phaser',
                name: 'Depth',
                type: 'float',
                value: 0.7,
                defaultValue: 0.7,
                minValue: 0,
                maxValue: 1,
                unit: '',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'phaser-feedback',
                deviceId: 'builtin-phaser',
                name: 'Feedback',
                type: 'float',
                value: 0.3,
                defaultValue: 0.3,
                minValue: 0,
                maxValue: 0.9,
                unit: '',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'phaser-stages',
                deviceId: 'builtin-phaser',
                name: 'Stages',
                type: 'int',
                value: 4,
                defaultValue: 4,
                minValue: 2,
                maxValue: 12,
                unit: '',
                automatable: false,
                hasAutomation: false,
            },
        ],
    },
    {
        id: 'builtin-distortion',
        name: 'Distortion',
        vendor: 'Sourdaw',
        format: 'builtin',
        category: 'effect',
        hasCustomUI: false,
        parameters: [
            {
                id: 'dist-drive',
                deviceId: 'builtin-distortion',
                name: 'Drive',
                type: 'float',
                value: 20,
                defaultValue: 20,
                minValue: 0,
                maxValue: 100,
                unit: '',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'dist-tone',
                deviceId: 'builtin-distortion',
                name: 'Tone',
                type: 'float',
                value: 4000,
                defaultValue: 4000,
                minValue: 200,
                maxValue: 8000,
                unit: 'Hz',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'dist-output',
                deviceId: 'builtin-distortion',
                name: 'Output Level',
                type: 'float',
                value: 0,
                defaultValue: 0,
                minValue: -24,
                maxValue: 0,
                unit: 'dB',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'dist-mix',
                deviceId: 'builtin-distortion',
                name: 'Dry/Wet',
                type: 'float',
                value: 0.5,
                defaultValue: 0.5,
                minValue: 0,
                maxValue: 1,
                unit: '',
                automatable: true,
                hasAutomation: false,
            },
        ],
    },
    {
        id: 'builtin-limiter',
        name: 'Limiter',
        vendor: 'Sourdaw',
        format: 'builtin',
        category: 'effect',
        hasCustomUI: false,
        platform: 'both',
        parameters: [
            {
                id: 'lim-threshold',
                deviceId: 'builtin-limiter',
                name: 'Threshold',
                type: 'float',
                value: -6,
                defaultValue: -6,
                minValue: -30,
                maxValue: 0,
                unit: 'dB',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'lim-release',
                deviceId: 'builtin-limiter',
                name: 'Release',
                type: 'float',
                value: 100,
                defaultValue: 100,
                minValue: 10,
                maxValue: 500,
                unit: 'ms',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'lim-ceiling',
                deviceId: 'builtin-limiter',
                name: 'Ceiling',
                type: 'float',
                value: -0.3,
                defaultValue: -0.3,
                minValue: -3,
                maxValue: 0,
                unit: 'dB',
                automatable: true,
                hasAutomation: false,
            },
        ],
    },
    {
        id: 'builtin-flanger',
        name: 'Flanger',
        vendor: 'Sourdaw',
        format: 'builtin',
        category: 'effect',
        hasCustomUI: false,
        parameters: [
            {
                id: 'flanger-rate',
                deviceId: 'builtin-flanger',
                name: 'Rate',
                type: 'float',
                value: 0.3,
                defaultValue: 0.3,
                minValue: 0.05,
                maxValue: 5,
                unit: 'Hz',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'flanger-depth',
                deviceId: 'builtin-flanger',
                name: 'Depth',
                type: 'float',
                value: 3,
                defaultValue: 3,
                minValue: 0,
                maxValue: 10,
                unit: 'ms',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'flanger-feedback',
                deviceId: 'builtin-flanger',
                name: 'Feedback',
                type: 'float',
                value: 0.5,
                defaultValue: 0.5,
                minValue: 0,
                maxValue: 0.95,
                unit: '',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'flanger-mix',
                deviceId: 'builtin-flanger',
                name: 'Dry/Wet',
                type: 'float',
                value: 0.5,
                defaultValue: 0.5,
                minValue: 0,
                maxValue: 1,
                unit: '',
                automatable: true,
                hasAutomation: false,
            },
        ],
    },
    {
        id: 'builtin-tremolo',
        name: 'Tremolo',
        vendor: 'Sourdaw',
        format: 'builtin',
        category: 'effect',
        hasCustomUI: false,
        parameters: [
            {
                id: 'trem-rate',
                deviceId: 'builtin-tremolo',
                name: 'Rate',
                type: 'float',
                value: 4,
                defaultValue: 4,
                minValue: 0.1,
                maxValue: 20,
                unit: 'Hz',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'trem-depth',
                deviceId: 'builtin-tremolo',
                name: 'Depth',
                type: 'float',
                value: 0.5,
                defaultValue: 0.5,
                minValue: 0,
                maxValue: 1,
                unit: '',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'trem-shape',
                deviceId: 'builtin-tremolo',
                name: 'Shape',
                type: 'choice',
                value: 0,
                defaultValue: 0,
                minValue: 0,
                maxValue: 1,
                unit: '',
                choices: ['Sine', 'Square'],
                automatable: false,
                hasAutomation: false,
            },
        ],
    },
    {
        id: 'builtin-bitcrusher',
        name: 'Bitcrusher',
        vendor: 'Sourdaw',
        format: 'builtin',
        category: 'effect',
        hasCustomUI: false,
        parameters: [
            {
                id: 'crush-bits',
                deviceId: 'builtin-bitcrusher',
                name: 'Bit Depth',
                type: 'int',
                value: 8,
                defaultValue: 8,
                minValue: 1,
                maxValue: 16,
                unit: 'bit',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'crush-rate',
                deviceId: 'builtin-bitcrusher',
                name: 'Rate Reduction',
                type: 'float',
                value: 1,
                defaultValue: 1,
                minValue: 1,
                maxValue: 40,
                unit: 'x',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'crush-mix',
                deviceId: 'builtin-bitcrusher',
                name: 'Dry/Wet',
                type: 'float',
                value: 0.5,
                defaultValue: 0.5,
                minValue: 0,
                maxValue: 1,
                unit: '',
                automatable: true,
                hasAutomation: false,
            },
        ],
    },
    {
        id: 'builtin-filter',
        name: 'Filter',
        vendor: 'Sourdaw',
        format: 'builtin',
        category: 'effect',
        hasCustomUI: false,
        parameters: [
            {
                id: 'filter-cutoff',
                deviceId: 'builtin-filter',
                name: 'Cutoff',
                type: 'float',
                value: 1000,
                defaultValue: 1000,
                minValue: 20,
                maxValue: 20000,
                unit: 'Hz',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'filter-resonance',
                deviceId: 'builtin-filter',
                name: 'Resonance',
                type: 'float',
                value: 1,
                defaultValue: 1,
                minValue: 0.1,
                maxValue: 20,
                unit: '',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'filter-type',
                deviceId: 'builtin-filter',
                name: 'Type',
                type: 'choice',
                value: 0,
                defaultValue: 0,
                minValue: 0,
                maxValue: 3,
                unit: '',
                choices: ['Lowpass', 'Highpass', 'Bandpass', 'Notch'],
                automatable: false,
                hasAutomation: false,
            },
        ],
    },
    {
        id: 'builtin-autopan',
        name: 'Auto-Pan',
        vendor: 'Sourdaw',
        format: 'builtin',
        category: 'effect',
        hasCustomUI: false,
        parameters: [
            {
                id: 'autopan-rate',
                deviceId: 'builtin-autopan',
                name: 'Rate',
                type: 'float',
                value: 2,
                defaultValue: 2,
                // Same story as `phaser-rate`: `applyAutoPanParams` writes it
                // to an `OscillatorNode.frequency`, and Nebula Drift ships a
                // 0.06 pan rate with a lane riding it to 0.07.
                minValue: 0,
                maxValue: 10,
                uiMinValue: 0.1,
                unit: 'Hz',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'autopan-depth',
                deviceId: 'builtin-autopan',
                name: 'Depth',
                type: 'float',
                value: 0.7,
                defaultValue: 0.7,
                minValue: 0,
                maxValue: 1,
                unit: '',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'autopan-shape',
                deviceId: 'builtin-autopan',
                name: 'Shape',
                type: 'choice',
                value: 0,
                defaultValue: 0,
                minValue: 0,
                maxValue: 1,
                unit: '',
                choices: ['Sine', 'Triangle'],
                automatable: false,
                hasAutomation: false,
            },
        ],
    },
    {
        id: 'builtin-convolution-reverb',
        name: 'Convolution Reverb',
        vendor: 'Sourdaw',
        format: 'builtin',
        category: 'effect',
        hasCustomUI: false,
        // The impulse response sets the tail and no exposed parameter reports its
        // length, so reserve a constant that covers the bundled IRs.
        tail: { kind: 'fixed', seconds: 6 },
        parameters: [
            {
                id: 'conv-ir',
                deviceId: 'builtin-convolution-reverb',
                name: 'IR Type',
                type: 'choice',
                value: 6,
                defaultValue: 6,
                minValue: 0,
                maxValue: 9,
                unit: '',
                choices: [
                    'Small Room',
                    'Large Hall',
                    'Cathedral',
                    'Plate',
                    'Spring',
                    'Chamber',
                    'Studio A',
                    'Studio B',
                    'Warehouse',
                    'Tunnel',
                ],
                automatable: false,
                hasAutomation: false,
            },
            {
                id: 'conv-mix',
                deviceId: 'builtin-convolution-reverb',
                name: 'Mix',
                type: 'float',
                value: 0.4,
                defaultValue: 0.4,
                minValue: 0,
                maxValue: 1,
                unit: '',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'conv-predelay',
                deviceId: 'builtin-convolution-reverb',
                name: 'Predelay',
                type: 'float',
                value: 10,
                defaultValue: 10,
                minValue: 0,
                maxValue: 200,
                unit: 'ms',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'conv-lowcut',
                deviceId: 'builtin-convolution-reverb',
                name: 'Low Cut',
                type: 'float',
                value: 60,
                defaultValue: 60,
                minValue: 20,
                maxValue: 500,
                unit: 'Hz',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'conv-highcut',
                deviceId: 'builtin-convolution-reverb',
                name: 'High Cut',
                type: 'float',
                value: 12000,
                defaultValue: 12000,
                minValue: 1000,
                maxValue: 20000,
                unit: 'Hz',
                automatable: true,
                hasAutomation: false,
            },
        ],
    },
    {
        id: 'builtin-stereo-widener',
        name: 'Stereo Widener',
        vendor: 'Sourdaw',
        format: 'builtin',
        category: 'utility',
        hasCustomUI: false,
        platform: 'both',
        parameters: [
            {
                id: 'width-amount',
                deviceId: 'builtin-stereo-widener',
                name: 'Width',
                type: 'float',
                value: 1,
                defaultValue: 1,
                minValue: 0,
                maxValue: 3,
                unit: '',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'width-mid',
                deviceId: 'builtin-stereo-widener',
                name: 'Mid Level',
                type: 'float',
                value: 0,
                defaultValue: 0,
                minValue: -12,
                maxValue: 6,
                unit: 'dB',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'width-side',
                deviceId: 'builtin-stereo-widener',
                name: 'Side Level',
                type: 'float',
                value: 0,
                defaultValue: 0,
                minValue: -12,
                maxValue: 6,
                unit: 'dB',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'width-mono-bass',
                deviceId: 'builtin-stereo-widener',
                name: 'Mono Bass',
                type: 'float',
                value: 200,
                defaultValue: 200,
                minValue: 20,
                maxValue: 500,
                unit: 'Hz',
                automatable: true,
                hasAutomation: false,
            },
        ],
    },
    {
        id: 'builtin-deesser',
        name: 'De-esser',
        vendor: 'Sourdaw',
        format: 'builtin',
        category: 'effect',
        hasCustomUI: false,
        platform: 'both',
        parameters: [
            {
                id: 'deess-threshold',
                deviceId: 'builtin-deesser',
                name: 'Threshold',
                type: 'float',
                value: -20,
                defaultValue: -20,
                minValue: -40,
                maxValue: 0,
                unit: 'dB',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'deess-freq',
                deviceId: 'builtin-deesser',
                name: 'Frequency',
                type: 'float',
                value: 6000,
                defaultValue: 6000,
                minValue: 2000,
                maxValue: 12000,
                unit: 'Hz',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'deess-range',
                deviceId: 'builtin-deesser',
                name: 'Range',
                type: 'float',
                value: -12,
                defaultValue: -12,
                minValue: -30,
                maxValue: 0,
                unit: 'dB',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'deess-listen',
                deviceId: 'builtin-deesser',
                name: 'Listen',
                type: 'bool',
                value: 0,
                defaultValue: 0,
                minValue: 0,
                maxValue: 1,
                unit: '',
                automatable: false,
                hasAutomation: false,
            },
        ],
    },
    {
        id: 'builtin-lufs-meter',
        name: 'LUFS Meter',
        vendor: 'Sourdaw',
        format: 'builtin',
        category: 'analyzer',
        hasCustomUI: false,
        platform: 'both',
        parameters: [
            {
                id: 'lufs-target',
                deviceId: 'builtin-lufs-meter',
                name: 'Target LUFS',
                type: 'float',
                value: -14,
                defaultValue: -14,
                minValue: -30,
                maxValue: -6,
                unit: 'LUFS',
                automatable: false,
                hasAutomation: false,
            },
            {
                id: 'lufs-window',
                deviceId: 'builtin-lufs-meter',
                name: 'Window',
                type: 'choice',
                value: 0,
                defaultValue: 0,
                minValue: 0,
                maxValue: 2,
                unit: '',
                choices: ['Momentary', 'Short-term', 'Integrated'],
                automatable: false,
                hasAutomation: false,
            },
        ],
    },
];
