import { type PluginDescriptor } from '../DeviceParameterTypes';

import { applyDescriptorGuidance, descriptorGuidance, parameterGuidance } from './DescriptorGuidance';
import { analysisGuidance, declaredControl, effectGuidance } from './GuidanceProfiles';

/** Built-in effect plugin descriptors (EQ, Compressor, Reverb, Delay, etc.) */
const BUILTIN_EFFECT_DESCRIPTOR_DATA: PluginDescriptor[] = [
    {
        id: 'builtin-eq',
        name: 'EQ',
        vendor: 'Sourdaw',
        format: 'builtin',
        category: 'effect',
        hasCustomUI: false,
        platform: 'both',
        parameters: [
            {
                id: 'eq-low-gain',
                deviceId: 'builtin-eq',
                name: 'Low Gain',
                type: 'float',
                value: 0,
                defaultValue: 0,
                minValue: -24,
                maxValue: 24,
                unit: 'dB',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'eq-low-freq',
                deviceId: 'builtin-eq',
                name: 'Low Freq',
                type: 'float',
                value: 100,
                defaultValue: 100,
                minValue: 20,
                maxValue: 500,
                unit: 'Hz',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'eq-low-q',
                deviceId: 'builtin-eq',
                name: 'Low Q',
                type: 'float',
                value: 1,
                defaultValue: 1,
                minValue: 0.1,
                maxValue: 10,
                unit: '',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'eq-mid-gain',
                deviceId: 'builtin-eq',
                name: 'Mid Gain',
                type: 'float',
                value: 0,
                defaultValue: 0,
                minValue: -24,
                maxValue: 24,
                unit: 'dB',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'eq-mid-freq',
                deviceId: 'builtin-eq',
                name: 'Mid Freq',
                type: 'float',
                value: 1000,
                defaultValue: 1000,
                minValue: 200,
                maxValue: 8000,
                unit: 'Hz',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'eq-mid-q',
                deviceId: 'builtin-eq',
                name: 'Mid Q',
                type: 'float',
                value: 1,
                defaultValue: 1,
                minValue: 0.1,
                maxValue: 10,
                unit: '',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'eq-high-gain',
                deviceId: 'builtin-eq',
                name: 'High Gain',
                type: 'float',
                value: 0,
                defaultValue: 0,
                minValue: -24,
                maxValue: 24,
                unit: 'dB',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'eq-high-freq',
                deviceId: 'builtin-eq',
                name: 'High Freq',
                type: 'float',
                value: 8000,
                defaultValue: 8000,
                minValue: 2000,
                maxValue: 20000,
                unit: 'Hz',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'eq-high-q',
                deviceId: 'builtin-eq',
                name: 'High Q',
                type: 'float',
                value: 1,
                defaultValue: 1,
                minValue: 0.1,
                maxValue: 10,
                unit: '',
                automatable: true,
                hasAutomation: false,
            },
        ],
    },
    {
        id: 'builtin-compressor',
        name: 'Compressor',
        vendor: 'Sourdaw',
        format: 'builtin',
        category: 'effect',
        hasCustomUI: false,
        platform: 'both',
        parameters: [
            {
                id: 'comp-threshold',
                deviceId: 'builtin-compressor',
                name: 'Threshold',
                type: 'float',
                value: -20,
                defaultValue: -20,
                minValue: -60,
                maxValue: 0,
                unit: 'dB',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'comp-ratio',
                deviceId: 'builtin-compressor',
                name: 'Ratio',
                type: 'float',
                value: 4,
                defaultValue: 4,
                minValue: 1,
                maxValue: 20,
                unit: ':1',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'comp-attack',
                deviceId: 'builtin-compressor',
                name: 'Attack',
                type: 'float',
                value: 10,
                defaultValue: 10,
                minValue: 0.1,
                maxValue: 100,
                unit: 'ms',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'comp-release',
                deviceId: 'builtin-compressor',
                name: 'Release',
                type: 'float',
                value: 100,
                defaultValue: 100,
                minValue: 10,
                maxValue: 1000,
                unit: 'ms',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'comp-knee',
                deviceId: 'builtin-compressor',
                name: 'Knee',
                type: 'float',
                value: 6,
                defaultValue: 6,
                minValue: 0,
                maxValue: 30,
                unit: 'dB',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'comp-makeup',
                deviceId: 'builtin-compressor',
                name: 'Makeup',
                type: 'float',
                value: 0,
                defaultValue: 0,
                minValue: 0,
                maxValue: 30,
                unit: 'dB',
                automatable: true,
                hasAutomation: false,
            },
        ],
    },
    {
        id: 'builtin-reverb',
        name: 'Reverb',
        vendor: 'Sourdaw',
        format: 'builtin',
        category: 'effect',
        hasCustomUI: false,
        platform: 'both',
        // The audible tail is the impulse response, which `createReverb` bakes at a
        // fixed `sampleRate * 2` — exactly 2 s — when the node is built.
        //
        // It deliberately does NOT read `rev-decay`. That knob reaches no audio
        // node: `applyReverbParams` has no `rev-decay` branch, a boundary pinned by
        // `applyReverbParams.spec.ts` ("does not consume rev-decay") and documented
        // at `AdjustmentBusNode.ts:44-49`. Declaring the tail from it made every
        // export reserve or truncate on a number the user cannot hear — "Ambient
        // Wash" (`rev-decay: 8`) bought 8 s of dead air, "Tight Room" (0.4) cut the
        // real 2 s tail short.
        //
        // Deriving seconds from `rev-decay` anyway would be inventing a conversion
        // for a dead control. If real decay support lands (Architecture-decision
        // #1), wire the DSP first and change this declaration in the same commit.
        // Pre-delay is genuinely honoured, so it still counts.
        tail: { kind: 'fixed', seconds: 2, predelayMsParameterId: 'rev-predelay' },
        parameters: [
            {
                id: 'rev-size',
                deviceId: 'builtin-reverb',
                name: 'Size',
                type: 'float',
                value: 0.5,
                defaultValue: 0.5,
                minValue: 0,
                maxValue: 1,
                unit: '',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'rev-decay',
                deviceId: 'builtin-reverb',
                name: 'Decay',
                type: 'float',
                value: 2,
                defaultValue: 2,
                minValue: 0.1,
                maxValue: 20,
                unit: 's',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'rev-damping',
                deviceId: 'builtin-reverb',
                name: 'Damping',
                type: 'float',
                value: 0.5,
                defaultValue: 0.5,
                minValue: 0,
                maxValue: 1,
                unit: '',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'rev-predelay',
                deviceId: 'builtin-reverb',
                name: 'Pre-Delay',
                type: 'float',
                value: 10,
                defaultValue: 10,
                minValue: 0,
                maxValue: 200,
                unit: 'ms',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'rev-lowcut',
                deviceId: 'builtin-reverb',
                name: 'Low Cut',
                type: 'float',
                value: 80,
                defaultValue: 80,
                minValue: 20,
                maxValue: 2000,
                unit: 'Hz',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'rev-mix',
                deviceId: 'builtin-reverb',
                name: 'Dry/Wet',
                type: 'float',
                value: 0.3,
                defaultValue: 0.3,
                minValue: 0,
                maxValue: 1,
                unit: '',
                automatable: true,
                hasAutomation: false,
            },
        ],
    },
    {
        id: 'builtin-delay',
        name: 'Delay',
        vendor: 'Sourdaw',
        format: 'builtin',
        category: 'effect',
        hasCustomUI: false,
        platform: 'both',
        tail: {
            kind: 'feedbackLoop',
            feedbackParameterId: 'delay-feedback',
            defaultFeedback: 0.4,
            maxFeedback: 0.95,
            loopParameterId: 'delay-time',
            loopUnit: 'ms',
            defaultLoopSeconds: 0.25,
        },
        parameters: [
            {
                id: 'delay-time',
                deviceId: 'builtin-delay',
                name: 'Time',
                type: 'float',
                value: 250,
                defaultValue: 250,
                minValue: 1,
                maxValue: 2000,
                unit: 'ms',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'delay-feedback',
                deviceId: 'builtin-delay',
                name: 'Feedback',
                type: 'float',
                value: 0.4,
                defaultValue: 0.4,
                minValue: 0,
                maxValue: 0.95,
                unit: '',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'delay-lowcut',
                deviceId: 'builtin-delay',
                name: 'Low Cut',
                type: 'float',
                value: 80,
                defaultValue: 80,
                minValue: 20,
                maxValue: 2000,
                unit: 'Hz',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'delay-highcut',
                deviceId: 'builtin-delay',
                name: 'High Cut',
                type: 'float',
                value: 12000,
                defaultValue: 12000,
                minValue: 1000,
                maxValue: 20000,
                unit: 'Hz',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'delay-mix',
                deviceId: 'builtin-delay',
                name: 'Dry/Wet',
                type: 'float',
                value: 0.3,
                defaultValue: 0.3,
                minValue: 0,
                maxValue: 1,
                unit: '',
                automatable: true,
                hasAutomation: false,
            },
        ],
    },
    {
        id: 'builtin-gain',
        name: 'Gain',
        vendor: 'Sourdaw',
        format: 'builtin',
        category: 'utility',
        hasCustomUI: false,
        platform: 'both',
        parameters: [
            {
                id: 'gain-level',
                deviceId: 'builtin-gain',
                name: 'Gain',
                type: 'float',
                value: 0,
                defaultValue: 0,
                minValue: -60,
                maxValue: 24,
                unit: 'dB',
                automatable: true,
                hasAutomation: false,
            },
        ],
    },
    {
        id: 'builtin-sidechain-compressor',
        name: 'Sidechain Compressor',
        vendor: 'Sourdaw',
        format: 'builtin',
        category: 'effect',
        hasCustomUI: false,
        parameters: [
            {
                id: 'sc-comp-threshold',
                deviceId: 'builtin-sidechain-compressor',
                name: 'Threshold',
                type: 'float',
                value: -20,
                defaultValue: -20,
                minValue: -60,
                maxValue: 0,
                unit: 'dB',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'sc-comp-ratio',
                deviceId: 'builtin-sidechain-compressor',
                name: 'Ratio',
                type: 'float',
                value: 4,
                defaultValue: 4,
                minValue: 1,
                maxValue: 20,
                unit: ':1',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'sc-comp-attack',
                deviceId: 'builtin-sidechain-compressor',
                name: 'Attack',
                type: 'float',
                value: 10,
                defaultValue: 10,
                minValue: 1,
                maxValue: 100,
                unit: 'ms',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'sc-comp-release',
                deviceId: 'builtin-sidechain-compressor',
                name: 'Release',
                type: 'float',
                value: 100,
                defaultValue: 100,
                minValue: 10,
                maxValue: 1000,
                unit: 'ms',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'sc-comp-makeup',
                deviceId: 'builtin-sidechain-compressor',
                name: 'Makeup',
                type: 'float',
                value: 0,
                defaultValue: 0,
                minValue: 0,
                maxValue: 30,
                unit: 'dB',
                automatable: true,
                hasAutomation: false,
            },
        ],
    },
    {
        id: 'builtin-chorus',
        name: 'Chorus',
        vendor: 'Sourdaw',
        format: 'builtin',
        category: 'effect',
        hasCustomUI: false,
        parameters: [
            {
                id: 'chorus-rate',
                deviceId: 'builtin-chorus',
                name: 'Rate',
                type: 'float',
                value: 1.5,
                defaultValue: 1.5,
                minValue: 0.1,
                maxValue: 10,
                unit: 'Hz',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'chorus-depth',
                deviceId: 'builtin-chorus',
                name: 'Depth',
                type: 'float',
                value: 5,
                defaultValue: 5,
                minValue: 0,
                maxValue: 20,
                unit: 'ms',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'chorus-feedback',
                deviceId: 'builtin-chorus',
                name: 'Feedback',
                type: 'float',
                value: 0.2,
                defaultValue: 0.2,
                minValue: 0,
                maxValue: 0.9,
                unit: '',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'chorus-mix',
                deviceId: 'builtin-chorus',
                name: 'Dry/Wet',
                type: 'float',
                value: 0.5,
                defaultValue: 0.5,
                minValue: 0,
                maxValue: 1,
                unit: '',
                automatable: true,
                hasAutomation: false,
            },
        ],
    },
    {
        id: 'builtin-phaser',
        name: 'Phaser',
        vendor: 'Sourdaw',
        format: 'builtin',
        category: 'effect',
        hasCustomUI: false,
        parameters: [
            {
                id: 'phaser-rate',
                deviceId: 'builtin-phaser',
                name: 'Rate',
                type: 'float',
                value: 0.5,
                defaultValue: 0.5,
                // `applyPhaserParams` assigns this to the sweep
                // `OscillatorNode.frequency`, which accepts any rate down to a
                // stopped LFO at 0 Hz. The old 0.1 was the knob's floor, and it
                // sat above values this repo already ships (Nebula Drift's
                // 0.05/0.06 and an 0.08 automation point,
                // `synth-pad-dark-drone`'s 0.05).
                minValue: 0,
                maxValue: 10,
                unit: 'Hz',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'phaser-depth',
                deviceId: 'builtin-phaser',
                name: 'Depth',
                type: 'float',
                value: 0.7,
                defaultValue: 0.7,
                minValue: 0,
                maxValue: 1,
                unit: '',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'phaser-feedback',
                deviceId: 'builtin-phaser',
                name: 'Feedback',
                type: 'float',
                value: 0.3,
                defaultValue: 0.3,
                minValue: 0,
                maxValue: 0.9,
                unit: '',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'phaser-stages',
                deviceId: 'builtin-phaser',
                name: 'Stages',
                type: 'int',
                value: 4,
                defaultValue: 4,
                minValue: 2,
                maxValue: 12,
                unit: '',
                automatable: false,
                hasAutomation: false,
            },
        ],
    },
    {
        id: 'builtin-distortion',
        name: 'Distortion',
        vendor: 'Sourdaw',
        format: 'builtin',
        category: 'effect',
        hasCustomUI: false,
        parameters: [
            {
                id: 'dist-drive',
                deviceId: 'builtin-distortion',
                name: 'Drive',
                type: 'float',
                value: 20,
                defaultValue: 20,
                minValue: 0,
                maxValue: 100,
                unit: '',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'dist-tone',
                deviceId: 'builtin-distortion',
                name: 'Tone',
                type: 'float',
                value: 4000,
                defaultValue: 4000,
                minValue: 200,
                maxValue: 8000,
                unit: 'Hz',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'dist-output',
                deviceId: 'builtin-distortion',
                name: 'Output Level',
                type: 'float',
                value: 0,
                defaultValue: 0,
                minValue: -24,
                maxValue: 0,
                unit: 'dB',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'dist-mix',
                deviceId: 'builtin-distortion',
                name: 'Dry/Wet',
                type: 'float',
                value: 0.5,
                defaultValue: 0.5,
                minValue: 0,
                maxValue: 1,
                unit: '',
                automatable: true,
                hasAutomation: false,
            },
        ],
    },
    {
        id: 'builtin-limiter',
        name: 'Limiter',
        vendor: 'Sourdaw',
        format: 'builtin',
        category: 'effect',
        hasCustomUI: false,
        platform: 'both',
        parameters: [
            {
                id: 'lim-threshold',
                deviceId: 'builtin-limiter',
                name: 'Threshold',
                type: 'float',
                value: -6,
                defaultValue: -6,
                minValue: -30,
                maxValue: 0,
                unit: 'dB',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'lim-release',
                deviceId: 'builtin-limiter',
                name: 'Release',
                type: 'float',
                value: 100,
                defaultValue: 100,
                minValue: 10,
                maxValue: 500,
                unit: 'ms',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'lim-ceiling',
                deviceId: 'builtin-limiter',
                name: 'Ceiling',
                type: 'float',
                value: -0.3,
                defaultValue: -0.3,
                minValue: -3,
                maxValue: 0,
                unit: 'dB',
                automatable: true,
                hasAutomation: false,
            },
        ],
    },
    {
        id: 'builtin-flanger',
        name: 'Flanger',
        vendor: 'Sourdaw',
        format: 'builtin',
        category: 'effect',
        hasCustomUI: false,
        parameters: [
            {
                id: 'flanger-rate',
                deviceId: 'builtin-flanger',
                name: 'Rate',
                type: 'float',
                value: 0.3,
                defaultValue: 0.3,
                minValue: 0.05,
                maxValue: 5,
                unit: 'Hz',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'flanger-depth',
                deviceId: 'builtin-flanger',
                name: 'Depth',
                type: 'float',
                value: 3,
                defaultValue: 3,
                minValue: 0,
                maxValue: 10,
                unit: 'ms',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'flanger-feedback',
                deviceId: 'builtin-flanger',
                name: 'Feedback',
                type: 'float',
                value: 0.5,
                defaultValue: 0.5,
                minValue: 0,
                maxValue: 0.95,
                unit: '',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'flanger-mix',
                deviceId: 'builtin-flanger',
                name: 'Dry/Wet',
                type: 'float',
                value: 0.5,
                defaultValue: 0.5,
                minValue: 0,
                maxValue: 1,
                unit: '',
                automatable: true,
                hasAutomation: false,
            },
        ],
    },
    {
        id: 'builtin-tremolo',
        name: 'Tremolo',
        vendor: 'Sourdaw',
        format: 'builtin',
        category: 'effect',
        hasCustomUI: false,
        parameters: [
            {
                id: 'trem-rate',
                deviceId: 'builtin-tremolo',
                name: 'Rate',
                type: 'float',
                value: 4,
                defaultValue: 4,
                minValue: 0.1,
                maxValue: 20,
                unit: 'Hz',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'trem-depth',
                deviceId: 'builtin-tremolo',
                name: 'Depth',
                type: 'float',
                value: 0.5,
                defaultValue: 0.5,
                minValue: 0,
                maxValue: 1,
                unit: '',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'trem-shape',
                deviceId: 'builtin-tremolo',
                name: 'Shape',
                type: 'choice',
                value: 0,
                defaultValue: 0,
                minValue: 0,
                maxValue: 1,
                unit: '',
                choices: ['Sine', 'Square'],
                automatable: false,
                hasAutomation: false,
            },
        ],
    },
    {
        id: 'builtin-bitcrusher',
        name: 'Bitcrusher',
        vendor: 'Sourdaw',
        format: 'builtin',
        category: 'effect',
        hasCustomUI: false,
        parameters: [
            {
                id: 'crush-bits',
                deviceId: 'builtin-bitcrusher',
                name: 'Bit Depth',
                type: 'int',
                value: 8,
                defaultValue: 8,
                minValue: 1,
                maxValue: 16,
                unit: 'bit',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'crush-rate',
                deviceId: 'builtin-bitcrusher',
                name: 'Rate Reduction',
                type: 'float',
                value: 1,
                defaultValue: 1,
                minValue: 1,
                maxValue: 40,
                unit: 'x',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'crush-mix',
                deviceId: 'builtin-bitcrusher',
                name: 'Dry/Wet',
                type: 'float',
                value: 0.5,
                defaultValue: 0.5,
                minValue: 0,
                maxValue: 1,
                unit: '',
                automatable: true,
                hasAutomation: false,
            },
        ],
    },
    {
        id: 'builtin-filter',
        name: 'Filter',
        vendor: 'Sourdaw',
        format: 'builtin',
        category: 'effect',
        hasCustomUI: false,
        parameters: [
            {
                id: 'filter-cutoff',
                deviceId: 'builtin-filter',
                name: 'Cutoff',
                type: 'float',
                value: 1000,
                defaultValue: 1000,
                minValue: 20,
                maxValue: 20000,
                unit: 'Hz',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'filter-resonance',
                deviceId: 'builtin-filter',
                name: 'Resonance',
                type: 'float',
                value: 1,
                defaultValue: 1,
                minValue: 0.1,
                maxValue: 20,
                unit: '',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'filter-type',
                deviceId: 'builtin-filter',
                name: 'Type',
                type: 'choice',
                value: 0,
                defaultValue: 0,
                minValue: 0,
                maxValue: 3,
                unit: '',
                choices: ['Lowpass', 'Highpass', 'Bandpass', 'Notch'],
                automatable: false,
                hasAutomation: false,
            },
        ],
    },
    {
        id: 'builtin-autopan',
        name: 'Auto-Pan',
        vendor: 'Sourdaw',
        format: 'builtin',
        category: 'effect',
        hasCustomUI: false,
        parameters: [
            {
                id: 'autopan-rate',
                deviceId: 'builtin-autopan',
                name: 'Rate',
                type: 'float',
                value: 2,
                defaultValue: 2,
                // Same story as `phaser-rate`: `applyAutoPanParams` writes it
                // to an `OscillatorNode.frequency`, and Nebula Drift ships a
                // 0.06 pan rate with a lane riding it to 0.07.
                minValue: 0,
                maxValue: 10,
                unit: 'Hz',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'autopan-depth',
                deviceId: 'builtin-autopan',
                name: 'Depth',
                type: 'float',
                value: 0.7,
                defaultValue: 0.7,
                minValue: 0,
                maxValue: 1,
                unit: '',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'autopan-shape',
                deviceId: 'builtin-autopan',
                name: 'Shape',
                type: 'choice',
                value: 0,
                defaultValue: 0,
                minValue: 0,
                maxValue: 1,
                unit: '',
                choices: ['Sine', 'Triangle'],
                automatable: false,
                hasAutomation: false,
            },
        ],
    },
    {
        id: 'builtin-convolution-reverb',
        name: 'Convolution Reverb',
        vendor: 'Sourdaw',
        format: 'builtin',
        category: 'effect',
        hasCustomUI: false,
        // The impulse response sets the tail and no exposed parameter reports its
        // length, so reserve a constant that covers the bundled IRs.
        tail: { kind: 'fixed', seconds: 6 },
        parameters: [
            {
                id: 'conv-ir',
                deviceId: 'builtin-convolution-reverb',
                name: 'IR Type',
                type: 'choice',
                value: 6,
                defaultValue: 6,
                minValue: 0,
                maxValue: 9,
                unit: '',
                choices: [
                    'Small Room',
                    'Large Hall',
                    'Cathedral',
                    'Plate',
                    'Spring',
                    'Chamber',
                    'Studio A',
                    'Studio B',
                    'Warehouse',
                    'Tunnel',
                ],
                automatable: false,
                hasAutomation: false,
            },
            {
                id: 'conv-mix',
                deviceId: 'builtin-convolution-reverb',
                name: 'Mix',
                type: 'float',
                value: 0.4,
                defaultValue: 0.4,
                minValue: 0,
                maxValue: 1,
                unit: '',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'conv-predelay',
                deviceId: 'builtin-convolution-reverb',
                name: 'Predelay',
                type: 'float',
                value: 10,
                defaultValue: 10,
                minValue: 0,
                maxValue: 200,
                unit: 'ms',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'conv-lowcut',
                deviceId: 'builtin-convolution-reverb',
                name: 'Low Cut',
                type: 'float',
                value: 60,
                defaultValue: 60,
                minValue: 20,
                maxValue: 500,
                unit: 'Hz',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'conv-highcut',
                deviceId: 'builtin-convolution-reverb',
                name: 'High Cut',
                type: 'float',
                value: 12000,
                defaultValue: 12000,
                minValue: 1000,
                maxValue: 20000,
                unit: 'Hz',
                automatable: true,
                hasAutomation: false,
            },
        ],
    },
    {
        id: 'builtin-stereo-widener',
        name: 'Stereo Widener',
        vendor: 'Sourdaw',
        format: 'builtin',
        category: 'utility',
        hasCustomUI: false,
        platform: 'both',
        parameters: [
            {
                id: 'width-amount',
                deviceId: 'builtin-stereo-widener',
                name: 'Width',
                type: 'float',
                value: 1,
                defaultValue: 1,
                minValue: 0,
                maxValue: 3,
                unit: '',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'width-mid',
                deviceId: 'builtin-stereo-widener',
                name: 'Mid Level',
                type: 'float',
                value: 0,
                defaultValue: 0,
                minValue: -12,
                maxValue: 6,
                unit: 'dB',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'width-side',
                deviceId: 'builtin-stereo-widener',
                name: 'Side Level',
                type: 'float',
                value: 0,
                defaultValue: 0,
                minValue: -12,
                maxValue: 6,
                unit: 'dB',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'width-mono-bass',
                deviceId: 'builtin-stereo-widener',
                name: 'Mono Bass',
                type: 'float',
                value: 200,
                defaultValue: 200,
                minValue: 20,
                maxValue: 500,
                unit: 'Hz',
                automatable: true,
                hasAutomation: false,
            },
        ],
    },
    {
        id: 'builtin-deesser',
        name: 'De-esser',
        vendor: 'Sourdaw',
        format: 'builtin',
        category: 'effect',
        hasCustomUI: false,
        platform: 'both',
        parameters: [
            {
                id: 'deess-threshold',
                deviceId: 'builtin-deesser',
                name: 'Threshold',
                type: 'float',
                value: -20,
                defaultValue: -20,
                minValue: -40,
                maxValue: 0,
                unit: 'dB',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'deess-freq',
                deviceId: 'builtin-deesser',
                name: 'Frequency',
                type: 'float',
                value: 6000,
                defaultValue: 6000,
                minValue: 2000,
                maxValue: 12000,
                unit: 'Hz',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'deess-range',
                deviceId: 'builtin-deesser',
                name: 'Range',
                type: 'float',
                value: -12,
                defaultValue: -12,
                minValue: -30,
                maxValue: 0,
                unit: 'dB',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'deess-listen',
                deviceId: 'builtin-deesser',
                name: 'Listen',
                type: 'bool',
                value: 0,
                defaultValue: 0,
                minValue: 0,
                maxValue: 1,
                unit: '',
                automatable: false,
                hasAutomation: false,
            },
        ],
    },
    {
        id: 'builtin-lufs-meter',
        name: 'LUFS Meter',
        vendor: 'Sourdaw',
        format: 'builtin',
        category: 'analyzer',
        hasCustomUI: false,
        platform: 'both',
        parameters: [
            {
                id: 'lufs-target',
                deviceId: 'builtin-lufs-meter',
                name: 'Target LUFS',
                type: 'float',
                value: -14,
                defaultValue: -14,
                minValue: -30,
                maxValue: -6,
                unit: 'LUFS',
                automatable: false,
                hasAutomation: false,
            },
            {
                id: 'lufs-window',
                deviceId: 'builtin-lufs-meter',
                name: 'Window',
                type: 'choice',
                value: 0,
                defaultValue: 0,
                minValue: 0,
                maxValue: 2,
                unit: '',
                choices: ['Momentary', 'Short-term', 'Integrated'],
                automatable: false,
                hasAutomation: false,
            },
        ],
    },
];

const noExternalModulation = {
    availability: 'unavailable' as const,
    reason: 'This descriptor declares no source-specific modulation route beyond its separate automation capability.',
};

const BUILTIN_EFFECT_DESCRIPTORS_GUIDANCE = [
    descriptorGuidance(
        'builtin-eq',
        effectGuidance(
            'Shape tonal balance with modest, source-specific band moves.',
            ['Start with cuts or moves within ±6 dB, then level-match bypass before judging.'],
            ['Band frequency selects the area, Q sets its width, and gain sets the amount of change.'],
            ['Narrow boosts can ring, exaggerate resonances, and consume headroom.'],
            {
                availability: 'unavailable',
                reason: 'EQ has no automatic output compensation; level-match bypass manually.',
            }
        ),
        declaredControl(
            'Parametric EQ control',
            'Changes the selected part of the spectrum.',
            ['Audition changes with neighboring bands and source level matched.'],
            ['Large boosts can reduce headroom and emphasize resonances.']
        ),
        {
            'eq-low-freq': parameterGuidance(
                'Low-band center frequency',
                'Selects the bass region that the low band shapes.',
                60,
                180,
                ['Use with low-band gain and Q to choose the breadth of bass shaping.'],
                ['Very low centers can mask kick and bass fundamentals.'],
                noExternalModulation
            ),
            'eq-mid-gain': parameterGuidance(
                'Mid-band gain',
                'Boosts or cuts the selected midrange emphasis.',
                -6,
                6,
                ['Its frequency and Q determine which midrange material changes.'],
                ['Boosts can add harshness and use output headroom.'],
                noExternalModulation
            ),
            'eq-high-q': parameterGuidance(
                'High-band Q',
                'Sets how narrowly the high-band gain is focused.',
                0.5,
                3,
                ['Use with high-band frequency and gain.'],
                ['High Q can isolate harsh resonances.'],
                noExternalModulation
            ),
        }
    ),
    descriptorGuidance(
        'builtin-compressor',
        effectGuidance(
            'Control dynamic range while preserving the source envelope.',
            ['Level-match makeup gain against bypass and watch for pumping.'],
            ['Threshold and ratio set reduction; attack and release shape the envelope response.'],
            ['Fast timing or excessive makeup can flatten transients and clip later stages.'],
            {
                availability: 'provided',
                parameterId: 'comp-makeup',
                detail: 'Makeup gain restores deliberate level after compression.',
            }
        ),
        declaredControl(
            'Compressor control',
            'Changes level reduction or the resulting envelope.',
            ['Evaluate threshold, ratio, attack, release, and makeup together.'],
            ['Aggressive settings can pump, dull transients, or raise noise.']
        ),
        {
            'comp-threshold': parameterGuidance(
                'Compression threshold',
                'Sets the input level where gain reduction begins.',
                -30,
                -12,
                ['Works with ratio and makeup gain to determine audible reduction.'],
                ['Low thresholds can over-compress program material.'],
                noExternalModulation
            ),
            'comp-ratio': parameterGuidance(
                'Compression ratio',
                'Sets how strongly signal above threshold is reduced.',
                2,
                6,
                ['Use with threshold to choose the amount of gain reduction.'],
                ['High ratios can make transients and ambience sound constrained.'],
                noExternalModulation
            ),
            'comp-attack': parameterGuidance(
                'Compression attack time',
                'Sets how quickly gain reduction catches transients.',
                5,
                30,
                ['Interact with release to determine envelope recovery.'],
                ['Very fast attacks can remove punch.'],
                noExternalModulation
            ),
            'comp-release': parameterGuidance(
                'Compression release time',
                'Sets how quickly gain reduction recovers after peaks.',
                50,
                250,
                ['Set against attack and source tempo to avoid audible pumping.'],
                ['Very short releases can distort low-frequency material.'],
                noExternalModulation
            ),
            'comp-makeup': parameterGuidance(
                'Makeup gain',
                'Restores output level after intentional gain reduction.',
                0,
                6,
                ['Level-match against bypass after threshold and ratio are set.'],
                ['Excess makeup can clip later devices.'],
                noExternalModulation
            ),
        }
    ),
    descriptorGuidance(
        'builtin-reverb',
        effectGuidance(
            'Place a source in an artificial acoustic space with controlled wet level.',
            ['Use wet mix conservatively and compare in the full arrangement.'],
            ['Size and decay determine tail density; damping and low cut determine tonal balance.'],
            ['Long or bright tails can obscure rhythm and accumulate low-frequency energy.'],
            {
                availability: 'not-applicable',
                reason: 'This reverb declares no automatic wet-path output compensation.',
            }
        ),
        declaredControl(
            'Reverb-space control',
            'Changes the reverb tail or wet-path balance.',
            ['Balance decay, damping, low cut, and wet mix together.'],
            ['Long bright tails can mask timing and source detail.']
        ),
        {
            'rev-mix': parameterGuidance(
                'Reverb wet mix',
                'Sets the proportion of reverberated signal in the output.',
                0.1,
                0.35,
                ['Balance with size and decay after setting pre-delay.'],
                ['High wet mix can push a source behind the arrangement.'],
                noExternalModulation
            ),
        }
    ),
    descriptorGuidance(
        'builtin-delay',
        effectGuidance(
            'Create rhythmic repeats while keeping feedback and wet level under control.',
            ['Increase feedback gradually and leave headroom for repeat accumulation.'],
            ['Delay time establishes rhythm; feedback establishes repeat count; filters shape repeat tone.'],
            ['High feedback can build unexpectedly and mask the dry signal.'],
            { availability: 'not-applicable', reason: 'This delay declares no automatic repeat-level compensation.' }
        ),
        declaredControl(
            'Delay-line control',
            'Changes repeat timing, tone, or level.',
            ['Set time and feedback before fine-tuning filters and mix.'],
            ['High feedback can accumulate energy and obscure timing.']
        ),
        {
            'delay-time': parameterGuidance(
                'Delay time',
                'Sets the spacing between repeated echoes.',
                80,
                750,
                ['Use with feedback to establish rhythmic density.'],
                ['Long unsynced times can clutter rhythmic material.'],
                noExternalModulation
            ),
            'delay-feedback': parameterGuidance(
                'Delay feedback',
                'Sets how much delayed signal returns for additional repeats.',
                0.15,
                0.65,
                ['Use with delay time and mix to control repeat density.'],
                ['High values can run away or mask the dry signal.'],
                noExternalModulation
            ),
        }
    ),
    descriptorGuidance(
        'builtin-gain',
        effectGuidance(
            'Trim a signal deliberately before the next processing stage.',
            ['Watch downstream headroom when adding gain.'],
            ['Use with later dynamics processors to establish staging.'],
            ['Positive gain can clip a later device even when this control itself is clean.'],
            {
                availability: 'not-applicable',
                reason: 'A gain utility is the level control itself, not automatic compensation.',
            }
        ),
        declaredControl(
            'Signal trim',
            'Changes the signal level entering later devices.',
            ['Set before downstream dynamics.'],
            ['Positive trim can clip later stages.']
        )
    ),
    descriptorGuidance(
        'builtin-sidechain-compressor',
        effectGuidance(
            'Apply sidechain-aware compression when a supported routing source is connected.',
            ['Confirm sidechain routing before relying on ducking and level-match makeup gain.'],
            ['Threshold and ratio react to the sidechain path while attack and release set the ducking envelope.'],
            ['Incorrect routing or excessive makeup can create unstable level changes.'],
            {
                availability: 'provided',
                parameterId: 'sc-comp-makeup',
                detail: 'Makeup gain restores deliberate level after sidechain reduction.',
            }
        ),
        declaredControl(
            'Sidechain compressor control',
            'Changes ducking depth or timing.',
            ['Set routing, threshold, ratio, and timing together.'],
            ['Aggressive ducking can remove musical attacks.']
        )
    ),
    descriptorGuidance(
        'builtin-chorus',
        effectGuidance(
            'Add moving detune and width to a source.',
            ['Keep wet depth moderate to preserve pitch focus.'],
            ['Rate and depth set movement; feedback and mix set density.'],
            ['High depth can blur pitch and mono compatibility.'],
            {
                availability: 'not-applicable',
                reason: 'This modulation effect declares no automatic level compensation.',
            }
        ),
        declaredControl(
            'Chorus modulation control',
            'Changes moving detune, width, or wet balance.',
            ['Balance rate, depth, feedback, and mix.'],
            ['Extreme depth can blur pitch definition.']
        )
    ),
    descriptorGuidance(
        'builtin-phaser',
        effectGuidance(
            'Sweep phase-cancelled bands for motion and color.',
            ['Use feedback sparingly on bright sources.'],
            ['Rate and depth control the sweep; feedback increases resonance.'],
            ['High feedback can create sharp resonances.'],
            { availability: 'not-applicable', reason: 'This phase effect declares no automatic level compensation.' }
        ),
        declaredControl(
            'Phaser control',
            'Changes phase-sweep motion or resonance.',
            ['Balance rate, depth, feedback, and stages.'],
            ['High feedback can sound piercing.']
        )
    ),
    descriptorGuidance(
        'builtin-distortion',
        effectGuidance(
            'Add harmonic saturation while staging output into later devices.',
            ['Lower output after increasing drive and compare bypass at matched level.'],
            ['Drive creates harmonics; tone filters them; output and mix set level and blend.'],
            ['High drive can alias, lose transients, and overload later stages.'],
            { availability: 'unavailable', reason: 'This distortion declares no automatic loudness matching.' }
        ),
        declaredControl(
            'Distortion control',
            'Changes harmonic density, tone, or blend.',
            ['Set drive before output and mix.'],
            ['High drive can reduce headroom and clarity.']
        )
    ),
    descriptorGuidance(
        'builtin-limiter',
        effectGuidance(
            'Catch peaks near a chosen output ceiling.',
            ['Leave ceiling margin for later conversion and compare against bypass.'],
            ['Threshold drives reduction while release controls recovery and ceiling caps output.'],
            ['Heavy limiting can flatten transients and raise apparent loudness deceptively.'],
            { availability: 'unavailable', reason: 'This limiter declares no automatic loudness matching.' }
        ),
        declaredControl(
            'Limiter control',
            'Changes peak reduction or output ceiling.',
            ['Set ceiling before driving threshold.'],
            ['Heavy limiting can remove punch.']
        )
    ),
    descriptorGuidance(
        'builtin-flanger',
        effectGuidance(
            'Create short comb-filter motion for color.',
            ['Keep feedback restrained on full-range material.'],
            ['Rate and depth sweep the delay; feedback increases comb resonance.'],
            ['High feedback can cause metallic peaks and level build-up.'],
            { availability: 'not-applicable', reason: 'This flanger declares no automatic level compensation.' }
        ),
        declaredControl(
            'Flanger control',
            'Changes comb-filter movement or blend.',
            ['Balance rate, depth, feedback, and mix.'],
            ['High feedback can create sharp peaks.']
        )
    ),
    descriptorGuidance(
        'builtin-tremolo',
        effectGuidance(
            'Impose rhythmic amplitude movement on a source.',
            ['Keep depth below full mute unless a hard chop is intentional.'],
            ['Rate sets rhythm, depth sets level movement, and shape sets contour.'],
            ['Full depth can remove note audibility between pulses.'],
            {
                availability: 'not-applicable',
                reason: 'This amplitude effect declares no automatic level compensation.',
            }
        ),
        declaredControl(
            'Tremolo control',
            'Changes rhythmic amplitude movement.',
            ['Balance rate, depth, and waveform shape.'],
            ['Extreme depth can make notes disappear.']
        )
    ),
    descriptorGuidance(
        'builtin-bitcrusher',
        effectGuidance(
            'Reduce resolution for deliberate digital texture.',
            ['Blend wet signal conservatively and reduce output if harshness increases level.'],
            ['Bit depth and sample rate set degradation; mix sets blend.'],
            ['Extreme reduction can add harsh aliases and obscure pitch.'],
            { availability: 'unavailable', reason: 'This bitcrusher declares no automatic loudness compensation.' }
        ),
        declaredControl(
            'Bitcrusher control',
            'Changes digital resolution or wet blend.',
            ['Set bit depth and rate before mix.'],
            ['Extreme reduction can create harsh aliases.']
        )
    ),
    descriptorGuidance(
        'builtin-filter',
        effectGuidance(
            'Shape spectral balance with a resonant filter.',
            ['Raise resonance gradually and level-match after strong filtering.'],
            ['Cutoff selects the transition region; resonance emphasizes it; type selects topology.'],
            ['High resonance can whistle or overemphasize a narrow frequency.'],
            { availability: 'unavailable', reason: 'This filter declares no automatic output compensation.' }
        ),
        declaredControl(
            'Filter control',
            'Changes the spectral transition or resonance.',
            ['Set type, cutoff, and resonance together.'],
            ['High resonance can create piercing peaks.']
        )
    ),
    descriptorGuidance(
        'builtin-autopan',
        effectGuidance(
            'Move a source across the stereo field rhythmically.',
            ['Check mono compatibility before using wide depth on critical material.'],
            ['Rate sets movement, depth sets width, and shape sets contour.'],
            ['Extreme depth can make a source unstable in mono.'],
            { availability: 'not-applicable', reason: 'This pan effect declares no automatic level compensation.' }
        ),
        declaredControl(
            'Auto-pan control',
            'Changes stereo movement.',
            ['Balance rate, depth, and shape.'],
            ['Wide movement can reduce mono stability.']
        )
    ),
    descriptorGuidance(
        'builtin-convolution-reverb',
        effectGuidance(
            'Place a source in an impulse-response space.',
            ['Use wet mix and pre-delay conservatively while checking arrangement masking.'],
            ['Impulse choice supplies character; filters and mix shape its placement.'],
            ['Long bright impulses can obscure rhythm and build low-frequency energy.'],
            {
                availability: 'not-applicable',
                reason: 'This convolution reverb declares no automatic wet-path compensation.',
            }
        ),
        declaredControl(
            'Convolution reverb control',
            'Changes impulse response timing, tone, or wet balance.',
            ['Choose the impulse before tuning filters and mix.'],
            ['Long impulses can mask source detail.']
        )
    ),
    descriptorGuidance(
        'builtin-stereo-widener',
        effectGuidance(
            'Adjust stereo width while preserving a stable low-frequency center.',
            ['Check mono compatibility after widening.'],
            ['Width, mid/side balance, and mono-bass setting jointly determine stereo stability.'],
            ['Excess width can collapse or cancel in mono.'],
            { availability: 'not-applicable', reason: 'This width effect declares no automatic level compensation.' }
        ),
        declaredControl(
            'Stereo-width control',
            'Changes mid/side balance or low-frequency mono behavior.',
            ['Check width settings with mono monitoring.'],
            ['Excess width can cancel in mono.']
        )
    ),
    descriptorGuidance(
        'builtin-deesser',
        effectGuidance(
            'Reduce excessive sibilance while preserving intelligibility.',
            ['Use listen mode to locate the sibilant band, then turn it off before judging.'],
            ['Frequency selects the band while threshold and range set reduction.'],
            ['Over-reduction can dull consonants and make vocals lisp.'],
            { availability: 'unavailable', reason: 'This de-esser declares no automatic output compensation.' }
        ),
        declaredControl(
            'De-esser control',
            'Changes sibilance detection or reduction.',
            ['Use listen, frequency, threshold, and range together.'],
            ['Excess reduction can dull articulation.']
        )
    ),
    descriptorGuidance(
        'builtin-lufs-meter',
        analysisGuidance(
            'Measure loudness against a delivery target without changing audio.',
            ['Treat readings as metering evidence, not a gain command.'],
            ['Target and window choose the comparison context for the measured loudness.'],
            ['Chasing short-term readings can cause unnecessary level changes.'],
            { availability: 'not-applicable', reason: 'This analyzer has no audio gain path to compensate.' }
        ),
        declaredControl(
            'Loudness-meter configuration',
            'Changes the meter target or time window without processing audio.',
            ['Choose a window appropriate to the delivery decision.'],
            ['Changing a target does not change measured audio.']
        )
    ),
];

export const BUILTIN_EFFECT_DESCRIPTORS = applyDescriptorGuidance(
    BUILTIN_EFFECT_DESCRIPTOR_DATA,
    BUILTIN_EFFECT_DESCRIPTORS_GUIDANCE
);
