/**
 * Unified Crumbs Suite — plugin descriptor.
 * Registers the Crumbs as a proper instrument with custom UI (bottom panel).
 */

import { type PluginDescriptor } from '../DeviceParameterTypes';

export const CRUMBS_DESCRIPTOR: PluginDescriptor = {
    id: 'builtin-crumbs',
    name: 'Crumbs',
    vendor: 'Sourdaw',
    format: 'builtin',
    category: 'instrument',
    hasCustomUI: true,
    // An instrument keeps sounding for its amp-envelope release after the last
    // note ends, which the export has to capture like any other tail.
    tail: { kind: 'decaySeconds', parameterId: 'release', defaultSeconds: 0.1 },
    parameters: [
        {
            id: 'masterGain',
            deviceId: 'builtin-crumbs',
            name: 'Gain',
            type: 'float',
            value: 0.8,
            defaultValue: 0.8,
            minValue: 0,
            maxValue: 1,
            unit: '',
            automatable: true,
            hasAutomation: false,
        },
        {
            id: 'attack',
            deviceId: 'builtin-crumbs',
            name: 'Attack',
            type: 'float',
            value: 0.001,
            defaultValue: 0.001,
            minValue: 0.001,
            maxValue: 2,
            unit: 's',
            automatable: true,
            hasAutomation: false,
            scaling: 'log',
        },
        {
            id: 'hold',
            deviceId: 'builtin-crumbs',
            name: 'Hold',
            type: 'float',
            value: 0,
            defaultValue: 0,
            minValue: 0,
            maxValue: 2,
            unit: 's',
            automatable: true,
            hasAutomation: false,
        },
        {
            id: 'decay',
            deviceId: 'builtin-crumbs',
            name: 'Decay',
            type: 'float',
            value: 0.3,
            defaultValue: 0.3,
            minValue: 0.001,
            maxValue: 2,
            unit: 's',
            automatable: true,
            hasAutomation: false,
            scaling: 'log',
        },
        {
            id: 'sustain',
            deviceId: 'builtin-crumbs',
            name: 'Sustain',
            type: 'float',
            value: 1.0,
            defaultValue: 1.0,
            minValue: 0,
            maxValue: 1,
            unit: '',
            automatable: true,
            hasAutomation: false,
        },
        {
            id: 'release',
            deviceId: 'builtin-crumbs',
            name: 'Release',
            type: 'float',
            value: 0.1,
            defaultValue: 0.1,
            minValue: 0.001,
            maxValue: 5,
            unit: 's',
            automatable: true,
            hasAutomation: false,
            scaling: 'log',
        },
        {
            id: 'filterCutoff',
            deviceId: 'builtin-crumbs',
            name: 'Filter Cutoff',
            type: 'float',
            value: 20000,
            defaultValue: 20000,
            minValue: 20,
            maxValue: 20000,
            unit: 'Hz',
            automatable: true,
            hasAutomation: false,
            scaling: 'log',
        },
        {
            id: 'filterResonance',
            deviceId: 'builtin-crumbs',
            name: 'Filter Resonance',
            type: 'float',
            value: 1,
            defaultValue: 1,
            minValue: 0.1,
            maxValue: 20,
            unit: '',
            automatable: true,
            hasAutomation: false,
        },
        {
            id: 'tune',
            deviceId: 'builtin-crumbs',
            name: 'Tune',
            type: 'float',
            value: 0,
            defaultValue: 0,
            minValue: -100,
            maxValue: 100,
            unit: 'cents',
            automatable: true,
            hasAutomation: false,
        },
        {
            id: 'pan',
            deviceId: 'builtin-crumbs',
            name: 'Pan',
            type: 'float',
            value: 0,
            defaultValue: 0,
            minValue: -1,
            maxValue: 1,
            unit: '',
            automatable: true,
            hasAutomation: false,
        },
    ],
};
