import { type PluginDescriptor } from '../DeviceParameterTypes';

/** Premium WASM plugin descriptors (Dutch Oven, Scoring). */
export const NATIVE_DSP_DESCRIPTORS: PluginDescriptor[] = [
    {
        id: 'dutch-oven',
        name: 'Dutch Oven',
        vendor: 'Sourdaw',
        format: 'builtin',
        category: 'effect',
        hasCustomUI: true,
        platform: 'both',
        // `decay` is a normalised coefficient, never seconds — the engines
        // convert it through `#/utils/reverbDecayLaw`, so the tail has to be
        // read through the same law. Reading the raw value as seconds would cap
        // the estimate near 1 s while the FDN reaches ~29.8 s at the top of the
        // knob, truncating the longest reverbs in the export.
        tail: {
            kind: 'mappedDecaySeconds',
            parameterId: 'decay',
            defaultValue: 0.5,
            law: 'dutch-oven-rt60',
            predelayMsParameterId: 'predelay',
        },
        parameters: [
            {
                id: 'mix',
                deviceId: 'dutch-oven',
                name: 'Mix',
                type: 'float',
                value: 0.3,
                defaultValue: 0.3,
                minValue: 0,
                maxValue: 1,
                unit: '',
                automatable: true,
                hasAutomation: false,
            },
            {
                // Unitless by contract: `decay` is a normalised coefficient,
                // never seconds. Every Dutch Oven engine converts it into its
                // own quantity (an RT60 for the FDN, an IR stretch for the
                // convolution path) through `#/utils/reverbDecayLaw`, so this
                // range and that law must be changed together.
                id: 'decay',
                deviceId: 'dutch-oven',
                name: 'Decay',
                type: 'float',
                value: 0.5,
                defaultValue: 0.5,
                minValue: 0,
                maxValue: 0.999,
                unit: '',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'damping',
                deviceId: 'dutch-oven',
                name: 'Damping',
                type: 'float',
                value: 0.0005,
                defaultValue: 0.0005,
                minValue: 0,
                maxValue: 0.999,
                unit: '',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'predelay',
                deviceId: 'dutch-oven',
                name: 'Pre-Delay',
                type: 'float',
                value: 15,
                defaultValue: 15,
                minValue: 0,
                maxValue: 500,
                unit: 'ms',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'size',
                deviceId: 'dutch-oven',
                name: 'Size',
                type: 'float',
                value: 0.75,
                defaultValue: 0.75,
                minValue: 0,
                maxValue: 1,
                unit: '',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'mod_rate',
                deviceId: 'dutch-oven',
                name: 'Mod Rate',
                type: 'float',
                value: 1.0,
                defaultValue: 1.0,
                minValue: 0.1,
                maxValue: 5.0,
                unit: 'Hz',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'mod_depth',
                deviceId: 'dutch-oven',
                name: 'Mod Depth',
                type: 'float',
                value: 0.3,
                defaultValue: 0.3,
                minValue: 0,
                maxValue: 1,
                unit: '',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'diffusion',
                deviceId: 'dutch-oven',
                name: 'Diffusion',
                type: 'float',
                value: 0.75,
                defaultValue: 0.75,
                minValue: 0,
                maxValue: 1,
                unit: '',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'high_cut',
                deviceId: 'dutch-oven',
                name: 'High Cut',
                type: 'float',
                value: 12000,
                defaultValue: 12000,
                minValue: 1000,
                maxValue: 20000,
                unit: 'Hz',
                scaling: 'log',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'low_cut',
                deviceId: 'dutch-oven',
                name: 'Low Cut',
                type: 'float',
                value: 80,
                defaultValue: 80,
                minValue: 20,
                maxValue: 1000,
                unit: 'Hz',
                scaling: 'log',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'width',
                deviceId: 'dutch-oven',
                name: 'Width',
                type: 'float',
                value: 1.0,
                defaultValue: 1.0,
                minValue: 0,
                maxValue: 2,
                unit: '',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'freeze',
                deviceId: 'dutch-oven',
                name: 'Freeze',
                type: 'bool',
                value: 0,
                defaultValue: 0,
                minValue: 0,
                maxValue: 1,
                unit: '',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'shimmer',
                deviceId: 'dutch-oven',
                name: 'Shimmer',
                type: 'bool',
                value: 0,
                defaultValue: 0,
                minValue: 0,
                maxValue: 1,
                unit: '',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'shimmer_amount',
                deviceId: 'dutch-oven',
                name: 'Shimmer Amount',
                type: 'float',
                value: 0.2,
                defaultValue: 0.2,
                minValue: 0,
                maxValue: 1,
                unit: '',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'shimmer_pitch',
                deviceId: 'dutch-oven',
                name: 'Shimmer Pitch',
                type: 'float',
                value: 1,
                defaultValue: 1,
                minValue: 0,
                maxValue: 1,
                unit: '',
                automatable: false,
                hasAutomation: false,
            },
            {
                id: 'gravity',
                deviceId: 'dutch-oven',
                name: 'Gravity',
                type: 'float',
                value: 0.5,
                defaultValue: 0.5,
                minValue: -1,
                maxValue: 1,
                unit: '',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'saturation',
                deviceId: 'dutch-oven',
                name: 'Saturation',
                type: 'bool',
                value: 0,
                defaultValue: 0,
                minValue: 0,
                maxValue: 1,
                unit: '',
                automatable: false,
                hasAutomation: false,
            },
            {
                id: 'early_late',
                deviceId: 'dutch-oven',
                name: 'Early/Late',
                type: 'float',
                value: 0.4,
                defaultValue: 0.4,
                minValue: 0,
                maxValue: 1,
                unit: '',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'density',
                deviceId: 'dutch-oven',
                name: 'Density',
                type: 'float',
                value: 1.0,
                defaultValue: 1.0,
                minValue: 0,
                maxValue: 1,
                unit: '',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'algorithm',
                deviceId: 'dutch-oven',
                name: 'Algorithm',
                type: 'int',
                value: 0,
                defaultValue: 0,
                minValue: 0,
                maxValue: 5,
                unit: '',
                automatable: false,
                hasAutomation: false,
            },
            {
                id: 'vintage',
                deviceId: 'dutch-oven',
                name: 'Vintage',
                type: 'int',
                value: 0,
                defaultValue: 0,
                minValue: 0,
                maxValue: 2,
                unit: '',
                automatable: false,
                hasAutomation: false,
            },
        ],
    },
    {
        id: 'native-scoring',
        name: 'Scoring',
        vendor: 'Sourdaw',
        format: 'builtin',
        category: 'analyzer',
        hasCustomUI: true,
        platform: 'both',
        parameters: [
            {
                id: 'a4_hz',
                deviceId: 'native-scoring',
                name: 'A4 Reference',
                type: 'float',
                value: 440,
                defaultValue: 440,
                minValue: 400,
                maxValue: 490,
                unit: 'Hz',
                automatable: false,
                hasAutomation: false,
            },
            {
                id: 'mute',
                deviceId: 'native-scoring',
                name: 'Mute Output',
                type: 'bool',
                value: 0,
                defaultValue: 0,
                minValue: 0,
                maxValue: 1,
                unit: '',
                automatable: false,
                hasAutomation: false,
            },
            {
                id: 'tone',
                deviceId: 'native-scoring',
                name: 'Reference Tone',
                type: 'bool',
                value: 0,
                defaultValue: 0,
                minValue: 0,
                maxValue: 1,
                unit: '',
                automatable: false,
                hasAutomation: false,
            },
        ],
    },
];
