import { type PluginDescriptor } from '../DeviceParameter';

/** Native DSP plugin descriptors (Tauri-native EQ, Compressor, Reverb, Delay, Gate, Gain). */
export const NATIVE_DSP_DESCRIPTORS: PluginDescriptor[] = [
    {
        id: 'native-eq',
        name: 'Native EQ',
        vendor: 'Sourdaw',
        format: 'builtin',
        category: 'effect',
        hasCustomUI: false,
        platform: 'native',
        parameters: [
            {
                id: 'band2_freq',
                deviceId: 'native-eq',
                name: 'Band 1 Freq',
                type: 'float',
                value: 250,
                defaultValue: 250,
                minValue: 20,
                maxValue: 20000,
                unit: 'Hz',
                scaling: 'log',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'band2_gain',
                deviceId: 'native-eq',
                name: 'Band 1 Gain',
                type: 'float',
                value: 0,
                defaultValue: 0,
                minValue: -24,
                maxValue: 24,
                unit: 'dB',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'band2_q',
                deviceId: 'native-eq',
                name: 'Band 1 Q',
                type: 'float',
                value: 1,
                defaultValue: 1,
                minValue: 0.1,
                maxValue: 18,
                unit: '',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'band3_freq',
                deviceId: 'native-eq',
                name: 'Band 2 Freq',
                type: 'float',
                value: 800,
                defaultValue: 800,
                minValue: 20,
                maxValue: 20000,
                unit: 'Hz',
                scaling: 'log',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'band3_gain',
                deviceId: 'native-eq',
                name: 'Band 2 Gain',
                type: 'float',
                value: 0,
                defaultValue: 0,
                minValue: -24,
                maxValue: 24,
                unit: 'dB',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'band3_q',
                deviceId: 'native-eq',
                name: 'Band 2 Q',
                type: 'float',
                value: 1,
                defaultValue: 1,
                minValue: 0.1,
                maxValue: 18,
                unit: '',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'band4_freq',
                deviceId: 'native-eq',
                name: 'Band 3 Freq',
                type: 'float',
                value: 2500,
                defaultValue: 2500,
                minValue: 20,
                maxValue: 20000,
                unit: 'Hz',
                scaling: 'log',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'band4_gain',
                deviceId: 'native-eq',
                name: 'Band 3 Gain',
                type: 'float',
                value: 0,
                defaultValue: 0,
                minValue: -24,
                maxValue: 24,
                unit: 'dB',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'band4_q',
                deviceId: 'native-eq',
                name: 'Band 3 Q',
                type: 'float',
                value: 1,
                defaultValue: 1,
                minValue: 0.1,
                maxValue: 18,
                unit: '',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'band5_freq',
                deviceId: 'native-eq',
                name: 'Band 4 Freq',
                type: 'float',
                value: 6000,
                defaultValue: 6000,
                minValue: 20,
                maxValue: 20000,
                unit: 'Hz',
                scaling: 'log',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'band5_gain',
                deviceId: 'native-eq',
                name: 'Band 4 Gain',
                type: 'float',
                value: 0,
                defaultValue: 0,
                minValue: -24,
                maxValue: 24,
                unit: 'dB',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'band5_q',
                deviceId: 'native-eq',
                name: 'Band 4 Q',
                type: 'float',
                value: 1,
                defaultValue: 1,
                minValue: 0.1,
                maxValue: 18,
                unit: '',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'output_gain',
                deviceId: 'native-eq',
                name: 'Output Gain',
                type: 'float',
                value: 0,
                defaultValue: 0,
                minValue: -24,
                maxValue: 24,
                unit: 'dB',
                automatable: true,
                hasAutomation: false,
            },
        ],
    },
    {
        id: 'native-compressor',
        name: 'Native Compressor',
        vendor: 'Sourdaw',
        format: 'builtin',
        category: 'effect',
        hasCustomUI: false,
        platform: 'native',
        parameters: [
            {
                id: 'threshold',
                deviceId: 'native-compressor',
                name: 'Threshold',
                type: 'float',
                value: -18,
                defaultValue: -18,
                minValue: -60,
                maxValue: 0,
                unit: 'dB',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'ratio',
                deviceId: 'native-compressor',
                name: 'Ratio',
                type: 'float',
                value: 4,
                defaultValue: 4,
                minValue: 1,
                maxValue: 20,
                unit: ':1',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'attack',
                deviceId: 'native-compressor',
                name: 'Attack',
                type: 'float',
                value: 0.01,
                defaultValue: 0.01,
                minValue: 0.0001,
                maxValue: 0.5,
                unit: 's',
                scaling: 'log',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'release',
                deviceId: 'native-compressor',
                name: 'Release',
                type: 'float',
                value: 0.1,
                defaultValue: 0.1,
                minValue: 0.005,
                maxValue: 2,
                unit: 's',
                scaling: 'log',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'knee',
                deviceId: 'native-compressor',
                name: 'Knee',
                type: 'float',
                value: 6,
                defaultValue: 6,
                minValue: 0,
                maxValue: 24,
                unit: 'dB',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'makeup',
                deviceId: 'native-compressor',
                name: 'Makeup',
                type: 'float',
                value: 0,
                defaultValue: 0,
                minValue: 0,
                maxValue: 40,
                unit: 'dB',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'mix',
                deviceId: 'native-compressor',
                name: 'Mix',
                type: 'float',
                value: 1,
                defaultValue: 1,
                minValue: 0,
                maxValue: 1,
                unit: '',
                automatable: true,
                hasAutomation: false,
            },
        ],
    },
    {
        id: 'native-limiter',
        name: 'Native Limiter',
        vendor: 'Sourdaw',
        format: 'builtin',
        category: 'effect',
        hasCustomUI: false,
        platform: 'native',
        parameters: [
            {
                id: 'ceiling',
                deviceId: 'native-limiter',
                name: 'Ceiling',
                type: 'float',
                value: -0.3,
                defaultValue: -0.3,
                minValue: -12,
                maxValue: 0,
                unit: 'dB',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'release',
                deviceId: 'native-limiter',
                name: 'Release',
                type: 'float',
                value: 0.05,
                defaultValue: 0.05,
                minValue: 0.01,
                maxValue: 0.5,
                unit: 's',
                scaling: 'log',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'lookahead',
                deviceId: 'native-limiter',
                name: 'Lookahead',
                type: 'float',
                value: 5,
                defaultValue: 5,
                minValue: 0.5,
                maxValue: 10,
                unit: 'ms',
                automatable: false,
                hasAutomation: false,
            },
        ],
    },
    {
        id: 'native-reverb',
        name: 'Native Reverb',
        vendor: 'Sourdaw',
        format: 'builtin',
        category: 'effect',
        hasCustomUI: false,
        platform: 'native',
        parameters: [
            {
                id: 'mix',
                deviceId: 'native-reverb',
                name: 'Mix',
                type: 'float',
                value: 0.3,
                defaultValue: 0.3,
                minValue: 0,
                maxValue: 1,
                unit: '',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'size',
                deviceId: 'native-reverb',
                name: 'Size',
                type: 'float',
                value: 0.7,
                defaultValue: 0.7,
                minValue: 0,
                maxValue: 1,
                unit: '',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'decay',
                deviceId: 'native-reverb',
                name: 'Decay',
                type: 'float',
                value: 0.7,
                defaultValue: 0.7,
                minValue: 0.05,
                maxValue: 0.99,
                unit: '',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'damping',
                deviceId: 'native-reverb',
                name: 'Damping',
                type: 'float',
                value: 0.5,
                defaultValue: 0.5,
                minValue: 0,
                maxValue: 0.99,
                unit: '',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'predelay',
                deviceId: 'native-reverb',
                name: 'Pre-Delay',
                type: 'float',
                value: 20,
                defaultValue: 20,
                minValue: 0,
                maxValue: 200,
                unit: 'ms',
                automatable: true,
                hasAutomation: false,
            },
        ],
    },
    {
        id: 'native-delay',
        name: 'Native Delay',
        vendor: 'Sourdaw',
        format: 'builtin',
        category: 'effect',
        hasCustomUI: false,
        platform: 'native',
        parameters: [
            {
                id: 'time_l',
                deviceId: 'native-delay',
                name: 'Time L',
                type: 'float',
                value: 0.25,
                defaultValue: 0.25,
                minValue: 0.001,
                maxValue: 2,
                unit: 's',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'time_r',
                deviceId: 'native-delay',
                name: 'Time R',
                type: 'float',
                value: 0.375,
                defaultValue: 0.375,
                minValue: 0.001,
                maxValue: 2,
                unit: 's',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'feedback',
                deviceId: 'native-delay',
                name: 'Feedback',
                type: 'float',
                value: 0.4,
                defaultValue: 0.4,
                minValue: 0,
                maxValue: 0.95,
                unit: '',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'mix',
                deviceId: 'native-delay',
                name: 'Mix',
                type: 'float',
                value: 0.3,
                defaultValue: 0.3,
                minValue: 0,
                maxValue: 1,
                unit: '',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'filter',
                deviceId: 'native-delay',
                name: 'Filter',
                type: 'float',
                value: 8000,
                defaultValue: 8000,
                minValue: 200,
                maxValue: 20000,
                unit: 'Hz',
                scaling: 'log',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'ping_pong',
                deviceId: 'native-delay',
                name: 'Ping-Pong',
                type: 'bool',
                value: 0,
                defaultValue: 0,
                minValue: 0,
                maxValue: 1,
                unit: '',
                automatable: false,
                hasAutomation: false,
            },
        ],
    },
    {
        id: 'native-gate',
        name: 'Native Gate',
        vendor: 'Sourdaw',
        format: 'builtin',
        category: 'effect',
        hasCustomUI: false,
        platform: 'native',
        parameters: [
            {
                id: 'threshold',
                deviceId: 'native-gate',
                name: 'Threshold',
                type: 'float',
                value: -40,
                defaultValue: -40,
                minValue: -80,
                maxValue: 0,
                unit: 'dB',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'attack',
                deviceId: 'native-gate',
                name: 'Attack',
                type: 'float',
                value: 0.001,
                defaultValue: 0.001,
                minValue: 0.0001,
                maxValue: 0.1,
                unit: 's',
                scaling: 'log',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'hold',
                deviceId: 'native-gate',
                name: 'Hold',
                type: 'float',
                value: 0.05,
                defaultValue: 0.05,
                minValue: 0,
                maxValue: 0.5,
                unit: 's',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'release',
                deviceId: 'native-gate',
                name: 'Release',
                type: 'float',
                value: 0.1,
                defaultValue: 0.1,
                minValue: 0.005,
                maxValue: 2,
                unit: 's',
                scaling: 'log',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'range',
                deviceId: 'native-gate',
                name: 'Range',
                type: 'float',
                value: -80,
                defaultValue: -80,
                minValue: -80,
                maxValue: 0,
                unit: 'dB',
                automatable: true,
                hasAutomation: false,
            },
        ],
    },
    {
        id: 'native-gain',
        name: 'Native Gain',
        vendor: 'Sourdaw',
        format: 'builtin',
        category: 'utility',
        hasCustomUI: false,
        platform: 'native',
        parameters: [
            {
                id: 'gain',
                deviceId: 'native-gain',
                name: 'Gain',
                type: 'float',
                value: 0,
                defaultValue: 0,
                minValue: -60,
                maxValue: 24,
                unit: 'dB',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'pan',
                deviceId: 'native-gain',
                name: 'Pan',
                type: 'float',
                value: 0,
                defaultValue: 0,
                minValue: -1,
                maxValue: 1,
                unit: '',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'phase_l',
                deviceId: 'native-gain',
                name: 'Phase Inv L',
                type: 'bool',
                value: 0,
                defaultValue: 0,
                minValue: 0,
                maxValue: 1,
                unit: '',
                automatable: false,
                hasAutomation: false,
            },
            {
                id: 'phase_r',
                deviceId: 'native-gain',
                name: 'Phase Inv R',
                type: 'bool',
                value: 0,
                defaultValue: 0,
                minValue: 0,
                maxValue: 1,
                unit: '',
                automatable: false,
                hasAutomation: false,
            },
            {
                id: 'mono',
                deviceId: 'native-gain',
                name: 'Mono',
                type: 'bool',
                value: 0,
                defaultValue: 0,
                minValue: 0,
                maxValue: 1,
                unit: '',
                automatable: false,
                hasAutomation: false,
            },
            {
                id: 'width',
                deviceId: 'native-gain',
                name: 'Stereo Width',
                type: 'float',
                value: 1,
                defaultValue: 1,
                minValue: 0,
                maxValue: 2,
                unit: '',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'dc_block',
                deviceId: 'native-gain',
                name: 'DC Block',
                type: 'bool',
                value: 0,
                defaultValue: 0,
                minValue: 0,
                maxValue: 1,
                unit: '',
                automatable: false,
                hasAutomation: false,
            },
        ],
    },
    {
        id: 'native-proof-chamber',
        name: 'Dutch Oven',
        vendor: 'Sourdaw',
        format: 'builtin',
        category: 'effect',
        hasCustomUI: true,
        platform: 'both',
        parameters: [
            {
                id: 'mix',
                deviceId: 'native-proof-chamber',
                name: 'Mix',
                type: 'float',
                value: 0.3,
                defaultValue: 0.3,
                minValue: 0,
                maxValue: 1,
                unit: '',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'decay',
                deviceId: 'native-proof-chamber',
                name: 'Decay',
                type: 'float',
                value: 0.5,
                defaultValue: 0.5,
                minValue: 0,
                maxValue: 0.999,
                unit: '',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'damping',
                deviceId: 'native-proof-chamber',
                name: 'Damping',
                type: 'float',
                value: 0.0005,
                defaultValue: 0.0005,
                minValue: 0,
                maxValue: 0.999,
                unit: '',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'predelay',
                deviceId: 'native-proof-chamber',
                name: 'Pre-Delay',
                type: 'float',
                value: 15,
                defaultValue: 15,
                minValue: 0,
                maxValue: 500,
                unit: 'ms',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'size',
                deviceId: 'native-proof-chamber',
                name: 'Size',
                type: 'float',
                value: 0.75,
                defaultValue: 0.75,
                minValue: 0,
                maxValue: 1,
                unit: '',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'mod_rate',
                deviceId: 'native-proof-chamber',
                name: 'Mod Rate',
                type: 'float',
                value: 1.0,
                defaultValue: 1.0,
                minValue: 0.1,
                maxValue: 5.0,
                unit: 'Hz',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'mod_depth',
                deviceId: 'native-proof-chamber',
                name: 'Mod Depth',
                type: 'float',
                value: 0.3,
                defaultValue: 0.3,
                minValue: 0,
                maxValue: 1,
                unit: '',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'diffusion',
                deviceId: 'native-proof-chamber',
                name: 'Diffusion',
                type: 'float',
                value: 0.75,
                defaultValue: 0.75,
                minValue: 0,
                maxValue: 1,
                unit: '',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'high_cut',
                deviceId: 'native-proof-chamber',
                name: 'High Cut',
                type: 'float',
                value: 12000,
                defaultValue: 12000,
                minValue: 1000,
                maxValue: 20000,
                unit: 'Hz',
                scaling: 'log',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'low_cut',
                deviceId: 'native-proof-chamber',
                name: 'Low Cut',
                type: 'float',
                value: 80,
                defaultValue: 80,
                minValue: 20,
                maxValue: 1000,
                unit: 'Hz',
                scaling: 'log',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'width',
                deviceId: 'native-proof-chamber',
                name: 'Width',
                type: 'float',
                value: 1.0,
                defaultValue: 1.0,
                minValue: 0,
                maxValue: 2,
                unit: '',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'freeze',
                deviceId: 'native-proof-chamber',
                name: 'Freeze',
                type: 'bool',
                value: 0,
                defaultValue: 0,
                minValue: 0,
                maxValue: 1,
                unit: '',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'shimmer',
                deviceId: 'native-proof-chamber',
                name: 'Shimmer',
                type: 'bool',
                value: 0,
                defaultValue: 0,
                minValue: 0,
                maxValue: 1,
                unit: '',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'shimmer_amount',
                deviceId: 'native-proof-chamber',
                name: 'Shimmer Amount',
                type: 'float',
                value: 0.2,
                defaultValue: 0.2,
                minValue: 0,
                maxValue: 1,
                unit: '',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'shimmer_pitch',
                deviceId: 'native-proof-chamber',
                name: 'Shimmer Pitch',
                type: 'float',
                value: 1,
                defaultValue: 1,
                minValue: 0,
                maxValue: 1,
                unit: '',
                automatable: false,
                hasAutomation: false,
            },
            {
                id: 'gravity',
                deviceId: 'native-proof-chamber',
                name: 'Gravity',
                type: 'float',
                value: 0.5,
                defaultValue: 0.5,
                minValue: -1,
                maxValue: 1,
                unit: '',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'saturation',
                deviceId: 'native-proof-chamber',
                name: 'Saturation',
                type: 'bool',
                value: 0,
                defaultValue: 0,
                minValue: 0,
                maxValue: 1,
                unit: '',
                automatable: false,
                hasAutomation: false,
            },
            {
                id: 'early_late',
                deviceId: 'native-proof-chamber',
                name: 'Early/Late',
                type: 'float',
                value: 0.4,
                defaultValue: 0.4,
                minValue: 0,
                maxValue: 1,
                unit: '',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'density',
                deviceId: 'native-proof-chamber',
                name: 'Density',
                type: 'float',
                value: 1.0,
                defaultValue: 1.0,
                minValue: 0,
                maxValue: 1,
                unit: '',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'algorithm',
                deviceId: 'native-proof-chamber',
                name: 'Algorithm',
                type: 'int',
                value: 0,
                defaultValue: 0,
                minValue: 0,
                maxValue: 5,
                unit: '',
                automatable: false,
                hasAutomation: false,
            },
            {
                id: 'vintage',
                deviceId: 'native-proof-chamber',
                name: 'Vintage',
                type: 'int',
                value: 0,
                defaultValue: 0,
                minValue: 0,
                maxValue: 2,
                unit: '',
                automatable: false,
                hasAutomation: false,
            },
        ],
    },
    {
        id: 'native-scoring',
        name: 'Scoring',
        vendor: 'Sourdaw',
        format: 'builtin',
        category: 'analyzer',
        hasCustomUI: true,
        platform: 'both',
        parameters: [
            {
                id: 'a4_hz',
                deviceId: 'native-scoring',
                name: 'A4 Reference',
                type: 'float',
                value: 440,
                defaultValue: 440,
                minValue: 400,
                maxValue: 490,
                unit: 'Hz',
                automatable: false,
                hasAutomation: false,
            },
            {
                id: 'mute',
                deviceId: 'native-scoring',
                name: 'Mute Output',
                type: 'bool',
                value: 0,
                defaultValue: 0,
                minValue: 0,
                maxValue: 1,
                unit: '',
                automatable: false,
                hasAutomation: false,
            },
            {
                id: 'tone',
                deviceId: 'native-scoring',
                name: 'Reference Tone',
                type: 'bool',
                value: 0,
                defaultValue: 0,
                minValue: 0,
                maxValue: 1,
                unit: '',
                automatable: false,
                hasAutomation: false,
            },
        ],
    },
];
