import { type WAMDescriptor } from '../../models/WamPluginHostTypes';

import { registerWAMPlugin } from './hostOperations/registerWAMPlugin';

const BUILTIN_WAM_DESCRIPTORS: WAMDescriptor[] = [
    {
        id: 'sourdaw.eq',
        name: 'Parametric EQ',
        vendor: 'Sourdaw',
        version: '1.0',
        category: 'effect',
        sdkVersion: '2.0',
        keywords: ['eq', 'filter', 'tone'],
    },
    {
        id: 'sourdaw.compressor',
        name: 'Compressor',
        vendor: 'Sourdaw',
        version: '1.0',
        category: 'effect',
        sdkVersion: '2.0',
        keywords: ['dynamics', 'compressor'],
    },
    {
        id: 'sourdaw.reverb',
        name: 'Reverb',
        vendor: 'Sourdaw',
        version: '1.0',
        category: 'effect',
        sdkVersion: '2.0',
        keywords: ['reverb', 'space'],
    },
    {
        id: 'sourdaw.delay',
        name: 'Delay',
        vendor: 'Sourdaw',
        version: '1.0',
        category: 'effect',
        sdkVersion: '2.0',
        keywords: ['delay', 'echo'],
    },
    {
        id: 'sourdaw.chorus',
        name: 'Chorus',
        vendor: 'Sourdaw',
        version: '1.0',
        category: 'effect',
        sdkVersion: '2.0',
        keywords: ['modulation', 'chorus'],
    },
    {
        id: 'sourdaw.distortion',
        name: 'Distortion',
        vendor: 'Sourdaw',
        version: '1.0',
        category: 'effect',
        sdkVersion: '2.0',
        keywords: ['distortion', 'saturation'],
    },
    {
        id: 'sourdaw.limiter',
        name: 'Limiter',
        vendor: 'Sourdaw',
        version: '1.0',
        category: 'effect',
        sdkVersion: '2.0',
        keywords: ['dynamics', 'limiter'],
    },
    {
        id: 'sourdaw.synth',
        name: 'Subtractive Synth',
        vendor: 'Sourdaw',
        version: '1.0',
        category: 'instrument',
        sdkVersion: '2.0',
        keywords: ['synth', 'subtractive'],
    },
    {
        id: 'sourdaw.drumkit',
        name: 'Drum Machine',
        vendor: 'Sourdaw',
        version: '1.0',
        category: 'instrument',
        sdkVersion: '2.0',
        keywords: ['drums', 'percussion'],
    },
    {
        id: 'sourdaw.sampler',
        name: 'Sampler',
        vendor: 'Sourdaw',
        version: '1.0',
        category: 'instrument',
        sdkVersion: '2.0',
        keywords: ['sampler', 'sample'],
    },
    {
        id: 'sourdaw.alchemy',
        name: 'Alchemy',
        vendor: 'Sourdaw',
        version: '1.0',
        category: 'instrument',
        sdkVersion: '2.0',
        keywords: ['synth', 'additive', 'spectral', 'virtual analog'],
        isHighEnd: true,
    },
    {
        id: 'sourdaw.space-designer',
        name: 'Space Designer',
        vendor: 'Sourdaw',
        version: '1.0',
        category: 'effect',
        sdkVersion: '2.0',
        keywords: ['reverb', 'convolution', 'impulse response'],
        isHighEnd: true,
    },
    {
        id: 'sourdaw.pro-eq',
        name: 'Pro EQ',
        vendor: 'Sourdaw',
        version: '1.0',
        category: 'effect',
        sdkVersion: '2.0',
        keywords: ['eq', 'parametric', 'mastering'],
        isHighEnd: true,
    },
];

export function registerBuiltinPlugins(): void {
    for (const desc of BUILTIN_WAM_DESCRIPTORS) {
        registerWAMPlugin(desc);
    }
}
