import { type PresetAction, clipAction } from './Types';

export const clipPresets: readonly PresetAction[] = [
    // ─── Clip operations ────────────────────────────────────────────────
    {
        id: 'duplicate-clip',
        label: 'Duplicate Clip',
        keywords: ['duplicate clip', 'copy clip', 'clone clip'],
        commandAliases: ['copy clip', 'clone clip'],
        category: 'Clip',
        requiresSelection: 'clip',
        buildAction: clipAction('duplicateClip', (id) => ({ clipId: id })),
    },
    {
        id: 'dup-clip-next-bar',
        label: 'Duplicate Clip to Next Bar',
        keywords: ['duplicate to next bar', 'copy to next bar'],
        category: 'Clip',
        requiresSelection: 'clip',
        buildAction: clipAction('duplicateClipToNextBar', (id) => ({ clipId: id })),
    },
    {
        id: 'remove-clip',
        label: 'Delete Clip',
        keywords: ['delete clip', 'remove clip'],
        category: 'Clip',
        requiresSelection: 'clip',
        isDestructive: true,
        buildAction: clipAction('removeClip', (id) => ({ clipId: id })),
    },
    {
        id: 'copy-clip',
        label: 'Copy Clip',
        keywords: ['copy clip', 'clipboard copy'],
        category: 'Clip',
        requiresSelection: 'clip',
        buildAction: () => ({ type: 'copyClip' }),
    },
    {
        id: 'cut-clip',
        label: 'Cut Clip',
        keywords: ['cut clip', 'clipboard cut'],
        category: 'Clip',
        requiresSelection: 'clip',
        buildAction: () => ({ type: 'cutClip' }),
    },
    {
        id: 'paste-clip',
        label: 'Paste Clip',
        keywords: ['paste', 'paste clip'],
        category: 'Clip',
        buildAction: () => ({ type: 'pasteClip' }),
    },
    {
        id: 'normalize-clip',
        label: 'Normalize Clip',
        keywords: ['normalize', 'normalize clip', 'loudness'],
        category: 'Clip',
        requiresSelection: 'clip',
        buildAction: clipAction('normalizeClip', (id) => ({ clipId: id })),
    },
    {
        id: 'reverse-clip',
        label: 'Reverse Clip',
        keywords: ['reverse clip', 'backwards'],
        category: 'Clip',
        requiresSelection: 'clip',
        buildAction: clipAction('reverseClip', (id) => ({ clipId: id })),
    },
    {
        id: 'mute-clip',
        label: 'Mute Clip',
        keywords: ['mute clip', 'silence clip'],
        category: 'Clip',
        requiresSelection: 'clip',
        buildAction: clipAction('muteClip', (id) => ({ clipId: id, muted: true })),
    },
    {
        id: 'unmute-clip',
        label: 'Unmute Clip',
        keywords: ['unmute clip'],
        category: 'Clip',
        requiresSelection: 'clip',
        buildAction: clipAction('muteClip', (id) => ({ clipId: id, muted: false })),
    },
    {
        id: 'lock-clip',
        label: 'Lock Clip',
        keywords: ['lock clip', 'lock'],
        category: 'Clip',
        requiresSelection: 'clip',
        buildAction: clipAction('lockClip', (id) => ({ clipId: id, locked: true })),
    },
    {
        id: 'unlock-clip',
        label: 'Unlock Clip',
        keywords: ['unlock clip', 'unlock'],
        category: 'Clip',
        requiresSelection: 'clip',
        buildAction: clipAction('lockClip', (id) => ({ clipId: id, locked: false })),
    },
    {
        id: 'loop-clip',
        label: 'Enable Clip Looping',
        keywords: ['loop clip', 'enable loop', 'clip loop'],
        category: 'Clip',
        requiresSelection: 'clip',
        buildAction: clipAction('setClipLoop', (id) => ({ clipId: id, enabled: true })),
    },
    {
        id: 'unloop-clip',
        label: 'Disable Clip Looping',
        keywords: ['unloop clip', 'disable loop'],
        category: 'Clip',
        requiresSelection: 'clip',
        buildAction: clipAction('setClipLoop', (id) => ({ clipId: id, enabled: false })),
    },
    {
        id: 'nudge-left',
        label: 'Nudge Clip Left',
        keywords: ['nudge left', 'move clip left'],
        category: 'Clip',
        requiresSelection: 'clip',
        buildAction: clipAction('nudgeClip', (id) => ({ clipId: id, beats: -1 })),
    },
    {
        id: 'nudge-right',
        label: 'Nudge Clip Right',
        keywords: ['nudge right', 'move clip right'],
        category: 'Clip',
        requiresSelection: 'clip',
        buildAction: clipAction('nudgeClip', (id) => ({ clipId: id, beats: 1 })),
    },
    {
        id: 'strip-silence',
        label: 'Strip Silence',
        keywords: ['strip silence', 'remove silence', 'clean clip'],
        category: 'Clip',
        requiresSelection: 'clip',
        buildAction: clipAction('stripSilence', (id) => ({ clipId: id })),
    },
    {
        id: 'detect-tempo',
        label: 'Detect Clip Tempo',
        keywords: ['detect tempo', 'tempo detect', 'bpm detection'],
        category: 'Clip',
        requiresSelection: 'clip',
        buildAction: clipAction('detectTempo', (id) => ({ clipId: id })),
    },
    {
        id: 'detect-key',
        label: 'Detect Clip Key',
        keywords: ['detect key', 'key detection', 'find key'],
        category: 'Clip',
        requiresSelection: 'clip',
        buildAction: clipAction('detectKey', (id) => ({ clipId: id })),
    },

    // ─── Stretch operations ─────────────────────────────────────────────
    {
        id: 'repitch-mode',
        label: 'Enable Repitch Mode',
        keywords: ['repitch', 'pitch stretch', 'varispeed'],
        category: 'Clip',
        requiresSelection: 'clip',
        buildAction: clipAction('setClipStretchMode', (id) => ({ clipId: id, mode: 'repitch' })),
    },
    // `timestretch` reaches the same playback-rate resample as `repitch` at both
    // schedulers — no pitch-preserving executor exists in the product. The two
    // modes differ only in clip geometry (a ratio change keeps a `timestretch`
    // clip's timeline length). The label says so rather than promising a
    // stretch the engine cannot perform; the mode id stays as-is because it is
    // persisted in saved projects.
    {
        id: 'timestretch-mode',
        label: 'Enable Timestretch (no pitch preservation yet)',
        keywords: ['timestretch', 'time stretch', 'elastic'],
        category: 'Clip',
        requiresSelection: 'clip',
        buildAction: clipAction('setClipStretchMode', (id) => ({ clipId: id, mode: 'timestretch' })),
    },
    {
        id: 'stretch-off',
        label: 'Disable Stretching',
        keywords: ['disable stretch', 'stretch off', 'no stretch'],
        category: 'Clip',
        requiresSelection: 'clip',
        buildAction: clipAction('setClipStretchMode', (id) => ({ clipId: id, mode: 'off' })),
    },
];
