import { type PresetAction, trackAction } from './types';

export const devicePresets: readonly PresetAction[] = [
    {
        id: 'add-eq',
        label: 'Add EQ',
        keywords: ['eq', 'equalizer', 'add eq', 'parametric'],
        category: 'Device',
        requiresSelection: 'track',
        buildAction: trackAction('addDevice', (id) => ({ trackId: id, deviceType: 'EQ' })),
    },
    {
        id: 'add-compressor',
        label: 'Add Compressor',
        keywords: ['compressor', 'comp', 'add compressor', 'dynamics'],
        category: 'Device',
        requiresSelection: 'track',
        buildAction: trackAction('addDevice', (id) => ({ trackId: id, deviceType: 'Compressor' })),
    },
    {
        id: 'add-reverb',
        label: 'Add Reverb',
        keywords: ['reverb', 'add reverb', 'room', 'hall', 'plate'],
        category: 'Device',
        requiresSelection: 'track',
        buildAction: trackAction('addDevice', (id) => ({ trackId: id, deviceType: 'Reverb' })),
    },
    {
        id: 'add-delay',
        label: 'Add Delay',
        keywords: ['delay', 'add delay', 'echo', 'repeat'],
        category: 'Device',
        requiresSelection: 'track',
        buildAction: trackAction('addDevice', (id) => ({ trackId: id, deviceType: 'Delay' })),
    },
    {
        id: 'add-gain',
        label: 'Add Gain Utility',
        keywords: ['gain', 'utility', 'add gain', 'trim', 'level'],
        category: 'Device',
        requiresSelection: 'track',
        buildAction: trackAction('addDevice', (id) => ({ trackId: id, deviceType: 'Gain' })),
    },
    {
        id: 'add-chorus',
        label: 'Add Chorus',
        keywords: ['chorus', 'add chorus', 'ensemble'],
        category: 'Device',
        requiresSelection: 'track',
        buildAction: trackAction('addDevice', (id) => ({ trackId: id, deviceType: 'Chorus' })),
    },
    {
        id: 'add-flanger',
        label: 'Add Flanger',
        keywords: ['flanger', 'add flanger'],
        category: 'Device',
        requiresSelection: 'track',
        buildAction: trackAction('addDevice', (id) => ({ trackId: id, deviceType: 'Flanger' })),
    },
    {
        id: 'add-phaser',
        label: 'Add Phaser',
        keywords: ['phaser', 'add phaser', 'phase'],
        category: 'Device',
        requiresSelection: 'track',
        buildAction: trackAction('addDevice', (id) => ({ trackId: id, deviceType: 'Phaser' })),
    },
    {
        id: 'add-distortion',
        label: 'Add Distortion',
        keywords: ['distortion', 'add distortion', 'overdrive', 'drive', 'saturation'],
        category: 'Device',
        requiresSelection: 'track',
        buildAction: trackAction('addDevice', (id) => ({ trackId: id, deviceType: 'Distortion' })),
    },
    {
        id: 'add-limiter',
        label: 'Add Limiter',
        keywords: ['limiter', 'add limiter', 'brick wall'],
        category: 'Device',
        requiresSelection: 'track',
        buildAction: trackAction('addDevice', (id) => ({ trackId: id, deviceType: 'Limiter' })),
    },
    {
        id: 'add-gate',
        label: 'Add Gate',
        keywords: ['gate', 'noise gate', 'add gate', 'expander'],
        category: 'Device',
        requiresSelection: 'track',
        buildAction: trackAction('addDevice', (id) => ({ trackId: id, deviceType: 'Gate' })),
    },
    {
        id: 'add-deesser',
        label: 'Add De-esser',
        keywords: ['deesser', 'de-esser', 'sibilance'],
        category: 'Device',
        requiresSelection: 'track',
        buildAction: trackAction('addDevice', (id) => ({ trackId: id, deviceType: 'DeEsser' })),
    },
    {
        id: 'add-autopan',
        label: 'Add Auto Pan',
        keywords: ['auto pan', 'autopan', 'panner', 'tremolo'],
        category: 'Device',
        requiresSelection: 'track',
        buildAction: trackAction('addDevice', (id) => ({ trackId: id, deviceType: 'AutoPan' })),
    },
    {
        id: 'add-bitcrusher',
        label: 'Add Bit Crusher',
        keywords: ['bitcrusher', 'bit crusher', 'downsample', 'lo-fi', 'lofi'],
        category: 'Device',
        requiresSelection: 'track',
        buildAction: trackAction('addDevice', (id) => ({ trackId: id, deviceType: 'BitCrusher' })),
    },
    {
        id: 'add-filter',
        label: 'Add Filter',
        keywords: ['filter', 'add filter', 'lowpass', 'highpass', 'bandpass'],
        category: 'Device',
        requiresSelection: 'track',
        buildAction: trackAction('addDevice', (id) => ({ trackId: id, deviceType: 'Filter' })),
    },
];
