import { type PresetAction, clipAction } from './types';

export const midiPresets: readonly PresetAction[] = [
    // ─── MIDI operations ────────────────────────────────────────────────
    {
        id: 'quantize',
        label: 'Quantize Notes',
        keywords: ['quantize', 'snap notes', 'align notes', 'grid'],
        category: 'MIDI',
        requiresSelection: 'clipMidi',
        buildAction: clipAction('quantizeNotes', (id) => ({ clipId: id, gridSize: 0.25 })),
    },
    {
        id: 'quantize-lengths',
        label: 'Quantize Note Lengths',
        keywords: ['quantize lengths', 'quantize durations', 'snap durations'],
        category: 'MIDI',
        requiresSelection: 'clipMidi',
        buildAction: clipAction('quantizeNoteLengths', (id) => ({ clipId: id, gridSize: 0.25 })),
    },
    {
        id: 'humanize',
        label: 'Humanize Notes',
        keywords: ['humanize', 'randomize timing', 'feel', 'swing'],
        category: 'MIDI',
        requiresSelection: 'clipMidi',
        buildAction: clipAction('humanizeNotes', (id) => ({ clipId: id, amount: 0.3 })),
    },
    {
        id: 'transpose-up-oct',
        label: 'Transpose Up 1 Octave',
        keywords: ['transpose up octave', 'octave up', '+12'],
        category: 'MIDI',
        requiresSelection: 'clipMidi',
        buildAction: clipAction('transposeNotes', (id) => ({ clipId: id, semitones: 12 })),
    },
    {
        id: 'transpose-dn-oct',
        label: 'Transpose Down 1 Octave',
        keywords: ['transpose down octave', 'octave down', '-12'],
        category: 'MIDI',
        requiresSelection: 'clipMidi',
        buildAction: clipAction('transposeNotes', (id) => ({ clipId: id, semitones: -12 })),
    },
    {
        id: 'transpose-up-5th',
        label: 'Transpose Up 5th',
        keywords: ['transpose up fifth', 'up 5th', '+7'],
        category: 'MIDI',
        requiresSelection: 'clipMidi',
        buildAction: clipAction('transposeNotes', (id) => ({ clipId: id, semitones: 7 })),
    },
    {
        id: 'transpose-dn-5th',
        label: 'Transpose Down 5th',
        keywords: ['transpose down fifth', 'down 5th', '-7'],
        category: 'MIDI',
        requiresSelection: 'clipMidi',
        buildAction: clipAction('transposeNotes', (id) => ({ clipId: id, semitones: -7 })),
    },
    {
        id: 'invert-notes',
        label: 'Invert Notes',
        keywords: ['invert', 'invert notes', 'mirror notes'],
        category: 'MIDI',
        requiresSelection: 'clipMidi',
        buildAction: clipAction('invertNotes', (id) => ({ clipId: id })),
    },
    {
        id: 'retrograde-notes',
        label: 'Retrograde Notes',
        keywords: ['retrograde', 'reverse notes', 'backwards notes'],
        category: 'MIDI',
        requiresSelection: 'clipMidi',
        buildAction: clipAction('retrogradeNotes', (id) => ({ clipId: id })),
    },
    {
        id: 'arpeggiate',
        label: 'Arpeggiate Notes',
        keywords: ['arpeggiate', 'arp', 'arpeggio'],
        category: 'MIDI',
        requiresSelection: 'clipMidi',
        buildAction: clipAction('arpeggiate', (id) => ({ clipId: id, pattern: 'up' })),
    },
    {
        id: 'compress-vel',
        label: 'Compress Velocities',
        keywords: ['compress velocity', 'compress velocities', 'velocity compress'],
        category: 'MIDI',
        requiresSelection: 'clipMidi',
        buildAction: clipAction('scaleVelocities', (id) => ({ clipId: id, curve: 'compress' })),
    },
    {
        id: 'expand-vel',
        label: 'Expand Velocities',
        keywords: ['expand velocity', 'expand velocities', 'velocity expand'],
        category: 'MIDI',
        requiresSelection: 'clipMidi',
        buildAction: clipAction('scaleVelocities', (id) => ({ clipId: id, curve: 'expand' })),
    },
    {
        id: 'extract-groove',
        label: 'Extract Groove Template',
        keywords: ['extract groove', 'groove template', 'capture feel'],
        category: 'MIDI',
        requiresSelection: 'clipMidi',
        buildAction: clipAction('extractGroove', (id) => ({ clipId: id })),
    },
    {
        id: 'audio-to-midi',
        label: 'Audio to MIDI',
        keywords: ['audio to midi', 'convert audio', 'onset detection', 'rhythm detect'],
        category: 'MIDI',
        requiresSelection: 'clip',
        buildAction: (ctx) =>
            ctx.selectedClipId
                ? { type: 'audioToMidi', payload: { clipId: ctx.selectedClipId, trackId: ctx.selectedTrackId } }
                : null,
    },

    // ─── Groove presets ─────────────────────────────────────────────────
    {
        id: 'groove-swing',
        label: 'Apply Swing Groove',
        keywords: ['swing', 'swing groove', 'shuffle'],
        category: 'MIDI',
        requiresSelection: 'clipMidi',
        buildAction: clipAction('applyGroove', (id) => ({ clipId: id, grooveId: 'swing-light' })),
    },
    {
        id: 'groove-heavy-sw',
        label: 'Apply Heavy Swing',
        keywords: ['heavy swing', 'swing heavy'],
        category: 'MIDI',
        requiresSelection: 'clipMidi',
        buildAction: clipAction('applyGroove', (id) => ({ clipId: id, grooveId: 'swing-heavy' })),
    },
    {
        id: 'groove-mpc60',
        label: 'Apply MPC 60 Groove',
        keywords: ['mpc', 'mpc 60', 'mpc60', 'mpc feel'],
        category: 'MIDI',
        requiresSelection: 'clipMidi',
        buildAction: clipAction('applyGroove', (id) => ({ clipId: id, grooveId: 'mpc-60' })),
    },
    {
        id: 'groove-sp1200',
        label: 'Apply SP-1200 Groove',
        keywords: ['sp1200', 'sp 1200', 'sp-1200'],
        category: 'MIDI',
        requiresSelection: 'clipMidi',
        buildAction: clipAction('applyGroove', (id) => ({ clipId: id, grooveId: 'sp-1200' })),
    },
    {
        id: 'groove-straight',
        label: 'Apply Straight Groove',
        keywords: ['straight', 'straight groove', 'no swing'],
        category: 'MIDI',
        requiresSelection: 'clipMidi',
        buildAction: clipAction('applyGroove', (id) => ({ clipId: id, grooveId: 'straight' })),
    },

    // ─── MPE / MIDI I/O ─────────────────────────────────────────────────
    {
        id: 'enable-mpe',
        label: 'Enable MPE',
        keywords: ['mpe', 'enable mpe', 'midi polyphonic expression'],
        category: 'MIDI',
        buildAction: () => ({ type: 'enableMpe' }),
    },
    {
        id: 'disable-mpe',
        label: 'Disable MPE',
        keywords: ['disable mpe'],
        category: 'MIDI',
        buildAction: () => ({ type: 'disableMpe' }),
    },
];
