import { type PresetAction, trackAction } from './Types';

export const trackPresets: readonly PresetAction[] = [
    // ─── Creation ───────────────────────────────────────────────────────
    {
        id: 'add-audio-track',
        label: 'Add Audio Track',
        keywords: ['add audio', 'new audio', 'create audio', 'audio track'],
        category: 'Track',
        buildAction: () => ({
            type: 'addTrack',
            payload: { name: `Audio ${String(Date.now() % 1000)}`, kind: 'audio' },
        }),
    },
    {
        id: 'add-midi-track',
        label: 'Add MIDI Track',
        keywords: ['add midi', 'new midi', 'create midi', 'midi track', 'instrument track'],
        category: 'Track',
        buildAction: () => ({ type: 'addTrack', payload: { name: `MIDI ${String(Date.now() % 1000)}`, kind: 'midi' } }),
    },
    {
        id: 'add-bus-track',
        label: 'Add Bus Track',
        keywords: ['add bus', 'new bus', 'create bus', 'bus track', 'aux', 'return'],
        category: 'Track',
        buildAction: () => ({ type: 'addTrack', payload: { name: `Bus ${String(Date.now() % 1000)}`, kind: 'bus' } }),
    },
    {
        id: 'add-folder',
        label: 'Create Folder Track',
        keywords: ['add folder', 'new folder', 'create folder', 'group folder'],
        category: 'Track',
        buildAction: () => ({ type: 'createFolder', payload: { name: `Folder ${String(Date.now() % 1000)}` } }),
    },

    // ─── Manipulation ───────────────────────────────────────────────────
    {
        id: 'mute-track',
        label: 'Mute Track',
        keywords: ['mute', 'mute track', 'silence track'],
        category: 'Track',
        requiresSelection: 'track',
        buildAction: trackAction('muteTrack', (id) => ({ trackId: id, muted: true })),
    },
    {
        id: 'unmute-track',
        label: 'Unmute Track',
        keywords: ['unmute', 'unmute track'],
        category: 'Track',
        requiresSelection: 'track',
        buildAction: trackAction('muteTrack', (id) => ({ trackId: id, muted: false })),
    },
    {
        id: 'solo-track',
        label: 'Solo Track',
        keywords: ['solo', 'solo track'],
        category: 'Track',
        requiresSelection: 'track',
        buildAction: trackAction('soloTrack', (id) => ({ trackId: id, soloed: true })),
    },
    {
        id: 'unsolo-track',
        label: 'Unsolo Track',
        keywords: ['unsolo', 'unsolo track'],
        category: 'Track',
        requiresSelection: 'track',
        buildAction: trackAction('soloTrack', (id) => ({ trackId: id, soloed: false })),
    },
    {
        id: 'clear-solos',
        label: 'Clear All Solos',
        keywords: ['clear solos', 'unsolo all', 'reset solos'],
        category: 'Track',
        buildAction: () => ({ type: 'clearSolos' }),
    },
    {
        id: 'arm-track',
        label: 'Arm Track for Recording',
        keywords: ['arm', 'arm track', 'record enable'],
        category: 'Track',
        requiresSelection: 'track',
        buildAction: trackAction('armTrack', (id) => ({ trackId: id, armed: true })),
    },
    {
        id: 'disarm-track',
        label: 'Disarm Track',
        keywords: ['disarm', 'disarm track', 'record disable'],
        category: 'Track',
        requiresSelection: 'track',
        buildAction: trackAction('armTrack', (id) => ({ trackId: id, armed: false })),
    },
    {
        id: 'duplicate-track',
        label: 'Duplicate Track',
        keywords: ['duplicate track', 'copy track', 'clone track'],
        category: 'Track',
        requiresSelection: 'track',
        buildAction: trackAction('duplicateTrack', (id) => ({ trackId: id })),
    },
    {
        id: 'remove-track',
        label: 'Delete Track',
        keywords: ['delete track', 'remove track'],
        category: 'Track',
        requiresSelection: 'track',
        isDestructive: true,
        buildAction: (context) => {
            if (!context.selectedTrackId || !context.selectedTrackKind || context.selectedTrackKind === 'master') {
                return null;
            }
            return { type: 'removeTrack', payload: { trackId: context.selectedTrackId } };
        },
    },
    {
        id: 'freeze-track',
        label: 'Freeze Track',
        keywords: ['freeze', 'freeze track', 'render track'],
        category: 'Track',
        requiresSelection: 'track',
        buildAction: trackAction('freezeTrack', (id) => ({ trackId: id })),
    },
    {
        id: 'unfreeze-track',
        label: 'Unfreeze Track',
        keywords: ['unfreeze', 'unfreeze track', 'thaw'],
        category: 'Track',
        requiresSelection: 'track',
        buildAction: trackAction('unfreezeTrack', (id) => ({ trackId: id })),
    },
    {
        id: 'bounce-in-place',
        label: 'Bounce Track In Place',
        keywords: ['bounce in place', 'bounce track', 'render in place', 'bip'],
        category: 'Track',
        requiresSelection: 'track',
        isDestructive: true,
        buildAction: trackAction('bounceInPlace', (id) => ({ trackId: id })),
    },
    {
        id: 'bounce-new-track',
        label: 'Bounce to New Track',
        keywords: ['bounce to new', 'bounce new track'],
        category: 'Track',
        requiresSelection: 'track',
        buildAction: trackAction('bounceToNewTrack', (id) => ({ trackId: id })),
    },
    {
        id: 'hide-track',
        label: 'Hide Track',
        keywords: ['hide track', 'hide'],
        category: 'Track',
        requiresSelection: 'track',
        buildAction: trackAction('hideTrack', (id) => ({ trackId: id, hidden: true })),
    },
    {
        id: 'show-track',
        label: 'Show Track',
        keywords: ['show track', 'unhide track'],
        category: 'Track',
        requiresSelection: 'track',
        buildAction: trackAction('hideTrack', (id) => ({ trackId: id, hidden: false })),
    },
    {
        id: 'disable-track',
        label: 'Disable Track',
        keywords: ['disable track', 'deactivate track'],
        category: 'Track',
        requiresSelection: 'track',
        buildAction: trackAction('disableTrack', (id) => ({ trackId: id, disabled: true })),
    },
    {
        id: 'enable-track',
        label: 'Enable Track',
        keywords: ['enable track', 'activate track'],
        category: 'Track',
        requiresSelection: 'track',
        buildAction: trackAction('disableTrack', (id) => ({ trackId: id, disabled: false })),
    },
    {
        id: 'fold-track',
        label: 'Fold Track',
        keywords: ['fold track', 'collapse track'],
        category: 'Track',
        requiresSelection: 'track',
        buildAction: trackAction('foldTrack', (id) => ({ trackId: id, folded: true })),
    },
    {
        id: 'unfold-track',
        label: 'Unfold Track',
        keywords: ['unfold track', 'expand track'],
        category: 'Track',
        requiresSelection: 'track',
        buildAction: trackAction('foldTrack', (id) => ({ trackId: id, folded: false })),
    },
    {
        id: 'solo-safe',
        label: 'Toggle Solo Safe',
        keywords: ['solo safe', 'solo lock'],
        category: 'Track',
        requiresSelection: 'track',
        buildAction: trackAction('toggleSoloSafe', (id) => ({ trackId: id })),
    },
];
