import { type PresetAction } from './Types';

export const transportPresets: readonly PresetAction[] = [
    {
        id: 'play',
        label: 'Play',
        keywords: ['play', 'start playback', 'resume', 'resume playback'],
        commandAliases: ['start playback', 'resume', 'resume playback'],
        category: 'Transport',
        buildAction: () => ({ type: 'setPlayback', payload: { playing: true } }),
    },
    {
        id: 'pause',
        label: 'Pause',
        keywords: ['pause', 'pause playback'],
        commandAliases: ['pause playback'],
        category: 'Transport',
        buildAction: () => ({ type: 'setPlayback', payload: { playing: false } }),
    },
    {
        id: 'stop',
        label: 'Stop',
        keywords: ['stop', 'halt'],
        commandAliases: ['halt'],
        category: 'Transport',
        buildAction: () => ({ type: 'stopPlayback' }),
    },
    {
        id: 'loop',
        label: 'Toggle Loop',
        keywords: ['loop', 'cycle', 'toggle loop'],
        commandAliases: ['loop', 'cycle'],
        category: 'Transport',
        buildAction: () => ({ type: 'toggleLoop' }),
    },
    {
        id: 'metronome',
        label: 'Toggle Metronome',
        keywords: ['metronome', 'click', 'click track', 'toggle metronome'],
        category: 'Transport',
        buildAction: () => ({ type: 'toggleMetronome' }),
    },
    {
        id: 'punch-in-out-on',
        label: 'Enable Punch In/Out',
        keywords: ['enable punch in/out', 'turn punch in/out on'],
        category: 'Transport',
        buildAction: () => ({ type: 'setPunchEnabled', payload: { enabled: true } }),
    },
    {
        id: 'punch-in-out-off',
        label: 'Disable Punch In/Out',
        keywords: ['disable punch in/out', 'turn punch in/out off'],
        category: 'Transport',
        buildAction: () => ({ type: 'setPunchEnabled', payload: { enabled: false } }),
    },
    {
        id: 'count-in',
        label: 'Toggle Count-In',
        keywords: ['count in', 'count-in', 'precount', 'toggle count'],
        category: 'Transport',
        buildAction: () => ({ type: 'toggleCountIn' }),
    },
    {
        id: 'pre-roll',
        label: 'Toggle Pre-Roll',
        keywords: ['pre roll', 'pre-roll', 'preroll'],
        category: 'Transport',
        buildAction: () => ({ type: 'togglePreRoll' }),
    },
];
