import type { AppAction, AppActionType } from '#/utils/handlerContract';

export const RUNTIME_ACTION_TYPES = [
    'importStemSet',
    'addTrack',
    'removeTrack',
    'removeAllTracks',
    'renameTrack',
    'selectTrack',
    'muteTrack',
    'soloTrack',
    'setSoloSafe',
    'toggleSoloSafe',
    'armTrack',
    'freezeTrack',
    'unfreezeTrack',
    'flattenTrack',
    'bounceInPlace',
    'duplicateTrack',
    'reorderTrack',
    'setTrackGain',
    'setTrackPan',
    'setTrackColor',
    'setTempo',
    'setTimeSignature',
    'setPlayback',
    'togglePlayback',
    'stopPlayback',
    'toggleRecording',
    'setMasterGain',
    'toggleLoop',
    'toggleMetronome',
    'setMetronomeVolume',
    'setLoopRegion',
    'setLoopEnabled',
    'setMetronomeEnabled',
    'restoreLoopRegion',
    'addClip',
    'moveClip',
    'duplicateClip',
    'duplicateClipToNextBar',
    'removeClip',
    'splitClip',
    'trimClipStart',
    'trimClipEnd',
    'setClipFade',
    'copyClip',
    'cutClip',
    'pasteClip',
    'addDevice',
    'bypassDevice',
    'removeDevice',
    'setDeviceParameter',
    'createBus',
    'createFolder',
    'setSend',
    'setWorkspaceMode',
    'openPreferencesDialog',
    'openMixer',
    'closeMixer',
    'toggleSidebar',
    'toggleInspector',
    'toggleChatPanel',
    'setEditingTool',
    'setMarqueeSelection',
    'addMarker',
    'removeMarker',
    'setMarkerColor',
    'addSection',
    'removeSection',
    'renameSection',
    'addAutomationLane',
    'automateSendRange',
    'automateSendRanges',
    'automateTrackGainRange',
    'renderProjectSections',
    'addAutomationPoint',
    'setAutomationLaneEnabled',
    'quantizeNotes',
    'removeShortMidiOverlaps',
    'createDrumPreviewBranches',
    'copyMidiArticulations',
    'quantizeNoteLengths',
    'transposeNotes',
    'humanizeNotes',
    'invertNotes',
    'retrogradeNotes',
    'scaleVelocities',
    'scaleAllVelocities',
    'setAllVelocities',
    'importMidiFile',
    'normalizeClip',
    'reverseClip',
    'glueClips',
    'nudgeClip',
    'crossfadeClips',
    'setClipGain',
    'setClipColor',
    'lockClip',
    'renameClip',
    'consolidateSelection',
    'bounceSelection',
    'seekPlayhead',
    'setPunchIn',
    'setPunchOut',
    'setPunchEnabled',
    'toggleCountIn',
    'setCountInBars',
    'togglePreRoll',
    'setPreRollBars',
    'addTimeSignatureChange',
    'removeTimeSignatureChange',
    'setTrackOutput',
    'addSend',
    'removeSend',
    'removeAutomationPoint',
    'setAutomationMode',
    'hideTrack',
    'disableTrack',
    'setTrackHeight',
    'setSnapValue',
    'zoomToFit',
    'zoomToSelection',
    'exportProject',
    'saveProject',
    'newProject',
    'importAudioFile',
    'exportMidi',
    'foldTrack',
    'groupTracks',
    'ungroupTracks',
    'scaleAutomation',
    'stretchAutomation',
    'invertAutomation',
    'reverseAutomation',
    'thinAutomation',
    'quantizeAutomation',
    'loadPreset',
    'savePreset',
    'generateDrumPattern',
    'generateMelody',
    'generateChordProgression',
    'setClipLoop',
    'setClipLoopLength',
    'extractGroove',
    'applyGroove',
    'setClipStretchMode',
    'setClipStretchRatio',
    'fitClipToBeats',
    'analyzeMix',
    'autoFixMix',
    'enableMpe',
    'disableMpe',
    'getLatencyReport',
    'createCollabSession',
    'joinCollabSession',
    'leaveCollabSession',
    'scanPlugins',
    'loadExternalPlugin',
    'audioToMidi',
    'muteClip',
    'clearSolos',
    'setTrackNotes',
    'setTrackInput',
    'zoomTracksVertical',
    'deleteTime',
    'insertTime',
    'duplicateTimeRange',
    'stripSilence',
    'detectTempo',
    'detectKey',
    'consolidateAllTracks',
    'arpeggiate',
    'addSidechainRoute',
    'removeSidechainRoute',
    'bounceToNewTrack',
    'createTrackAlternative',
    'switchTrackAlternative',
    'renameTrackAlternative',
    'deleteTrackAlternative',
    'addChordEvent',
    'addCvOutput',
    'addNotes',
    'assignToVca',
    'autoOrganizeProject',
    'captureScratchPad',
    'clearAllMidiMappings',
    'clearChordTrack',
    'clearMidiOutput',
    'clearScratchPad',
    'commitScratchPad',
    'compareToReference',
    'completeMidi',
    'connectPush',
    'createAdjustmentLayer',
    'addAdjustmentRegion',
    'createCompGroup',
    'createPatternInstance',
    'createProjectVersion',
    'createVcaGroup',
    'createVersionBranch',
    'deleteMacro',
    'deleteTrackTemplate',
    'detachPatternInstance',
    'detectSongStructure',
    'detectTransients',
    'disconnectPush',
    'enableWarping',
    'exportDawProject',
    'generateAllTransitions',
    'generateBassline',
    'generateFill',
    'getMentorTips',
    'labelUndoBranch',
    'loadRaveModel',
    'loadTrackTemplate',
    'nextSetlistItem',
    'playMacro',
    'previousSetlistItem',
    'quantizeTransients',
    'redo',
    'removeChordEvent',
    'removeFromVca',
    'restoreAutomationLanePoints',
    'restoreClip',
    'restoreProjectVersion',
    'restoreTrack',
    'saveTrackTemplate',
    'searchSamples',
    'setControlSurface',
    'setMidiOutput',
    'setRaveBlend',
    'setVcaGain',
    'setWarpAlgorithm',
    'setWarpPitchShift',
    'startMacroRecording',
    'stopMacroRecording',
    'switchMonitor',
    'toggleChordTrack',
    'toggleControlRoomDim',
    'toggleControlRoomMono',
    'toggleLoopRecord',
    'toggleNodeView',
    'togglePunchRecording',
    'toggleScratchPad',
    'toggleUndoTree',
    'triggerScene',
    'undo',
    'variationMidi',
] as const satisfies readonly AppActionType[];

export type RuntimeActionType = (typeof RUNTIME_ACTION_TYPES)[number];

type AppActionOf<ActionType extends AppActionType> = Extract<AppAction, { type: ActionType }>;
type AppActionPayload<ActionType extends AppActionType> =
    AppActionOf<ActionType> extends { payload: infer Payload } ? Payload : never;

export const RUNTIME_ACTION_OVERRIDE_PAYLOAD_KEYS = {
    importStemSet: ['selectionId', 'groupName', 'stems'],
    addTrack: ['name', 'kind', 'select'],
    muteTrack: ['trackId', 'muted'],
    setTrackGain: ['trackId', 'gain'],
    setTrackPan: ['trackId', 'pan'],
    armTrack: ['trackId', 'armed'],
    lockClip: ['clipId', 'locked'],
    muteClip: ['clipId', 'muted'],
    setClipColor: ['clipId', 'color'],
    setClipFade: ['clipId', 'fadeInBeats', 'fadeOutBeats'],
    setClipLoop: ['clipId', 'enabled'],
    setPunchEnabled: ['enabled'],
    addClip: ['trackId', 'startBeat', 'endBeat', 'name', 'type', 'audioBufferId'],
    addNotes: ['clipId', 'notes'],
    addDevice: ['trackId', 'deviceType', 'afterDeviceId'],
    removeDevice: ['deviceId', 'expectedTrackId', 'expectedDeviceIds'],
    setDeviceParameter: [
        'deviceId',
        'paramId',
        'value',
        'expectedTrackId',
        'expectedDeviceType',
        'expectedDeviceIds',
        'expectedValue',
        'expectedTrackFrozen',
    ],
    createBus: ['name'],
    createTrackAlternative: ['trackId', 'name', 'duplicateActive'],
    deleteTrackAlternative: ['trackId', 'alternativeId'],
    duplicateClip: ['clipId'],
    duplicateClipToNextBar: ['clipId'],
    glueClips: ['clipIds'],
    splitClip: ['clipId', 'beat'],
    addMarker: ['beat', 'name'],
    addSection: ['startBeat', 'endBeat', 'name'],
    addAutomationLane: ['trackId', 'parameterId', 'parameterName'],
    automateSendRange: ['trackIds', 'busId', 'sectionName', 'reductionDb'],
    automateSendRanges: ['trackIds', 'busId', 'sectionIds', 'tailBars', 'targetLevelDb'],
    automateTrackGainRange: ['trackIds', 'sectionName', 'gainDb'],
    renderProjectSections: ['sectionIds'],
    addAutomationPoint: ['laneId', 'beat', 'value', 'curve', 'tension', 'stairSteps', 'cp1', 'cp2'],
    removeAutomationPoint: ['laneId', 'pointIndex'],
    addSidechainRoute: ['sourceTrackId', 'targetTrackId', 'targetDeviceId'],
    removeSidechainRoute: ['sourceTrackId', 'targetTrackId'],
    arpeggiate: ['clipId', 'pattern', 'rate', 'octaves', 'gate'],
    quantizeNotes: ['clipId', 'gridSize'],
    removeShortMidiOverlaps: ['clipId', 'maximumOverlapMs'],
    createDrumPreviewBranches: ['sectionId', 'candidateCount', 'varyingRoles'],
    copyMidiArticulations: ['sourceClipId', 'targetClipId'],
    transposeNotes: ['clipId', 'semitones'],
    setAutomationMode: ['trackId', 'mode'],
    scaleAutomation: ['laneId', 'factor'],
    stretchAutomation: ['laneId', 'factor'],
    thinAutomation: ['laneId', 'tolerance'],
    quantizeAutomation: ['laneId', 'gridSize'],
    generateDrumPattern: ['style', 'trackId', 'bars', 'density'],
    generateMelody: ['style', 'key', 'scale', 'trackId', 'bars'],
    generateChordProgression: ['style', 'key', 'scale', 'trackId', 'bars', 'voicing'],
    extractGroove: ['clipId'],
    createCollabSession: ['name'],
    joinCollabSession: ['inviteString', 'peerName'],
    createVcaGroup: ['name', 'trackIds'],
    addChordEvent: ['beat', 'root', 'quality', 'duration'],
    createAdjustmentLayer: ['name', 'effectType'],
    addAdjustmentRegion: ['layerId', 'startBeat', 'endBeat', 'blend', 'fadeInBeats', 'fadeOutBeats'],
} as const satisfies Partial<Record<RuntimeActionType, readonly string[]>>;

export const RUNTIME_ACTION_OVERRIDE_REQUIRED_PAYLOAD_KEYS = {
    importStemSet: ['selectionId', 'groupName', 'stems'],
    addTrack: ['name', 'kind'],
    muteTrack: ['trackId', 'muted'],
    setTrackGain: ['trackId', 'gain'],
    setTrackPan: ['trackId', 'pan'],
    armTrack: ['trackId', 'armed'],
    lockClip: ['clipId', 'locked'],
    muteClip: ['clipId', 'muted'],
    setClipColor: ['clipId', 'color'],
    setClipFade: ['clipId', 'fadeInBeats', 'fadeOutBeats'],
    setClipLoop: ['clipId', 'enabled'],
    setPunchEnabled: ['enabled'],
    addClip: ['trackId', 'startBeat', 'endBeat', 'name'],
    addNotes: ['clipId', 'notes'],
    addDevice: ['trackId', 'deviceType'],
    removeDevice: ['deviceId'],
    setDeviceParameter: ['deviceId', 'paramId', 'value'],
    createBus: ['name'],
    createTrackAlternative: ['trackId', 'name', 'duplicateActive'],
    deleteTrackAlternative: ['trackId', 'alternativeId'],
    duplicateClip: ['clipId'],
    duplicateClipToNextBar: ['clipId'],
    glueClips: ['clipIds'],
    splitClip: ['clipId', 'beat'],
    addMarker: ['beat', 'name'],
    addSection: ['startBeat', 'endBeat', 'name'],
    addAutomationLane: ['trackId', 'parameterId', 'parameterName'],
    automateSendRange: ['trackIds', 'busId', 'sectionName', 'reductionDb'],
    automateSendRanges: ['trackIds', 'busId', 'sectionIds', 'tailBars', 'targetLevelDb'],
    automateTrackGainRange: ['trackIds', 'sectionName', 'gainDb'],
    renderProjectSections: ['sectionIds'],
    addAutomationPoint: ['laneId', 'beat', 'value'],
    removeAutomationPoint: ['laneId', 'pointIndex'],
    addSidechainRoute: ['sourceTrackId', 'targetTrackId'],
    removeSidechainRoute: ['sourceTrackId', 'targetTrackId'],
    arpeggiate: ['clipId'],
    quantizeNotes: ['clipId', 'gridSize'],
    removeShortMidiOverlaps: ['clipId', 'maximumOverlapMs'],
    createDrumPreviewBranches: ['sectionId', 'candidateCount', 'varyingRoles'],
    copyMidiArticulations: ['sourceClipId', 'targetClipId'],
    transposeNotes: ['clipId', 'semitones'],
    setAutomationMode: ['trackId', 'mode'],
    scaleAutomation: ['laneId', 'factor'],
    stretchAutomation: ['laneId', 'factor'],
    thinAutomation: ['laneId'],
    quantizeAutomation: ['laneId', 'gridSize'],
    generateDrumPattern: ['style'],
    generateMelody: ['style'],
    generateChordProgression: ['style'],
    extractGroove: ['clipId'],
    createCollabSession: ['name'],
    joinCollabSession: ['inviteString', 'peerName'],
    createVcaGroup: ['name', 'trackIds'],
    addChordEvent: ['beat', 'root', 'quality'],
    createAdjustmentLayer: ['name', 'effectType'],
    addAdjustmentRegion: ['layerId', 'startBeat', 'endBeat', 'blend', 'fadeInBeats', 'fadeOutBeats'],
} as const satisfies {
    [
        ActionType in keyof typeof RUNTIME_ACTION_OVERRIDE_PAYLOAD_KEYS
    ]: readonly (typeof RUNTIME_ACTION_OVERRIDE_PAYLOAD_KEYS)[ActionType][number][];
};

type RuntimePayloadOverrideType = keyof typeof RUNTIME_ACTION_OVERRIDE_PAYLOAD_KEYS;
type RuntimeAllowedPayloadKey<ActionType extends RuntimePayloadOverrideType> =
    (typeof RUNTIME_ACTION_OVERRIDE_PAYLOAD_KEYS)[ActionType][number];
type RuntimeRequiredPayloadKey<ActionType extends RuntimePayloadOverrideType> =
    (typeof RUNTIME_ACTION_OVERRIDE_REQUIRED_PAYLOAD_KEYS)[ActionType][number];
type RuntimePayloadOverride<ActionType extends RuntimePayloadOverrideType> =
    Exclude<RuntimeAllowedPayloadKey<ActionType>, keyof AppActionPayload<ActionType>> extends never
        ? Pick<
              AppActionPayload<ActionType>,
              Extract<RuntimeAllowedPayloadKey<ActionType>, keyof AppActionPayload<ActionType>>
          >
        : never;
type RuntimeAddNotesPayload = {
    clipId: AppActionPayload<'addNotes'>['clipId'];
    notes: Array<Omit<AppActionPayload<'addNotes'>['notes'][number], 'id'>>;
};
type RuntimeImportStemSetPayload = Pick<AppActionPayload<'importStemSet'>, 'selectionId' | 'groupName'> & {
    stems: Array<Pick<AppActionPayload<'importStemSet'>['stems'][number], 'stemId' | 'role'>>;
};
type RuntimeActionWithPayload<ActionType extends RuntimePayloadOverrideType> = ActionType extends 'addNotes'
    ? Omit<AppActionOf<ActionType>, 'payload'> & { payload: RuntimeAddNotesPayload }
    : ActionType extends 'importStemSet'
      ? Omit<AppActionOf<ActionType>, 'payload'> & { payload: RuntimeImportStemSetPayload }
      : Omit<AppActionOf<ActionType>, 'payload'> & {
            payload: RuntimePayloadOverride<ActionType> &
                Required<
                    Pick<
                        AppActionPayload<ActionType>,
                        Extract<RuntimeRequiredPayloadKey<ActionType>, keyof AppActionPayload<ActionType>>
                    >
                >;
        };

type CanonicalRuntimeAction = Exclude<
    Extract<AppAction, { type: RuntimeActionType }>,
    { type: RuntimePayloadOverrideType }
>;
type RuntimePayloadOverrideAction = {
    [ActionType in RuntimePayloadOverrideType]: RuntimeActionWithPayload<ActionType>;
}[RuntimePayloadOverrideType];

export type RuntimeAction = CanonicalRuntimeAction | RuntimePayloadOverrideAction;
