import type { AppAction, AppActionType } from '#/utils/handlerContract';

export const RUNTIME_ACTION_TYPES = [
    'addTrack',
    'removeTrack',
    'removeAllTracks',
    'renameTrack',
    'selectTrack',
    'muteTrack',
    'soloTrack',
    'toggleSoloSafe',
    'armTrack',
    'freezeTrack',
    'unfreezeTrack',
    'flattenTrack',
    'bounceInPlace',
    'duplicateTrack',
    'reorderTrack',
    'setTrackGain',
    'setTrackPan',
    'setTrackColor',
    'setTempo',
    'setTimeSignature',
    'togglePlayback',
    'stopPlayback',
    'toggleRecording',
    'setMasterGain',
    'toggleLoop',
    'toggleMetronome',
    'setMetronomeVolume',
    'setLoopRegion',
    'addClip',
    'moveClip',
    'duplicateClip',
    'duplicateClipToNextBar',
    'removeClip',
    'splitClip',
    'trimClipStart',
    'trimClipEnd',
    'setClipFade',
    'copyClip',
    'cutClip',
    'pasteClip',
    'addDevice',
    'bypassDevice',
    'removeDevice',
    'setDeviceParameter',
    'createBus',
    'createFolder',
    'setSend',
    'setWorkspaceMode',
    'openPreferencesDialog',
    'openMixer',
    'closeMixer',
    'toggleSidebar',
    'toggleInspector',
    'toggleChatPanel',
    'setEditingTool',
    'setMarqueeSelection',
    'addMarker',
    'removeMarker',
    'setMarkerColor',
    'addSection',
    'removeSection',
    'renameSection',
    'addAutomationLane',
    'addAutomationPoint',
    'quantizeNotes',
    'quantizeNoteLengths',
    'transposeNotes',
    'humanizeNotes',
    'invertNotes',
    'retrogradeNotes',
    'scaleVelocities',
    'scaleAllVelocities',
    'setAllVelocities',
    'importMidiFile',
    'normalizeClip',
    'reverseClip',
    'glueClips',
    'nudgeClip',
    'crossfadeClips',
    'setClipGain',
    'setClipColor',
    'lockClip',
    'renameClip',
    'consolidateSelection',
    'bounceSelection',
    'seekPlayhead',
    'setPunchIn',
    'setPunchOut',
    'togglePunch',
    'toggleCountIn',
    'setCountInBars',
    'togglePreRoll',
    'setPreRollBars',
    'addTimeSignatureChange',
    'removeTimeSignatureChange',
    'setTrackOutput',
    'addSend',
    'removeSend',
    'removeAutomationPoint',
    'setAutomationMode',
    'hideTrack',
    'disableTrack',
    'setTrackHeight',
    'setSnapValue',
    'zoomToFit',
    'zoomToSelection',
    'exportProject',
    'saveProject',
    'newProject',
    'importAudioFile',
    'exportMidi',
    'foldTrack',
    'groupTracks',
    'ungroupTracks',
    'scaleAutomation',
    'stretchAutomation',
    'invertAutomation',
    'reverseAutomation',
    'thinAutomation',
    'quantizeAutomation',
    'loadPreset',
    'savePreset',
    'generateDrumPattern',
    'generateMelody',
    'generateChordProgression',
    'setClipLoop',
    'setClipLoopLength',
    'extractGroove',
    'applyGroove',
    'setClipStretchMode',
    'setClipStretchRatio',
    'fitClipToBeats',
    'analyzeMix',
    'autoFixMix',
    'enableMpe',
    'disableMpe',
    'getLatencyReport',
    'createCollabSession',
    'joinCollabSession',
    'leaveCollabSession',
    'scanPlugins',
    'loadExternalPlugin',
    'audioToMidi',
    'muteClip',
    'clearSolos',
    'setTrackNotes',
    'setTrackInput',
    'zoomTracksVertical',
    'deleteTime',
    'insertTime',
    'duplicateTimeRange',
    'stripSilence',
    'detectTempo',
    'detectKey',
    'consolidateAllTracks',
    'arpeggiate',
    'addSidechainRoute',
    'removeSidechainRoute',
    'bounceToNewTrack',
    'createTrackAlternative',
    'switchTrackAlternative',
    'renameTrackAlternative',
    'deleteTrackAlternative',
    'addChordEvent',
    'addCvOutput',
    'addNotes',
    'assignToVca',
    'autoOrganizeProject',
    'captureScratchPad',
    'clearAllMidiMappings',
    'clearChordTrack',
    'clearMidiOutput',
    'clearScratchPad',
    'commitScratchPad',
    'compareToReference',
    'completeMidi',
    'connectPush',
    'createAdjustmentLayer',
    'createCompGroup',
    'createPatternInstance',
    'createProjectVersion',
    'createVcaGroup',
    'createVersionBranch',
    'deleteMacro',
    'deleteTrackTemplate',
    'detachPatternInstance',
    'detectSongStructure',
    'detectTransients',
    'disconnectPush',
    'enableWarping',
    'exportDawProject',
    'generateAllTransitions',
    'generateAudio',
    'generateBassline',
    'generateFill',
    'getMentorTips',
    'labelUndoBranch',
    'loadRaveModel',
    'loadTrackTemplate',
    'nextSetlistItem',
    'playMacro',
    'previousSetlistItem',
    'quantizeTransients',
    'redo',
    'removeChordEvent',
    'removeFromVca',
    'restoreAutomationLanePoints',
    'restoreClip',
    'restoreDsoSnapshot',
    'restoreProjectVersion',
    'restoreTrack',
    'saveTrackTemplate',
    'searchSamples',
    'setControlSurface',
    'setMidiOutput',
    'setRaveBlend',
    'setVcaGain',
    'setWarpAlgorithm',
    'setWarpPitchShift',
    'startMacroRecording',
    'stemSeparate',
    'stopMacroRecording',
    'switchMonitor',
    'toggleChordTrack',
    'toggleControlRoomDim',
    'toggleControlRoomMono',
    'toggleLoopRecord',
    'toggleNodeView',
    'togglePunchRecording',
    'toggleScratchPad',
    'toggleUndoTree',
    'triggerScene',
    'undo',
    'variationMidi',
] as const satisfies readonly AppActionType[];

export type RuntimeActionType = (typeof RUNTIME_ACTION_TYPES)[number];

type AppActionOf<ActionType extends AppActionType> = Extract<AppAction, { type: ActionType }>;
type AppActionPayload<ActionType extends AppActionType> =
    AppActionOf<ActionType> extends { payload: infer Payload } ? Payload : never;

type RuntimePayloadOverrides = {
    createTrackAlternative: Omit<AppActionPayload<'createTrackAlternative'>, 'alternativeId'>;
    deleteTrackAlternative: Omit<AppActionPayload<'deleteTrackAlternative'>, 'fallbackAlternativeId'>;
    duplicateClip: Omit<AppActionPayload<'duplicateClip'>, 'targetClipId'>;
    duplicateClipToNextBar: Omit<AppActionPayload<'duplicateClipToNextBar'>, 'targetClipId'>;
    addMarker: Omit<AppActionPayload<'addMarker'>, 'markerId' | 'color'>;
    addSection: Omit<AppActionPayload<'addSection'>, 'sectionId' | 'color'>;
    addAutomationLane: Omit<AppActionPayload<'addAutomationLane'>, 'laneId'>;
    generateDrumPattern: Omit<AppActionPayload<'generateDrumPattern'>, 'startBeat'>;
    generateMelody: Omit<AppActionPayload<'generateMelody'>, 'octave' | 'density' | 'startBeat'>;
    generateChordProgression: Omit<AppActionPayload<'generateChordProgression'>, 'startBeat'>;
    extractGroove: Pick<AppActionPayload<'extractGroove'>, 'clipId'>;
    createCollabSession: AppActionPayload<'createCollabSession'> & { name: string };
    joinCollabSession: AppActionPayload<'joinCollabSession'> & { peerName: string };
    createVcaGroup: Omit<AppActionPayload<'createVcaGroup'>, 'vcaGroupId'>;
    addChordEvent: Omit<AppActionPayload<'addChordEvent'>, 'eventId'>;
    createAdjustmentLayer: Omit<AppActionPayload<'createAdjustmentLayer'>, 'layerId'>;
};

type RuntimePayloadOverrideType = keyof RuntimePayloadOverrides;
type RuntimeActionWithPayload<ActionType extends RuntimePayloadOverrideType> = Omit<
    AppActionOf<ActionType>,
    'payload'
> & { payload: RuntimePayloadOverrides[ActionType] };

type CanonicalRuntimeAction = Exclude<
    Extract<AppAction, { type: RuntimeActionType }>,
    { type: RuntimePayloadOverrideType }
>;
type RuntimePayloadOverrideAction = {
    [ActionType in RuntimePayloadOverrideType]: RuntimeActionWithPayload<ActionType>;
}[RuntimePayloadOverrideType];

export type RuntimeAction = CanonicalRuntimeAction | RuntimePayloadOverrideAction;
