import { describe, it, expect, vi, beforeEach } from 'vitest';

// --- Worklet global scope shims -------------------------------------------
// The processor module runs in AudioWorklet global scope, which provides
// AudioWorkletProcessor, registerProcessor and `sampleRate`. Provide them so
// the real module can be imported and self-register.
const registry = new Map<string, new (...args: unknown[]) => AudioWorkletProcessorLike>();
const postedMessages: unknown[] = [];

class AudioWorkletProcessorShim {
    port = {
        onmessage: null as ((event: { data: unknown }) => void) | null,
        postMessage: vi.fn((msg: unknown) => {
            postedMessages.push(msg);
        }),
    };
}

type AudioWorkletProcessorLike = {
    port: {
        onmessage: ((event: { data: unknown }) => void) | null;
        postMessage: (msg: unknown) => void;
    };
    process(inputs: Float32Array[][], outputs: Float32Array[][]): boolean;
    // RT-safe cached WASM-memory views, asserted for reuse across render quanta.
    _wasmInL: Float32Array | null;
    _wasmInR: Float32Array | null;
    _wasmOutL: Float32Array | null;
    _wasmOutR: Float32Array | null;
    _faulted: boolean;
};

vi.stubGlobal('AudioWorkletProcessor', AudioWorkletProcessorShim);
vi.stubGlobal('registerProcessor', (name: string, proc: new (...args: unknown[]) => AudioWorkletProcessorLike) => {
    registry.set(name, proc);
});
vi.stubGlobal('sampleRate', 48000);

// --- WASM module mock ------------------------------------------------------
// Captures every shift handed to the WASM instance so the test can assert the
// value the worklet computed for a given transport + blob state.
// `legacyBinary` simulates the committed pre-fix wasm glue, which lacks
// set_shift_semitones / get_right_ptr (regenerated by `pnpm wasm:dsp`).
const shiftCalls: number[] = [];
let legacyBinary = false;
const WASM_HEAP = new ArrayBuffer(8192);

class KneadInstanceMock {
    set_shift_semitones(value: number): void {
        shiftCalls.push(value);
    }
    get_input_left_ptr(): number {
        return 0;
    }
    get_input_right_ptr(): number {
        return 256;
    }
    process(): number {
        return 512;
    }
    get_right_ptr(): number {
        return 768;
    }
}

class KneadInstanceLegacyMock {
    get_input_left_ptr(): number {
        return 0;
    }
    get_input_right_ptr(): number {
        return 256;
    }
    process(): number {
        return 512;
    }
}

vi.mock('../../wasm/daw_dsp.js', () => ({
    initSync: vi.fn(() => ({ memory: { buffer: WASM_HEAP } })),
    // Plain function (not vi.fn) so `new KneadInstance(...)` works; the
    // returned object overrides the fresh `this`.
    KneadInstance: function () {
        return legacyBinary ? new KneadInstanceLegacyMock() : new KneadInstanceMock();
    } as unknown as typeof KneadInstanceMock,
}));

const MINIMAL_WASM_MODULE = new WebAssembly.Module(new Uint8Array([0x00, 0x61, 0x73, 0x6d, 0x01, 0x00, 0x00, 0x00]));

// Transport SAB layout mirrored from kneadProcessor.ts.
const TRANSPORT_BEAT_F64 = 0;
const TRANSPORT_TEMPO_F64 = 1;
const TRANSPORT_IS_PLAYING_F64 = 5;

function makePlayingTransport(beat: number, tempo: number): SharedArrayBuffer {
    // 16 f64 slots is comfortably past Int32 seq index 14 (bytes 56-60).
    const sab = new SharedArrayBuffer(16 * 8);
    const f64 = new Float64Array(sab);
    f64[TRANSPORT_BEAT_F64] = beat;
    f64[TRANSPORT_TEMPO_F64] = tempo;
    f64[TRANSPORT_IS_PLAYING_F64] = 1; // playing
    // Seq counter (Int32 index 14) is left at 0 (even, unchanged) so the
    // seqlock read succeeds on the first attempt.
    return sab;
}

async function loadProcessor(): Promise<AudioWorkletProcessorLike> {
    await import('../kneadProcessor');
    const Ctor = registry.get('knead-processor');
    if (!Ctor) {
        throw new Error('knead-processor was not registered');
    }
    return new Ctor({ processorOptions: { wasmModule: MINIMAL_WASM_MODULE } });
}

function sendMessage(proc: AudioWorkletProcessorLike, data: unknown): void {
    proc.port.onmessage?.({ data });
}

describe('KneadProcessor pitch-shift computation', () => {
    beforeEach(() => {
        shiftCalls.length = 0;
        postedMessages.length = 0;
        legacyBinary = false;
    });

    it('ignores a duplicate init after becoming ready', async () => {
        const proc = await loadProcessor();
        sendMessage(proc, { type: 'init', wasmModule: MINIMAL_WASM_MODULE });
        postedMessages.length = 0;

        sendMessage(proc, { type: 'init', wasmModule: MINIMAL_WASM_MODULE });

        expect(postedMessages).toEqual([]);
        expect(proc._faulted).toBe(false);
    });

    it('feeds a finite shift to the WASM instance when both pitch centers are present', async () => {
        const proc = await loadProcessor();
        const transportSAB = makePlayingTransport(2, 120);
        sendMessage(proc, { type: 'init', wasmModule: MINIMAL_WASM_MODULE, transportSAB });

        sendMessage(proc, {
            type: 'update-state',
            clips: {
                c1: {
                    startBeat: 0,
                    endBeat: 4,
                    blobs: [
                        {
                            startTime: 0,
                            endTime: 10,
                            pitchCenterCents: 6200,
                            originalPitchCenterCents: 6000,
                        },
                    ],
                },
            },
        });

        const input = [new Float32Array(128)];
        const output = [new Float32Array(128), new Float32Array(128)];
        proc.process([input], [output]);

        // (6200 - 6000) / 100 == 2 semitones.
        expect(shiftCalls.at(-1)).toBe(2);
    });

    it('does not produce a NaN shift when originalPitchCenterCents is missing after a project reload', async () => {
        const proc = await loadProcessor();

        const transportSAB = makePlayingTransport(2, 120);
        sendMessage(proc, { type: 'init', wasmModule: MINIMAL_WASM_MODULE, transportSAB });

        // A blob rehydrated from the persisted (narrow) schema has no
        // originalPitchCenterCents — exactly the post-CRDT-round-trip shape.
        sendMessage(proc, {
            type: 'update-state',
            clips: {
                c1: {
                    startBeat: 0,
                    endBeat: 4,
                    blobs: [
                        {
                            startTime: 0,
                            endTime: 10,
                            pitchCenterCents: 6200,
                            // originalPitchCenterCents intentionally absent
                        },
                    ],
                },
            },
        });

        const input = [new Float32Array(128)];
        const output = [new Float32Array(128), new Float32Array(128)];
        proc.process([input], [output]);

        const lastShift = shiftCalls.at(-1);
        expect(lastShift).not.toBeNaN();
        // Missing original is treated as the current center → zero shift.
        expect(lastShift).toBe(0);
    });

    it('reuses the WASM-memory typed-array views across render quanta (no per-block allocation)', async () => {
        const proc = await loadProcessor();
        const transportSAB = makePlayingTransport(2, 120);
        sendMessage(proc, { type: 'init', wasmModule: MINIMAL_WASM_MODULE, transportSAB });
        sendMessage(proc, {
            type: 'update-state',
            clips: {
                c1: {
                    startBeat: 0,
                    endBeat: 4,
                    blobs: [{ startTime: 0, endTime: 10, pitchCenterCents: 6200, originalPitchCenterCents: 6000 }],
                },
            },
        });

        const input = [new Float32Array(128), new Float32Array(128)];
        const output = [new Float32Array(128), new Float32Array(128)];

        // First render quantum builds the views.
        proc.process([input], [output]);
        const firstInL = proc._wasmInL;
        const firstInR = proc._wasmInR;
        const firstOutL = proc._wasmOutL;
        expect(firstInL).toBeInstanceOf(Float32Array);
        expect(firstInR).toBeInstanceOf(Float32Array);
        expect(firstOutL).toBeInstanceOf(Float32Array);

        // Subsequent quanta with the same buffer/ptrs/frames must reuse the very
        // same view objects — a fresh Float32Array here would be a per-block alloc.
        proc.process([input], [output]);
        proc.process([input], [output]);
        expect(proc._wasmInL).toBe(firstInL);
        expect(proc._wasmInR).toBe(firstInR);
        expect(proc._wasmOutL).toBe(firstOutL);
    });

    it('routes the right output channel from get_right_ptr when the binary exposes it', async () => {
        const proc = await loadProcessor();
        sendMessage(proc, { type: 'init', wasmModule: MINIMAL_WASM_MODULE });

        const input = [new Float32Array(128), new Float32Array(128)];
        const leftOut = new Float32Array(128);
        const rightOut = new Float32Array(128);
        proc.process([input], [[leftOut, rightOut]]);

        // Mock layout: process() -> 512 (left), get_right_ptr() -> 768.
        expect(proc._wasmOutL).toBeInstanceOf(Float32Array);
        expect(proc._wasmOutR).toBeInstanceOf(Float32Array);
        expect(proc._wasmOutL?.byteOffset).toBe(512);
        expect(proc._wasmOutR?.byteOffset).toBe(768);
    });

    it('keeps processing without faulting on a legacy binary that lacks the shift/right exports', async () => {
        legacyBinary = true;
        const proc = await loadProcessor();
        const transportSAB = makePlayingTransport(2, 120);
        sendMessage(proc, { type: 'init', wasmModule: MINIMAL_WASM_MODULE, transportSAB });
        sendMessage(proc, {
            type: 'update-state',
            clips: {
                c1: {
                    startBeat: 0,
                    endBeat: 4,
                    blobs: [{ startTime: 0, endTime: 10, pitchCenterCents: 6200, originalPitchCenterCents: 6000 }],
                },
            },
        });

        const input = [new Float32Array(128), new Float32Array(128)];
        const leftOut = new Float32Array(128);
        const rightOut = new Float32Array(128);

        // The pre-fix processor threw TypeError here and faulted into
        // permanent passthrough; now it must keep processing every quantum.
        proc.process([input], [[leftOut, rightOut]]);
        proc.process([input], [[leftOut, rightOut]]);

        expect(proc._faulted).toBe(false);
        expect(shiftCalls).toHaveLength(0);
        // Right output falls back to the left result buffer on legacy binaries.
        expect(proc._wasmOutL).toBeInstanceOf(Float32Array);
        expect(proc._wasmOutR).toBeNull();
        const errorMessages = postedMessages.filter(
            (msg) => typeof msg === 'object' && msg !== null && 'type' in msg && msg.type === 'error'
        );
        expect(errorMessages).toHaveLength(0);
    });
});

describe('KneadProcessor message handling & process guards', () => {
    beforeEach(() => {
        shiftCalls.length = 0;
        postedMessages.length = 0;
        legacyBinary = false;
    });

    it('forwards shift_semitones param to the instance and ignores other param names before init', async () => {
        const proc = await loadProcessor();
        // Before init: param is dropped (instance is null / not ready).
        sendMessage(proc, { type: 'param', name: 'shift_semitones', value: 7 });
        expect(shiftCalls).toEqual([]);

        sendMessage(proc, { type: 'init', wasmModule: MINIMAL_WASM_MODULE });
        // After init: shift_semitones is forwarded.
        sendMessage(proc, { type: 'param', name: 'shift_semitones', value: 3 });
        expect(shiftCalls).toEqual([3]);
        // An unrelated param name does not call set_shift_semitones.
        const before = shiftCalls.length;
        sendMessage(proc, { type: 'param', name: 'somethingElse', value: 1 });
        expect(shiftCalls.length).toBe(before);
    });

    it('toggles bypass without affecting the instance', async () => {
        const proc = await loadProcessor();
        sendMessage(proc, { type: 'init', wasmModule: MINIMAL_WASM_MODULE });
        sendMessage(proc, { type: 'bypass', bypassed: true });
        sendMessage(proc, { type: 'bypass', bypassed: false });
        // bypass stores a flag; no error posted.
        const errors = postedMessages.filter(
            (m) => typeof m === 'object' && m !== null && 'type' in m && (m as { type: string }).type === 'error'
        );
        expect(errors).toHaveLength(0);
    });

    it('passthrough-copies when not ready (input && output present) and returns early with no input', async () => {
        const proc = await loadProcessor();
        const output = [new Float32Array(4).fill(0), new Float32Array(4).fill(0)];
        // Not ready, but input && output present → passthrough copies in→out.
        proc.process([[new Float32Array([0.1, 0.2, 0.3, 0.4])], []], [output]);
        expect(Array.from(output[0]!)).toEqual([0.1, 0.2, 0.3, 0.4].map((v) => new Float32Array([v])[0]));

        // Not ready, no input → early return (no passthrough).
        const output2 = [new Float32Array(4).fill(9), new Float32Array(4).fill(9)];
        proc.process([], [output2]);
        expect(Array.from(output2[0]!)).toEqual([9, 9, 9, 9]);
    });

    it('returns early when the left input channel is absent (ready instance)', async () => {
        const proc = await loadProcessor();
        sendMessage(proc, { type: 'init', wasmModule: MINIMAL_WASM_MODULE });
        const output = [new Float32Array(4).fill(0), new Float32Array(4).fill(0)];
        // input[0] absent → !in0 guard → early return, no shift applied.
        proc.process([[]], [output]);
        expect(shiftCalls.every((s) => s === 0)).toBe(true);
    });

    it('computes zero shift when transport is not playing', async () => {
        const proc = await loadProcessor();
        // Transport SAB left at defaults → isPlaying (slot 5) = 0 → not playing.
        const sab = new SharedArrayBuffer(16 * 8);
        const f64 = new Float64Array(sab);
        f64[TRANSPORT_BEAT_F64] = 2;
        f64[TRANSPORT_TEMPO_F64] = 120;
        f64[TRANSPORT_IS_PLAYING_F64] = 0; // stopped
        sendMessage(proc, { type: 'init', wasmModule: MINIMAL_WASM_MODULE, transportSAB: sab });
        sendMessage(proc, {
            type: 'update-state',
            clips: {
                c1: {
                    startBeat: 0,
                    endBeat: 4,
                    blobs: [{ startTime: 0, endTime: 10, pitchCenterCents: 6200, originalPitchCenterCents: 6000 }],
                },
            },
        });
        proc.process(
            [[new Float32Array(128)], [new Float32Array(128)]],
            [[new Float32Array(128), new Float32Array(128)]]
        );
        // Not playing → no clip lookup → shift stays 0.
        expect(shiftCalls.at(-1)).toBe(0);
    });

    it('computes zero shift when the playhead is outside every clip range', async () => {
        const proc = await loadProcessor();
        const transportSAB = makePlayingTransport(99, 120); // beat 9, outside clip [0,4]
        sendMessage(proc, { type: 'init', wasmModule: MINIMAL_WASM_MODULE, transportSAB });
        sendMessage(proc, {
            type: 'update-state',
            clips: {
                c1: {
                    startBeat: 0,
                    endBeat: 4,
                    blobs: [{ startTime: 0, endTime: 10, pitchCenterCents: 6200, originalPitchCenterCents: 6000 }],
                },
            },
        });
        proc.process(
            [[new Float32Array(128)], [new Float32Array(128)]],
            [[new Float32Array(128), new Float32Array(128)]]
        );
        expect(shiftCalls.at(-1)).toBe(0);
    });

    it('computes zero shift when the active clip has no blob at the playhead', async () => {
        const proc = await loadProcessor();
        const transportSAB = makePlayingTransport(2, 120); // inside clip range
        sendMessage(proc, { type: 'init', wasmModule: MINIMAL_WASM_MODULE, transportSAB });
        // Blob window [1000, 2000]s — playhead (beat 2 @120bpm = 1s) is before it.
        sendMessage(proc, {
            type: 'update-state',
            clips: {
                c1: {
                    startBeat: 0,
                    endBeat: 4,
                    blobs: [{ startTime: 1000, endTime: 2000, pitchCenterCents: 6200, originalPitchCenterCents: 6000 }],
                },
            },
        });
        proc.process(
            [[new Float32Array(128)], [new Float32Array(128)]],
            [[new Float32Array(128), new Float32Array(128)]]
        );
        expect(shiftCalls.at(-1)).toBe(0);
    });

    it('faults and passthrough-copies when the WASM instance throws mid-process', async () => {
        const proc = await loadProcessor();
        sendMessage(proc, { type: 'init', wasmModule: MINIMAL_WASM_MODULE });
        // Sabotage the instance by replacing process() to throw.
        const inst = (proc as unknown as { _instance: { process(): number } })._instance;
        inst.process = () => {
            throw new Error('wasm trap');
        };
        const output = [new Float32Array([0, 0, 0, 0]), new Float32Array([0, 0, 0, 0])];
        proc.process([[new Float32Array([0.5, 0.6, 0.7, 0.8])], [new Float32Array([0.5, 0.6, 0.7, 0.8])]], [output]);
        const errors = postedMessages.filter(
            (m) => typeof m === 'object' && m !== null && 'type' in m && (m as { type: string }).type === 'error'
        );
        expect(errors).toHaveLength(1);
        // Passthrough copied the input into the (4-frame) output (Float32).
        expect(Array.from(output[0]!)).toEqual([0.5, 0.6, 0.7, 0.8].map((v) => new Float32Array([v])[0]));
        expect(proc._faulted).toBe(true);
    });
});
