import { describe, it, expect, vi, beforeEach } from 'vitest';

// --- Worklet global scope shims -------------------------------------------
// The processor module runs in AudioWorklet global scope, which provides
// AudioWorkletProcessor, registerProcessor and `sampleRate`. Provide them so
// the real module can be imported and self-register.
const registry = new Map<string, new (...args: unknown[]) => AudioWorkletProcessorLike>();
const postedMessages: unknown[] = [];

class AudioWorkletProcessorShim {
    port = {
        onmessage: null as ((event: { data: unknown }) => void) | null,
        postMessage: vi.fn((msg: unknown) => {
            postedMessages.push(msg);
        }),
    };
}

type AudioWorkletProcessorLike = {
    port: {
        onmessage: ((event: { data: unknown }) => void) | null;
        postMessage: (msg: unknown) => void;
    };
    process(inputs: Float32Array[][], outputs: Float32Array[][]): boolean;
    _faulted: boolean;
};

// Mock WASM heap layout, in bytes (inputs at 0 / 256). 128 frames = 512 bytes per
// window, so the windows deliberately overlap — the assertions below read
// expectations back out of the heap after the call rather than assuming what
// landed where.
const OUT_LEFT_PTR = 512;
const OUT_RIGHT_PTR = 768;
const FRAMES = 128;

vi.stubGlobal('AudioWorkletProcessor', AudioWorkletProcessorShim);
vi.stubGlobal('registerProcessor', (name: string, proc: new (...args: unknown[]) => AudioWorkletProcessorLike) => {
    registry.set(name, proc);
});
vi.stubGlobal('sampleRate', 48000);

// --- WASM module mock ------------------------------------------------------
// Captures every shift handed to the WASM instance so the test can assert the
// value the worklet computed for a given transport + blob state.
// `legacyBinary` simulates the committed pre-fix wasm glue, which lacks
// set_shift_semitones / get_right_ptr (regenerated by `pnpm wasm:dsp`).
const shiftCalls: number[] = [];
let legacyBinary = false;
const WASM_HEAP = new ArrayBuffer(8192);

/** Fill the mock heap with a per-index ramp so every window has distinct content. */
function seedHeapRamp(): void {
    const floats = new Float32Array(WASM_HEAP);
    for (let index = 0; index < floats.length; index++) {
        floats[index] = index * 1.5 + 1;
    }
}

/** Read a wasm output window straight out of the heap, as the processor sees it. */
function heapWindow(byteOffset: number): number[] {
    return Array.from(new Float32Array(WASM_HEAP, byteOffset, FRAMES));
}

// The engine's real group delay: yin_cfg.frame_size (2048) minus one, measured
// bit-exactly by knead/engine.rs::reported_latency_matches_measured_group_delay.
const KNEAD_LATENCY_SAMPLES = 2047;

class KneadInstanceMock {
    set_shift_semitones(value: number): void {
        shiftCalls.push(value);
    }
    get_input_left_ptr(): number {
        return 0;
    }
    get_input_right_ptr(): number {
        return 256;
    }
    process(): number {
        return 512;
    }
    get_right_ptr(): number {
        return 768;
    }
    get_latency_samples(): number {
        return KNEAD_LATENCY_SAMPLES;
    }
}

// Models a binary predating only the two *feature-detected* exports
// (set_shift_semitones / get_right_ptr). get_latency_samples is declared
// non-optionally by the committed glue, like gluten's, so it is present here.
class KneadInstanceLegacyMock {
    get_input_left_ptr(): number {
        return 0;
    }
    get_input_right_ptr(): number {
        return 256;
    }
    process(): number {
        return 512;
    }
    get_latency_samples(): number {
        return KNEAD_LATENCY_SAMPLES;
    }
}

vi.mock('../../wasm/daw_dsp.js', () => ({
    initSync: vi.fn(() => ({ memory: { buffer: WASM_HEAP } })),
    // Plain function (not vi.fn) so `new KneadInstance(...)` works; the
    // returned object overrides the fresh `this`.
    KneadInstance: function () {
        return legacyBinary ? new KneadInstanceLegacyMock() : new KneadInstanceMock();
    } as unknown as typeof KneadInstanceMock,
}));

const MINIMAL_WASM_MODULE = new WebAssembly.Module(new Uint8Array([0x00, 0x61, 0x73, 0x6d, 0x01, 0x00, 0x00, 0x00]));

// Transport SAB layout mirrored from kneadProcessor.ts.
const TRANSPORT_BEAT_F64 = 0;
const TRANSPORT_TEMPO_F64 = 1;
const TRANSPORT_IS_PLAYING_F64 = 5;

function makePlayingTransport(beat: number, tempo: number): SharedArrayBuffer {
    // 16 f64 slots is comfortably past Int32 seq index 14 (bytes 56-60).
    const sab = new SharedArrayBuffer(16 * 8);
    const f64 = new Float64Array(sab);
    f64[TRANSPORT_BEAT_F64] = beat;
    f64[TRANSPORT_TEMPO_F64] = tempo;
    f64[TRANSPORT_IS_PLAYING_F64] = 1; // playing
    // Seq counter (Int32 index 14) is left at 0 (even, unchanged) so the
    // seqlock read succeeds on the first attempt.
    return sab;
}

async function loadProcessor(): Promise<AudioWorkletProcessorLike> {
    await import('../kneadProcessor');
    const Ctor = registry.get('knead-processor');
    if (!Ctor) {
        throw new Error('knead-processor was not registered');
    }
    return new Ctor({ processorOptions: { wasmModule: MINIMAL_WASM_MODULE } });
}

function sendMessage(proc: AudioWorkletProcessorLike, data: unknown): void {
    proc.port.onmessage?.({ data });
}

describe('KneadProcessor pitch-shift computation', () => {
    beforeEach(() => {
        shiftCalls.length = 0;
        postedMessages.length = 0;
        legacyBinary = false;
    });

    it('ignores a duplicate init after becoming ready', async () => {
        const proc = await loadProcessor();
        sendMessage(proc, { type: 'init', wasmModule: MINIMAL_WASM_MODULE });
        postedMessages.length = 0;

        sendMessage(proc, { type: 'init', wasmModule: MINIMAL_WASM_MODULE });

        expect(postedMessages).toEqual([]);
        expect(proc._faulted).toBe(false);
    });

    // The ready handshake is the only channel by which Knead's delay reaches PDC:
    // wasmDeviceRegistry reads `latency` off it and calls reportLatency. Posting a
    // bare `{ type: 'ready' }` (the pre-fix message) leaves the registry defaulting
    // to zero, which is how the delay stayed invisible to compensation.
    it('carries the instance group delay on the ready handshake so PDC can compensate it', async () => {
        const proc = await loadProcessor();
        sendMessage(proc, { type: 'init', wasmModule: MINIMAL_WASM_MODULE });

        expect(postedMessages).toEqual([{ type: 'ready', latency: KNEAD_LATENCY_SAMPLES }]);
    });

    it('feeds a finite shift to the WASM instance when both pitch centers are present', async () => {
        const proc = await loadProcessor();
        const transportSAB = makePlayingTransport(2, 120);
        sendMessage(proc, { type: 'init', wasmModule: MINIMAL_WASM_MODULE, transportSAB });

        sendMessage(proc, {
            type: 'update-state',
            clips: {
                c1: {
                    startBeat: 0,
                    endBeat: 4,
                    blobs: [
                        {
                            startTime: 0,
                            endTime: 10,
                            pitchCenterCents: 6200,
                            originalPitchCenterCents: 6000,
                        },
                    ],
                },
            },
        });

        const input = [new Float32Array(128)];
        const output = [new Float32Array(128), new Float32Array(128)];
        proc.process([input], [output]);

        // (6200 - 6000) / 100 == 2 semitones.
        expect(shiftCalls.at(-1)).toBe(2);
    });

    it('does not produce a NaN shift when originalPitchCenterCents is missing after a project reload', async () => {
        const proc = await loadProcessor();

        const transportSAB = makePlayingTransport(2, 120);
        sendMessage(proc, { type: 'init', wasmModule: MINIMAL_WASM_MODULE, transportSAB });

        // A blob rehydrated from the persisted (narrow) schema has no
        // originalPitchCenterCents — exactly the post-CRDT-round-trip shape.
        sendMessage(proc, {
            type: 'update-state',
            clips: {
                c1: {
                    startBeat: 0,
                    endBeat: 4,
                    blobs: [
                        {
                            startTime: 0,
                            endTime: 10,
                            pitchCenterCents: 6200,
                            // originalPitchCenterCents intentionally absent
                        },
                    ],
                },
            },
        });

        const input = [new Float32Array(128)];
        const output = [new Float32Array(128), new Float32Array(128)];
        proc.process([input], [output]);

        const lastShift = shiftCalls.at(-1);
        expect(lastShift).not.toBeNaN();
        // Missing original is treated as the current center → zero shift.
        expect(lastShift).toBe(0);
    });

    it('reuses the WASM-memory typed-array views across render quanta (no per-block allocation)', async () => {
        const proc = await loadProcessor();
        const transportSAB = makePlayingTransport(2, 120);
        sendMessage(proc, { type: 'init', wasmModule: MINIMAL_WASM_MODULE, transportSAB });
        sendMessage(proc, {
            type: 'update-state',
            clips: {
                c1: {
                    startBeat: 0,
                    endBeat: 4,
                    blobs: [{ startTime: 0, endTime: 10, pitchCenterCents: 6200, originalPitchCenterCents: 6000 }],
                },
            },
        });

        const input = [new Float32Array(FRAMES), new Float32Array(FRAMES)];
        const output = [new Float32Array(FRAMES), new Float32Array(FRAMES)];

        // First render quantum builds the four views (in L/R, out L/R).
        proc.process([input], [output]);

        // Steady state: same buffer, same pointers, same frame count. Every view
        // must be served from cache — a fresh `new Float32Array(memory, ...)` here
        // is a heap allocation on the audio thread, ~344 times a second per device.
        // Counting constructions asserts the property directly rather than through
        // the identity of a private field.
        const RealFloat32Array = globalThis.Float32Array;
        let constructions = 0;
        const CountingFloat32Array = new Proxy(RealFloat32Array, {
            construct(target, args: ConstructorParameters<typeof Float32Array>) {
                constructions++;
                return new target(...args);
            },
        });
        vi.stubGlobal('Float32Array', CountingFloat32Array);
        try {
            proc.process([input], [output]);
            proc.process([input], [output]);
        } finally {
            vi.stubGlobal('Float32Array', RealFloat32Array);
        }

        expect(constructions).toBe(0);
    });

    it('routes the right output channel from get_right_ptr when the binary exposes it', async () => {
        const proc = await loadProcessor();
        sendMessage(proc, { type: 'init', wasmModule: MINIMAL_WASM_MODULE });

        seedHeapRamp();
        const input = [new Float32Array(FRAMES), new Float32Array(FRAMES)];
        const leftOut = new Float32Array(FRAMES);
        const rightOut = new Float32Array(FRAMES);
        proc.process([input], [[leftOut, rightOut]]);

        // Mock layout: process() -> 512 (left), get_right_ptr() -> 768. Each output
        // channel must carry its own wasm window, read back out of the heap as it
        // stands after the call.
        const expectedLeft = heapWindow(OUT_LEFT_PTR);
        const expectedRight = heapWindow(OUT_RIGHT_PTR);
        // Guard the guard: if the two windows held the same samples, a right
        // channel sourced from the left pointer would pass this test.
        expect(expectedLeft).not.toEqual(expectedRight);
        expect(Array.from(leftOut)).toEqual(expectedLeft);
        expect(Array.from(rightOut)).toEqual(expectedRight);
    });

    it('keeps processing without faulting on a legacy binary that lacks the shift/right exports', async () => {
        legacyBinary = true;
        const proc = await loadProcessor();
        const transportSAB = makePlayingTransport(2, 120);
        sendMessage(proc, { type: 'init', wasmModule: MINIMAL_WASM_MODULE, transportSAB });
        sendMessage(proc, {
            type: 'update-state',
            clips: {
                c1: {
                    startBeat: 0,
                    endBeat: 4,
                    blobs: [{ startTime: 0, endTime: 10, pitchCenterCents: 6200, originalPitchCenterCents: 6000 }],
                },
            },
        });

        seedHeapRamp();
        const input = [new Float32Array(FRAMES), new Float32Array(FRAMES)];
        const leftOut = new Float32Array(FRAMES);
        const rightOut = new Float32Array(FRAMES);

        // The pre-fix processor threw TypeError here and faulted into
        // permanent passthrough; now it must keep processing every quantum.
        proc.process([input], [[leftOut, rightOut]]);
        proc.process([input], [[leftOut, rightOut]]);

        expect(proc._faulted).toBe(false);
        expect(shiftCalls).toHaveLength(0);
        // No get_right_ptr on a legacy binary: the right output mirrors the left
        // result window rather than reading an undefined pointer.
        const expectedLeft = heapWindow(OUT_LEFT_PTR);
        expect(Array.from(leftOut)).toEqual(expectedLeft);
        expect(Array.from(rightOut)).toEqual(expectedLeft);
        const errorMessages = postedMessages.filter(
            (msg) => typeof msg === 'object' && msg !== null && 'type' in msg && msg.type === 'error'
        );
        expect(errorMessages).toHaveLength(0);
    });
});

describe('KneadProcessor message handling & process guards', () => {
    beforeEach(() => {
        shiftCalls.length = 0;
        postedMessages.length = 0;
        legacyBinary = false;
    });

    it('forwards shift_semitones param to the instance and ignores other param names before init', async () => {
        const proc = await loadProcessor();
        // Before init: param is dropped (instance is null / not ready).
        sendMessage(proc, { type: 'param', name: 'shift_semitones', value: 7 });
        expect(shiftCalls).toEqual([]);

        sendMessage(proc, { type: 'init', wasmModule: MINIMAL_WASM_MODULE });
        // After init: shift_semitones is forwarded.
        sendMessage(proc, { type: 'param', name: 'shift_semitones', value: 3 });
        expect(shiftCalls).toEqual([3]);
        // An unrelated param name does not call set_shift_semitones.
        const before = shiftCalls.length;
        sendMessage(proc, { type: 'param', name: 'somethingElse', value: 1 });
        expect(shiftCalls.length).toBe(before);
    });

    it('toggles bypass without affecting the instance', async () => {
        const proc = await loadProcessor();
        sendMessage(proc, { type: 'init', wasmModule: MINIMAL_WASM_MODULE });
        sendMessage(proc, { type: 'bypass', bypassed: true });
        sendMessage(proc, { type: 'bypass', bypassed: false });
        // bypass stores a flag; no error posted.
        const errors = postedMessages.filter(
            (m) => typeof m === 'object' && m !== null && 'type' in m && (m as { type: string }).type === 'error'
        );
        expect(errors).toHaveLength(0);
    });

    it('passthrough-copies when not ready (input && output present) and returns early with no input', async () => {
        const proc = await loadProcessor();
        const output = [new Float32Array(4).fill(0), new Float32Array(4).fill(0)];
        // Not ready, but input && output present → passthrough copies in→out.
        proc.process([[new Float32Array([0.1, 0.2, 0.3, 0.4])], []], [output]);
        expect(Array.from(output[0]!)).toEqual([0.1, 0.2, 0.3, 0.4].map((v) => new Float32Array([v])[0]));

        // Not ready, no input → early return (no passthrough).
        const output2 = [new Float32Array(4).fill(9), new Float32Array(4).fill(9)];
        proc.process([], [output2]);
        expect(Array.from(output2[0]!)).toEqual([9, 9, 9, 9]);
    });

    it('returns early when the left input channel is absent (ready instance)', async () => {
        const proc = await loadProcessor();
        sendMessage(proc, { type: 'init', wasmModule: MINIMAL_WASM_MODULE });
        const output = [new Float32Array(4).fill(0), new Float32Array(4).fill(0)];
        // input[0] absent → !in0 guard → early return, no shift applied.
        proc.process([[]], [output]);
        expect(shiftCalls.every((s) => s === 0)).toBe(true);
    });

    it('computes zero shift when transport is not playing', async () => {
        const proc = await loadProcessor();
        // Transport SAB left at defaults → isPlaying (slot 5) = 0 → not playing.
        const sab = new SharedArrayBuffer(16 * 8);
        const f64 = new Float64Array(sab);
        f64[TRANSPORT_BEAT_F64] = 2;
        f64[TRANSPORT_TEMPO_F64] = 120;
        f64[TRANSPORT_IS_PLAYING_F64] = 0; // stopped
        sendMessage(proc, { type: 'init', wasmModule: MINIMAL_WASM_MODULE, transportSAB: sab });
        sendMessage(proc, {
            type: 'update-state',
            clips: {
                c1: {
                    startBeat: 0,
                    endBeat: 4,
                    blobs: [{ startTime: 0, endTime: 10, pitchCenterCents: 6200, originalPitchCenterCents: 6000 }],
                },
            },
        });
        proc.process(
            [[new Float32Array(128)], [new Float32Array(128)]],
            [[new Float32Array(128), new Float32Array(128)]]
        );
        // Not playing → no clip lookup → shift stays 0.
        expect(shiftCalls.at(-1)).toBe(0);
    });

    it('computes zero shift when the playhead is outside every clip range', async () => {
        const proc = await loadProcessor();
        const transportSAB = makePlayingTransport(99, 120); // beat 9, outside clip [0,4]
        sendMessage(proc, { type: 'init', wasmModule: MINIMAL_WASM_MODULE, transportSAB });
        sendMessage(proc, {
            type: 'update-state',
            clips: {
                c1: {
                    startBeat: 0,
                    endBeat: 4,
                    blobs: [{ startTime: 0, endTime: 10, pitchCenterCents: 6200, originalPitchCenterCents: 6000 }],
                },
            },
        });
        proc.process(
            [[new Float32Array(128)], [new Float32Array(128)]],
            [[new Float32Array(128), new Float32Array(128)]]
        );
        expect(shiftCalls.at(-1)).toBe(0);
    });

    it('computes zero shift when the active clip has no blob at the playhead', async () => {
        const proc = await loadProcessor();
        const transportSAB = makePlayingTransport(2, 120); // inside clip range
        sendMessage(proc, { type: 'init', wasmModule: MINIMAL_WASM_MODULE, transportSAB });
        // Blob window [1000, 2000]s — playhead (beat 2 @120bpm = 1s) is before it.
        sendMessage(proc, {
            type: 'update-state',
            clips: {
                c1: {
                    startBeat: 0,
                    endBeat: 4,
                    blobs: [{ startTime: 1000, endTime: 2000, pitchCenterCents: 6200, originalPitchCenterCents: 6000 }],
                },
            },
        });
        proc.process(
            [[new Float32Array(128)], [new Float32Array(128)]],
            [[new Float32Array(128), new Float32Array(128)]]
        );
        expect(shiftCalls.at(-1)).toBe(0);
    });

    it('faults and passthrough-copies when the WASM instance throws mid-process', async () => {
        const proc = await loadProcessor();
        sendMessage(proc, { type: 'init', wasmModule: MINIMAL_WASM_MODULE });
        // Sabotage the instance by replacing process() to throw.
        const inst = (proc as unknown as { _instance: { process(): number } })._instance;
        inst.process = () => {
            throw new Error('wasm trap');
        };
        const output = [new Float32Array([0, 0, 0, 0]), new Float32Array([0, 0, 0, 0])];
        proc.process([[new Float32Array([0.5, 0.6, 0.7, 0.8])], [new Float32Array([0.5, 0.6, 0.7, 0.8])]], [output]);
        const errors = postedMessages.filter(
            (m) => typeof m === 'object' && m !== null && 'type' in m && (m as { type: string }).type === 'error'
        );
        expect(errors).toHaveLength(1);
        // Passthrough copied the input into the (4-frame) output (Float32).
        expect(Array.from(output[0]!)).toEqual([0.5, 0.6, 0.7, 0.8].map((v) => new Float32Array([v])[0]));
        expect(proc._faulted).toBe(true);
    });
});
