/**
 * AudioWorkletProcessor for the Knead pitch editor.
 *
 * Manages the WASM KneadInstance and applies pitch shifts derived from
 * the current playback position and the active clip's NoteBlobs.
 */

import { resolveProcessorWasmModule } from '../transformers/resolveProcessorWasmModule';
import { initSync, KneadInstance } from '../wasm/daw_dsp.js';

/**
 * Runtime surface of the current daw-dsp crate's KneadInstance (knead/mod.rs).
 * The committed WASM glue predates these exports — it is regenerated by
 * `pnpm wasm:dsp` after the Rust change lands — so the methods are optional
 * here and the processor feature-detects them: with an older binary the
 * worklet keeps processing (unshifted, right channel mirrored from left)
 * instead of throwing a TypeError and faulting into permanent passthrough.
 */
type KneadRuntimeInstance = KneadInstance & {
    set_shift_semitones?(semitones: number): void;
    get_right_ptr?(): number;
};

type KneadClipBlob = {
    startTime: number;
    endTime: number;
    pitchCenterCents: number;
    originalPitchCenterCents: number;
};

type KneadClip = {
    startBeat: number;
    endBeat: number;
    blobs: KneadClipBlob[];
};

type KneadMsg =
    | { type: 'init'; transportSAB?: SharedArrayBuffer }
    | { type: 'update-state'; clips: Record<string, KneadClip> }
    | { type: 'param'; name: string; value: number }
    | { type: 'bypass'; bypassed: boolean };

// Transport SAB layout — kept in lockstep with the writer in
// repositories/createWebAudioEngine.ts (TRANSPORT_F64 / TRANSPORT_SEQ_I32).
// The seven f64 data fields are guarded by a seqlock counter in the Int32 view;
// the reader retries while the counter is odd (write in progress) or changes
// across the read, so it never consumes a snapshot torn across the field writes.
const TRANSPORT_BEAT_F64 = 0;
const TRANSPORT_TEMPO_F64 = 1;
const TRANSPORT_IS_PLAYING_F64 = 5;
const TRANSPORT_SEQ_I32 = 14;
// Bound the seqlock retry so a misbehaving writer can never hang the RT thread;
// on exhaustion the reader falls back to the (possibly torn, but bounded) last
// sample rather than spinning forever.
const TRANSPORT_SEQ_MAX_RETRIES = 8;

class KneadProcessor extends AudioWorkletProcessor {
    _instance: KneadRuntimeInstance | null = null;
    _memory: WebAssembly.Memory | null = null;
    _ready = false;
    _faulted = false;
    _bypassed = false;

    _transportSAB: SharedArrayBuffer | null = null;
    _transportView: Float64Array | null = null;
    _transportSeqView: Int32Array | null = null;

    _clips: Record<string, KneadClip> = {};

    // RT-safe WASM-memory views. A `new Float32Array(memory, ptr, frames)` is a
    // heap allocation even though it copies no bytes, so we must not build one
    // per render quantum. These views are rebuilt only when the backing buffer,
    // pointer, or frame count actually changes (memory growth, first block, or a
    // block-size change) — steady-state playback reuses them with zero allocation.
    _wasmInL: Float32Array | null = null;
    _wasmInR: Float32Array | null = null;
    _wasmOutL: Float32Array | null = null;
    _wasmOutR: Float32Array | null = null;
    _viewBuffer: ArrayBufferLike | null = null;
    _viewInputLeftPtr = -1;
    _viewInputRightPtr = -1;
    _viewResultPtr = -1;
    _viewResultRightPtr = -1;
    _viewFrames = -1;

    constructor(...args: unknown[]) {
        super();
        let wasmModule = resolveProcessorWasmModule(args[0]);
        this.port.onmessage = (event: MessageEvent<KneadMsg>) => {
            const msg = event.data;
            try {
                if (msg.type === 'init') {
                    if (this._ready) {
                        return;
                    }
                    if (!wasmModule) {
                        throw new TypeError('KneadProcessor requires a compiled WASM module');
                    }
                    this._initWasm(wasmModule, msg.transportSAB ?? null);
                    wasmModule = null;
                } else if (msg.type === 'update-state') {
                    this._clips = msg.clips;
                } else if (msg.type === 'param' && this._instance !== null && this._ready && !this._faulted) {
                    if (msg.name === 'shift_semitones') {
                        this._instance.set_shift_semitones?.(msg.value);
                    }
                } else if (msg.type === 'bypass') {
                    this._bypassed = msg.bypassed;
                }
            } catch (error) {
                // Same policy as the process() catch below. A throw at the wasm
                // boundary may leave the instance trapped, and a trap carries no
                // message, so it cannot be told apart from a recoverable error.
                // This catch already reported; what it did not do was stop the
                // instance being handed the next message.
                console.error('KneadProcessor error:', error);
                this._faulted = true;
                this.port.postMessage({ type: 'error', message: String(error) });
            }
        };
    }

    _initWasm(wasmModule: WebAssembly.Module, transportSAB: SharedArrayBuffer | null): void {
        const wasmExports = initSync({ module: wasmModule });
        this._memory = wasmExports.memory;
        this._instance = new KneadInstance(sampleRate);
        this._transportSAB = transportSAB;
        if (transportSAB) {
            this._transportView = new Float64Array(transportSAB);
            this._transportSeqView = new Int32Array(transportSAB);
        }
        this._ready = true;
        this.port.postMessage({ type: 'ready' });
    }

    process(inputs: Float32Array[][], outputs: Float32Array[][]): boolean {
        const input = inputs[0];
        const output = outputs[0];

        if (!this._ready || this._faulted || !input || !output || input.length === 0 || output.length === 0) {
            if (input && output) {
                this._passthrough(input, output);
            }
            return true;
        }

        const in0 = input[0];
        if (!in0) {
            return true;
        }
        const frames = in0.length;

        // Resolve current temporal position
        let currentShiftSemitones = 0;
        if (this._transportView && this._transportSeqView) {
            const view = this._transportView;
            const seq = this._transportSeqView;

            // Seqlock read: sample the three transport fields between two reads of
            // the sequence counter. If the counter was odd (a write was mid-flight)
            // or moved between the two reads, the snapshot is torn — retry. A bound
            // keeps the RT thread from spinning if the writer misbehaves.
            let currentBeat = 0;
            let tempo = 120;
            let isPlaying = false;
            for (let attempt = 0; attempt <= TRANSPORT_SEQ_MAX_RETRIES; attempt++) {
                const before = Atomics.load(seq, TRANSPORT_SEQ_I32);
                currentBeat = view[TRANSPORT_BEAT_F64] ?? 0;
                tempo = view[TRANSPORT_TEMPO_F64] ?? 120;
                isPlaying = (view[TRANSPORT_IS_PLAYING_F64] ?? 0) > 0.5;
                const after = Atomics.load(seq, TRANSPORT_SEQ_I32);
                if (before === after && (before & 1) === 0) {
                    break;
                }
            }

            if (isPlaying) {
                let activeClip: KneadClip | null = null;
                for (const clipId in this._clips) {
                    const clip = this._clips[clipId];
                    if (clip && currentBeat >= clip.startBeat && currentBeat <= clip.endBeat) {
                        activeClip = clip;
                        break;
                    }
                }

                if (activeClip) {
                    const songTimeSeconds = (currentBeat / tempo) * 60;
                    const clipStartTimeSeconds = (activeClip.startBeat / tempo) * 60;
                    const clipTimeSeconds = songTimeSeconds - clipStartTimeSeconds;

                    // Explicit loop rather than Array.prototype.find: the arrow
                    // passed to find() is a fresh closure allocation per render
                    // quantum, which the RT audio thread must avoid.
                    let blob: KneadClipBlob | null = null;
                    const blobs = activeClip.blobs;
                    for (let index = 0; index < blobs.length; index++) {
                        const candidate = blobs[index];
                        if (
                            candidate &&
                            clipTimeSeconds >= candidate.startTime &&
                            clipTimeSeconds <= candidate.endTime
                        ) {
                            blob = candidate;
                            break;
                        }
                    }

                    if (blob) {
                        // originalPitchCenterCents is absent from the persisted clip
                        // blob schema (Arrangement/Project forks), so after a project
                        // reload it rehydrates as undefined. A bare subtraction would
                        // yield NaN and silently corrupt the shift; fall back to the
                        // current center (zero shift) when the original is not finite.
                        const originalCents = blob.originalPitchCenterCents;
                        const baseCents = Number.isFinite(originalCents) ? originalCents : blob.pitchCenterCents;
                        const centsDelta = blob.pitchCenterCents - baseCents;
                        currentShiftSemitones = centsDelta / 100;
                    }
                }
            }
        }

        try {
            const inst = this._instance;
            const mem = this._memory?.buffer;
            if (!inst || !mem) {
                return true;
            }

            inst.set_shift_semitones?.(currentShiftSemitones);

            const inputLeftPtr = inst.get_input_left_ptr();
            const inputRightPtr = inst.get_input_right_ptr();

            // Invalidate every cached view if the backing buffer or frame count
            // changed (memory growth / block-size change); otherwise reuse them.
            if (mem !== this._viewBuffer || frames !== this._viewFrames) {
                this._viewBuffer = mem;
                this._viewFrames = frames;
                this._viewInputLeftPtr = -1;
                this._viewInputRightPtr = -1;
                this._viewResultPtr = -1;
                this._viewResultRightPtr = -1;
            }

            if (!this._wasmInL || inputLeftPtr !== this._viewInputLeftPtr) {
                this._wasmInL = new Float32Array(mem, inputLeftPtr, frames);
                this._viewInputLeftPtr = inputLeftPtr;
            }
            if (!this._wasmInR || inputRightPtr !== this._viewInputRightPtr) {
                this._wasmInR = new Float32Array(mem, inputRightPtr, frames);
                this._viewInputRightPtr = inputRightPtr;
            }

            this._wasmInL.set(in0);
            this._wasmInR.set(input[1] ?? in0);

            const resultPtr = inst.process(frames);
            // Re-read the live buffer AFTER process(): a Rust-side allocation can
            // grow the linear memory mid-call and detach the pre-call `mem`, so the
            // output views must map the post-grow buffer (audit RT-7). Building them
            // over the stale `mem` reads detached (zero) memory. A grow also stales
            // the cached output pointers and the tracked view buffer, so invalidate
            // both here for this quantum and the next.
            const outMem = this._memory?.buffer ?? mem;
            if (outMem !== mem) {
                this._viewBuffer = outMem;
                this._viewResultPtr = -1;
                this._viewResultRightPtr = -1;
            }
            // Older wasm binaries predate get_right_ptr; mirror left into the
            // right output there rather than faulting.
            const resultRightPtr = inst.get_right_ptr?.();

            if (!this._wasmOutL || resultPtr !== this._viewResultPtr) {
                this._wasmOutL = new Float32Array(outMem, resultPtr, frames);
                this._viewResultPtr = resultPtr;
            }
            if (resultRightPtr !== undefined && (!this._wasmOutR || resultRightPtr !== this._viewResultRightPtr)) {
                this._wasmOutR = new Float32Array(outMem, resultRightPtr, frames);
                this._viewResultRightPtr = resultRightPtr;
            }
            const wasmOutL = this._wasmOutL;
            const out0 = output[0];
            if (out0) {
                out0.set(wasmOutL);
            }
            const wasmOutR = this._wasmOutR ?? wasmOutL;
            const out1 = output[1];
            if (out1) {
                out1.set(wasmOutR);
            }
        } catch (error) {
            this._faulted = true;
            this.port.postMessage({ type: 'error', message: String(error) });
            this._passthrough(input, output);
        }

        return true;
    }

    _passthrough(input: Float32Array[], output: Float32Array[]): void {
        for (let ch = 0; ch < Math.min(input.length, output.length); ch++) {
            const inCh = input[ch];
            const outCh = output[ch];
            if (inCh && outCh) {
                outCh.set(inCh);
            }
        }
    }
}

registerProcessor('knead-processor', KneadProcessor);
