/**
 * AudioWorkletProcessor for the Knead pitch editor.
 *
 * Manages the WASM KneadInstance and applies pitch shifts derived from
 * the current playback position and the active clip's NoteBlobs.
 */

import { resolveProcessorWasmModule } from '../transformers/resolveProcessorWasmModule';
import { initSync, KneadInstance } from '../wasm/daw_dsp.js';

import { WasmView } from './wasmView';

/**
 * Runtime surface of the current daw-dsp crate's KneadInstance (knead/mod.rs).
 * The committed WASM glue predates these exports — it is regenerated by
 * `pnpm wasm:dsp` after the Rust change lands — so the methods are optional
 * here and the processor feature-detects them: with an older binary the
 * worklet keeps processing (unshifted, right channel mirrored from left)
 * instead of throwing a TypeError and faulting into permanent passthrough.
 */
type KneadRuntimeInstance = KneadInstance & {
    set_shift_semitones?(semitones: number): void;
    get_right_ptr?(): number;
};

type KneadClipBlob = {
    startTime: number;
    endTime: number;
    pitchCenterCents: number;
    originalPitchCenterCents: number;
};

type KneadClip = {
    startBeat: number;
    endBeat: number;
    blobs: KneadClipBlob[];
};

type KneadMsg =
    | { type: 'init'; transportSAB?: SharedArrayBuffer }
    | { type: 'update-state'; clips: Record<string, KneadClip> }
    | { type: 'param'; name: string; value: number }
    | { type: 'bypass'; bypassed: boolean };

// Transport SAB layout — kept in lockstep with the writer in
// repositories/createWebAudioEngine.ts (TRANSPORT_F64 / TRANSPORT_SEQ_I32).
// The seven f64 data fields are guarded by a seqlock counter in the Int32 view;
// the reader retries while the counter is odd (write in progress) or changes
// across the read, so it never consumes a snapshot torn across the field writes.
const TRANSPORT_BEAT_F64 = 0;
const TRANSPORT_TEMPO_F64 = 1;
const TRANSPORT_IS_PLAYING_F64 = 5;
const TRANSPORT_SEQ_I32 = 14;
// Bound the seqlock retry so a misbehaving writer can never hang the RT thread;
// on exhaustion the reader falls back to the (possibly torn, but bounded) last
// sample rather than spinning forever.
const TRANSPORT_SEQ_MAX_RETRIES = 8;

/**
 * Samples the bypass crossfade takes, each way.
 *
 * 64 at 48 kHz is 1.33 ms — short enough that the toggle still reads as
 * instant, long enough to remove the discontinuity between the dry signal and
 * the wet one 2047 samples behind it. Half a block, so a toggle completes
 * inside one `process` call and never straddles a quantum boundary.
 */
const BYPASS_FADE_SAMPLES = 64;

class KneadProcessor extends AudioWorkletProcessor {
    _instance: KneadRuntimeInstance | null = null;
    _memory: WebAssembly.Memory | null = null;
    _ready = false;
    _faulted = false;
    _bypassed = false;
    /**
     * Where the bypass crossfade currently sits: 0 fully wet, 1 fully dry.
     *
     * A separate value from {@link _bypassed} because the flag flips on a port
     * message and the mix has to travel there over {@link BYPASS_FADE_SAMPLES},
     * on both edges. At rest it equals the flag, and the dry path is then
     * bit-exact rather than scaled by a gain of 1.
     */
    _bypassRamp = 0;

    _transportSAB: SharedArrayBuffer | null = null;
    _transportView: Float64Array | null = null;
    _transportSeqView: Int32Array | null = null;

    _clips: Record<string, KneadClip> = {};

    // RT-safe WASM-memory views: each rebuilds itself only when its own backing
    // buffer, pointer, or length changes, so a memory.grow() buffer-identity change
    // invalidates every view independently (audit RT-7). See wasmView.ts.
    //
    // This used to be a hand-rolled cache with one shared `_viewBuffer` field and
    // four separately-tracked pointers. It advanced that field to the post-grow
    // buffer after process() while resetting only the two OUTPUT pointers, so on
    // the following quantum the buffer identity compared equal, the INPUT views
    // were never rebuilt, and writing into them threw on the detached pre-grow
    // buffer — faulting the node into permanent passthrough. Per-view keying makes
    // that class of partial invalidation unrepresentable.
    _inLeftView = new WasmView();
    _inRightView = new WasmView();
    _outLeftView = new WasmView();
    _outRightView = new WasmView();

    constructor(...args: unknown[]) {
        super();
        let wasmModule = resolveProcessorWasmModule(args[0]);
        this.port.onmessage = (event: MessageEvent<KneadMsg>) => {
            const msg = event.data;
            try {
                if (msg.type === 'init') {
                    if (this._ready) {
                        return;
                    }
                    if (!wasmModule) {
                        throw new TypeError('KneadProcessor requires a compiled WASM module');
                    }
                    this._initWasm(wasmModule, msg.transportSAB ?? null);
                    wasmModule = null;
                } else if (msg.type === 'update-state') {
                    this._clips = msg.clips;
                } else if (msg.type === 'param' && this._instance !== null && this._ready && !this._faulted) {
                    if (msg.name === 'shift_semitones') {
                        this._instance.set_shift_semitones?.(msg.value);
                    }
                } else if (msg.type === 'bypass') {
                    this._bypassed = msg.bypassed;
                }
            } catch (error) {
                // Same policy as the process() catch below. A throw at the wasm
                // boundary may leave the instance trapped, and a trap carries no
                // message, so it cannot be told apart from a recoverable error.
                // This catch already reported; what it did not do was stop the
                // instance being handed the next message.
                console.error('KneadProcessor error:', error);
                this._faulted = true;
                this.port.postMessage({ type: 'error', message: String(error) });
            }
        };
    }

    _initWasm(wasmModule: WebAssembly.Module, transportSAB: SharedArrayBuffer | null): void {
        const wasmExports = initSync({ module: wasmModule });
        this._memory = wasmExports.memory;
        this._instance = new KneadInstance(sampleRate);
        this._transportSAB = transportSAB;
        if (transportSAB) {
            this._transportView = new Float64Array(transportSAB);
            this._transportSeqView = new Int32Array(transportSAB);
        }
        this._ready = true;
        // Knead buffers a whole analysis frame before it emits anything, so it
        // delays its track unconditionally — at zero shift too. Report that delay
        // on the ready handshake, the same seam gluten/bacteria/proof use, so PDC
        // can offset the track instead of leaving the vocal behind the mix
        // (ADR 0016 ruling 3).
        this.port.postMessage({ type: 'ready', latency: this._instance.get_latency_samples() });
    }

    process(inputs: Float32Array[][], outputs: Float32Array[][]): boolean {
        const input = inputs[0];
        const output = outputs[0];

        if (!this._ready || this._faulted || !input || !output || input.length === 0 || output.length === 0) {
            if (input && output) {
                this._passthrough(input, output);
            }
            return true;
        }

        const in0 = input[0];
        if (!in0) {
            return true;
        }
        const frames = in0.length;

        // Resolve current temporal position
        let currentShiftSemitones = 0;
        if (this._transportView && this._transportSeqView) {
            const view = this._transportView;
            const seq = this._transportSeqView;

            // Seqlock read: sample the three transport fields between two reads of
            // the sequence counter. If the counter was odd (a write was mid-flight)
            // or moved between the two reads, the snapshot is torn — retry. A bound
            // keeps the RT thread from spinning if the writer misbehaves.
            let currentBeat = 0;
            let tempo = 120;
            let isPlaying = false;
            for (let attempt = 0; attempt <= TRANSPORT_SEQ_MAX_RETRIES; attempt++) {
                const before = Atomics.load(seq, TRANSPORT_SEQ_I32);
                currentBeat = view[TRANSPORT_BEAT_F64] ?? 0;
                tempo = view[TRANSPORT_TEMPO_F64] ?? 120;
                isPlaying = (view[TRANSPORT_IS_PLAYING_F64] ?? 0) > 0.5;
                const after = Atomics.load(seq, TRANSPORT_SEQ_I32);
                if (before === after && (before & 1) === 0) {
                    break;
                }
            }

            if (isPlaying) {
                let activeClip: KneadClip | null = null;
                for (const clipId in this._clips) {
                    const clip = this._clips[clipId];
                    if (clip && currentBeat >= clip.startBeat && currentBeat <= clip.endBeat) {
                        activeClip = clip;
                        break;
                    }
                }

                if (activeClip) {
                    const songTimeSeconds = (currentBeat / tempo) * 60;
                    const clipStartTimeSeconds = (activeClip.startBeat / tempo) * 60;
                    const clipTimeSeconds = songTimeSeconds - clipStartTimeSeconds;

                    // Explicit loop rather than Array.prototype.find: the arrow
                    // passed to find() is a fresh closure allocation per render
                    // quantum, which the RT audio thread must avoid.
                    let blob: KneadClipBlob | null = null;
                    const blobs = activeClip.blobs;
                    for (let index = 0; index < blobs.length; index++) {
                        const candidate = blobs[index];
                        if (
                            candidate &&
                            clipTimeSeconds >= candidate.startTime &&
                            clipTimeSeconds <= candidate.endTime
                        ) {
                            blob = candidate;
                            break;
                        }
                    }

                    if (blob) {
                        // originalPitchCenterCents is absent from the persisted clip
                        // blob schema (Arrangement/Project forks), so after a project
                        // reload it rehydrates as undefined. A bare subtraction would
                        // yield NaN and silently corrupt the shift; fall back to the
                        // current center (zero shift) when the original is not finite.
                        const originalCents = blob.originalPitchCenterCents;
                        const baseCents = Number.isFinite(originalCents) ? originalCents : blob.pitchCenterCents;
                        const centsDelta = blob.pitchCenterCents - baseCents;
                        currentShiftSemitones = centsDelta / 100;
                    }
                }
            }
        }

        try {
            const inst = this._instance;
            const mem = this._memory?.buffer;
            if (!inst || !mem) {
                return true;
            }

            inst.set_shift_semitones?.(currentShiftSemitones);

            const inputLeftPtr = inst.get_input_left_ptr();
            const inputRightPtr = inst.get_input_right_ptr();

            this._inLeftView.get(mem, inputLeftPtr, frames).set(in0);
            this._inRightView.get(mem, inputRightPtr, frames).set(input[1] ?? in0);

            const resultPtr = inst.process(frames);

            // Bypass swaps the OUTPUT only — the engine above has already been
            // handed this quantum's input and has advanced its state.
            //
            // Knead buffers a 2048-sample analysis frame (2047 samples of group
            // delay) and resynthesises across it, and KneadInstance exposes no
            // reset. Starving the engine for the duration of a bypass would
            // leave its ring buffer holding pre-bypass audio, so un-bypassing
            // would splice ~43 ms of stale signal back in; resetting is not
            // available and would cost a whole detector warm-up anyway. Keeping
            // it fed makes resuming continuous — the same block it would have
            // emitted had bypass never been engaged — at the cost of the DSP
            // running while inaudible.
            //
            // Latency is deliberately untouched: the ready handshake reported
            // the group delay once and PDC still holds that offset, which is
            // what every sibling with a reported latency does on bypass
            // (proof-chamber here, gluten/crust in the Rust engines).
            // Fully bypassed and the ramp has arrived: nothing to blend, and the
            // dry path stays bit-exact. Any ramp still in flight falls through
            // to the crossfade below, which needs the wet buffers.
            if (this._bypassed && this._bypassRamp >= 1) {
                this._passthrough(input, output);
                return true;
            }

            // Re-read the live buffer AFTER process(): a Rust-side allocation can
            // grow the linear memory mid-call and detach the pre-call `mem`, so the
            // output views must map the post-grow buffer (audit RT-7). Building them
            // over the stale `mem` reads detached (zero) memory. The input views
            // above are keyed on the buffer they were built over, so the next
            // quantum re-reads `memory.buffer`, sees the new identity, and rebuilds
            // them — no separate invalidation bookkeeping to keep in step.
            const outMem = this._memory?.buffer ?? mem;
            // Older wasm binaries predate get_right_ptr; mirror left into the
            // right output there rather than faulting.
            const resultRightPtr = inst.get_right_ptr?.();

            const wasmOutL = this._outLeftView.get(outMem, resultPtr, frames);
            const wasmOutR =
                resultRightPtr === undefined ? wasmOutL : this._outRightView.get(outMem, resultRightPtr, frames);

            // Crossfade the swap rather than splicing it.
            //
            // The wet path lags the dry by the 2047-sample group delay, so the
            // two are ~43 ms apart in the source material and decorrelated. A
            // hard switch between them is a discontinuity in both directions —
            // engaging bypass and leaving it — and reads as a click on any
            // non-silent programme. Keeping the engine fed (above) prevents a
            // *stale* frame bleeding back on resume; it does nothing for this.
            //
            // Equal power, because the two sides are decorrelated: a linear
            // crossfade would dip ~3 dB through the middle of every toggle.
            const target = this._bypassed ? 1 : 0;
            const out0 = output[0];
            const out1 = output[1];
            for (let frame = 0; frame < frames; frame++) {
                if (this._bypassRamp !== target) {
                    const step = 1 / BYPASS_FADE_SAMPLES;
                    this._bypassRamp =
                        target > this._bypassRamp
                            ? Math.min(target, this._bypassRamp + step)
                            : Math.max(target, this._bypassRamp - step);
                }
                const dryGain = Math.sin((this._bypassRamp * Math.PI) / 2);
                const wetGain = Math.cos((this._bypassRamp * Math.PI) / 2);
                if (out0) {
                    out0[frame] = (wasmOutL[frame] ?? 0) * wetGain + (input[0]?.[frame] ?? 0) * dryGain;
                }
                if (out1) {
                    const dryRight = input[1]?.[frame] ?? input[0]?.[frame] ?? 0;
                    out1[frame] = (wasmOutR[frame] ?? 0) * wetGain + dryRight * dryGain;
                }
            }
        } catch (error) {
            this._faulted = true;
            this.port.postMessage({ type: 'error', message: String(error) });
            this._passthrough(input, output);
        }

        return true;
    }

    _passthrough(input: Float32Array[], output: Float32Array[]): void {
        for (let ch = 0; ch < Math.min(input.length, output.length); ch++) {
            const inCh = input[ch];
            const outCh = output[ch];
            if (inCh && outCh) {
                outCh.set(inCh);
            }
        }
    }
}

registerProcessor('knead-processor', KneadProcessor);
