[package]
name = "daw-core"
version = "0.1.0"
edition = "2021"
description = "Core Domain Types (TrackId, Beats) for Sourdaw, used everywhere."

[lib]
crate-type = ["rlib"]

[dependencies]
serde = { version = "1", features = ["derive"] }
specta = { version = "2.0.0-rc.20", features = ["derive"] }
triple_buffer = "9.0.0"
