export type DeviceParameterType = 'float' | 'int' | 'bool' | 'choice';

export type DeviceParameter = {
    id: string;
    deviceId: string;
    name: string;
    type: DeviceParameterType;
    value: number;
    defaultValue: number;
    minValue: number;
    maxValue: number;
    unit: string;
    choices?: string[];
    automatable: boolean;
    hasAutomation: boolean;
};

export type PluginFormat = 'builtin' | 'vst3' | 'clap' | 'au';

export type PluginDescriptor = {
    id: string;
    name: string;
    vendor: string;
    format: PluginFormat;
    category: 'instrument' | 'effect' | 'analyzer' | 'utility';
    parameters: DeviceParameter[];
    hasCustomUI: boolean;
};

export const BUILTIN_PLUGINS: PluginDescriptor[] = [
    {
        id: 'builtin-eq',
        name: 'EQ',
        vendor: 'WebDAW',
        format: 'builtin',
        category: 'effect',
        hasCustomUI: false,
        parameters: [
            {
                id: 'eq-low-gain',
                deviceId: 'builtin-eq',
                name: 'Low Gain',
                type: 'float',
                value: 0,
                defaultValue: 0,
                minValue: -24,
                maxValue: 24,
                unit: 'dB',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'eq-low-freq',
                deviceId: 'builtin-eq',
                name: 'Low Freq',
                type: 'float',
                value: 100,
                defaultValue: 100,
                minValue: 20,
                maxValue: 500,
                unit: 'Hz',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'eq-low-q',
                deviceId: 'builtin-eq',
                name: 'Low Q',
                type: 'float',
                value: 1,
                defaultValue: 1,
                minValue: 0.1,
                maxValue: 10,
                unit: '',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'eq-mid-gain',
                deviceId: 'builtin-eq',
                name: 'Mid Gain',
                type: 'float',
                value: 0,
                defaultValue: 0,
                minValue: -24,
                maxValue: 24,
                unit: 'dB',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'eq-mid-freq',
                deviceId: 'builtin-eq',
                name: 'Mid Freq',
                type: 'float',
                value: 1000,
                defaultValue: 1000,
                minValue: 200,
                maxValue: 8000,
                unit: 'Hz',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'eq-mid-q',
                deviceId: 'builtin-eq',
                name: 'Mid Q',
                type: 'float',
                value: 1,
                defaultValue: 1,
                minValue: 0.1,
                maxValue: 10,
                unit: '',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'eq-high-gain',
                deviceId: 'builtin-eq',
                name: 'High Gain',
                type: 'float',
                value: 0,
                defaultValue: 0,
                minValue: -24,
                maxValue: 24,
                unit: 'dB',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'eq-high-freq',
                deviceId: 'builtin-eq',
                name: 'High Freq',
                type: 'float',
                value: 8000,
                defaultValue: 8000,
                minValue: 2000,
                maxValue: 20000,
                unit: 'Hz',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'eq-high-q',
                deviceId: 'builtin-eq',
                name: 'High Q',
                type: 'float',
                value: 1,
                defaultValue: 1,
                minValue: 0.1,
                maxValue: 10,
                unit: '',
                automatable: true,
                hasAutomation: false,
            },
        ],
    },
    {
        id: 'builtin-compressor',
        name: 'Compressor',
        vendor: 'WebDAW',
        format: 'builtin',
        category: 'effect',
        hasCustomUI: false,
        parameters: [
            {
                id: 'comp-threshold',
                deviceId: 'builtin-compressor',
                name: 'Threshold',
                type: 'float',
                value: -20,
                defaultValue: -20,
                minValue: -60,
                maxValue: 0,
                unit: 'dB',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'comp-ratio',
                deviceId: 'builtin-compressor',
                name: 'Ratio',
                type: 'float',
                value: 4,
                defaultValue: 4,
                minValue: 1,
                maxValue: 20,
                unit: ':1',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'comp-attack',
                deviceId: 'builtin-compressor',
                name: 'Attack',
                type: 'float',
                value: 10,
                defaultValue: 10,
                minValue: 0.1,
                maxValue: 100,
                unit: 'ms',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'comp-release',
                deviceId: 'builtin-compressor',
                name: 'Release',
                type: 'float',
                value: 100,
                defaultValue: 100,
                minValue: 10,
                maxValue: 1000,
                unit: 'ms',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'comp-knee',
                deviceId: 'builtin-compressor',
                name: 'Knee',
                type: 'float',
                value: 6,
                defaultValue: 6,
                minValue: 0,
                maxValue: 30,
                unit: 'dB',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'comp-makeup',
                deviceId: 'builtin-compressor',
                name: 'Makeup',
                type: 'float',
                value: 0,
                defaultValue: 0,
                minValue: 0,
                maxValue: 30,
                unit: 'dB',
                automatable: true,
                hasAutomation: false,
            },
        ],
    },
    {
        id: 'builtin-reverb',
        name: 'Reverb',
        vendor: 'WebDAW',
        format: 'builtin',
        category: 'effect',
        hasCustomUI: false,
        parameters: [
            {
                id: 'rev-size',
                deviceId: 'builtin-reverb',
                name: 'Size',
                type: 'float',
                value: 0.5,
                defaultValue: 0.5,
                minValue: 0,
                maxValue: 1,
                unit: '',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'rev-decay',
                deviceId: 'builtin-reverb',
                name: 'Decay',
                type: 'float',
                value: 2,
                defaultValue: 2,
                minValue: 0.1,
                maxValue: 20,
                unit: 's',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'rev-damping',
                deviceId: 'builtin-reverb',
                name: 'Damping',
                type: 'float',
                value: 0.5,
                defaultValue: 0.5,
                minValue: 0,
                maxValue: 1,
                unit: '',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'rev-predelay',
                deviceId: 'builtin-reverb',
                name: 'Pre-Delay',
                type: 'float',
                value: 10,
                defaultValue: 10,
                minValue: 0,
                maxValue: 200,
                unit: 'ms',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'rev-lowcut',
                deviceId: 'builtin-reverb',
                name: 'Low Cut',
                type: 'float',
                value: 80,
                defaultValue: 80,
                minValue: 20,
                maxValue: 2000,
                unit: 'Hz',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'rev-mix',
                deviceId: 'builtin-reverb',
                name: 'Dry/Wet',
                type: 'float',
                value: 0.3,
                defaultValue: 0.3,
                minValue: 0,
                maxValue: 1,
                unit: '',
                automatable: true,
                hasAutomation: false,
            },
        ],
    },
    {
        id: 'builtin-delay',
        name: 'Delay',
        vendor: 'WebDAW',
        format: 'builtin',
        category: 'effect',
        hasCustomUI: false,
        parameters: [
            {
                id: 'delay-time',
                deviceId: 'builtin-delay',
                name: 'Time',
                type: 'float',
                value: 250,
                defaultValue: 250,
                minValue: 1,
                maxValue: 2000,
                unit: 'ms',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'delay-feedback',
                deviceId: 'builtin-delay',
                name: 'Feedback',
                type: 'float',
                value: 0.4,
                defaultValue: 0.4,
                minValue: 0,
                maxValue: 0.95,
                unit: '',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'delay-lowcut',
                deviceId: 'builtin-delay',
                name: 'Low Cut',
                type: 'float',
                value: 80,
                defaultValue: 80,
                minValue: 20,
                maxValue: 2000,
                unit: 'Hz',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'delay-highcut',
                deviceId: 'builtin-delay',
                name: 'High Cut',
                type: 'float',
                value: 12000,
                defaultValue: 12000,
                minValue: 1000,
                maxValue: 20000,
                unit: 'Hz',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'delay-mix',
                deviceId: 'builtin-delay',
                name: 'Dry/Wet',
                type: 'float',
                value: 0.3,
                defaultValue: 0.3,
                minValue: 0,
                maxValue: 1,
                unit: '',
                automatable: true,
                hasAutomation: false,
            },
        ],
    },
    {
        id: 'builtin-gain',
        name: 'Gain',
        vendor: 'WebDAW',
        format: 'builtin',
        category: 'utility',
        hasCustomUI: false,
        parameters: [
            {
                id: 'gain-level',
                deviceId: 'builtin-gain',
                name: 'Gain',
                type: 'float',
                value: 0,
                defaultValue: 0,
                minValue: -60,
                maxValue: 24,
                unit: 'dB',
                automatable: true,
                hasAutomation: false,
            },
        ],
    },
    {
        id: 'builtin-sidechain-compressor',
        name: 'Sidechain Compressor',
        vendor: 'WebDAW',
        format: 'builtin',
        category: 'effect',
        hasCustomUI: false,
        parameters: [
            {
                id: 'sc-comp-threshold',
                deviceId: 'builtin-sidechain-compressor',
                name: 'Threshold',
                type: 'float',
                value: -20,
                defaultValue: -20,
                minValue: -60,
                maxValue: 0,
                unit: 'dB',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'sc-comp-ratio',
                deviceId: 'builtin-sidechain-compressor',
                name: 'Ratio',
                type: 'float',
                value: 4,
                defaultValue: 4,
                minValue: 1,
                maxValue: 20,
                unit: ':1',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'sc-comp-attack',
                deviceId: 'builtin-sidechain-compressor',
                name: 'Attack',
                type: 'float',
                value: 10,
                defaultValue: 10,
                minValue: 1,
                maxValue: 100,
                unit: 'ms',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'sc-comp-release',
                deviceId: 'builtin-sidechain-compressor',
                name: 'Release',
                type: 'float',
                value: 100,
                defaultValue: 100,
                minValue: 10,
                maxValue: 1000,
                unit: 'ms',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'sc-comp-makeup',
                deviceId: 'builtin-sidechain-compressor',
                name: 'Makeup',
                type: 'float',
                value: 0,
                defaultValue: 0,
                minValue: 0,
                maxValue: 30,
                unit: 'dB',
                automatable: true,
                hasAutomation: false,
            },
        ],
    },
    {
        id: 'builtin-chorus',
        name: 'Chorus',
        vendor: 'WebDAW',
        format: 'builtin',
        category: 'effect',
        hasCustomUI: false,
        parameters: [
            {
                id: 'chorus-rate',
                deviceId: 'builtin-chorus',
                name: 'Rate',
                type: 'float',
                value: 1.5,
                defaultValue: 1.5,
                minValue: 0.1,
                maxValue: 10,
                unit: 'Hz',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'chorus-depth',
                deviceId: 'builtin-chorus',
                name: 'Depth',
                type: 'float',
                value: 5,
                defaultValue: 5,
                minValue: 0,
                maxValue: 20,
                unit: 'ms',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'chorus-feedback',
                deviceId: 'builtin-chorus',
                name: 'Feedback',
                type: 'float',
                value: 0.2,
                defaultValue: 0.2,
                minValue: 0,
                maxValue: 0.9,
                unit: '',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'chorus-mix',
                deviceId: 'builtin-chorus',
                name: 'Dry/Wet',
                type: 'float',
                value: 0.5,
                defaultValue: 0.5,
                minValue: 0,
                maxValue: 1,
                unit: '',
                automatable: true,
                hasAutomation: false,
            },
        ],
    },
    {
        id: 'builtin-phaser',
        name: 'Phaser',
        vendor: 'WebDAW',
        format: 'builtin',
        category: 'effect',
        hasCustomUI: false,
        parameters: [
            {
                id: 'phaser-rate',
                deviceId: 'builtin-phaser',
                name: 'Rate',
                type: 'float',
                value: 0.5,
                defaultValue: 0.5,
                minValue: 0.1,
                maxValue: 10,
                unit: 'Hz',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'phaser-depth',
                deviceId: 'builtin-phaser',
                name: 'Depth',
                type: 'float',
                value: 0.7,
                defaultValue: 0.7,
                minValue: 0,
                maxValue: 1,
                unit: '',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'phaser-feedback',
                deviceId: 'builtin-phaser',
                name: 'Feedback',
                type: 'float',
                value: 0.3,
                defaultValue: 0.3,
                minValue: 0,
                maxValue: 0.9,
                unit: '',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'phaser-stages',
                deviceId: 'builtin-phaser',
                name: 'Stages',
                type: 'int',
                value: 4,
                defaultValue: 4,
                minValue: 2,
                maxValue: 12,
                unit: '',
                automatable: false,
                hasAutomation: false,
            },
        ],
    },
    {
        id: 'builtin-distortion',
        name: 'Distortion',
        vendor: 'WebDAW',
        format: 'builtin',
        category: 'effect',
        hasCustomUI: false,
        parameters: [
            {
                id: 'dist-drive',
                deviceId: 'builtin-distortion',
                name: 'Drive',
                type: 'float',
                value: 20,
                defaultValue: 20,
                minValue: 0,
                maxValue: 100,
                unit: '',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'dist-tone',
                deviceId: 'builtin-distortion',
                name: 'Tone',
                type: 'float',
                value: 4000,
                defaultValue: 4000,
                minValue: 200,
                maxValue: 8000,
                unit: 'Hz',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'dist-output',
                deviceId: 'builtin-distortion',
                name: 'Output Level',
                type: 'float',
                value: 0,
                defaultValue: 0,
                minValue: -24,
                maxValue: 0,
                unit: 'dB',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'dist-mix',
                deviceId: 'builtin-distortion',
                name: 'Dry/Wet',
                type: 'float',
                value: 0.5,
                defaultValue: 0.5,
                minValue: 0,
                maxValue: 1,
                unit: '',
                automatable: true,
                hasAutomation: false,
            },
        ],
    },
    {
        id: 'builtin-limiter',
        name: 'Limiter',
        vendor: 'WebDAW',
        format: 'builtin',
        category: 'effect',
        hasCustomUI: false,
        parameters: [
            {
                id: 'lim-threshold',
                deviceId: 'builtin-limiter',
                name: 'Threshold',
                type: 'float',
                value: -6,
                defaultValue: -6,
                minValue: -30,
                maxValue: 0,
                unit: 'dB',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'lim-release',
                deviceId: 'builtin-limiter',
                name: 'Release',
                type: 'float',
                value: 100,
                defaultValue: 100,
                minValue: 10,
                maxValue: 500,
                unit: 'ms',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'lim-ceiling',
                deviceId: 'builtin-limiter',
                name: 'Ceiling',
                type: 'float',
                value: -0.3,
                defaultValue: -0.3,
                minValue: -3,
                maxValue: 0,
                unit: 'dB',
                automatable: true,
                hasAutomation: false,
            },
        ],
    },
    {
        id: 'builtin-flanger',
        name: 'Flanger',
        vendor: 'WebDAW',
        format: 'builtin',
        category: 'effect',
        hasCustomUI: false,
        parameters: [
            {
                id: 'flanger-rate',
                deviceId: 'builtin-flanger',
                name: 'Rate',
                type: 'float',
                value: 0.3,
                defaultValue: 0.3,
                minValue: 0.05,
                maxValue: 5,
                unit: 'Hz',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'flanger-depth',
                deviceId: 'builtin-flanger',
                name: 'Depth',
                type: 'float',
                value: 3,
                defaultValue: 3,
                minValue: 0,
                maxValue: 10,
                unit: 'ms',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'flanger-feedback',
                deviceId: 'builtin-flanger',
                name: 'Feedback',
                type: 'float',
                value: 0.5,
                defaultValue: 0.5,
                minValue: 0,
                maxValue: 0.95,
                unit: '',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'flanger-mix',
                deviceId: 'builtin-flanger',
                name: 'Dry/Wet',
                type: 'float',
                value: 0.5,
                defaultValue: 0.5,
                minValue: 0,
                maxValue: 1,
                unit: '',
                automatable: true,
                hasAutomation: false,
            },
        ],
    },
    {
        id: 'builtin-tremolo',
        name: 'Tremolo',
        vendor: 'WebDAW',
        format: 'builtin',
        category: 'effect',
        hasCustomUI: false,
        parameters: [
            {
                id: 'trem-rate',
                deviceId: 'builtin-tremolo',
                name: 'Rate',
                type: 'float',
                value: 4,
                defaultValue: 4,
                minValue: 0.1,
                maxValue: 20,
                unit: 'Hz',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'trem-depth',
                deviceId: 'builtin-tremolo',
                name: 'Depth',
                type: 'float',
                value: 0.5,
                defaultValue: 0.5,
                minValue: 0,
                maxValue: 1,
                unit: '',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'trem-shape',
                deviceId: 'builtin-tremolo',
                name: 'Shape',
                type: 'choice',
                value: 0,
                defaultValue: 0,
                minValue: 0,
                maxValue: 1,
                unit: '',
                choices: ['Sine', 'Square'],
                automatable: false,
                hasAutomation: false,
            },
        ],
    },
    {
        id: 'builtin-bitcrusher',
        name: 'Bitcrusher',
        vendor: 'WebDAW',
        format: 'builtin',
        category: 'effect',
        hasCustomUI: false,
        parameters: [
            {
                id: 'crush-bits',
                deviceId: 'builtin-bitcrusher',
                name: 'Bit Depth',
                type: 'int',
                value: 8,
                defaultValue: 8,
                minValue: 1,
                maxValue: 16,
                unit: 'bit',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'crush-rate',
                deviceId: 'builtin-bitcrusher',
                name: 'Rate Reduction',
                type: 'float',
                value: 1,
                defaultValue: 1,
                minValue: 1,
                maxValue: 40,
                unit: 'x',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'crush-mix',
                deviceId: 'builtin-bitcrusher',
                name: 'Dry/Wet',
                type: 'float',
                value: 0.5,
                defaultValue: 0.5,
                minValue: 0,
                maxValue: 1,
                unit: '',
                automatable: true,
                hasAutomation: false,
            },
        ],
    },
    {
        id: 'builtin-filter',
        name: 'Filter',
        vendor: 'WebDAW',
        format: 'builtin',
        category: 'effect',
        hasCustomUI: false,
        parameters: [
            {
                id: 'filter-cutoff',
                deviceId: 'builtin-filter',
                name: 'Cutoff',
                type: 'float',
                value: 1000,
                defaultValue: 1000,
                minValue: 20,
                maxValue: 20000,
                unit: 'Hz',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'filter-resonance',
                deviceId: 'builtin-filter',
                name: 'Resonance',
                type: 'float',
                value: 1,
                defaultValue: 1,
                minValue: 0.1,
                maxValue: 20,
                unit: '',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'filter-type',
                deviceId: 'builtin-filter',
                name: 'Type',
                type: 'choice',
                value: 0,
                defaultValue: 0,
                minValue: 0,
                maxValue: 3,
                unit: '',
                choices: ['Lowpass', 'Highpass', 'Bandpass', 'Notch'],
                automatable: false,
                hasAutomation: false,
            },
        ],
    },
    {
        id: 'builtin-autopan',
        name: 'Auto-Pan',
        vendor: 'WebDAW',
        format: 'builtin',
        category: 'effect',
        hasCustomUI: false,
        parameters: [
            {
                id: 'autopan-rate',
                deviceId: 'builtin-autopan',
                name: 'Rate',
                type: 'float',
                value: 2,
                defaultValue: 2,
                minValue: 0.1,
                maxValue: 10,
                unit: 'Hz',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'autopan-depth',
                deviceId: 'builtin-autopan',
                name: 'Depth',
                type: 'float',
                value: 0.7,
                defaultValue: 0.7,
                minValue: 0,
                maxValue: 1,
                unit: '',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'autopan-shape',
                deviceId: 'builtin-autopan',
                name: 'Shape',
                type: 'choice',
                value: 0,
                defaultValue: 0,
                minValue: 0,
                maxValue: 1,
                unit: '',
                choices: ['Sine', 'Triangle'],
                automatable: false,
                hasAutomation: false,
            },
        ],
    },
    // -- Instruments --
    {
        id: 'builtin-synth',
        name: 'Synth',
        vendor: 'WebDAW',
        format: 'builtin',
        category: 'instrument',
        hasCustomUI: false,
        parameters: [
            {
                id: 'waveform',
                deviceId: 'builtin-synth',
                name: 'Waveform',
                type: 'choice',
                value: 2,
                defaultValue: 2,
                minValue: 0,
                maxValue: 3,
                unit: '',
                choices: ['Sine', 'Triangle', 'Sawtooth', 'Square'],
                automatable: false,
                hasAutomation: false,
            },
            {
                id: 'attack',
                deviceId: 'builtin-synth',
                name: 'Attack',
                type: 'float',
                value: 0.01,
                defaultValue: 0.01,
                minValue: 0.001,
                maxValue: 2,
                unit: 's',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'decay',
                deviceId: 'builtin-synth',
                name: 'Decay',
                type: 'float',
                value: 0.2,
                defaultValue: 0.2,
                minValue: 0.001,
                maxValue: 2,
                unit: 's',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'sustain',
                deviceId: 'builtin-synth',
                name: 'Sustain',
                type: 'float',
                value: 0.7,
                defaultValue: 0.7,
                minValue: 0,
                maxValue: 1,
                unit: '',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'release',
                deviceId: 'builtin-synth',
                name: 'Release',
                type: 'float',
                value: 0.3,
                defaultValue: 0.3,
                minValue: 0.001,
                maxValue: 5,
                unit: 's',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'filterCutoff',
                deviceId: 'builtin-synth',
                name: 'Filter Cutoff',
                type: 'float',
                value: 5000,
                defaultValue: 5000,
                minValue: 20,
                maxValue: 20000,
                unit: 'Hz',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'filterResonance',
                deviceId: 'builtin-synth',
                name: 'Filter Resonance',
                type: 'float',
                value: 1,
                defaultValue: 1,
                minValue: 0.1,
                maxValue: 20,
                unit: '',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'filterType',
                deviceId: 'builtin-synth',
                name: 'Filter Type',
                type: 'choice',
                value: 0,
                defaultValue: 0,
                minValue: 0,
                maxValue: 2,
                unit: '',
                choices: ['Lowpass', 'Highpass', 'Bandpass'],
                automatable: false,
                hasAutomation: false,
            },
            {
                id: 'filterEnvAmount',
                deviceId: 'builtin-synth',
                name: 'Filter Env',
                type: 'float',
                value: 0,
                defaultValue: 0,
                minValue: 0,
                maxValue: 10000,
                unit: 'Hz',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'detune',
                deviceId: 'builtin-synth',
                name: 'Detune',
                type: 'float',
                value: 0,
                defaultValue: 0,
                minValue: -100,
                maxValue: 100,
                unit: 'cents',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'gain',
                deviceId: 'builtin-synth',
                name: 'Gain',
                type: 'float',
                value: 0.3,
                defaultValue: 0.3,
                minValue: 0,
                maxValue: 1,
                unit: '',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'osc2Waveform',
                deviceId: 'builtin-synth',
                name: 'Osc 2 Wave',
                type: 'choice',
                value: 2,
                defaultValue: 2,
                minValue: 0,
                maxValue: 3,
                unit: '',
                choices: ['Sine', 'Triangle', 'Sawtooth', 'Square'],
                automatable: false,
                hasAutomation: false,
            },
            {
                id: 'osc2Detune',
                deviceId: 'builtin-synth',
                name: 'Osc 2 Detune',
                type: 'float',
                value: 0,
                defaultValue: 0,
                minValue: -1200,
                maxValue: 1200,
                unit: 'cents',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'osc2Mix',
                deviceId: 'builtin-synth',
                name: 'Osc 2 Mix',
                type: 'float',
                value: 0,
                defaultValue: 0,
                minValue: 0,
                maxValue: 1,
                unit: '',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'subOscLevel',
                deviceId: 'builtin-synth',
                name: 'Sub-Osc Level',
                type: 'float',
                value: 0,
                defaultValue: 0,
                minValue: 0,
                maxValue: 1,
                unit: '',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'noiseLevel',
                deviceId: 'builtin-synth',
                name: 'Noise Level',
                type: 'float',
                value: 0,
                defaultValue: 0,
                minValue: 0,
                maxValue: 1,
                unit: '',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'vibratoRate',
                deviceId: 'builtin-synth',
                name: 'Vibrato Rate',
                type: 'float',
                value: 0,
                defaultValue: 0,
                minValue: 0,
                maxValue: 10,
                unit: 'Hz',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'vibratoDepth',
                deviceId: 'builtin-synth',
                name: 'Vibrato Depth',
                type: 'float',
                value: 0,
                defaultValue: 0,
                minValue: 0,
                maxValue: 50,
                unit: 'cents',
                automatable: true,
                hasAutomation: false,
            },
            {
                id: 'stereoSpread',
                deviceId: 'builtin-synth',
                name: 'Stereo Spread',
                type: 'float',
                value: 0,
                defaultValue: 0,
                minValue: 0,
                maxValue: 1,
                unit: '',
                automatable: true,
                hasAutomation: false,
            },
        ],
    },
    {
        id: 'builtin-drum-kit',
        name: 'Drum Kit',
        vendor: 'WebDAW',
        format: 'builtin',
        category: 'instrument',
        hasCustomUI: false,
        parameters: [
            {
                id: 'kit',
                deviceId: 'builtin-drum-kit',
                name: 'Kit',
                type: 'choice',
                value: 0,
                defaultValue: 0,
                minValue: 0,
                maxValue: 3,
                unit: '',
                choices: ['808 Kit', 'Analog Kit', 'Electronic Kit', 'Acoustic Kit'],
                automatable: false,
                hasAutomation: false,
            },
            {
                id: 'gain',
                deviceId: 'builtin-drum-kit',
                name: 'Gain',
                type: 'float',
                value: 0.8,
                defaultValue: 0.8,
                minValue: 0,
                maxValue: 1,
                unit: '',
                automatable: true,
                hasAutomation: false,
            },
        ],
    },
];

function createSynthVariant(id: string, name: string, overrides: Record<string, number>): PluginDescriptor {
    const base = BUILTIN_PLUGINS.find((p) => p.id === 'builtin-synth')!;
    return {
        id,
        name,
        vendor: 'WebDAW',
        format: 'builtin',
        category: 'instrument',
        hasCustomUI: false,
        parameters: base.parameters.map((p) => {
            const val = overrides[p.id] !== undefined ? overrides[p.id]! : p.defaultValue as number;
            return { ...p, deviceId: id, value: val, defaultValue: val };
        }),
    };
}

BUILTIN_PLUGINS.push(
    createSynthVariant('builtin-synth-mellotron', 'Mellotron', { waveform: 3, attack: 0.1, decay: 0.4, release: 0.3, filterCutoff: 2500, vibratoRate: 5.5, vibratoDepth: 20, noiseLevel: 0.05 }),
    createSynthVariant('builtin-synth-strings', 'Analog Strings', { waveform: 2, attack: 0.3, release: 1.2, osc2Mix: 0.5, osc2Detune: 15, stereoSpread: 1 }),
    createSynthVariant('builtin-synth-808bass', '808 Bass', { waveform: 0, attack: 0.01, decay: 1.2, sustain: 0, subOscLevel: 1.0, filterCutoff: 800, filterEnvAmount: 1200 }),
    createSynthVariant('builtin-synth-brass', 'Classic Brass', { waveform: 2, attack: 0.05, filterEnvAmount: 3000, osc2Waveform: 3, osc2Mix: 0.3, filterCutoff: 500, filterResonance: 3, stereoSpread: 0.5 })
);

function createDrumVariant(id: string, name: string, kitIndex: number): PluginDescriptor {
    const base = BUILTIN_PLUGINS.find((p) => p.id === 'builtin-drum-kit')!;
    return {
        id,
        name,
        vendor: 'WebDAW',
        format: 'builtin',
        category: 'instrument',
        hasCustomUI: false,
        parameters: base.parameters.map((p) => {
            if (p.id === 'kit') {
                return { ...p, deviceId: id, value: kitIndex, defaultValue: kitIndex };
            }
            return { ...p, deviceId: id };
        }),
    };
}

BUILTIN_PLUGINS.push(
    createDrumVariant('builtin-drum-machine-808', '808 Drum Machine', 0),
    createDrumVariant('builtin-drum-machine-analog', 'Analog Drum Machine', 1),
    createDrumVariant('builtin-drum-machine-electronic', 'Electronic Drum Machine', 2),
    createDrumVariant('builtin-drum-machine-acoustic', 'Acoustic Drum Kit', 3)
);

export function getPluginById(pluginId: string): PluginDescriptor | undefined {
    return BUILTIN_PLUGINS.find((p) => p.id === pluginId);
}
