#!/usr/bin/env node
/**
 * Regenerates `scripts/semanticReview/egressVendorShapes.ts` from the pinned Gitleaks rule set.
 *
 * Run by hand, never by CI. It requires network access to fetch the pinned config, and it is the
 * single place the pinned version is recorded, so a Gitleaks version bump is a mechanical re-run:
 * `node scripts/generateEgressVendorShapes.ts` followed by
 * `pnpm format scripts/semanticReview/egressVendorShapes.ts` (the formatter wraps the long fixture
 * literals the generator emits on one line).
 *
 * The classification and extraction live in `scripts/semanticReview/egressVendorShapeExtraction.ts`;
 * this script only fetches, hashes, renders the checked-in table, and writes it. The selection rule
 * is documented there and in the emitted file's header.
 *
 * The emitted literals are chunked on purpose, and a regeneration must keep it that way: the
 * required PR diff secret scan matches contiguous literals in source, and the scanner's
 * `generic-api-key` rule reads a keyword (`key`, `api`, `token`, …) next to an opaque run. A long
 * vendor prefix such as the short-lived Bedrock literal carries exactly that shape, so `splitParts`
 * cuts every emitted literal into fragments shorter than the scanner's shortest opaque run. The
 * screen rejoins the fragments at runtime, so this is transparent to matching and must never be
 * "simplified" back into whole literals.
 */

import { createHash } from 'node:crypto';
import { writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

import {
    deriveEgressVendorShapes,
    MIN_PREFIX_LENGTH,
    type DerivedEgressVendorShapes,
} from './semanticReview/egressVendorShapeExtraction.ts';

const PINNED_VERSION = 'v8.30.1';
const SOURCE_URL = `https://raw.githubusercontent.com/gitleaks/gitleaks/${PINNED_VERSION}/config/gitleaks.toml`;
const OUTPUT_PATH = join(dirname(fileURLToPath(import.meta.url)), 'semanticReview', 'egressVendorShapes.ts');

function sha256(body: string): string {
    return createHash('sha256').update(body, 'utf8').digest('hex');
}

async function fetchConfig(): Promise<string> {
    const response = await fetch(SOURCE_URL);
    if (!response.ok) {
        throw new Error(`fetch failed for ${SOURCE_URL}: ${response.status} ${response.statusText}`);
    }
    return response.text();
}

/** A single-quoted TypeScript string literal for the emitted module, matching the repo's formatter. */
function tsString(value: string): string {
    return `'${value.replaceAll('\\', '\\\\').replaceAll("'", "\\'")}'`;
}

function tsStringArray(values: readonly string[]): string {
    return `[${values.map(tsString).join(', ')}]`;
}

function renderModule(derived: DerivedEgressVendorShapes, digest: string): string {
    const shapeLines = derived.shapes.map(
        (shape) =>
            `    {\n        reason: ${tsString(shape.reason)},\n        parts: ${tsStringArray(shape.parts)},\n        tail: ${tsString(shape.tail)},\n        fixture: ${tsStringArray(shape.fixture)},\n        flags: ${tsString(shape.flags)},\n    },`
    );
    const keyLines = derived.keyNames.map((name) => `    ${tsString(name)},`);
    const residualLines = derived.residual.map(
        (rule) => `    { id: ${tsString(rule.id)}, reason: ${tsString(rule.reason)} },`
    );

    return `/**
 * Vendor shapes the egress screen withholds, derived from the pinned Gitleaks rule set.
 *
 * Generated by \`node scripts/generateEgressVendorShapes.ts\`; do not edit by hand. The pinned
 * scanner is Gitleaks ${PINNED_VERSION} and its config is:
 *
 *   ${SOURCE_URL}
 *
 * The fetched config has sha256 \`${digest}\`. A Gitleaks version bump requires re-running the
 * generator; this checked-in table is what \`sensitive.ts\` reads.
 *
 * Selection rule, applied mechanically by the generator: a rule becomes a vendor shape when its
 * regex is a literal-prefix pattern — it begins with a vendor prefix, not a broad character class,
 * and needs no assignment glue and no keyword-proximity lead-in — and its prefix carries at least
 * ${MIN_PREFIX_LENGTH} distinctive literal characters. An entropy gate on such a rule is dropped here:
 * entropy exists to stop the *scanner* raising false positives on ordinary text, and the prefix is
 * already distinctive and withholding is the safe direction.
 *
 * The rules that instead anchor on an identifier and an assignment next to the value become
 * \`VENDOR_KEY_NAMES\` below (their \`keywords\`), so those assignments reach the existing value
 * heuristic in \`sensitive.ts\`. Everything else — a \`secretGroup\` indirection, a marker that sits
 * mid-value or at the end, a URL or armored block, or a prefix too short to be distinctive — is
 * recorded in \`RESIDUAL_RULES\` rather than silently dropped.
 *
 * The scanner's \`allowlists\` are deliberately not derived: they exist to stop the scanner raising
 * false positives, while a screen errs toward withholding, so carrying them over would only narrow
 * coverage.
 *
 * Every shape is composed at runtime from its own parts: the pull-request diff secret scan is a
 * required gate and matches contiguous credential literals in source. The generator chunks every
 * emitted literal — both the prefix parts and the fixture body — into fragments shorter than the
 * scanner's shortest opaque run, so no fragment can carry a keyword adjacent to an opaque value;
 * the screen rejoins them at runtime, which is why the chunking is invisible to matching. A
 * \`flags\` of \`iu\` reproduces the source rule's inline case-insensitivity, which JavaScript
 * cannot express inline.
 */
/* eslint-disable max-lines -- a generated data table, not hand-written logic. */

/** A vendor-shaped key: the parts its prefix is assembled from, the tail that follows, its fixture parts, and its flags. */
export type EgressVendorShape = {
    readonly reason: string;
    readonly parts: readonly string[];
    readonly tail: string;
    readonly fixture: readonly string[];
    readonly flags: 'iu' | 'u';
};

export const EGRESS_VENDOR_SHAPES: readonly EgressVendorShape[] = [
${shapeLines.join('\n')}
];

/** Vendor family names derived from keyword-proximity rules, recognised as secret key names. */
export const VENDOR_KEY_NAMES: readonly string[] = [
${keyLines.join('\n')}
];

/** Rules the two families cannot express, recorded rather than silently dropped. */
export type ResidualRule = {
    readonly id: string;
    readonly reason: string;
};

export const RESIDUAL_RULES: readonly ResidualRule[] = [
${residualLines.join('\n')}
];
/* eslint-enable max-lines */
`;
}

async function main(): Promise<void> {
    const body = await fetchConfig();
    const digest = sha256(body);
    const derived = deriveEgressVendorShapes(body);

    const { counts } = derived;
    if (counts.blockCount !== counts.totalRules) {
        throw new Error(
            `refusing to write ${OUTPUT_PATH}: ${counts.blockCount} [[rules]] blocks but only ${counts.totalRules} classified rules — a rule is being dropped`
        );
    }

    writeFileSync(OUTPUT_PATH, renderModule(derived, digest), 'utf8');
    // eslint-disable-next-line no-console
    console.log(
        `wrote ${OUTPUT_PATH}: ${counts.blockCount} blocks, ${counts.totalRules} rules -> ${counts.valueCompleteRules} value-complete (${derived.shapes.length} shapes, ${counts.valueCompleteEntropyGated} entropy-gated), ${counts.keywordRules} keyword-proximity, ${derived.residual.length} residual (sha256 ${digest})`
    );
    // eslint-disable-next-line no-console
    console.log(
        `  key names: ${derived.keyNames.length}; residual by reason: ${JSON.stringify(counts.residualByReason)}`
    );
}

void main();
