import { type SoundPreset } from '#/modules/Arrangement/models/SoundPreset';
import { synth, comp, delay, eq, filter, bitcrusher, AUTHOR } from './presetHelpers';

export const bassPresets: SoundPreset[] = [
    // ─── Bass ────────────────────────────────────────────────────────────
    {
        id: 'factory-bass-sub',
        name: 'Sub Bass',
        category: 'bass',
        subcategory: 'analog',
        description: 'Deep sine sub bass with long sustain and a dark filter. Pure low-end foundation.',
        trackKind: 'midi',
        devices: [
            synth('Sub Bass', {
                waveform: 0,
                attack: 0.01,
                decay: 0.1,
                sustain: 0.9,
                release: 0.4,
                filterCutoff: 200,
                filterResonance: 0,
                filterType: 0,
                detune: 0,
                gain: 0.4,
                subOscLevel: 0.6,
            }),
            comp('Compressor', { 'comp-threshold': -18, 'comp-ratio': 4, 'comp-attack': 10, 'comp-release': 100 }),
            eq('EQ', { 'eq-low-gain': 4, 'eq-low-freq': 60, 'eq-high-gain': -6, 'eq-high-freq': 8000 }),
        ],
        tags: ['sub', 'sine', 'deep', 'low-end'],
        author: AUTHOR,
        isFactory: true,
    },
    {
        id: 'factory-bass-analog',
        name: 'Analog Bass',
        category: 'bass',
        subcategory: 'analog',
        description: 'Punchy sawtooth bass with short decay and compression for mix presence.',
        trackKind: 'midi',
        devices: [
            synth('Analog Bass', {
                waveform: 2,
                attack: 0.005,
                decay: 0.25,
                sustain: 0.5,
                release: 0.15,
                filterCutoff: 800,
                filterResonance: 2,
                filterType: 0,
                filterEnvAmount: 2000,
                detune: 5,
                gain: 0.35,
                subOscLevel: 0.4,
                filterVelocitySensitivity: 0.6,
            }),
            comp('Compressor', { 'comp-threshold': -15, 'comp-ratio': 6, 'comp-attack': 5, 'comp-release': 80 }),
        ],
        tags: ['analog', 'sawtooth', 'punchy', 'compressed'],
        author: AUTHOR,
        isFactory: true,
    },
    {
        id: 'factory-bass-wobble',
        name: 'Wobble Bass',
        category: 'bass',
        subcategory: 'digital',
        description: 'Aggressive square wave bass with high resonance and a short delay tail.',
        trackKind: 'midi',
        devices: [
            synth('Wobble Bass', {
                waveform: 3,
                attack: 0.08,
                decay: 0.3,
                sustain: 0.6,
                release: 0.2,
                filterCutoff: 400,
                filterResonance: 8,
                filterType: 0,
                detune: 0,
                gain: 0.3,
            }),
            delay('Delay', { 'delay-time': 100, 'delay-feedback': 0.2, 'delay-mix': 0.2 }),
        ],
        tags: ['wobble', 'square', 'resonant', 'dubstep'],
        author: AUTHOR,
        isFactory: true,
    },
    {
        id: 'factory-bass-reese',
        name: 'Reese Bass',
        category: 'bass',
        subcategory: 'analog',
        description: 'Thick detuned sawtooth bass with low-end EQ boost. Classic DnB texture.',
        trackKind: 'midi',
        devices: [
            synth('Reese Bass', {
                waveform: 2,
                attack: 0.01,
                decay: 0.2,
                sustain: 0.8,
                release: 0.3,
                filterCutoff: 600,
                filterResonance: 1,
                filterType: 0,
                detune: 15,
                gain: 0.35,
                osc2Waveform: 2,
                osc2Mix: 0.5,
                osc2Detune: -12,
                subOscLevel: 0.3,
            }),
            eq('EQ', { 'eq-low-gain': 6, 'eq-low-freq': 80 }),
        ],
        tags: ['reese', 'detuned', 'dnb', 'thick'],
        author: AUTHOR,
        isFactory: true,
    },
    {
        id: 'factory-bass-acid',
        name: 'Acid Bass',
        category: 'bass',
        subcategory: 'analog',
        description: 'Squelchy sawtooth with high resonance and fast decay. 303-style acid line.',
        trackKind: 'midi',
        devices: [
            synth('Acid Bass', {
                waveform: 2,
                attack: 0.005,
                decay: 0.15,
                sustain: 0.3,
                release: 0.1,
                filterCutoff: 600,
                filterResonance: 12,
                filterType: 0,
                filterEnvAmount: 4000,
                detune: 0,
                gain: 0.3,
            }),
            comp('Compressor', { 'comp-threshold': -12, 'comp-ratio': 5, 'comp-attack': 3, 'comp-release': 60 }),
        ],
        tags: ['acid', '303', 'squelch', 'resonant'],
        author: AUTHOR,
        isFactory: true,
    },
    {
        id: 'factory-bass-filtered',
        name: 'Filtered Bass',
        category: 'bass',
        subcategory: 'digital',
        description: 'Sawtooth bass with resonant lowpass filter sweep.',
        trackKind: 'midi',
        devices: [
            synth('Filtered Bass', {
                waveform: 2,
                attack: 0.005,
                decay: 0.3,
                sustain: 0.6,
                release: 0.15,
                filterCutoff: 500,
                filterResonance: 4,
                filterType: 0,
                detune: 3,
                gain: 0.35,
            }),
            filter('Filter', { 'filter-cutoff': 600, 'filter-resonance': 6, 'filter-type': 0 }),
        ],
        tags: ['filtered', 'sweep', 'resonant', 'bass'],
        author: AUTHOR,
        isFactory: true,
    },
    {
        id: 'factory-bass-bitcrushed',
        name: 'Bitcrushed Bass',
        category: 'bass',
        subcategory: 'digital',
        description: 'Gritty distorted bass with bit reduction for lo-fi textures.',
        trackKind: 'midi',
        devices: [
            synth('Bitcrushed Bass', {
                waveform: 2,
                attack: 0.005,
                decay: 0.2,
                sustain: 0.7,
                release: 0.1,
                filterCutoff: 1200,
                filterResonance: 2,
                filterType: 0,
                detune: 0,
                gain: 0.35,
            }),
            bitcrusher('Bitcrusher', { 'crush-bits': 6, 'crush-mix': 0.6 }),
            comp('Compressor', { 'comp-threshold': -15, 'comp-ratio': 6, 'comp-attack': 3 }),
        ],
        tags: ['bitcrushed', 'gritty', 'lo-fi', 'bass'],
        author: AUTHOR,
        isFactory: true,
    },
];
