/**
 * Expanded factory presets — additional 100+ presets for effects and instruments.
 * These are merged into FACTORY_PRESETS at module load time.
 */
import { type SoundPreset } from '../../models/SoundPreset';

import { bitcrusher } from './presetHelpers/bitcrusher';
import { chorus } from './presetHelpers/chorus';
import { comp } from './presetHelpers/comp';
import { convReverb } from './presetHelpers/convReverb';
import { delay } from './presetHelpers/delay';
import { distortion } from './presetHelpers/distortion';
import { eq } from './presetHelpers/eq';
import { filter } from './presetHelpers/filter';
import { flanger } from './presetHelpers/flanger';
import { AUTHOR } from './presetHelpers/helpers';
import { limiter } from './presetHelpers/limiter';
import { phaser } from './presetHelpers/phaser';
import { reverb } from './presetHelpers/reverb';
import { synth } from './presetHelpers/synth';
import { tremolo } from './presetHelpers/tremolo';

// ── Effect-Only Presets (audio track chains) ─────────────────────────────

export const EXPANDED_FX_PRESETS: SoundPreset[] = [
    // ── EQ Presets ───────────────────────────────────────────────────────
    {
        id: 'fx-eq-vocal-presence',
        name: 'Vocal Presence EQ',
        category: 'fx',
        subcategory: 'eq',
        description: 'Boosts upper mids for vocal clarity and cuts mud at 250Hz.',
        trackKind: 'audio',
        devices: [
            eq('Vocal Presence', {
                'eq-low-gain': -3,
                'eq-low-freq': 250,
                'eq-mid-gain': 4,
                'eq-mid-freq': 3000,
                'eq-mid-q': 1.5,
                'eq-high-gain': 2,
                'eq-high-freq': 10000,
            }),
        ],
        tags: ['vocal', 'presence', 'clarity', 'eq'],
        author: AUTHOR,
        isFactory: true,
    },
    {
        id: 'fx-eq-bass-scoop',
        name: 'Bass Scoop EQ',
        category: 'fx',
        subcategory: 'eq',
        description: 'Classic smiley-face EQ for bass guitars — boosts lows and highs, scoops mids.',
        trackKind: 'audio',
        devices: [
            eq('Bass Scoop', {
                'eq-low-gain': 4,
                'eq-low-freq': 80,
                'eq-mid-gain': -4,
                'eq-mid-freq': 800,
                'eq-mid-q': 0.8,
                'eq-high-gain': 3,
                'eq-high-freq': 5000,
            }),
        ],
        tags: ['bass', 'scoop', 'smiley', 'eq'],
        author: AUTHOR,
        isFactory: true,
    },
    {
        id: 'fx-eq-telephone',
        name: 'Telephone Filter',
        category: 'fx',
        subcategory: 'eq',
        description: 'Bandpass effect simulating old telephone speaker frequency response.',
        trackKind: 'audio',
        devices: [
            eq('Telephone', {
                'eq-low-gain': -12,
                'eq-low-freq': 300,
                'eq-mid-gain': 6,
                'eq-mid-freq': 1500,
                'eq-mid-q': 3,
                'eq-high-gain': -12,
                'eq-high-freq': 3000,
            }),
        ],
        tags: ['telephone', 'lo-fi', 'bandpass', 'effect'],
        author: AUTHOR,
        isFactory: true,
    },
    {
        id: 'fx-eq-high-cut',
        name: 'High Cut (Dark)',
        category: 'fx',
        subcategory: 'eq',
        description: 'Gentle high shelf cut for taming harsh recordings or creating dark ambience.',
        trackKind: 'audio',
        devices: [eq('High Cut', { 'eq-high-gain': -8, 'eq-high-freq': 6000 })],
        tags: ['dark', 'warm', 'high-cut', 'eq'],
        author: AUTHOR,
        isFactory: true,
    },
    {
        id: 'fx-eq-air',
        name: 'Air (Brightness)',
        category: 'fx',
        subcategory: 'eq',
        description: 'Adds sparkle and air in the highest frequencies for modern open sound.',
        trackKind: 'audio',
        devices: [eq('Air', { 'eq-high-gain': 5, 'eq-high-freq': 12000, 'eq-mid-gain': -1, 'eq-mid-freq': 2500 })],
        tags: ['air', 'bright', 'sparkle', 'eq'],
        author: AUTHOR,
        isFactory: true,
    },
    {
        id: 'fx-eq-mid-forward',
        name: 'Mid-Forward Mix',
        category: 'fx',
        subcategory: 'eq',
        description: 'Pushes the mid range forward for cutting through a busy mix.',
        trackKind: 'audio',
        devices: [
            eq('Mid Forward', {
                'eq-low-gain': -2,
                'eq-mid-gain': 5,
                'eq-mid-freq': 2000,
                'eq-mid-q': 1.2,
                'eq-high-gain': -1,
            }),
        ],
        tags: ['mid', 'forward', 'cut-through', 'eq'],
        author: AUTHOR,
        isFactory: true,
    },

    // ── Compressor Presets ───────────────────────────────────────────────
    {
        id: 'fx-comp-vocal-glue',
        name: 'Vocal Glue',
        category: 'fx',
        subcategory: 'dynamics',
        description: 'Gentle compression that evens out vocal dynamics without squashing.',
        trackKind: 'audio',
        devices: [
            comp('Vocal Glue', {
                'comp-threshold': -18,
                'comp-ratio': 3,
                'comp-attack': 15,
                'comp-release': 150,
                'comp-makeup': 3,
            }),
        ],
        tags: ['vocal', 'gentle', 'glue', 'compression'],
        author: AUTHOR,
        isFactory: true,
    },
    {
        id: 'fx-comp-drum-bus',
        name: 'Drum Bus Crush',
        category: 'fx',
        subcategory: 'dynamics',
        description: 'Aggressive bus compression for punchy, glued drum groups.',
        trackKind: 'audio',
        devices: [
            comp('Drum Bus', {
                'comp-threshold': -24,
                'comp-ratio': 6,
                'comp-attack': 5,
                'comp-release': 80,
                'comp-makeup': 6,
            }),
        ],
        tags: ['drums', 'bus', 'punch', 'aggressive'],
        author: AUTHOR,
        isFactory: true,
    },
    {
        id: 'fx-comp-parallel-crush',
        name: 'Parallel Crush',
        category: 'fx',
        subcategory: 'dynamics',
        description: 'Heavy compression designed for blending in parallel — adds density and excitement.',
        trackKind: 'audio',
        devices: [
            comp('Parallel Crush', {
                'comp-threshold': -30,
                'comp-ratio': 10,
                'comp-attack': 1,
                'comp-release': 50,
                'comp-makeup': 10,
            }),
        ],
        tags: ['parallel', 'crush', 'density', 'excitement'],
        author: AUTHOR,
        isFactory: true,
    },
    {
        id: 'fx-comp-gentle-mix',
        name: 'Gentle Mix Comp',
        category: 'fx',
        subcategory: 'dynamics',
        description: 'Transparent master bus style compression — barely noticeable but adds cohesion.',
        trackKind: 'audio',
        devices: [
            comp('Gentle Mix', {
                'comp-threshold': -12,
                'comp-ratio': 2,
                'comp-attack': 30,
                'comp-release': 200,
                'comp-makeup': 1,
            }),
        ],
        tags: ['gentle', 'transparent', 'master', 'cohesion'],
        author: AUTHOR,
        isFactory: true,
    },
    {
        id: 'fx-comp-sidechain-pump',
        name: 'Sidechain Pump',
        category: 'fx',
        subcategory: 'dynamics',
        description: 'Fast attack, slow release compression for the classic EDM pumping effect.',
        trackKind: 'audio',
        devices: [
            comp('SC Pump', {
                'comp-threshold': -28,
                'comp-ratio': 8,
                'comp-attack': 1,
                'comp-release': 300,
                'comp-makeup': 4,
            }),
        ],
        tags: ['sidechain', 'pump', 'edm', 'electronic'],
        author: AUTHOR,
        isFactory: true,
    },

    // ── Reverb Presets ──────────────────────────────────────────────────
    {
        id: 'fx-rev-small-room',
        name: 'Small Room',
        category: 'fx',
        subcategory: 'reverb',
        description: 'Tight, intimate room reverb for natural space without washing out.',
        trackKind: 'audio',
        devices: [reverb('Small Room', { 'rev-size': 0.2, 'rev-decay': 0.6, 'rev-damping': 0.7, 'rev-mix': 0.2 })],
        tags: ['room', 'small', 'tight', 'natural'],
        author: AUTHOR,
        isFactory: true,
    },
    {
        id: 'fx-rev-large-hall',
        name: 'Large Hall',
        category: 'fx',
        subcategory: 'reverb',
        description: 'Big, open hall reverb for levain or cinematic grandeur.',
        trackKind: 'audio',
        devices: [reverb('Large Hall', { 'rev-size': 0.85, 'rev-decay': 4.5, 'rev-damping': 0.3, 'rev-mix': 0.35 })],
        tags: ['hall', 'large', 'levain', 'cinematic'],
        author: AUTHOR,
        isFactory: true,
    },
    {
        id: 'fx-rev-plate',
        name: 'Plate Reverb',
        category: 'fx',
        subcategory: 'reverb',
        description: 'Classic bright plate reverb for vocals and snare drums.',
        trackKind: 'audio',
        devices: [reverb('Plate', { 'rev-size': 0.6, 'rev-decay': 2.2, 'rev-damping': 0.2, 'rev-mix': 0.3 })],
        tags: ['plate', 'bright', 'vocal', 'classic'],
        author: AUTHOR,
        isFactory: true,
    },
    {
        id: 'fx-rev-ambient-wash',
        name: 'Ambient Wash',
        category: 'fx',
        subcategory: 'reverb',
        description: 'Long, dreamy reverb tail for ambient pads and atmospheric textures.',
        trackKind: 'audio',
        devices: [reverb('Ambient Wash', { 'rev-size': 0.95, 'rev-decay': 8, 'rev-damping': 0.15, 'rev-mix': 0.55 })],
        tags: ['ambient', 'dreamy', 'long', 'atmospheric'],
        author: AUTHOR,
        isFactory: true,
    },
    {
        id: 'fx-rev-gated-80s',
        name: 'Gated 80s Reverb',
        category: 'fx',
        subcategory: 'reverb',
        description: 'Short, explosive gated reverb in the style of 80s drum production.',
        trackKind: 'audio',
        devices: [reverb('Gated 80s', { 'rev-size': 0.7, 'rev-decay': 0.3, 'rev-damping': 0.1, 'rev-mix': 0.6 })],
        tags: ['gated', '80s', 'drums', 'explosive'],
        author: AUTHOR,
        isFactory: true,
    },
    {
        id: 'fx-rev-spring',
        name: 'Spring Reverb',
        category: 'fx',
        subcategory: 'reverb',
        description: 'Bright, metallic spring reverb for guitars and vintage character.',
        trackKind: 'audio',
        devices: [reverb('Spring', { 'rev-size': 0.3, 'rev-decay': 1.5, 'rev-damping': 0.15, 'rev-mix': 0.35 })],
        tags: ['spring', 'guitar', 'vintage', 'metallic'],
        author: AUTHOR,
        isFactory: true,
    },

    // ── Convolution Reverb Presets ──────────────────────────────────────
    {
        id: 'fx-conv-studio-room',
        name: 'Studio Room (Conv)',
        category: 'fx',
        subcategory: 'reverb',
        description: 'Tight studio room with natural early reflections — perfect for drums and vocals.',
        trackKind: 'audio',
        devices: [
            convReverb('Studio Room', {
                'conv-ir': 6,
                'conv-mix': 0.25,
                'conv-predelay': 5,
                'conv-lowcut': 80,
                'conv-highcut': 10000,
            }),
        ],
        tags: ['convolution', 'studio', 'room', 'natural'],
        author: AUTHOR,
        isFactory: true,
    },
    {
        id: 'fx-conv-plate-shimmer',
        name: 'Plate Shimmer (Conv)',
        category: 'fx',
        subcategory: 'reverb',
        description: 'Bright, dense plate reverb with extended high-frequency shimmer.',
        trackKind: 'audio',
        devices: [
            convReverb('Plate Shimmer', {
                'conv-ir': 3,
                'conv-mix': 0.35,
                'conv-predelay': 10,
                'conv-lowcut': 100,
                'conv-highcut': 16000,
            }),
        ],
        tags: ['convolution', 'plate', 'shimmer', 'bright'],
        author: AUTHOR,
        isFactory: true,
    },
    {
        id: 'fx-conv-cathedral',
        name: 'Cathedral (Conv)',
        category: 'fx',
        subcategory: 'reverb',
        description: 'Massive cathedral space with 5+ seconds of lush decay — cinematic and epic.',
        trackKind: 'audio',
        devices: [
            convReverb('Cathedral', {
                'conv-ir': 2,
                'conv-mix': 0.4,
                'conv-predelay': 30,
                'conv-lowcut': 40,
                'conv-highcut': 8000,
            }),
        ],
        tags: ['convolution', 'cathedral', 'epic', 'cinematic'],
        author: AUTHOR,
        isFactory: true,
    },
    {
        id: 'fx-conv-vintage-spring',
        name: 'Vintage Spring (Conv)',
        category: 'fx',
        subcategory: 'reverb',
        description: 'Characterful spring reverb emulation with metallic resonance and drip.',
        trackKind: 'audio',
        devices: [
            convReverb('Vintage Spring', {
                'conv-ir': 4,
                'conv-mix': 0.3,
                'conv-predelay': 3,
                'conv-lowcut': 200,
                'conv-highcut': 6000,
            }),
        ],
        tags: ['convolution', 'spring', 'vintage', 'guitar'],
        author: AUTHOR,
        isFactory: true,
    },
    {
        id: 'fx-conv-warehouse',
        name: 'Abandoned Warehouse (Conv)',
        category: 'fx',
        subcategory: 'reverb',
        description: 'Cavernous industrial warehouse with long, diffuse reflections.',
        trackKind: 'audio',
        devices: [
            convReverb('Warehouse', {
                'conv-ir': 8,
                'conv-mix': 0.35,
                'conv-predelay': 50,
                'conv-lowcut': 50,
                'conv-highcut': 7000,
            }),
        ],
        tags: ['convolution', 'warehouse', 'industrial', 'cavernous'],
        author: AUTHOR,
        isFactory: true,
    },
    {
        id: 'fx-conv-dark-tunnel',
        name: 'Dark Tunnel (Conv)',
        category: 'fx',
        subcategory: 'reverb',
        description: 'Narrow tunnel reverb with resonant low-mids and dark character.',
        trackKind: 'audio',
        devices: [
            convReverb('Dark Tunnel', {
                'conv-ir': 9,
                'conv-mix': 0.3,
                'conv-predelay': 20,
                'conv-lowcut': 30,
                'conv-highcut': 5000,
            }),
        ],
        tags: ['convolution', 'tunnel', 'dark', 'narrow'],
        author: AUTHOR,
        isFactory: true,
    },

    // ── Delay Presets ───────────────────────────────────────────────────
    {
        id: 'fx-delay-slapback',
        name: 'Slapback Delay',
        category: 'fx',
        subcategory: 'delay',
        description: 'Short 80ms slapback for rockabilly vocals and guitars.',
        trackKind: 'audio',
        devices: [delay('Slapback', { 'delay-time': 80, 'delay-feedback': 0, 'delay-mix': 0.35 })],
        tags: ['slapback', 'short', 'vocal', 'guitar'],
        author: AUTHOR,
        isFactory: true,
    },
    {
        id: 'fx-delay-dotted-eighth',
        name: 'Dotted Eighth',
        category: 'fx',
        subcategory: 'delay',
        description: 'Rhythmic dotted eighth note delay for The Edge-style guitar textures.',
        trackKind: 'audio',
        devices: [delay('Dotted 8th', { 'delay-time': 375, 'delay-feedback': 0.35, 'delay-mix': 0.25 })],
        tags: ['dotted', 'eighth', 'rhythmic', 'guitar'],
        author: AUTHOR,
        isFactory: true,
    },
    {
        id: 'fx-delay-ping-pong',
        name: 'Ping Pong',
        category: 'fx',
        subcategory: 'delay',
        description: 'Stereo ping-pong delay bouncing left to right for width and movement.',
        trackKind: 'audio',
        devices: [delay('Ping Pong', { 'delay-time': 300, 'delay-feedback': 0.45, 'delay-mix': 0.3 })],
        tags: ['ping-pong', 'stereo', 'width', 'movement'],
        author: AUTHOR,
        isFactory: true,
    },
    {
        id: 'fx-delay-dub-echo',
        name: 'Dub Echo',
        category: 'fx',
        subcategory: 'delay',
        description: 'Long feedback delay with filtering for classic dub reggae textures.',
        trackKind: 'audio',
        devices: [
            delay('Dub Echo', { 'delay-time': 500, 'delay-feedback': 0.65, 'delay-mix': 0.3 }),
            eq('Dub Filter', { 'eq-high-gain': -6, 'eq-high-freq': 4000, 'eq-low-gain': -3, 'eq-low-freq': 150 }),
        ],
        tags: ['dub', 'echo', 'reggae', 'long'],
        author: AUTHOR,
        isFactory: true,
    },

    // ── Modulation FX Presets ────────────────────────────────────────────
    {
        id: 'fx-chorus-classic',
        name: 'Classic Chorus',
        category: 'fx',
        subcategory: 'modulation',
        description: 'Warm, lush chorus like the Roland Dimension D — thickens any source.',
        trackKind: 'audio',
        devices: [
            chorus('Classic Chorus', {
                'chorus-rate': 0.8,
                'chorus-depth': 5,
                'chorus-feedback': 0.15,
                'chorus-mix': 0.4,
            }),
        ],
        tags: ['chorus', 'classic', 'lush', 'warm'],
        author: AUTHOR,
        isFactory: true,
    },
    {
        id: 'fx-chorus-slow-shimmer',
        name: 'Slow Shimmer',
        category: 'fx',
        subcategory: 'modulation',
        description: 'Ultra-slow, deep chorus for pads and strings — creates a shimmering width.',
        trackKind: 'audio',
        devices: [
            chorus('Slow Shimmer', {
                'chorus-rate': 0.2,
                'chorus-depth': 10,
                'chorus-feedback': 0.3,
                'chorus-mix': 0.5,
            }),
        ],
        tags: ['shimmer', 'slow', 'deep', 'pad'],
        author: AUTHOR,
        isFactory: true,
    },
    {
        id: 'fx-phaser-slow-sweep',
        name: 'Slow Phaser Sweep',
        category: 'fx',
        subcategory: 'modulation',
        description: 'Slow, deep phaser sweep for psychedelic guitar or synth pad textures.',
        trackKind: 'audio',
        devices: [
            phaser('Slow Sweep', {
                'phaser-rate': 0.15,
                'phaser-depth': 0.8,
                'phaser-feedback': 0.6,
                'phaser-stages': 6,
            }),
        ],
        tags: ['phaser', 'slow', 'psychedelic', 'sweep'],
        author: AUTHOR,
        isFactory: true,
    },
    {
        id: 'fx-flanger-jet',
        name: 'Jet Flanger',
        category: 'fx',
        subcategory: 'modulation',
        description: 'Metallic jet flyby effect with high feedback — dramatic and aggressive.',
        trackKind: 'audio',
        devices: [
            flanger('Jet Flanger', {
                'flanger-rate': 0.15,
                'flanger-depth': 8,
                'flanger-feedback': 0.85,
                'flanger-mix': 0.6,
            }),
        ],
        tags: ['jet', 'flanger', 'metallic', 'aggressive'],
        author: AUTHOR,
        isFactory: true,
    },
    {
        id: 'fx-trem-vintage',
        name: 'Vintage Tremolo',
        category: 'fx',
        subcategory: 'modulation',
        description: 'Classic tube-amp tremolo at medium speed for vintage guitar tones.',
        trackKind: 'audio',
        devices: [tremolo('Vintage Trem', { 'trem-rate': 5, 'trem-depth': 0.7, 'trem-shape': 0 })],
        tags: ['tremolo', 'vintage', 'guitar', 'classic'],
        author: AUTHOR,
        isFactory: true,
    },
    {
        id: 'fx-leslie-sim',
        name: 'Leslie Simulator',
        category: 'fx',
        subcategory: 'modulation',
        description: 'Simulated Leslie rotary speaker combining chorus, tremolo, and phasing.',
        trackKind: 'audio',
        devices: [
            chorus('Leslie Chorus', {
                'chorus-rate': 5.5,
                'chorus-depth': 4,
                'chorus-feedback': 0.1,
                'chorus-mix': 0.3,
            }),
            tremolo('Leslie Trem', { 'trem-rate': 6, 'trem-depth': 0.3, 'trem-shape': 0 }),
        ],
        tags: ['leslie', 'rotary', 'organ', 'speaker'],
        author: AUTHOR,
        isFactory: true,
    },

    // ── Distortion / Lo-Fi Presets ──────────────────────────────────────
    {
        id: 'fx-dist-warm-overdrive',
        name: 'Warm Overdrive',
        category: 'fx',
        subcategory: 'distortion',
        description: 'Mild tube-style overdrive that adds warmth and harmonics without harshness.',
        trackKind: 'audio',
        devices: [distortion('Warm OD', { 'dist-drive': 3, 'dist-tone': 4000, 'dist-mix': 0.4 })],
        tags: ['overdrive', 'warm', 'tube', 'subtle'],
        author: AUTHOR,
        isFactory: true,
    },
    {
        id: 'fx-dist-fuzz',
        name: 'Fuzz Box',
        category: 'fx',
        subcategory: 'distortion',
        description: 'Aggressive fuzz distortion for heavy guitar or synth leads.',
        trackKind: 'audio',
        devices: [distortion('Fuzz', { 'dist-drive': 9, 'dist-tone': 3000, 'dist-mix': 0.7 })],
        tags: ['fuzz', 'heavy', 'aggressive', 'guitar'],
        author: AUTHOR,
        isFactory: true,
    },
    {
        id: 'fx-lofi-vinyl',
        name: 'Lo-Fi Vinyl',
        category: 'fx',
        subcategory: 'lofi',
        description: 'Vinyl-style lo-fi with bitcrushing, filtering, and subtle noise texture.',
        trackKind: 'audio',
        devices: [
            bitcrusher('Vinyl Crunch', { 'crush-bits': 12, 'crush-rate': 0.8, 'crush-mix': 0.25 }),
            eq('Vinyl EQ', { 'eq-low-gain': -2, 'eq-high-gain': -5, 'eq-high-freq': 8000 }),
        ],
        tags: ['lo-fi', 'vinyl', 'retro', 'chill'],
        author: AUTHOR,
        isFactory: true,
    },
    {
        id: 'fx-lofi-retro-radio',
        name: 'Retro Radio',
        category: 'fx',
        subcategory: 'lofi',
        description: 'Old transistor radio simulation with bandpass filter and bitcrushing.',
        trackKind: 'audio',
        devices: [
            bitcrusher('Radio Bits', { 'crush-bits': 10, 'crush-rate': 0.6, 'crush-mix': 0.3 }),
            eq('Radio Band', {
                'eq-low-gain': -10,
                'eq-low-freq': 400,
                'eq-mid-gain': 5,
                'eq-mid-freq': 1800,
                'eq-mid-q': 3,
                'eq-high-gain': -10,
                'eq-high-freq': 3500,
            }),
        ],
        tags: ['radio', 'retro', 'lo-fi', 'bandpass'],
        author: AUTHOR,
        isFactory: true,
    },

    // ── Mix Bus / Mastering Chains ──────────────────────────────────────
    {
        id: 'fx-chain-vocal-strip',
        name: 'Vocal Channel Strip',
        category: 'fx',
        subcategory: 'channel-strip',
        description: 'Complete vocal chain: EQ for clarity, compression for consistency, reverb for space.',
        trackKind: 'audio',
        devices: [
            eq('Vocal EQ', {
                'eq-low-gain': -4,
                'eq-low-freq': 120,
                'eq-mid-gain': 3,
                'eq-mid-freq': 3000,
                'eq-mid-q': 1.5,
                'eq-high-gain': 2,
                'eq-high-freq': 10000,
            }),
            comp('Vocal Comp', {
                'comp-threshold': -18,
                'comp-ratio': 3,
                'comp-attack': 10,
                'comp-release': 120,
                'comp-makeup': 3,
            }),
            reverb('Vocal Space', { 'rev-size': 0.4, 'rev-decay': 1.5, 'rev-damping': 0.5, 'rev-mix': 0.15 }),
        ],
        tags: ['vocal', 'channel-strip', 'complete', 'mixing'],
        author: AUTHOR,
        isFactory: true,
    },
    {
        id: 'fx-chain-guitar-clean',
        name: 'Clean Guitar Strip',
        category: 'fx',
        subcategory: 'channel-strip',
        description: 'Clean guitar chain: warm EQ, light compression, chorus, and spring reverb.',
        trackKind: 'audio',
        devices: [
            eq('Guitar EQ', {
                'eq-low-gain': -2,
                'eq-low-freq': 100,
                'eq-mid-gain': 2,
                'eq-mid-freq': 1500,
                'eq-high-gain': 1,
                'eq-high-freq': 6000,
            }),
            comp('Light Comp', {
                'comp-threshold': -15,
                'comp-ratio': 2.5,
                'comp-attack': 20,
                'comp-release': 150,
                'comp-makeup': 2,
            }),
            chorus('Guitar Chorus', { 'chorus-rate': 0.6, 'chorus-depth': 4, 'chorus-mix': 0.25 }),
            reverb('Spring', { 'rev-size': 0.3, 'rev-decay': 1.5, 'rev-damping': 0.2, 'rev-mix': 0.25 }),
        ],
        tags: ['guitar', 'clean', 'channel-strip', 'warm'],
        author: AUTHOR,
        isFactory: true,
    },
    {
        id: 'fx-chain-master-bus',
        name: 'Master Bus Polish',
        category: 'fx',
        subcategory: 'mastering',
        description: 'Subtle master bus chain: gentle EQ shaping, glue compression, and limiting.',
        trackKind: 'audio',
        devices: [
            eq('Master EQ', {
                'eq-low-gain': 1,
                'eq-low-freq': 60,
                'eq-mid-gain': -1,
                'eq-mid-freq': 350,
                'eq-high-gain': 1.5,
                'eq-high-freq': 12000,
            }),
            comp('Bus Glue', {
                'comp-threshold': -12,
                'comp-ratio': 2,
                'comp-attack': 30,
                'comp-release': 250,
                'comp-makeup': 1,
            }),
            // 150 ms, not 0.15 s — see the unit note in the `limiter` helper.
            limiter('Brick Wall', { 'lim-threshold': -1, 'lim-release': 150 }),
        ],
        tags: ['mastering', 'bus', 'polish', 'limiter'],
        author: AUTHOR,
        isFactory: true,
    },
    {
        id: 'fx-chain-drum-punch',
        name: 'Drum Punch Strip',
        category: 'fx',
        subcategory: 'channel-strip',
        description: 'Drum processing chain: transient-enhancing EQ, fast compression, and tight room.',
        trackKind: 'audio',
        devices: [
            eq('Drum EQ', {
                'eq-low-gain': 3,
                'eq-low-freq': 80,
                'eq-mid-gain': 2,
                'eq-mid-freq': 4000,
                'eq-mid-q': 2,
                'eq-high-gain': 1,
                'eq-high-freq': 10000,
            }),
            comp('Drum Punch', {
                'comp-threshold': -20,
                'comp-ratio': 5,
                'comp-attack': 3,
                'comp-release': 60,
                'comp-makeup': 4,
            }),
            reverb('Tight Room', { 'rev-size': 0.15, 'rev-decay': 0.4, 'rev-damping': 0.7, 'rev-mix': 0.1 }),
        ],
        tags: ['drums', 'punch', 'transient', 'channel-strip'],
        author: AUTHOR,
        isFactory: true,
    },

    // ── Creative FX Presets ──────────────────────────────────────────────
    {
        id: 'fx-creative-space-echo',
        name: 'Space Echo',
        category: 'fx',
        subcategory: 'creative',
        description: 'Modulated delay with reverb tail creating expansive space textures.',
        trackKind: 'audio',
        devices: [
            delay('Space Delay', { 'delay-time': 400, 'delay-feedback': 0.55, 'delay-mix': 0.35 }),
            chorus('Mod Wash', { 'chorus-rate': 0.3, 'chorus-depth': 6, 'chorus-mix': 0.2 }),
            reverb('Space Tail', { 'rev-size': 0.9, 'rev-decay': 5, 'rev-damping': 0.2, 'rev-mix': 0.4 }),
        ],
        tags: ['space', 'echo', 'ambient', 'creative'],
        author: AUTHOR,
        isFactory: true,
    },
    {
        id: 'fx-creative-shimmer',
        name: 'Shimmer Reverb',
        category: 'fx',
        subcategory: 'creative',
        description: 'Reverb with octave-up pitch shifting for ethereal, ambient textures.',
        trackKind: 'audio',
        devices: [
            reverb('Shimmer', { 'rev-size': 0.95, 'rev-decay': 7, 'rev-damping': 0.1, 'rev-mix': 0.5 }),
            eq('Shimmer Bright', { 'eq-high-gain': 4, 'eq-high-freq': 8000, 'eq-low-gain': -3 }),
            chorus('Detune', { 'chorus-rate': 0.1, 'chorus-depth': 12, 'chorus-mix': 0.3 }),
        ],
        tags: ['shimmer', 'ethereal', 'ambient', 'creative'],
        author: AUTHOR,
        isFactory: true,
    },
    {
        id: 'fx-creative-industrial',
        name: 'Industrial Crush',
        category: 'fx',
        subcategory: 'creative',
        description: 'Aggressive bitcrushing, distortion, and filtering for harsh industrial textures.',
        trackKind: 'audio',
        devices: [
            distortion('Industrial', { 'dist-drive': 8, 'dist-tone': 2500, 'dist-mix': 0.6 }),
            bitcrusher('Crush', { 'crush-bits': 6, 'crush-rate': 0.4, 'crush-mix': 0.5 }),
            filter('Resonant', { 'filter-cutoff': 2000, 'filter-resonance': 5, 'filter-type': 0 }),
        ],
        tags: ['industrial', 'harsh', 'noise', 'creative'],
        author: AUTHOR,
        isFactory: true,
    },
];

// ── Synth Instrument Presets ─────────────────────────────────────────────

export const EXPANDED_SYNTH_PRESETS: SoundPreset[] = [
    // ── Pads ────────────────────────────────────────────────────────────
    {
        id: 'synth-pad-warm-strings',
        name: 'Warm Strings Pad',
        category: 'pad',
        subcategory: 'analog',
        description: 'Slow, evolving string-like pad with chorus for cinematic warmth.',
        trackKind: 'midi',
        devices: [
            synth('Warm Strings', {
                waveform: 2,
                attack: 0.8,
                decay: 0.5,
                sustain: 0.7,
                release: 2,
                filterCutoff: 2000,
                filterResonance: 0.5,
                filterType: 0,
                detune: 8,
                gain: 0.25,
            }),
            chorus('Pad Chorus', { 'chorus-rate': 0.5, 'chorus-depth': 8, 'chorus-mix': 0.35 }),
            reverb('Pad Space', { 'rev-size': 0.8, 'rev-decay': 4, 'rev-mix': 0.3 }),
        ],
        tags: ['pad', 'strings', 'warm', 'cinematic'],
        author: AUTHOR,
        isFactory: true,
    },
    {
        id: 'synth-pad-ethereal',
        name: 'Ethereal Pad',
        category: 'pad',
        subcategory: 'atmospheric',
        description: 'Shimmering, high-frequency pad with long release for ambient soundscapes.',
        trackKind: 'midi',
        devices: [
            synth('Ethereal', {
                waveform: 0,
                attack: 1.5,
                decay: 1,
                sustain: 0.6,
                release: 4,
                filterCutoff: 6000,
                filterResonance: 1.5,
                filterType: 0,
                detune: 12,
                gain: 0.2,
                subOscLevel: 0.3,
            }),
            chorus('Shimmer', { 'chorus-rate': 0.2, 'chorus-depth': 12, 'chorus-mix': 0.4 }),
            reverb('Vast', { 'rev-size': 0.95, 'rev-decay': 8, 'rev-damping': 0.1, 'rev-mix': 0.5 }),
        ],
        tags: ['pad', 'ethereal', 'ambient', 'shimmer'],
        author: AUTHOR,
        isFactory: true,
    },
    {
        id: 'synth-pad-dark-drone',
        name: 'Dark Drone',
        category: 'pad',
        subcategory: 'atmospheric',
        description: 'Low, ominous drone pad for dark ambient and cinematic tension.',
        trackKind: 'midi',
        devices: [
            synth('Dark Drone', {
                waveform: 2,
                attack: 2,
                decay: 1,
                sustain: 0.8,
                release: 3,
                filterCutoff: 500,
                filterResonance: 2,
                filterType: 0,
                detune: 15,
                gain: 0.3,
                subOscLevel: 0.5,
            }),
            phaser('Dark Phase', { 'phaser-rate': 0.05, 'phaser-depth': 0.9, 'phaser-feedback': 0.7 }),
            reverb('Cavern', { 'rev-size': 0.9, 'rev-decay': 6, 'rev-damping': 0.6, 'rev-mix': 0.4 }),
        ],
        tags: ['drone', 'dark', 'ominous', 'cinematic'],
        author: AUTHOR,
        isFactory: true,
    },

    // ── Leads ───────────────────────────────────────────────────────────
    {
        id: 'synth-lead-screamer',
        name: 'Screamer Lead',
        category: 'lead',
        subcategory: 'aggressive',
        description: 'High-gain resonant lead that cuts through any mix with aggressive filter sweep.',
        trackKind: 'midi',
        devices: [
            synth('Screamer', {
                waveform: 2,
                attack: 0.01,
                decay: 0.2,
                sustain: 0.7,
                release: 0.2,
                filterCutoff: 4000,
                filterResonance: 6,
                filterType: 0,
                detune: 5,
                gain: 0.3,
                filterEnvAmount: 3000,
            }),
            distortion('Lead Drive', { 'dist-drive': 4, 'dist-tone': 5000, 'dist-mix': 0.3 }),
        ],
        tags: ['lead', 'aggressive', 'screamer', 'resonant'],
        author: AUTHOR,
        isFactory: true,
    },
    {
        id: 'synth-lead-liquid',
        name: 'Liquid Lead',
        category: 'lead',
        subcategory: 'smooth',
        description: 'Smooth, singing lead with portamento feel — great for melodic lines.',
        trackKind: 'midi',
        devices: [
            synth('Liquid', {
                waveform: 1,
                attack: 0.05,
                decay: 0.3,
                sustain: 0.6,
                release: 0.5,
                filterCutoff: 3000,
                filterResonance: 2,
                filterType: 0,
                gain: 0.3,
            }),
            delay('Lead Echo', { 'delay-time': 200, 'delay-feedback': 0.2, 'delay-mix': 0.15 }),
            reverb('Lead Space', { 'rev-size': 0.4, 'rev-decay': 1.5, 'rev-mix': 0.2 }),
        ],
        tags: ['lead', 'smooth', 'liquid', 'melodic'],
        author: AUTHOR,
        isFactory: true,
    },
    {
        id: 'synth-lead-retro-sync',
        name: 'Retro Sync Lead',
        category: 'lead',
        subcategory: 'analog',
        description: 'Hard-sync style lead with nasal, biting character for retro synth lines.',
        trackKind: 'midi',
        devices: [
            synth('Retro Sync', {
                waveform: 3,
                attack: 0.005,
                decay: 0.15,
                sustain: 0.5,
                release: 0.15,
                filterCutoff: 5000,
                filterResonance: 3,
                filterType: 0,
                detune: 20,
                osc2Waveform: 2,
                osc2Mix: 0.4,
                gain: 0.25,
            }),
        ],
        tags: ['lead', 'retro', 'sync', 'biting'],
        author: AUTHOR,
        isFactory: true,
    },

    // ── Bass ────────────────────────────────────────────────────────────
    {
        id: 'synth-bass-reese',
        name: 'Reese Bass',
        category: 'bass',
        subcategory: 'electronic',
        description: 'Detuned saw bass with phaser movement — classic D&B and dubstep foundation.',
        trackKind: 'midi',
        devices: [
            synth('Reese', {
                waveform: 2,
                attack: 0.01,
                decay: 0.3,
                sustain: 0.8,
                release: 0.3,
                filterCutoff: 800,
                filterResonance: 2,
                filterType: 0,
                detune: 25,
                gain: 0.35,
            }),
            phaser('Reese Phase', { 'phaser-rate': 0.1, 'phaser-depth': 0.8, 'phaser-feedback': 0.5 }),
        ],
        tags: ['bass', 'reese', 'dnb', 'dubstep'],
        author: AUTHOR,
        isFactory: true,
    },
    {
        id: 'synth-bass-808-sine',
        name: '808 Sub Sine',
        category: 'bass',
        subcategory: 'electronic',
        description: 'Pure sine sub bass with pitch envelope for trap and hip-hop 808 hits.',
        trackKind: 'midi',
        devices: [
            synth('808 Sine', {
                waveform: 0,
                attack: 0.005,
                decay: 0.8,
                sustain: 0.3,
                release: 0.8,
                filterCutoff: 150,
                filterType: 0,
                gain: 0.45,
                subOscLevel: 0,
            }),
        ],
        tags: ['808', 'sub', 'trap', 'hip-hop'],
        author: AUTHOR,
        isFactory: true,
    },
    {
        id: 'synth-bass-acid',
        name: 'Acid Bass',
        category: 'bass',
        subcategory: 'electronic',
        description: 'Classic 303-style acid bass with resonant filter sweep and short decay.',
        trackKind: 'midi',
        devices: [
            synth('Acid', {
                waveform: 2,
                attack: 0.001,
                decay: 0.2,
                sustain: 0.1,
                release: 0.1,
                filterCutoff: 600,
                filterResonance: 8,
                filterType: 0,
                filterEnvAmount: 4000,
                gain: 0.3,
            }),
            distortion('Acid OD', { 'dist-drive': 3, 'dist-tone': 3000, 'dist-mix': 0.2 }),
        ],
        tags: ['acid', '303', 'squelch', 'resonant'],
        author: AUTHOR,
        isFactory: true,
    },

    // ── Keys ────────────────────────────────────────────────────────────
    {
        id: 'synth-keys-electric-piano',
        name: 'Electric Piano',
        category: 'keys',
        subcategory: 'electric',
        description: 'Rhodes-like electric piano with tremolo and subtle chorus warmth.',
        trackKind: 'midi',
        devices: [
            synth('E-Piano', {
                waveform: 0,
                attack: 0.005,
                decay: 1.5,
                sustain: 0.3,
                release: 0.8,
                filterCutoff: 3000,
                filterResonance: 0.5,
                filterType: 0,
                gain: 0.3,
            }),
            tremolo('EP Trem', { 'trem-rate': 3.5, 'trem-depth': 0.25, 'trem-shape': 0 }),
            chorus('EP Chorus', { 'chorus-rate': 0.4, 'chorus-depth': 3, 'chorus-mix': 0.2 }),
        ],
        tags: ['electric', 'piano', 'rhodes', 'keys'],
        author: AUTHOR,
        isFactory: true,
    },
    {
        id: 'synth-keys-wurlitzer',
        name: 'Wurlitzer',
        category: 'keys',
        subcategory: 'electric',
        description: 'Bright, barky Wurlitzer-style electric piano with tremolo.',
        trackKind: 'midi',
        devices: [
            synth('Wurli', {
                waveform: 1,
                attack: 0.003,
                decay: 1,
                sustain: 0.2,
                release: 0.5,
                filterCutoff: 4000,
                filterResonance: 1.5,
                filterType: 0,
                gain: 0.3,
            }),
            tremolo('Wurli Trem', { 'trem-rate': 5, 'trem-depth': 0.5, 'trem-shape': 0 }),
        ],
        tags: ['wurlitzer', 'electric', 'piano', 'barky'],
        author: AUTHOR,
        isFactory: true,
    },
    {
        id: 'synth-keys-clavinet',
        name: 'Clavinet',
        category: 'keys',
        subcategory: 'electric',
        description: 'Funky clavinet-style tone with sharp attack and wah-like filter.',
        trackKind: 'midi',
        devices: [
            synth('Clav', {
                waveform: 3,
                attack: 0.001,
                decay: 0.5,
                sustain: 0.1,
                release: 0.15,
                filterCutoff: 5000,
                filterResonance: 3,
                filterType: 0,
                filterEnvAmount: 2000,
                gain: 0.25,
            }),
            phaser('Wah', { 'phaser-rate': 0.3, 'phaser-depth': 0.6, 'phaser-feedback': 0.4 }),
        ],
        tags: ['clavinet', 'funky', 'wah', 'percussive'],
        author: AUTHOR,
        isFactory: true,
    },

    // ── Arps & Sequences ────────────────────────────────────────────────
    {
        id: 'synth-arp-crystal',
        name: 'Crystal Arp',
        category: 'synth',
        subcategory: 'arp',
        description: 'Bright, glassy arp sound with short decay and long delay tail.',
        trackKind: 'midi',
        devices: [
            synth('Crystal', {
                waveform: 1,
                attack: 0.001,
                decay: 0.3,
                sustain: 0.05,
                release: 0.2,
                filterCutoff: 8000,
                filterResonance: 1,
                filterType: 0,
                gain: 0.25,
            }),
            delay('Arp Delay', { 'delay-time': 188, 'delay-feedback': 0.45, 'delay-mix': 0.3 }),
            reverb('Arp Space', { 'rev-size': 0.6, 'rev-decay': 2, 'rev-mix': 0.2 }),
        ],
        tags: ['arp', 'crystal', 'bright', 'glassy'],
        author: AUTHOR,
        isFactory: true,
    },
    {
        id: 'synth-arp-dark-pulse',
        name: 'Dark Pulse',
        category: 'synth',
        subcategory: 'arp',
        description: 'Short, dark pulsing sound for techno and electronic sequences.',
        trackKind: 'midi',
        devices: [
            synth('Dark Pulse', {
                waveform: 3,
                attack: 0.001,
                decay: 0.15,
                sustain: 0,
                release: 0.1,
                filterCutoff: 1200,
                filterResonance: 3,
                filterType: 0,
                gain: 0.3,
            }),
            delay('Pulse Echo', { 'delay-time': 125, 'delay-feedback': 0.3, 'delay-mix': 0.2 }),
        ],
        tags: ['pulse', 'dark', 'techno', 'sequence'],
        author: AUTHOR,
        isFactory: true,
    },

    // ── SFX / Textures ──────────────────────────────────────────────────
    {
        id: 'synth-sfx-noise-sweep',
        name: 'Noise Sweep',
        category: 'synth',
        subcategory: 'texture',
        description: 'Filtered noise sweep for risers, transitions, and impact effects.',
        trackKind: 'midi',
        devices: [
            synth('Noise', {
                waveform: 0,
                attack: 2,
                decay: 0.5,
                sustain: 0.8,
                release: 1,
                filterCutoff: 200,
                filterResonance: 4,
                filterType: 0,
                filterEnvAmount: 8000,
                gain: 0.2,
                noiseLevel: 0.8,
            }),
            reverb('Riser Space', { 'rev-size': 0.8, 'rev-decay': 3, 'rev-mix': 0.4 }),
        ],
        tags: ['noise', 'sweep', 'riser', 'transition'],
        author: AUTHOR,
        isFactory: true,
    },
    {
        id: 'synth-sfx-glitch-pluck',
        name: 'Glitch Pluck',
        category: 'synth',
        subcategory: 'digital',
        description: 'Short glitchy pluck sound with bitcrushing for electronic productions.',
        trackKind: 'midi',
        devices: [
            synth('Glitch', {
                waveform: 3,
                attack: 0.001,
                decay: 0.08,
                sustain: 0,
                release: 0.05,
                filterCutoff: 6000,
                filterResonance: 4,
                filterType: 0,
                gain: 0.25,
            }),
            bitcrusher('Glitch Crush', { 'crush-bits': 8, 'crush-rate': 0.5, 'crush-mix': 0.4 }),
        ],
        tags: ['glitch', 'pluck', 'digital', 'electronic'],
        author: AUTHOR,
        isFactory: true,
    },
];
