import { type SoundPreset } from '../../models/SoundPreset';

import { chorus } from './presetHelpers/chorus';
import { eq } from './presetHelpers/eq';
import { AUTHOR } from './presetHelpers/helpers';
import { reverb } from './presetHelpers/reverb';
import { synth } from './presetHelpers/synth';

export const keysPresets: SoundPreset[] = [
    // ─── Keys ────────────────────────────────────────────────────────────
    {
        id: 'factory-keys-organ',
        name: 'Organ',
        category: 'keys',
        subcategory: 'analog',
        description: 'Full-bodied square wave organ with sustain and a hint of room reverb.',
        trackKind: 'midi',
        devices: [
            synth('Organ', {
                waveform: 3,
                attack: 0.001,
                decay: 0.1,
                sustain: 1.0,
                release: 0.1,
                filterCutoff: 5000,
                filterResonance: 0.5,
                filterType: 0,
                detune: 0,
                gain: 0.25,
                osc2Waveform: 0,
                osc2Mix: 0.3,
                osc2Detune: 0,
                subOscLevel: 0.2,
            }),
            reverb('Reverb', { 'rev-size': 0.3, 'rev-decay': 1.0, 'rev-mix': 0.15 }),
            chorus('Chorus', { 'chorus-rate': 2.0, 'chorus-depth': 4, 'chorus-mix': 0.2 }),
        ],
        tags: ['organ', 'sustained', 'square', 'classic'],
        author: AUTHOR,
        isFactory: true,
    },
    {
        id: 'factory-keys-pluck',
        name: 'Pluck',
        category: 'keys',
        subcategory: 'digital',
        description: 'Snappy triangle pluck with very short decay. Percussive and clean.',
        trackKind: 'midi',
        devices: [
            synth('Pluck', {
                waveform: 1,
                attack: 0.001,
                decay: 0.15,
                sustain: 0.1,
                release: 0.1,
                filterCutoff: 2000,
                filterResonance: 1,
                filterType: 0,
                filterEnvAmount: 5000,
                detune: 0,
                gain: 0.3,
                noiseLevel: 0.1,
            }),
            reverb('Room', { 'rev-size': 0.3, 'rev-decay': 1.2, 'rev-mix': 0.2 }),
            chorus('Chorus', { 'chorus-rate': 0.8, 'chorus-depth': 4, 'chorus-mix': 0.2 }),
        ],
        tags: ['pluck', 'percussive', 'short', 'triangle'],
        author: AUTHOR,
        isFactory: true,
    },
    {
        id: 'factory-keys-bell',
        name: 'Bell',
        category: 'keys',
        subcategory: 'digital',
        description: 'Pure sine bell with long decay and no sustain. Crystalline tone with reverb.',
        trackKind: 'midi',
        devices: [
            synth('Bell', {
                waveform: 0,
                attack: 0.001,
                decay: 1.5,
                sustain: 0.0,
                release: 0.5,
                filterCutoff: 4000,
                filterResonance: 0.5,
                filterType: 0,
                filterEnvAmount: 6000,
                detune: 0,
                gain: 0.25,
                osc2Waveform: 0,
                osc2Mix: 0.3,
                osc2Detune: 700,
            }),
            reverb('Reverb', { 'rev-size': 0.5, 'rev-decay': 3, 'rev-mix': 0.3 }),
            chorus('Shimmer', { 'chorus-rate': 0.4, 'chorus-depth': 5, 'chorus-mix': 0.2 }),
        ],
        tags: ['bell', 'sine', 'crystalline', 'percussive'],
        author: AUTHOR,
        isFactory: true,
    },
    {
        id: 'factory-keys-marimba',
        name: 'Marimba',
        category: 'keys',
        subcategory: 'acoustic',
        description: 'Warm sine marimba with short decay. Woody, mallet-like character.',
        trackKind: 'midi',
        devices: [
            synth('Marimba', {
                waveform: 0,
                attack: 0.001,
                decay: 0.3,
                sustain: 0.0,
                release: 0.15,
                filterCutoff: 3000,
                filterResonance: 0.5,
                filterType: 0,
                filterEnvAmount: 4000,
                detune: 0,
                gain: 0.3,
                noiseLevel: 0.08,
            }),
            reverb('Room', { 'rev-size': 0.35, 'rev-decay': 1.5, 'rev-mix': 0.2 }),
            eq('Body', { 'eq-low-gain': 2, 'eq-low-freq': 200, 'eq-high-gain': 3, 'eq-high-freq': 5000 }),
        ],
        tags: ['marimba', 'mallet', 'percussive', 'acoustic'],
        author: AUTHOR,
        isFactory: true,
    },
];
