import { type SoundPreset } from '../../models/SoundPreset';
import { synth } from './presetHelpers/synth';
import { reverb } from './presetHelpers/reverb';
import { delay } from './presetHelpers/delay';
import { eq } from './presetHelpers/eq';
import { flanger } from './presetHelpers/flanger';
import { bitcrusher } from './presetHelpers/bitcrusher';
import { tremolo } from './presetHelpers/tremolo';
import { autopan } from './presetHelpers/autopan';
import { AUTHOR } from './presetHelpers/helpers';

export const leadPresets: SoundPreset[] = [
    // ─── Lead ────────────────────────────────────────────────────────────
    {
        id: 'factory-lead-classic',
        name: 'Classic Lead',
        category: 'lead',
        subcategory: 'analog',
        description: 'Warm sawtooth lead with delay. Versatile mono-style synth lead.',
        trackKind: 'midi',
        devices: [
            synth('Classic Lead', {
                waveform: 2,
                attack: 0.05,
                decay: 0.2,
                sustain: 0.7,
                release: 0.3,
                filterCutoff: 3000,
                filterResonance: 1,
                filterType: 0,
                detune: 0,
                gain: 0.3,
            }),
            delay('Delay', { 'delay-time': 250, 'delay-feedback': 0.3, 'delay-mix': 0.25 }),
            reverb('Reverb', { 'rev-size': 0.4, 'rev-decay': 1.8, 'rev-mix': 0.2 }),
        ],
        tags: ['classic', 'sawtooth', 'delay', 'mono'],
        author: AUTHOR,
        isFactory: true,
    },
    {
        id: 'factory-lead-square',
        name: 'Square Lead',
        category: 'lead',
        subcategory: 'digital',
        description: 'Bright square wave lead with a touch of room reverb.',
        trackKind: 'midi',
        devices: [
            synth('Square Lead', {
                waveform: 3,
                attack: 0.01,
                decay: 0.15,
                sustain: 0.7,
                release: 0.2,
                filterCutoff: 4000,
                filterResonance: 1,
                filterType: 0,
                detune: 0,
                gain: 0.3,
            }),
            reverb('Reverb', { 'rev-size': 0.3, 'rev-decay': 1.2, 'rev-mix': 0.2 }),
            delay('Delay', { 'delay-time': 200, 'delay-feedback': 0.25, 'delay-mix': 0.2 }),
        ],
        tags: ['square', 'bright', 'reverb', 'retro'],
        author: AUTHOR,
        isFactory: true,
    },
    {
        id: 'factory-lead-bright',
        name: 'Bright Lead',
        category: 'lead',
        subcategory: 'digital',
        description: 'Open sawtooth lead with high-end EQ boost and rhythmic delay.',
        trackKind: 'midi',
        devices: [
            synth('Bright Lead', {
                waveform: 2,
                attack: 0.01,
                decay: 0.2,
                sustain: 0.7,
                release: 0.25,
                filterCutoff: 8000,
                filterResonance: 3,
                filterType: 0,
                detune: 0,
                gain: 0.25,
            }),
            eq('EQ', { 'eq-high-gain': 4, 'eq-high-freq': 6000 }),
            delay('Delay', { 'delay-time': 200, 'delay-feedback': 0.3, 'delay-mix': 0.2 }),
        ],
        tags: ['bright', 'sawtooth', 'eq', 'delay'],
        author: AUTHOR,
        isFactory: true,
    },
    {
        id: 'factory-lead-detuned',
        name: 'Detuned Lead',
        category: 'lead',
        subcategory: 'analog',
        description: 'Fat detuned sawtooth lead with lush reverb. Great for melodies.',
        trackKind: 'midi',
        devices: [
            synth('Detuned Lead', {
                waveform: 2,
                attack: 0.02,
                decay: 0.2,
                sustain: 0.7,
                release: 0.3,
                filterCutoff: 5000,
                filterResonance: 1,
                filterType: 0,
                detune: 20,
                gain: 0.3,
            }),
            reverb('Reverb', { 'rev-size': 0.5, 'rev-decay': 2.5, 'rev-mix': 0.3 }),
            delay('Delay', { 'delay-time': 300, 'delay-feedback': 0.25, 'delay-mix': 0.18 }),
        ],
        tags: ['detuned', 'fat', 'reverb', 'melody'],
        author: AUTHOR,
        isFactory: true,
    },
    {
        id: 'factory-lead-soft',
        name: 'Soft Lead',
        category: 'lead',
        subcategory: 'analog',
        description: 'Gentle triangle lead with slow attack and spacious reverb.',
        trackKind: 'midi',
        devices: [
            synth('Soft Lead', {
                waveform: 1,
                attack: 0.1,
                decay: 0.3,
                sustain: 0.6,
                release: 0.5,
                filterCutoff: 2000,
                filterResonance: 0.5,
                filterType: 0,
                detune: 0,
                gain: 0.3,
            }),
            reverb('Reverb', { 'rev-size': 0.8, 'rev-decay': 4, 'rev-mix': 0.4 }),
            delay('Delay', { 'delay-time': 400, 'delay-feedback': 0.3, 'delay-mix': 0.2 }),
        ],
        tags: ['soft', 'triangle', 'gentle', 'reverb'],
        author: AUTHOR,
        isFactory: true,
    },
    {
        id: 'factory-lead-formant',
        name: 'Formant Lead',
        category: 'lead',
        subcategory: 'digital',
        description: 'Vowel-like lead using resonant bandpass filter with auto-pan.',
        trackKind: 'midi',
        devices: [
            synth('Formant Lead', {
                waveform: 2,
                attack: 0.02,
                decay: 0.2,
                sustain: 0.7,
                release: 0.3,
                filterCutoff: 2000,
                filterResonance: 8,
                filterType: 2,
                detune: 0,
                gain: 0.3,
            }),
            autopan('Auto-Pan', { 'autopan-rate': 1, 'autopan-depth': 0.5 }),
            reverb('Reverb', { 'rev-size': 0.4, 'rev-decay': 2.0, 'rev-mix': 0.25 }),
        ],
        tags: ['formant', 'vowel', 'resonant', 'autopan'],
        author: AUTHOR,
        isFactory: true,
    },
    {
        id: 'factory-lead-glitch',
        name: 'Glitch Lead',
        category: 'lead',
        subcategory: 'digital',
        description: 'Erratic bitcrushed lead with tremolo and delay for glitch textures.',
        trackKind: 'midi',
        devices: [
            synth('Glitch Lead', {
                waveform: 2,
                attack: 0.001,
                decay: 0.08,
                sustain: 0.5,
                release: 0.1,
                filterCutoff: 6000,
                filterResonance: 3,
                filterType: 0,
                detune: 0,
                gain: 0.25,
            }),
            bitcrusher('Bitcrusher', { 'crush-bits': 5, 'crush-mix': 0.5 }),
            tremolo('Tremolo', { 'trem-rate': 8, 'trem-depth': 0.7, 'trem-shape': 1 }),
            delay('Delay', { 'delay-time': 125, 'delay-feedback': 0.4, 'delay-mix': 0.3 }),
        ],
        tags: ['glitch', 'bitcrushed', 'tremolo', 'chaotic'],
        author: AUTHOR,
        isFactory: true,
    },
    {
        id: 'factory-lead-trance',
        name: 'Trance Lead',
        category: 'lead',
        subcategory: 'digital',
        description: 'Classic trance lead with flanger and dotted-note delay.',
        trackKind: 'midi',
        devices: [
            synth('Trance Lead', {
                waveform: 2,
                attack: 0.01,
                decay: 0.2,
                sustain: 0.7,
                release: 0.3,
                filterCutoff: 5000,
                filterResonance: 2,
                filterType: 0,
                detune: 10,
                gain: 0.25,
            }),
            flanger('Flanger', {
                'flanger-rate': 0.5,
                'flanger-depth': 4,
                'flanger-feedback': 0.6,
                'flanger-mix': 0.4,
            }),
            delay('Delay', { 'delay-time': 375, 'delay-feedback': 0.35, 'delay-mix': 0.25 }),
        ],
        tags: ['trance', 'flanger', 'delay', 'uplifting'],
        author: AUTHOR,
        isFactory: true,
    },
];
