import { type SoundPreset } from '#/modules/Arrangement/models/SoundPreset';
import { synth, reverb, delay, filter, tremolo, chorus, AUTHOR } from './presetHelpers';

export const padPresets: SoundPreset[] = [
    // ─── Pad ─────────────────────────────────────────────────────────────
    {
        id: 'factory-pad-warm',
        name: 'Warm Pad',
        category: 'pad',
        subcategory: 'analog',
        description: 'Lush sawtooth pad with slow attack and deep reverb. Fills the stereo field.',
        trackKind: 'midi',
        devices: [
            synth('Warm Pad', {
                waveform: 2,
                attack: 0.5,
                decay: 0.5,
                sustain: 0.8,
                release: 2.0,
                filterCutoff: 2000,
                filterResonance: 0.5,
                filterType: 0,
                detune: 5,
                gain: 0.25,
                osc2Waveform: 2,
                osc2Mix: 0.5,
                osc2Detune: 7,
                noiseLevel: 0.05,
                stereoSpread: 0.7,
                vibratoRate: 3.5,
                vibratoDepth: 8,
                vibratoDelay: 1.0,
            }),
            chorus('Chorus', { 'chorus-rate': 0.8, 'chorus-depth': 6, 'chorus-mix': 0.35 }),
            reverb('Reverb', { 'rev-size': 0.8, 'rev-decay': 5, 'rev-damping': 0.4, 'rev-mix': 0.5 }),
        ],
        tags: ['warm', 'lush', 'sawtooth', 'ambient'],
        author: AUTHOR,
        isFactory: true,
    },
    {
        id: 'factory-pad-ethereal',
        name: 'Ethereal Pad',
        category: 'pad',
        subcategory: 'digital',
        description: 'Airy sine pad with long tails. Huge reverb and delay for ambient textures.',
        trackKind: 'midi',
        devices: [
            synth('Ethereal Pad', {
                waveform: 0,
                attack: 0.8,
                decay: 0.5,
                sustain: 0.9,
                release: 3.0,
                filterCutoff: 3000,
                filterResonance: 0.5,
                filterType: 0,
                detune: 0,
                gain: 0.2,
                osc2Waveform: 1,
                osc2Mix: 0.4,
                osc2Detune: 5,
                noiseLevel: 0.08,
                stereoSpread: 0.8,
            }),
            reverb('Reverb', { 'rev-size': 1.0, 'rev-decay': 8, 'rev-damping': 0.3, 'rev-mix': 0.6 }),
            delay('Delay', { 'delay-time': 500, 'delay-feedback': 0.4, 'delay-mix': 0.25 }),
        ],
        tags: ['ethereal', 'ambient', 'sine', 'spacious'],
        author: AUTHOR,
        isFactory: true,
    },
    {
        id: 'factory-pad-dark',
        name: 'Dark Pad',
        category: 'pad',
        subcategory: 'analog',
        description: 'Moody square pad with low cutoff. Dark and brooding atmosphere.',
        trackKind: 'midi',
        devices: [
            synth('Dark Pad', {
                waveform: 3,
                attack: 0.3,
                decay: 0.4,
                sustain: 0.7,
                release: 1.5,
                filterCutoff: 800,
                filterResonance: 1,
                filterType: 0,
                detune: 3,
                gain: 0.25,
                osc2Waveform: 2,
                osc2Mix: 0.3,
                osc2Detune: -5,
                subOscLevel: 0.2,
            }),
            reverb('Reverb', { 'rev-size': 0.6, 'rev-decay': 3, 'rev-damping': 0.6, 'rev-mix': 0.4 }),
        ],
        tags: ['dark', 'moody', 'square', 'cinematic'],
        author: AUTHOR,
        isFactory: true,
    },
    {
        id: 'factory-pad-shimmer',
        name: 'Shimmer Pad',
        category: 'pad',
        subcategory: 'digital',
        description: 'Bright triangle pad with detune, reverb, and rhythmic delay. Sparkling texture.',
        trackKind: 'midi',
        devices: [
            synth('Shimmer Pad', {
                waveform: 1,
                attack: 0.4,
                decay: 0.3,
                sustain: 0.8,
                release: 2.0,
                filterCutoff: 6000,
                filterResonance: 1,
                filterType: 0,
                detune: 10,
                gain: 0.2,
                osc2Waveform: 0,
                osc2Mix: 0.4,
                osc2Detune: 12,
                noiseLevel: 0.06,
            }),
            reverb('Reverb', { 'rev-size': 0.8, 'rev-decay': 5, 'rev-damping': 0.3, 'rev-mix': 0.5 }),
            delay('Delay', { 'delay-time': 375, 'delay-feedback': 0.3, 'delay-mix': 0.2 }),
        ],
        tags: ['shimmer', 'bright', 'triangle', 'delay'],
        author: AUTHOR,
        isFactory: true,
    },
    {
        id: 'factory-pad-ambient',
        name: 'Ambient Pad',
        category: 'pad',
        subcategory: 'digital',
        description: 'Ultra-slow sine pad with massive reverb tail. Evolving ambient drone.',
        trackKind: 'midi',
        devices: [
            synth('Ambient Pad', {
                waveform: 0,
                attack: 1.0,
                decay: 0.5,
                sustain: 0.9,
                release: 4.0,
                filterCutoff: 4000,
                filterResonance: 0.5,
                filterType: 0,
                detune: 0,
                gain: 0.2,
            }),
            reverb('Reverb', { 'rev-size': 1.0, 'rev-decay': 10, 'rev-damping': 0.2, 'rev-mix': 0.7 }),
        ],
        tags: ['ambient', 'drone', 'sine', 'evolving'],
        author: AUTHOR,
        isFactory: true,
    },
    {
        id: 'factory-pad-filtered',
        name: 'Filtered Pad',
        category: 'pad',
        subcategory: 'digital',
        description: 'Evolving pad with resonant filter and tremolo modulation.',
        trackKind: 'midi',
        devices: [
            synth('Filtered Pad', {
                waveform: 2,
                attack: 0.6,
                decay: 0.4,
                sustain: 0.8,
                release: 2.0,
                filterCutoff: 3000,
                filterResonance: 1,
                filterType: 0,
                detune: 5,
                gain: 0.2,
            }),
            filter('Filter', { 'filter-cutoff': 2000, 'filter-resonance': 4, 'filter-type': 0 }),
            tremolo('Tremolo', { 'trem-rate': 0.5, 'trem-depth': 0.3 }),
            reverb('Reverb', { 'rev-size': 0.8, 'rev-decay': 5, 'rev-mix': 0.5 }),
        ],
        tags: ['filtered', 'evolving', 'tremolo', 'pad'],
        author: AUTHOR,
        isFactory: true,
    },
];
