import { type SoundPreset } from '#/modules/Arrangement/models/SoundPreset';
import { synth, reverb, eq, tremolo, chorus, AUTHOR } from './presetHelpers';

export const stringsPresets: SoundPreset[] = [
    // ─── Strings ─────────────────────────────────────────────────────────
    {
        id: 'factory-strings-soft',
        name: 'Soft Strings',
        category: 'strings',
        subcategory: 'analog',
        description: 'Gentle sawtooth string ensemble with slow attack and lush reverb.',
        trackKind: 'midi',
        devices: [
            synth('Soft Strings', {
                waveform: 2,
                attack: 0.3,
                decay: 0.3,
                sustain: 0.8,
                release: 1.0,
                filterCutoff: 2500,
                filterResonance: 0.5,
                filterType: 0,
                filterEnvAmount: 1000,
                detune: 8,
                gain: 0.25,
                osc2Waveform: 2,
                osc2Mix: 0.5,
                osc2Detune: 6,
                noiseLevel: 0.04,
                vibratoRate: 5,
                vibratoDepth: 15,
                stereoSpread: 0.6,
            }),
            reverb('Reverb', { 'rev-size': 0.8, 'rev-decay': 4, 'rev-damping': 0.4, 'rev-mix': 0.4 }),
            eq('Air', { 'eq-high-gain': 3, 'eq-high-freq': 8000, 'eq-low-gain': 1, 'eq-low-freq': 200 }),
        ],
        tags: ['strings', 'ensemble', 'soft', 'lush'],
        author: AUTHOR,
        isFactory: true,
    },
    {
        id: 'factory-strings-bright',
        name: 'Bright Strings',
        category: 'strings',
        subcategory: 'analog',
        description: 'Expressive sawtooth strings with high-end boost and medium reverb.',
        trackKind: 'midi',
        devices: [
            synth('Bright Strings', {
                waveform: 2,
                attack: 0.15,
                decay: 0.3,
                sustain: 0.8,
                release: 0.8,
                filterCutoff: 5000,
                filterResonance: 0.5,
                filterType: 0,
                detune: 6,
                gain: 0.25,
                osc2Waveform: 2,
                osc2Mix: 0.45,
                osc2Detune: -5,
                noiseLevel: 0.08,
                vibratoRate: 5.5,
                vibratoDepth: 20,
                stereoSpread: 0.7,
            }),
            eq('EQ', { 'eq-high-gain': 3, 'eq-high-freq': 5000 }),
            reverb('Reverb', { 'rev-size': 0.6, 'rev-decay': 3, 'rev-mix': 0.3 }),
        ],
        tags: ['strings', 'bright', 'expressive', 'ensemble'],
        author: AUTHOR,
        isFactory: true,
    },
    {
        id: 'factory-strings-tremolo',
        name: 'Tremolo Strings',
        category: 'strings',
        subcategory: 'analog',
        description: 'Classic tremolo string ensemble with gentle vibrato and hall reverb.',
        trackKind: 'midi',
        devices: [
            synth('Tremolo Strings', {
                waveform: 2,
                attack: 0.2,
                decay: 0.3,
                sustain: 0.8,
                release: 1.0,
                filterCutoff: 3000,
                filterResonance: 0.5,
                filterType: 0,
                detune: 6,
                gain: 0.25,
            }),
            tremolo('Tremolo', { 'trem-rate': 6, 'trem-depth': 0.3 }),
            reverb('Reverb', { 'rev-size': 0.8, 'rev-decay': 4, 'rev-mix': 0.4 }),
        ],
        tags: ['strings', 'tremolo', 'classical', 'ensemble'],
        author: AUTHOR,
        isFactory: true,
    },
    {
        id: 'factory-strings-analog',
        name: 'Analog Strings',
        category: 'strings',
        subcategory: 'analog',
        description: 'Lush dual-oscillator string ensemble with wide stereo spread.',
        trackKind: 'midi',
        devices: [
            synth('Analog Strings', {
                waveform: 2,
                attack: 0.3,
                release: 1.2,
                osc2Mix: 0.5,
                osc2Detune: 15,
                stereoSpread: 1,
            }),
            reverb('Reverb', { 'rev-size': 0.8, 'rev-decay': 4.0, 'rev-mix': 0.4 }),
            chorus('Ensemble', { 'chorus-rate': 0.5, 'chorus-depth': 6, 'chorus-mix': 0.25 }),
        ],
        tags: ['strings', 'analog', 'ensemble', 'lush'],
        author: AUTHOR,
        isFactory: true,
    },
    {
        id: 'factory-strings-cello',
        name: 'Cello',
        category: 'strings',
        subcategory: 'acoustic',
        description: 'Rich, expressive cello with natural vibrato and warm tone.',
        trackKind: 'midi',
        devices: [
            synth('Cello', {
                waveform: 2,
                attack: 0.15,
                decay: 0.2,
                sustain: 0.85,
                release: 0.5,
                filterCutoff: 1500,
                filterResonance: 1,
                filterType: 0,
                filterEnvAmount: 800,
                detune: 3,
                gain: 0.25,
                osc2Waveform: 2,
                osc2Mix: 0.3,
                osc2Detune: -3,
                noiseLevel: 0.02,
                vibratoRate: 5.5,
                vibratoDepth: 18,
                stereoSpread: 0.3,
            }),
            eq('EQ', { 'eq-low-gain': 2, 'eq-low-freq': 250, 'eq-high-gain': -3, 'eq-high-freq': 5000 }),
            reverb('Reverb', { 'rev-size': 0.5, 'rev-decay': 2.5, 'rev-mix': 0.25 }),
        ],
        tags: ['cello', 'strings', 'bowed', 'expressive', 'levain'],
        author: AUTHOR,
        isFactory: true,
    },
    {
        id: 'factory-faust-plucked-string',
        name: 'Plucked String',
        category: 'strings',
        subcategory: 'acoustic',
        description: 'Short-decay pluck. Natural acoustic feel.',
        trackKind: 'midi',
        devices: [
            synth('Plucked String', {
                waveform: 1,
                attack: 0.001,
                decay: 0.5,
                sustain: 0.0,
                release: 0.2,
                filterCutoff: 2000,
                filterResonance: 1,
                filterType: 0,
                filterEnvAmount: 4000,
                detune: 0,
                gain: 0.3,
                noiseLevel: 0.15,
            }),
            reverb('Reverb', { 'rev-size': 0.35, 'rev-decay': 1.5, 'rev-mix': 0.2 }),
            eq('Body', { 'eq-low-gain': 2, 'eq-low-freq': 200, 'eq-high-gain': 2, 'eq-high-freq': 5000 }),
        ],
        tags: ['pluck', 'string', 'acoustic'],
        author: AUTHOR,
        isFactory: true,
    },
];
