import { type DevicePreset, type SoundPreset } from '#/modules/Track/models/SoundPreset';

const AUTHOR = 'WebDAW';

const synth = (name: string, params: Record<string, number>): DevicePreset => ({
    type: 'synth',
    name,
    parameterValues: params,
});

const eq = (
    name: string,
    params: Partial<
        Record<
            | 'eq-low-gain'
            | 'eq-low-freq'
            | 'eq-mid-gain'
            | 'eq-mid-freq'
            | 'eq-mid-q'
            | 'eq-high-gain'
            | 'eq-high-freq',
            number
        >
    >
): DevicePreset => ({
    type: 'builtin-eq',
    name,
    parameterValues: {
        'eq-low-gain': 0,
        'eq-low-freq': 100,
        'eq-mid-gain': 0,
        'eq-mid-freq': 1000,
        'eq-mid-q': 1,
        'eq-high-gain': 0,
        'eq-high-freq': 8000,
        ...params,
    },
});

const comp = (
    name: string,
    params: Partial<Record<'comp-threshold' | 'comp-ratio' | 'comp-attack' | 'comp-release' | 'comp-makeup', number>>
): DevicePreset => ({
    type: 'builtin-compressor',
    name,
    parameterValues: {
        'comp-threshold': -20,
        'comp-ratio': 4,
        'comp-attack': 10,
        'comp-release': 100,
        'comp-makeup': 0,
        ...params,
    },
});

const reverb = (
    name: string,
    params: Partial<Record<'rev-size' | 'rev-decay' | 'rev-damping' | 'rev-mix', number>>
): DevicePreset => ({
    type: 'builtin-reverb',
    name,
    parameterValues: {
        'rev-size': 0.5,
        'rev-decay': 2,
        'rev-damping': 0.5,
        'rev-mix': 0.3,
        ...params,
    },
});

const delay = (
    name: string,
    params: Partial<Record<'delay-time' | 'delay-feedback' | 'delay-mix', number>>
): DevicePreset => ({
    type: 'builtin-delay',
    name,
    parameterValues: {
        'delay-time': 250,
        'delay-feedback': 0.4,
        'delay-mix': 0.3,
        ...params,
    },
});

const gain = (name: string, level: number): DevicePreset => ({
    type: 'builtin-gain',
    name,
    parameterValues: { 'gain-level': level },
});

const flanger = (
    name: string,
    params: Partial<Record<'flanger-rate' | 'flanger-depth' | 'flanger-feedback' | 'flanger-mix', number>>
): DevicePreset => ({
    type: 'builtin-flanger',
    name,
    parameterValues: {
        'flanger-rate': 0.3,
        'flanger-depth': 3,
        'flanger-feedback': 0.5,
        'flanger-mix': 0.5,
        ...params,
    },
});

const tremolo = (
    name: string,
    params: Partial<Record<'trem-rate' | 'trem-depth' | 'trem-shape', number>>
): DevicePreset => ({
    type: 'builtin-tremolo',
    name,
    parameterValues: { 'trem-rate': 4, 'trem-depth': 0.5, 'trem-shape': 0, ...params },
});

const bitcrusher = (
    name: string,
    params: Partial<Record<'crush-bits' | 'crush-rate' | 'crush-mix', number>>
): DevicePreset => ({
    type: 'builtin-bitcrusher',
    name,
    parameterValues: { 'crush-bits': 8, 'crush-rate': 1, 'crush-mix': 0.5, ...params },
});

const filter = (
    name: string,
    params: Partial<Record<'filter-cutoff' | 'filter-resonance' | 'filter-type', number>>
): DevicePreset => ({
    type: 'builtin-filter',
    name,
    parameterValues: { 'filter-cutoff': 1000, 'filter-resonance': 1, 'filter-type': 0, ...params },
});

const autopan = (
    name: string,
    params: Partial<Record<'autopan-rate' | 'autopan-depth' | 'autopan-shape', number>>
): DevicePreset => ({
    type: 'builtin-autopan',
    name,
    parameterValues: { 'autopan-rate': 2, 'autopan-depth': 0.7, 'autopan-shape': 0, ...params },
});

const faustInstrument = (faustModuleId: string, name: string, params: Record<string, number> = {}): DevicePreset => ({
    type: faustModuleId,
    name,
    parameterValues: params,
});

// --- Synth preset helpers (waveform: 0=sine,1=tri,2=saw,3=square; filterType: 0=lp,1=hp,2=bp) ---

const FACTORY_PRESETS: SoundPreset[] = [
    // ─── Bass ────────────────────────────────────────────────────────────
    {
        id: 'factory-bass-sub',
        name: 'Sub Bass',
        category: 'bass',
        subcategory: 'analog',
        description: 'Deep sine sub bass with long sustain and a dark filter. Pure low-end foundation.',
        trackKind: 'midi',
        devices: [
            synth('Sub Bass', {
                waveform: 0,
                attack: 0.01,
                decay: 0.1,
                sustain: 0.9,
                release: 0.4,
                filterCutoff: 200,
                filterResonance: 0,
                filterType: 0,
                detune: 0,
                gain: 0.4,
                subOscLevel: 0.6,
            }),
        ],
        tags: ['sub', 'sine', 'deep', 'low-end'],
        author: AUTHOR,
        isFactory: true,
    },
    {
        id: 'factory-bass-analog',
        name: 'Analog Bass',
        category: 'bass',
        subcategory: 'analog',
        description: 'Punchy sawtooth bass with short decay and compression for mix presence.',
        trackKind: 'midi',
        devices: [
            synth('Analog Bass', {
                waveform: 2,
                attack: 0.005,
                decay: 0.25,
                sustain: 0.5,
                release: 0.15,
                filterCutoff: 800,
                filterResonance: 2,
                filterType: 0,
                detune: 5,
                gain: 0.35,
                subOscLevel: 0.4,
            }),
            comp('Compressor', { 'comp-threshold': -15, 'comp-ratio': 6, 'comp-attack': 5, 'comp-release': 80 }),
        ],
        tags: ['analog', 'sawtooth', 'punchy', 'compressed'],
        author: AUTHOR,
        isFactory: true,
    },
    {
        id: 'factory-bass-wobble',
        name: 'Wobble Bass',
        category: 'bass',
        subcategory: 'digital',
        description: 'Aggressive square wave bass with high resonance and a short delay tail.',
        trackKind: 'midi',
        devices: [
            synth('Wobble Bass', {
                waveform: 3,
                attack: 0.08,
                decay: 0.3,
                sustain: 0.6,
                release: 0.2,
                filterCutoff: 400,
                filterResonance: 8,
                filterType: 0,
                detune: 0,
                gain: 0.3,
            }),
            delay('Delay', { 'delay-time': 100, 'delay-feedback': 0.2, 'delay-mix': 0.2 }),
        ],
        tags: ['wobble', 'square', 'resonant', 'dubstep'],
        author: AUTHOR,
        isFactory: true,
    },
    {
        id: 'factory-bass-reese',
        name: 'Reese Bass',
        category: 'bass',
        subcategory: 'analog',
        description: 'Thick detuned sawtooth bass with low-end EQ boost. Classic DnB texture.',
        trackKind: 'midi',
        devices: [
            synth('Reese Bass', {
                waveform: 2,
                attack: 0.01,
                decay: 0.2,
                sustain: 0.8,
                release: 0.3,
                filterCutoff: 600,
                filterResonance: 1,
                filterType: 0,
                detune: 15,
                gain: 0.35,
                osc2Waveform: 2,
                osc2Mix: 0.5,
                osc2Detune: -12,
                subOscLevel: 0.3,
            }),
            eq('EQ', { 'eq-low-gain': 6, 'eq-low-freq': 80 }),
        ],
        tags: ['reese', 'detuned', 'dnb', 'thick'],
        author: AUTHOR,
        isFactory: true,
    },
    {
        id: 'factory-bass-acid',
        name: 'Acid Bass',
        category: 'bass',
        subcategory: 'analog',
        description: 'Squelchy sawtooth with high resonance and fast decay. 303-style acid line.',
        trackKind: 'midi',
        devices: [
            synth('Acid Bass', {
                waveform: 2,
                attack: 0.005,
                decay: 0.1,
                sustain: 0.3,
                release: 0.1,
                filterCutoff: 1200,
                filterResonance: 10,
                filterType: 0,
                detune: 0,
                gain: 0.3,
            }),
            comp('Compressor', { 'comp-threshold': -12, 'comp-ratio': 5, 'comp-attack': 3, 'comp-release': 60 }),
        ],
        tags: ['acid', '303', 'squelch', 'resonant'],
        author: AUTHOR,
        isFactory: true,
    },

    // ─── Lead ────────────────────────────────────────────────────────────
    {
        id: 'factory-lead-classic',
        name: 'Classic Lead',
        category: 'lead',
        subcategory: 'analog',
        description: 'Warm sawtooth lead with delay. Versatile mono-style synth lead.',
        trackKind: 'midi',
        devices: [
            synth('Classic Lead', {
                waveform: 2,
                attack: 0.05,
                decay: 0.2,
                sustain: 0.7,
                release: 0.3,
                filterCutoff: 3000,
                filterResonance: 1,
                filterType: 0,
                detune: 0,
                gain: 0.3,
            }),
            delay('Delay', { 'delay-time': 250, 'delay-feedback': 0.3, 'delay-mix': 0.25 }),
        ],
        tags: ['classic', 'sawtooth', 'delay', 'mono'],
        author: AUTHOR,
        isFactory: true,
    },
    {
        id: 'factory-lead-square',
        name: 'Square Lead',
        category: 'lead',
        subcategory: 'digital',
        description: 'Bright square wave lead with a touch of room reverb.',
        trackKind: 'midi',
        devices: [
            synth('Square Lead', {
                waveform: 3,
                attack: 0.01,
                decay: 0.15,
                sustain: 0.7,
                release: 0.2,
                filterCutoff: 4000,
                filterResonance: 1,
                filterType: 0,
                detune: 0,
                gain: 0.3,
            }),
            reverb('Reverb', { 'rev-size': 0.3, 'rev-decay': 1.2, 'rev-mix': 0.2 }),
        ],
        tags: ['square', 'bright', 'reverb', 'retro'],
        author: AUTHOR,
        isFactory: true,
    },
    {
        id: 'factory-lead-bright',
        name: 'Bright Lead',
        category: 'lead',
        subcategory: 'digital',
        description: 'Open sawtooth lead with high-end EQ boost and rhythmic delay.',
        trackKind: 'midi',
        devices: [
            synth('Bright Lead', {
                waveform: 2,
                attack: 0.01,
                decay: 0.2,
                sustain: 0.7,
                release: 0.25,
                filterCutoff: 8000,
                filterResonance: 3,
                filterType: 0,
                detune: 0,
                gain: 0.25,
            }),
            eq('EQ', { 'eq-high-gain': 4, 'eq-high-freq': 6000 }),
            delay('Delay', { 'delay-time': 200, 'delay-feedback': 0.3, 'delay-mix': 0.2 }),
        ],
        tags: ['bright', 'sawtooth', 'eq', 'delay'],
        author: AUTHOR,
        isFactory: true,
    },
    {
        id: 'factory-lead-detuned',
        name: 'Detuned Lead',
        category: 'lead',
        subcategory: 'analog',
        description: 'Fat detuned sawtooth lead with lush reverb. Great for melodies.',
        trackKind: 'midi',
        devices: [
            synth('Detuned Lead', {
                waveform: 2,
                attack: 0.02,
                decay: 0.2,
                sustain: 0.7,
                release: 0.3,
                filterCutoff: 5000,
                filterResonance: 1,
                filterType: 0,
                detune: 20,
                gain: 0.3,
            }),
            reverb('Reverb', { 'rev-size': 0.5, 'rev-decay': 2.5, 'rev-mix': 0.3 }),
        ],
        tags: ['detuned', 'fat', 'reverb', 'melody'],
        author: AUTHOR,
        isFactory: true,
    },
    {
        id: 'factory-lead-soft',
        name: 'Soft Lead',
        category: 'lead',
        subcategory: 'analog',
        description: 'Gentle triangle lead with slow attack and spacious reverb.',
        trackKind: 'midi',
        devices: [
            synth('Soft Lead', {
                waveform: 1,
                attack: 0.1,
                decay: 0.3,
                sustain: 0.6,
                release: 0.5,
                filterCutoff: 2000,
                filterResonance: 0.5,
                filterType: 0,
                detune: 0,
                gain: 0.3,
            }),
            reverb('Reverb', { 'rev-size': 0.8, 'rev-decay': 4, 'rev-mix': 0.4 }),
        ],
        tags: ['soft', 'triangle', 'gentle', 'reverb'],
        author: AUTHOR,
        isFactory: true,
    },

    // ─── Pad ─────────────────────────────────────────────────────────────
    {
        id: 'factory-pad-warm',
        name: 'Warm Pad',
        category: 'pad',
        subcategory: 'analog',
        description: 'Lush sawtooth pad with slow attack and deep reverb. Fills the stereo field.',
        trackKind: 'midi',
        devices: [
            synth('Warm Pad', {
                waveform: 2,
                attack: 0.5,
                decay: 0.5,
                sustain: 0.8,
                release: 2.0,
                filterCutoff: 2000,
                filterResonance: 0.5,
                filterType: 0,
                detune: 5,
                gain: 0.25,
                osc2Waveform: 2,
                osc2Mix: 0.5,
                osc2Detune: 7,
                noiseLevel: 0.05,
            }),
            reverb('Reverb', { 'rev-size': 0.8, 'rev-decay': 5, 'rev-damping': 0.4, 'rev-mix': 0.5 }),
        ],
        tags: ['warm', 'lush', 'sawtooth', 'ambient'],
        author: AUTHOR,
        isFactory: true,
    },
    {
        id: 'factory-pad-ethereal',
        name: 'Ethereal Pad',
        category: 'pad',
        subcategory: 'digital',
        description: 'Airy sine pad with long tails. Huge reverb and delay for ambient textures.',
        trackKind: 'midi',
        devices: [
            synth('Ethereal Pad', {
                waveform: 0,
                attack: 0.8,
                decay: 0.5,
                sustain: 0.9,
                release: 3.0,
                filterCutoff: 3000,
                filterResonance: 0.5,
                filterType: 0,
                detune: 0,
                gain: 0.2,
                osc2Waveform: 1,
                osc2Mix: 0.4,
                osc2Detune: 5,
                noiseLevel: 0.08,
            }),
            reverb('Reverb', { 'rev-size': 1.0, 'rev-decay': 8, 'rev-damping': 0.3, 'rev-mix': 0.6 }),
            delay('Delay', { 'delay-time': 500, 'delay-feedback': 0.4, 'delay-mix': 0.25 }),
        ],
        tags: ['ethereal', 'ambient', 'sine', 'spacious'],
        author: AUTHOR,
        isFactory: true,
    },
    {
        id: 'factory-pad-dark',
        name: 'Dark Pad',
        category: 'pad',
        subcategory: 'analog',
        description: 'Moody square pad with low cutoff. Dark and brooding atmosphere.',
        trackKind: 'midi',
        devices: [
            synth('Dark Pad', {
                waveform: 3,
                attack: 0.3,
                decay: 0.4,
                sustain: 0.7,
                release: 1.5,
                filterCutoff: 800,
                filterResonance: 1,
                filterType: 0,
                detune: 3,
                gain: 0.25,
                osc2Waveform: 2,
                osc2Mix: 0.3,
                osc2Detune: -5,
                subOscLevel: 0.2,
            }),
            reverb('Reverb', { 'rev-size': 0.6, 'rev-decay': 3, 'rev-damping': 0.6, 'rev-mix': 0.4 }),
        ],
        tags: ['dark', 'moody', 'square', 'cinematic'],
        author: AUTHOR,
        isFactory: true,
    },
    {
        id: 'factory-pad-shimmer',
        name: 'Shimmer Pad',
        category: 'pad',
        subcategory: 'digital',
        description: 'Bright triangle pad with detune, reverb, and rhythmic delay. Sparkling texture.',
        trackKind: 'midi',
        devices: [
            synth('Shimmer Pad', {
                waveform: 1,
                attack: 0.4,
                decay: 0.3,
                sustain: 0.8,
                release: 2.0,
                filterCutoff: 6000,
                filterResonance: 1,
                filterType: 0,
                detune: 10,
                gain: 0.2,
                osc2Waveform: 0,
                osc2Mix: 0.4,
                osc2Detune: 12,
                noiseLevel: 0.06,
            }),
            reverb('Reverb', { 'rev-size': 0.8, 'rev-decay': 5, 'rev-damping': 0.3, 'rev-mix': 0.5 }),
            delay('Delay', { 'delay-time': 375, 'delay-feedback': 0.3, 'delay-mix': 0.2 }),
        ],
        tags: ['shimmer', 'bright', 'triangle', 'delay'],
        author: AUTHOR,
        isFactory: true,
    },
    {
        id: 'factory-pad-ambient',
        name: 'Ambient Pad',
        category: 'pad',
        subcategory: 'digital',
        description: 'Ultra-slow sine pad with massive reverb tail. Evolving ambient drone.',
        trackKind: 'midi',
        devices: [
            synth('Ambient Pad', {
                waveform: 0,
                attack: 1.0,
                decay: 0.5,
                sustain: 0.9,
                release: 4.0,
                filterCutoff: 4000,
                filterResonance: 0.5,
                filterType: 0,
                detune: 0,
                gain: 0.2,
            }),
            reverb('Reverb', { 'rev-size': 1.0, 'rev-decay': 10, 'rev-damping': 0.2, 'rev-mix': 0.7 }),
        ],
        tags: ['ambient', 'drone', 'sine', 'evolving'],
        author: AUTHOR,
        isFactory: true,
    },

    // ─── Keys ────────────────────────────────────────────────────────────
    {
        id: 'factory-keys-epiano',
        name: 'Electric Piano',
        category: 'keys',
        subcategory: 'digital',
        description: 'Classic electric piano tone using Faust DSP.',
        trackKind: 'midi',
        devices: [
            faustInstrument('faust-rhodes', 'Rhodes Piano', {}),
            eq('EQ', { 'eq-mid-gain': 2, 'eq-mid-freq': 1200, 'eq-mid-q': 1.5 }),
        ],
        tags: ['electric-piano', 'keys', 'rhodes', 'classic'],
        author: AUTHOR,
        isFactory: true,
    },
    {
        id: 'factory-keys-fmpiano',
        name: 'FM Piano',
        category: 'keys',
        subcategory: 'digital',
        description: 'Classic DX7-style FM electric piano using Faust DSP.',
        trackKind: 'midi',
        devices: [
            faustInstrument('faust-fm-synth', 'FM Synth', {
                '/fm_synth/ratio': 2,
                '/fm_synth/index': 5
            }),
            delay('Delay', { 'delay-time': 300, 'delay-feedback': 0.3, 'delay-mix': 0.15 }),
            reverb('Reverb', { 'rev-size': 0.5, 'rev-decay': 2, 'rev-mix': 0.2 }),
        ],
        tags: ['fm', 'keys', 'dx7', 'digital'],
        author: AUTHOR,
        isFactory: true,
    },
    {
        id: 'factory-keys-organ',
        name: 'Organ',
        category: 'keys',
        subcategory: 'analog',
        description: 'Full-bodied square wave organ with sustain and a hint of room reverb.',
        trackKind: 'midi',
        devices: [
            synth('Organ', {
                waveform: 3,
                attack: 0.001,
                decay: 0.1,
                sustain: 1.0,
                release: 0.1,
                filterCutoff: 5000,
                filterResonance: 0.5,
                filterType: 0,
                detune: 0,
                gain: 0.25,
                osc2Waveform: 0,
                osc2Mix: 0.3,
                osc2Detune: 0,
                subOscLevel: 0.2,
            }),
            reverb('Reverb', { 'rev-size': 0.3, 'rev-decay': 1.0, 'rev-mix': 0.15 }),
        ],
        tags: ['organ', 'sustained', 'square', 'classic'],
        author: AUTHOR,
        isFactory: true,
    },
    {
        id: 'factory-keys-pluck',
        name: 'Pluck',
        category: 'keys',
        subcategory: 'digital',
        description: 'Snappy triangle pluck with very short decay. Percussive and clean.',
        trackKind: 'midi',
        devices: [
            synth('Pluck', {
                waveform: 1,
                attack: 0.001,
                decay: 0.15,
                sustain: 0.1,
                release: 0.1,
                filterCutoff: 4000,
                filterResonance: 1,
                filterType: 0,
                detune: 0,
                gain: 0.3,
            }),
        ],
        tags: ['pluck', 'percussive', 'short', 'triangle'],
        author: AUTHOR,
        isFactory: true,
    },
    {
        id: 'factory-keys-bell',
        name: 'Bell',
        category: 'keys',
        subcategory: 'digital',
        description: 'Pure sine bell with long decay and no sustain. Crystalline tone with reverb.',
        trackKind: 'midi',
        devices: [
            synth('Bell', {
                waveform: 0,
                attack: 0.001,
                decay: 1.5,
                sustain: 0.0,
                release: 0.5,
                filterCutoff: 8000,
                filterResonance: 0.5,
                filterType: 0,
                detune: 0,
                gain: 0.25,
                osc2Waveform: 0,
                osc2Mix: 0.3,
                osc2Detune: 700,
            }),
            reverb('Reverb', { 'rev-size': 0.5, 'rev-decay': 3, 'rev-mix': 0.3 }),
        ],
        tags: ['bell', 'sine', 'crystalline', 'percussive'],
        author: AUTHOR,
        isFactory: true,
    },
    {
        id: 'factory-keys-marimba',
        name: 'Marimba',
        category: 'keys',
        subcategory: 'acoustic',
        description: 'Warm sine marimba with short decay. Woody, mallet-like character.',
        trackKind: 'midi',
        devices: [
            synth('Marimba', {
                waveform: 0,
                attack: 0.001,
                decay: 0.3,
                sustain: 0.0,
                release: 0.15,
                filterCutoff: 6000,
                filterResonance: 0.5,
                filterType: 0,
                detune: 0,
                gain: 0.3,
            }),
        ],
        tags: ['marimba', 'mallet', 'percussive', 'acoustic'],
        author: AUTHOR,
        isFactory: true,
    },

    // ─── Strings ─────────────────────────────────────────────────────────
    {
        id: 'factory-strings-soft',
        name: 'Soft Strings',
        category: 'strings',
        subcategory: 'analog',
        description: 'Gentle sawtooth string ensemble with slow attack and lush reverb.',
        trackKind: 'midi',
        devices: [
            synth('Soft Strings', {
                waveform: 2,
                attack: 0.3,
                decay: 0.3,
                sustain: 0.8,
                release: 1.0,
                filterCutoff: 2500,
                filterResonance: 0.5,
                filterType: 0,
                detune: 8,
                gain: 0.25,
                osc2Waveform: 2,
                osc2Mix: 0.5,
                osc2Detune: 6,
                noiseLevel: 0.1,
            }),
            reverb('Reverb', { 'rev-size': 0.8, 'rev-decay': 4, 'rev-damping': 0.4, 'rev-mix': 0.4 }),
        ],
        tags: ['strings', 'ensemble', 'soft', 'lush'],
        author: AUTHOR,
        isFactory: true,
    },
    {
        id: 'factory-strings-bright',
        name: 'Bright Strings',
        category: 'strings',
        subcategory: 'analog',
        description: 'Expressive sawtooth strings with high-end boost and medium reverb.',
        trackKind: 'midi',
        devices: [
            synth('Bright Strings', {
                waveform: 2,
                attack: 0.15,
                decay: 0.3,
                sustain: 0.8,
                release: 0.8,
                filterCutoff: 5000,
                filterResonance: 0.5,
                filterType: 0,
                detune: 6,
                gain: 0.25,
                osc2Waveform: 2,
                osc2Mix: 0.45,
                osc2Detune: -5,
                noiseLevel: 0.08,
            }),
            eq('EQ', { 'eq-high-gain': 3, 'eq-high-freq': 5000 }),
            reverb('Reverb', { 'rev-size': 0.6, 'rev-decay': 3, 'rev-mix': 0.3 }),
        ],
        tags: ['strings', 'bright', 'expressive', 'ensemble'],
        author: AUTHOR,
        isFactory: true,
    },

    // ─── FX ──────────────────────────────────────────────────────────────
    {
        id: 'factory-fx-noise-sweep',
        name: 'Noise Sweep',
        category: 'fx',
        subcategory: 'digital',
        description: 'Resonant square sweep with long attack and feedback delay. Tension builder.',
        trackKind: 'midi',
        devices: [
            synth('Noise Sweep', {
                waveform: 3,
                attack: 1.0,
                decay: 0.5,
                sustain: 0.6,
                release: 1.0,
                filterCutoff: 500,
                filterResonance: 12,
                filterType: 0,
                detune: 0,
                gain: 0.2,
            }),
            delay('Delay', { 'delay-time': 500, 'delay-feedback': 0.7, 'delay-mix': 0.4 }),
        ],
        tags: ['noise', 'sweep', 'tension', 'fx'],
        author: AUTHOR,
        isFactory: true,
    },
    {
        id: 'factory-fx-stab',
        name: 'Stab',
        category: 'fx',
        subcategory: 'digital',
        description: 'Punchy sawtooth stab with instant attack and reverb tail.',
        trackKind: 'midi',
        devices: [
            synth('Stab', {
                waveform: 2,
                attack: 0.001,
                decay: 0.05,
                sustain: 0.0,
                release: 0.05,
                filterCutoff: 6000,
                filterResonance: 1,
                filterType: 0,
                detune: 0,
                gain: 0.35,
            }),
            reverb('Reverb', { 'rev-size': 0.5, 'rev-decay': 2, 'rev-mix': 0.4 }),
        ],
        tags: ['stab', 'punchy', 'short', 'hit'],
        author: AUTHOR,
        isFactory: true,
    },
    {
        id: 'factory-fx-riser',
        name: 'Riser',
        category: 'fx',
        subcategory: 'digital',
        description: 'Slow-building sawtooth riser with bright filter and rhythmic delay.',
        trackKind: 'midi',
        devices: [
            synth('Riser', {
                waveform: 2,
                attack: 2.0,
                decay: 0.3,
                sustain: 0.8,
                release: 0.5,
                filterCutoff: 8000,
                filterResonance: 2,
                filterType: 0,
                detune: 5,
                gain: 0.2,
            }),
            delay('Delay', { 'delay-time': 250, 'delay-feedback': 0.5, 'delay-mix': 0.3 }),
        ],
        tags: ['riser', 'build', 'transition', 'fx'],
        author: AUTHOR,
        isFactory: true,
    },

    // ─── Vocal (audio track effect chains) ───────────────────────────────
    {
        id: 'factory-vocal-warmth',
        name: 'Vocal Warmth',
        category: 'vocal',
        description: 'Warm vocal chain with low-mid presence boost and gentle compression.',
        trackKind: 'audio',
        devices: [
            eq('EQ', { 'eq-low-gain': 3, 'eq-low-freq': 300, 'eq-high-gain': -2, 'eq-high-freq': 3000 }),
            comp('Compressor', { 'comp-threshold': -18, 'comp-ratio': 3, 'comp-attack': 5, 'comp-release': 120 }),
        ],
        tags: ['vocal', 'warm', 'eq', 'compression'],
        author: AUTHOR,
        isFactory: true,
    },
    {
        id: 'factory-vocal-presence',
        name: 'Vocal Presence',
        category: 'vocal',
        description: 'Bright vocal chain that cuts through the mix with presence boost and compression.',
        trackKind: 'audio',
        devices: [
            eq('EQ', {
                'eq-mid-gain': 4,
                'eq-mid-freq': 3000,
                'eq-mid-q': 1.5,
                'eq-low-gain': -2,
                'eq-low-freq': 200,
            }),
            comp('Compressor', { 'comp-threshold': -15, 'comp-ratio': 4, 'comp-attack': 8, 'comp-release': 100 }),
        ],
        tags: ['vocal', 'presence', 'bright', 'clarity'],
        author: AUTHOR,
        isFactory: true,
    },
    {
        id: 'factory-vocal-reverb',
        name: 'Vocal Reverb',
        category: 'vocal',
        description: 'Controlled vocal with compression into a plate-style reverb.',
        trackKind: 'audio',
        devices: [
            comp('Compressor', { 'comp-threshold': -20, 'comp-ratio': 3, 'comp-attack': 8, 'comp-release': 100 }),
            reverb('Reverb', { 'rev-size': 0.4, 'rev-decay': 1.5, 'rev-damping': 0.6, 'rev-mix': 0.25 }),
        ],
        tags: ['vocal', 'reverb', 'plate', 'polished'],
        author: AUTHOR,
        isFactory: true,
    },
    {
        id: 'factory-vocal-radio',
        name: 'Radio Voice',
        category: 'vocal',
        description: 'Narrow-band vocal with heavy compression. Lo-fi broadcast character.',
        trackKind: 'audio',
        devices: [
            eq('EQ', {
                'eq-low-gain': -8,
                'eq-low-freq': 300,
                'eq-mid-gain': 4,
                'eq-mid-freq': 2000,
                'eq-mid-q': 2,
                'eq-high-gain': -4,
                'eq-high-freq': 6000,
            }),
            comp('Compressor', { 'comp-threshold': -10, 'comp-ratio': 8, 'comp-attack': 2, 'comp-release': 50 }),
        ],
        tags: ['vocal', 'radio', 'lo-fi', 'compressed'],
        author: AUTHOR,
        isFactory: true,
    },

    // ─── Guitar (audio track effect chains) ──────────────────────────────
    {
        id: 'factory-guitar-clean',
        name: 'Clean Guitar',
        category: 'guitar',
        description: 'Clean guitar tone with a subtle mid scoop and small room reverb.',
        trackKind: 'audio',
        devices: [
            eq('EQ', { 'eq-mid-gain': -2, 'eq-mid-freq': 800, 'eq-mid-q': 1.5 }),
            reverb('Reverb', { 'rev-size': 0.25, 'rev-decay': 0.8, 'rev-mix': 0.15 }),
        ],
        tags: ['guitar', 'clean', 'room', 'natural'],
        author: AUTHOR,
        isFactory: true,
    },
    {
        id: 'factory-guitar-crunch',
        name: 'Crunch Guitar',
        category: 'guitar',
        description: 'Aggressive crunch tone with heavy compression and mid-range bite.',
        trackKind: 'audio',
        devices: [
            comp('Compressor', { 'comp-threshold': -10, 'comp-ratio': 8, 'comp-attack': 1, 'comp-release': 60 }),
            eq('EQ', { 'eq-mid-gain': 4, 'eq-mid-freq': 1000, 'eq-mid-q': 1.5 }),
        ],
        tags: ['guitar', 'crunch', 'aggressive', 'compressed'],
        author: AUTHOR,
        isFactory: true,
    },
    {
        id: 'factory-guitar-ambient',
        name: 'Ambient Guitar',
        category: 'guitar',
        description: 'Spacious ambient guitar with large reverb and modulated delay.',
        trackKind: 'audio',
        devices: [
            reverb('Reverb', { 'rev-size': 0.8, 'rev-decay': 5, 'rev-damping': 0.3, 'rev-mix': 0.5 }),
            delay('Delay', { 'delay-time': 400, 'delay-feedback': 0.4, 'delay-mix': 0.3 }),
        ],
        tags: ['guitar', 'ambient', 'spacious', 'atmospheric'],
        author: AUTHOR,
        isFactory: true,
    },

    // ─── Drums (audio track effect chains) ───────────────────────────────
    {
        id: 'factory-drums-punchy',
        name: 'Punchy Drums',
        category: 'drums',
        description: 'Tight drum bus with fast compression and low/high shelf boosts.',
        trackKind: 'audio',
        devices: [
            comp('Compressor', { 'comp-threshold': -15, 'comp-ratio': 6, 'comp-attack': 1, 'comp-release': 60 }),
            eq('EQ', { 'eq-low-gain': 4, 'eq-low-freq': 80, 'eq-high-gain': 3, 'eq-high-freq': 10000 }),
        ],
        tags: ['drums', 'punchy', 'tight', 'compressed'],
        author: AUTHOR,
        isFactory: true,
    },
    {
        id: 'factory-drums-room',
        name: 'Room Drums',
        category: 'drums',
        description: 'Natural drum room with gentle compression and short reverb.',
        trackKind: 'audio',
        devices: [
            comp('Compressor', { 'comp-threshold': -20, 'comp-ratio': 3, 'comp-attack': 5, 'comp-release': 100 }),
            reverb('Reverb', { 'rev-size': 0.3, 'rev-decay': 0.8, 'rev-mix': 0.2 }),
        ],
        tags: ['drums', 'room', 'natural', 'live'],
        author: AUTHOR,
        isFactory: true,
    },
    {
        id: 'factory-drums-crispy',
        name: 'Crispy Drums',
        category: 'drums',
        description: 'Bright, crispy drum treatment with high-end boost and mid cut.',
        trackKind: 'audio',
        devices: [
            eq('EQ', {
                'eq-high-gain': 5,
                'eq-high-freq': 8000,
                'eq-mid-gain': -2,
                'eq-mid-freq': 400,
                'eq-mid-q': 1.5,
            }),
            comp('Compressor', { 'comp-threshold': -12, 'comp-ratio': 4, 'comp-attack': 3, 'comp-release': 80 }),
        ],
        tags: ['drums', 'crispy', 'bright', 'snappy'],
        author: AUTHOR,
        isFactory: true,
    },
    {
        id: 'factory-drums-808',
        name: '808 Kit',
        category: 'drums',
        description: 'Heavy low-end 808-style processing with sub boost and controlled dynamics.',
        trackKind: 'audio',
        devices: [
            eq('EQ', { 'eq-low-gain': 6, 'eq-low-freq': 60 }),
            comp('Compressor', { 'comp-threshold': -18, 'comp-ratio': 4, 'comp-attack': 5, 'comp-release': 100 }),
        ],
        tags: ['drums', '808', 'trap', 'sub'],
        author: AUTHOR,
        isFactory: true,
    },

    // ─── General / Mix (audio track effect chains) ───────────────────────
    {
        id: 'factory-mix-glue',
        name: 'Glue Compressor',
        category: 'fx',
        description: 'Gentle bus compressor that glues a mix together. Slow attack, musical release.',
        trackKind: 'audio',
        devices: [
            comp('Compressor', { 'comp-threshold': -12, 'comp-ratio': 2, 'comp-attack': 30, 'comp-release': 200 }),
        ],
        tags: ['glue', 'bus', 'mix', 'subtle'],
        author: AUTHOR,
        isFactory: true,
    },
    {
        id: 'factory-mix-stereo-spread',
        name: 'Stereo Spread',
        category: 'fx',
        description: 'Short delay-based stereo widening effect. Adds width without phase issues.',
        trackKind: 'audio',
        devices: [delay('Delay', { 'delay-time': 20, 'delay-feedback': 0.1, 'delay-mix': 0.3 })],
        tags: ['stereo', 'width', 'delay', 'spatial'],
        author: AUTHOR,
        isFactory: true,
    },
    {
        id: 'factory-mix-tape-saturation',
        name: 'Tape Saturation',
        category: 'fx',
        description: 'Tape-style saturation with heavy compression and gentle high-end roll-off.',
        trackKind: 'audio',
        devices: [
            comp('Compressor', { 'comp-threshold': -8, 'comp-ratio': 10, 'comp-attack': 1, 'comp-release': 50 }),
            eq('EQ', { 'eq-high-gain': -3, 'eq-high-freq': 8000 }),
        ],
        tags: ['tape', 'saturation', 'warm', 'analog'],
        author: AUTHOR,
        isFactory: true,
    },
    {
        id: 'factory-mix-lofi',
        name: 'Lo-Fi',
        category: 'fx',
        description: 'Lo-fi effect chain with bandwidth limiting and extreme compression.',
        trackKind: 'audio',
        devices: [
            eq('EQ', { 'eq-high-gain': -12, 'eq-high-freq': 4000, 'eq-low-gain': -6, 'eq-low-freq': 200 }),
            comp('Compressor', { 'comp-threshold': -5, 'comp-ratio': 12, 'comp-attack': 1, 'comp-release': 40 }),
        ],
        tags: ['lo-fi', 'vintage', 'crushed', 'retro'],
        author: AUTHOR,
        isFactory: true,
    },

    // ─── Extra synth presets for variety ──────────────────────────────────
    {
        id: 'factory-synth-supersaw',
        name: 'Supersaw',
        category: 'synth',
        subcategory: 'digital',
        description: 'Wide detuned sawtooth with reverb and delay. Classic trance/EDM supersaw.',
        trackKind: 'midi',
        devices: [
            synth('Supersaw', {
                waveform: 2,
                attack: 0.02,
                decay: 0.3,
                sustain: 0.8,
                release: 0.5,
                filterCutoff: 6000,
                filterResonance: 1,
                filterType: 0,
                detune: 25,
                gain: 0.2,
            }),
            reverb('Reverb', { 'rev-size': 0.6, 'rev-decay': 3, 'rev-mix': 0.35 }),
            delay('Delay', { 'delay-time': 187, 'delay-feedback': 0.25, 'delay-mix': 0.15 }),
        ],
        tags: ['supersaw', 'trance', 'edm', 'wide'],
        author: AUTHOR,
        isFactory: true,
    },
    {
        id: 'factory-synth-chip',
        name: 'Chiptune',
        category: 'synth',
        subcategory: 'digital',
        description: 'Retro square wave with no filter and fast envelope. 8-bit game sound.',
        trackKind: 'midi',
        devices: [
            synth('Chiptune', {
                waveform: 3,
                attack: 0.001,
                decay: 0.1,
                sustain: 0.8,
                release: 0.05,
                filterCutoff: 20000,
                filterResonance: 0,
                filterType: 0,
                detune: 0,
                gain: 0.2,
            }),
        ],
        tags: ['chiptune', '8-bit', 'retro', 'game'],
        author: AUTHOR,
        isFactory: true,
    },
    {
        id: 'factory-synth-brass',
        name: 'Synth Brass',
        category: 'synth',
        subcategory: 'analog',
        description: 'Bold sawtooth brass stab with medium attack and resonant filter.',
        trackKind: 'midi',
        devices: [
            synth('Synth Brass', {
                waveform: 2,
                attack: 0.08,
                decay: 0.2,
                sustain: 0.7,
                release: 0.2,
                filterCutoff: 3500,
                filterResonance: 3,
                filterType: 0,
                detune: 10,
                gain: 0.3,
            }),
            comp('Compressor', { 'comp-threshold': -15, 'comp-ratio': 3, 'comp-attack': 10, 'comp-release': 100 }),
        ],
        tags: ['brass', 'stab', 'bold', 'analog'],
        author: AUTHOR,
        isFactory: true,
    },
    {
        id: 'factory-synth-flute',
        name: 'Synth Flute',
        category: 'synth',
        subcategory: 'acoustic',
        description: 'Soft sine flute with gentle attack and airy reverb.',
        trackKind: 'midi',
        devices: [
            synth('Synth Flute', {
                waveform: 0,
                attack: 0.08,
                decay: 0.2,
                sustain: 0.6,
                release: 0.3,
                filterCutoff: 4000,
                filterResonance: 0.5,
                filterType: 0,
                detune: 0,
                gain: 0.25,
            }),
            reverb('Reverb', { 'rev-size': 0.5, 'rev-decay': 2, 'rev-damping': 0.4, 'rev-mix': 0.3 }),
        ],
        tags: ['flute', 'soft', 'woodwind', 'airy'],
        author: AUTHOR,
        isFactory: true,
    },
    {
        id: 'factory-synth-arp',
        name: 'Arp Synth',
        category: 'synth',
        subcategory: 'digital',
        description: 'Snappy triangle for arpeggiated sequences with delay and reverb.',
        trackKind: 'midi',
        devices: [
            synth('Arp Synth', {
                waveform: 1,
                attack: 0.001,
                decay: 0.12,
                sustain: 0.2,
                release: 0.1,
                filterCutoff: 5000,
                filterResonance: 2,
                filterType: 0,
                detune: 0,
                gain: 0.25,
            }),
            delay('Delay', { 'delay-time': 166, 'delay-feedback': 0.35, 'delay-mix': 0.25 }),
            reverb('Reverb', { 'rev-size': 0.4, 'rev-decay': 1.5, 'rev-mix': 0.2 }),
        ],
        tags: ['arp', 'sequence', 'snappy', 'rhythmic'],
        author: AUTHOR,
        isFactory: true,
    },
    {
        id: 'factory-synth-hoover',
        name: 'Hoover',
        category: 'synth',
        subcategory: 'digital',
        description: 'Heavily detuned sawtooth with wide filter. Classic rave hoover sound.',
        trackKind: 'midi',
        devices: [
            synth('Hoover', {
                waveform: 2,
                attack: 0.01,
                decay: 0.3,
                sustain: 0.7,
                release: 0.3,
                filterCutoff: 4000,
                filterResonance: 4,
                filterType: 0,
                detune: 30,
                gain: 0.25,
            }),
            comp('Compressor', { 'comp-threshold': -12, 'comp-ratio': 4, 'comp-attack': 5, 'comp-release': 80 }),
            reverb('Reverb', { 'rev-size': 0.4, 'rev-decay': 1.5, 'rev-mix': 0.2 }),
        ],
        tags: ['hoover', 'rave', 'detuned', 'classic'],
        author: AUTHOR,
        isFactory: true,
    },

    // ─── Extra audio effect presets ──────────────────────────────────────
    {
        id: 'factory-mix-vocal-double',
        name: 'Vocal Doubler',
        category: 'vocal',
        description: 'Short delay doubling effect for thickening vocals.',
        trackKind: 'audio',
        devices: [
            delay('Delay', { 'delay-time': 30, 'delay-feedback': 0.05, 'delay-mix': 0.25 }),
            reverb('Reverb', { 'rev-size': 0.2, 'rev-decay': 0.5, 'rev-mix': 0.1 }),
        ],
        tags: ['vocal', 'double', 'thicken', 'delay'],
        author: AUTHOR,
        isFactory: true,
    },
    {
        id: 'factory-guitar-slapback',
        name: 'Slapback Guitar',
        category: 'guitar',
        description: 'Classic slapback delay for rockabilly and country guitar tones.',
        trackKind: 'audio',
        devices: [
            delay('Delay', { 'delay-time': 120, 'delay-feedback': 0.15, 'delay-mix': 0.3 }),
            eq('EQ', { 'eq-mid-gain': 2, 'eq-mid-freq': 1500, 'eq-mid-q': 1 }),
        ],
        tags: ['guitar', 'slapback', 'rockabilly', 'country'],
        author: AUTHOR,
        isFactory: true,
    },
    {
        id: 'factory-drums-parallel',
        name: 'Parallel Crush',
        category: 'drums',
        description: 'Extreme parallel-style compression for drum impact and energy.',
        trackKind: 'audio',
        devices: [
            comp('Compressor', { 'comp-threshold': -30, 'comp-ratio': 20, 'comp-attack': 0.5, 'comp-release': 30 }),
            eq('EQ', { 'eq-low-gain': 3, 'eq-low-freq': 100, 'eq-high-gain': 4, 'eq-high-freq': 8000 }),
            gain('Gain', -6),
        ],
        tags: ['drums', 'parallel', 'crush', 'impact'],
        author: AUTHOR,
        isFactory: true,
    },
    {
        id: 'factory-mix-master-bus',
        name: 'Master Bus',
        category: 'fx',
        description: 'Gentle master bus processing with glue compression and subtle EQ shaping.',
        trackKind: 'audio',
        devices: [
            eq('EQ', { 'eq-low-gain': 1, 'eq-low-freq': 80, 'eq-high-gain': 1, 'eq-high-freq': 12000 }),
            comp('Compressor', { 'comp-threshold': -10, 'comp-ratio': 2, 'comp-attack': 30, 'comp-release': 200 }),
            gain('Gain', 1),
        ],
        tags: ['master', 'bus', 'mastering', 'glue'],
        author: AUTHOR,
        isFactory: true,
    },

    // ─── New presets using new effects ─────────────────────────────────────
    {
        id: 'factory-synth-chiptune',
        name: 'Chiptune',
        category: 'synth',
        subcategory: 'digital',
        description: '8-bit square wave with bitcrusher for retro gaming sound.',
        trackKind: 'midi',
        devices: [
            synth('Chiptune', {
                waveform: 3,
                attack: 0.001,
                decay: 0.1,
                sustain: 0.8,
                release: 0.05,
                filterCutoff: 8000,
                filterResonance: 0.5,
                filterType: 0,
                detune: 0,
                gain: 0.3,
            }),
            bitcrusher('Bitcrusher', { 'crush-bits': 4, 'crush-mix': 0.8 }),
        ],
        tags: ['chiptune', '8-bit', 'retro', 'gaming'],
        author: AUTHOR,
        isFactory: true,
    },
    {
        id: 'factory-lead-formant',
        name: 'Formant Lead',
        category: 'lead',
        subcategory: 'digital',
        description: 'Vowel-like lead using resonant bandpass filter with auto-pan.',
        trackKind: 'midi',
        devices: [
            synth('Formant Lead', {
                waveform: 2,
                attack: 0.02,
                decay: 0.2,
                sustain: 0.7,
                release: 0.3,
                filterCutoff: 2000,
                filterResonance: 8,
                filterType: 2,
                detune: 0,
                gain: 0.3,
            }),
            autopan('Auto-Pan', { 'autopan-rate': 1, 'autopan-depth': 0.5 }),
        ],
        tags: ['formant', 'vowel', 'resonant', 'autopan'],
        author: AUTHOR,
        isFactory: true,
    },
    {
        id: 'factory-bass-filtered',
        name: 'Filtered Bass',
        category: 'bass',
        subcategory: 'digital',
        description: 'Sawtooth bass with resonant lowpass filter sweep.',
        trackKind: 'midi',
        devices: [
            synth('Filtered Bass', {
                waveform: 2,
                attack: 0.005,
                decay: 0.3,
                sustain: 0.6,
                release: 0.15,
                filterCutoff: 500,
                filterResonance: 4,
                filterType: 0,
                detune: 3,
                gain: 0.35,
            }),
            filter('Filter', { 'filter-cutoff': 600, 'filter-resonance': 6, 'filter-type': 0 }),
        ],
        tags: ['filtered', 'sweep', 'resonant', 'bass'],
        author: AUTHOR,
        isFactory: true,
    },
    {
        id: 'factory-bass-bitcrushed',
        name: 'Bitcrushed Bass',
        category: 'bass',
        subcategory: 'digital',
        description: 'Gritty distorted bass with bit reduction for lo-fi textures.',
        trackKind: 'midi',
        devices: [
            synth('Bitcrushed Bass', {
                waveform: 2,
                attack: 0.005,
                decay: 0.2,
                sustain: 0.7,
                release: 0.1,
                filterCutoff: 1200,
                filterResonance: 2,
                filterType: 0,
                detune: 0,
                gain: 0.35,
            }),
            bitcrusher('Bitcrusher', { 'crush-bits': 6, 'crush-mix': 0.6 }),
            comp('Compressor', { 'comp-threshold': -15, 'comp-ratio': 6, 'comp-attack': 3 }),
        ],
        tags: ['bitcrushed', 'gritty', 'lo-fi', 'bass'],
        author: AUTHOR,
        isFactory: true,
    },
    {
        id: 'factory-lead-glitch',
        name: 'Glitch Lead',
        category: 'lead',
        subcategory: 'digital',
        description: 'Erratic bitcrushed lead with tremolo and delay for glitch textures.',
        trackKind: 'midi',
        devices: [
            synth('Glitch Lead', {
                waveform: 2,
                attack: 0.001,
                decay: 0.08,
                sustain: 0.5,
                release: 0.1,
                filterCutoff: 6000,
                filterResonance: 3,
                filterType: 0,
                detune: 0,
                gain: 0.25,
            }),
            bitcrusher('Bitcrusher', { 'crush-bits': 5, 'crush-mix': 0.5 }),
            tremolo('Tremolo', { 'trem-rate': 8, 'trem-depth': 0.7, 'trem-shape': 1 }),
            delay('Delay', { 'delay-time': 125, 'delay-feedback': 0.4, 'delay-mix': 0.3 }),
        ],
        tags: ['glitch', 'bitcrushed', 'tremolo', 'chaotic'],
        author: AUTHOR,
        isFactory: true,
    },
    {
        id: 'factory-lead-trance',
        name: 'Trance Lead',
        category: 'lead',
        subcategory: 'digital',
        description: 'Classic trance lead with flanger and dotted-note delay.',
        trackKind: 'midi',
        devices: [
            synth('Trance Lead', {
                waveform: 2,
                attack: 0.01,
                decay: 0.2,
                sustain: 0.7,
                release: 0.3,
                filterCutoff: 5000,
                filterResonance: 2,
                filterType: 0,
                detune: 10,
                gain: 0.25,
            }),
            flanger('Flanger', {
                'flanger-rate': 0.5,
                'flanger-depth': 4,
                'flanger-feedback': 0.6,
                'flanger-mix': 0.4,
            }),
            delay('Delay', { 'delay-time': 375, 'delay-feedback': 0.35, 'delay-mix': 0.25 }),
        ],
        tags: ['trance', 'flanger', 'delay', 'uplifting'],
        author: AUTHOR,
        isFactory: true,
    },
    {
        id: 'factory-pad-filtered',
        name: 'Filtered Pad',
        category: 'pad',
        subcategory: 'digital',
        description: 'Evolving pad with resonant filter and tremolo modulation.',
        trackKind: 'midi',
        devices: [
            synth('Filtered Pad', {
                waveform: 2,
                attack: 0.6,
                decay: 0.4,
                sustain: 0.8,
                release: 2.0,
                filterCutoff: 3000,
                filterResonance: 1,
                filterType: 0,
                detune: 5,
                gain: 0.2,
            }),
            filter('Filter', { 'filter-cutoff': 2000, 'filter-resonance': 4, 'filter-type': 0 }),
            tremolo('Tremolo', { 'trem-rate': 0.5, 'trem-depth': 0.3 }),
            reverb('Reverb', { 'rev-size': 0.8, 'rev-decay': 5, 'rev-mix': 0.5 }),
        ],
        tags: ['filtered', 'evolving', 'tremolo', 'pad'],
        author: AUTHOR,
        isFactory: true,
    },
    {
        id: 'factory-strings-tremolo',
        name: 'Tremolo Strings',
        category: 'strings',
        subcategory: 'analog',
        description: 'Classic tremolo string ensemble with gentle vibrato and hall reverb.',
        trackKind: 'midi',
        devices: [
            synth('Tremolo Strings', {
                waveform: 2,
                attack: 0.2,
                decay: 0.3,
                sustain: 0.8,
                release: 1.0,
                filterCutoff: 3000,
                filterResonance: 0.5,
                filterType: 0,
                detune: 6,
                gain: 0.25,
            }),
            tremolo('Tremolo', { 'trem-rate': 6, 'trem-depth': 0.3 }),
            reverb('Reverb', { 'rev-size': 0.8, 'rev-decay': 4, 'rev-mix': 0.4 }),
        ],
        tags: ['strings', 'tremolo', 'classical', 'ensemble'],
        author: AUTHOR,
        isFactory: true,
    },
    {
        id: 'factory-drums-crushed',
        name: 'Crushed Drums',
        category: 'drums',
        description: 'Aggressive bitcrushed drum processing for industrial/noise textures.',
        trackKind: 'audio',
        devices: [
            bitcrusher('Bitcrusher', { 'crush-bits': 6, 'crush-mix': 0.6 }),
            comp('Compressor', { 'comp-threshold': -10, 'comp-ratio': 8, 'comp-attack': 1, 'comp-release': 60 }),
        ],
        tags: ['drums', 'crushed', 'industrial', 'bitcrusher'],
        author: AUTHOR,
        isFactory: true,
    },
    {
        id: 'factory-drums-lofi-beat',
        name: 'Lo-Fi Beat',
        category: 'drums',
        description: 'Vinyl-style lo-fi drum chain with bitcrusher and high-cut filter.',
        trackKind: 'audio',
        devices: [
            bitcrusher('Bitcrusher', { 'crush-bits': 10, 'crush-mix': 0.4 }),
            filter('Filter', { 'filter-cutoff': 4000, 'filter-resonance': 0.5, 'filter-type': 0 }),
            comp('Compressor', { 'comp-threshold': -12, 'comp-ratio': 3, 'comp-attack': 5 }),
        ],
        tags: ['drums', 'lo-fi', 'vinyl', 'chill'],
        author: AUTHOR,
        isFactory: true,
    },
    {
        id: 'factory-drums-tremolo',
        name: 'Tremolo Drums',
        category: 'drums',
        description: 'Rhythmic tremolo on drums for pulsating gate-like effect.',
        trackKind: 'audio',
        devices: [
            comp('Compressor', { 'comp-threshold': -15, 'comp-ratio': 4, 'comp-attack': 3, 'comp-release': 80 }),
            tremolo('Tremolo', { 'trem-rate': 8, 'trem-depth': 0.6, 'trem-shape': 1 }),
        ],
        tags: ['drums', 'tremolo', 'gate', 'rhythmic'],
        author: AUTHOR,
        isFactory: true,
    },
    {
        id: 'factory-fx-telephone',
        name: 'Telephone',
        category: 'fx',
        description: 'Narrow band telephone effect with heavy filtering and compression.',
        trackKind: 'audio',
        devices: [
            filter('HP Filter', { 'filter-cutoff': 300, 'filter-resonance': 0.7, 'filter-type': 1 }),
            filter('LP Filter', { 'filter-cutoff': 3500, 'filter-resonance': 0.7, 'filter-type': 0 }),
            comp('Compressor', { 'comp-threshold': -8, 'comp-ratio': 10, 'comp-attack': 1, 'comp-release': 40 }),
            bitcrusher('Bitcrusher', { 'crush-bits': 10, 'crush-mix': 0.3 }),
        ],
        tags: ['telephone', 'narrows', 'filtered', 'lo-fi'],
        author: AUTHOR,
        isFactory: true,
    },
    {
        id: 'factory-fx-underwater',
        name: 'Underwater',
        category: 'fx',
        description: 'Submerged sound with heavy low-pass filter, chorus, and reverb.',
        trackKind: 'audio',
        devices: [
            filter('LP Filter', { 'filter-cutoff': 600, 'filter-resonance': 2, 'filter-type': 0 }),
            reverb('Reverb', { 'rev-size': 1, 'rev-decay': 6, 'rev-damping': 0.3, 'rev-mix': 0.6 }),
        ],
        tags: ['underwater', 'submerged', 'filtered', 'wet'],
        author: AUTHOR,
        isFactory: true,
    },
    {
        id: 'factory-guitar-flanged',
        name: 'Flanged Guitar',
        category: 'guitar',
        description: 'Classic jet-sweep flanger on guitar with room reverb.',
        trackKind: 'audio',
        devices: [
            flanger('Flanger', {
                'flanger-rate': 0.2,
                'flanger-depth': 5,
                'flanger-feedback': 0.7,
                'flanger-mix': 0.5,
            }),
            reverb('Reverb', { 'rev-size': 0.3, 'rev-decay': 1, 'rev-mix': 0.15 }),
        ],
        tags: ['guitar', 'flanger', 'jet', 'sweep'],
        author: AUTHOR,
        isFactory: true,
    },
    {
        id: 'factory-synth-autopan',
        name: 'Auto-Pan Synth',
        category: 'synth',
        subcategory: 'digital',
        description: 'Wide moving synth pad with auto-pan and lush reverb.',
        trackKind: 'midi',
        devices: [
            synth('Auto-Pan Synth', {
                waveform: 2,
                attack: 0.3,
                decay: 0.3,
                sustain: 0.8,
                release: 1.5,
                filterCutoff: 4000,
                filterResonance: 1,
                filterType: 0,
                detune: 8,
                gain: 0.2,
            }),
            autopan('Auto-Pan', { 'autopan-rate': 0.5, 'autopan-depth': 0.8, 'autopan-shape': 1 }),
            reverb('Reverb', { 'rev-size': 0.7, 'rev-decay': 4, 'rev-mix': 0.4 }),
        ],
        tags: ['autopan', 'wide', 'moving', 'spatial'],
        author: AUTHOR,
        isFactory: true,
    },
];

const DRUM_KIT_PRESETS: SoundPreset[] = [
    {
        id: 'factory-drumkit-808',
        name: '808 Kit',
        category: 'drums',
        subcategory: 'electronic',
        description: 'Classic 808-style drum kit with deep kick, snappy snare, and crisp hats',
        trackKind: 'midi',
        devices: [
            { type: 'drum-kit', name: '808 Kit', parameterValues: { kitId: 0 } },
            comp('Drum Comp', { 'comp-threshold': -15, 'comp-ratio': 4, 'comp-attack': 1, 'comp-release': 80 }),
        ],
        tags: ['808', 'trap', 'hip-hop', 'electronic', 'drum-kit'],
        author: AUTHOR,
        isFactory: true,
    },
    {
        id: 'factory-drumkit-analog',
        name: 'Analog Kit',
        category: 'drums',
        subcategory: 'analog',
        description: 'Warm analog-style drum kit with round kick and soft hats',
        trackKind: 'midi',
        devices: [
            { type: 'drum-kit', name: 'Analog Kit', parameterValues: { kitId: 1 } },
            eq('Drum EQ', { 'eq-low-gain': 3, 'eq-low-freq': 80, 'eq-high-gain': 2, 'eq-high-freq': 10000 }),
        ],
        tags: ['analog', 'vintage', 'warm', 'drum-kit'],
        author: AUTHOR,
        isFactory: true,
    },
    {
        id: 'factory-drumkit-electronic',
        name: 'Electronic Kit',
        category: 'drums',
        subcategory: 'electronic',
        description: 'Aggressive electronic drum kit with high resonance and punchy transients',
        trackKind: 'midi',
        devices: [
            { type: 'drum-kit', name: 'Electronic Kit', parameterValues: { kitId: 2 } },
            comp('Punch Comp', { 'comp-threshold': -10, 'comp-ratio': 6, 'comp-attack': 0.5, 'comp-release': 60 }),
            eq('Presence EQ', { 'eq-mid-gain': 3, 'eq-mid-freq': 3000, 'eq-high-gain': 4, 'eq-high-freq': 8000 }),
        ],
        tags: ['electronic', 'edm', 'aggressive', 'drum-kit'],
        author: AUTHOR,
        isFactory: true,
    },
    {
        id: 'factory-drumkit-acoustic',
        name: 'Acoustic Kit',
        category: 'drums',
        subcategory: 'acoustic',
        description: 'Natural-sounding synthesized acoustic drum kit with room character',
        trackKind: 'midi',
        devices: [
            { type: 'drum-kit', name: 'Acoustic Kit', parameterValues: { kitId: 3 } },
            reverb('Room', { 'rev-size': 0.3, 'rev-decay': 1.2, 'rev-mix': 0.15 }),
            eq('Natural EQ', { 'eq-low-gain': 2, 'eq-low-freq': 100, 'eq-mid-gain': -1, 'eq-mid-freq': 500 }),
        ],
        tags: ['acoustic', 'natural', 'room', 'drum-kit'],
        author: AUTHOR,
        isFactory: true,
    },
];
export { FACTORY_PRESETS, DRUM_KIT_PRESETS };
