/**
 * Fermenter factory presets — curated starting points for the master synth.
 */

import { type SoundPreset, type DevicePreset } from '#/modules/Arrangement/models/SoundPreset';
import { type FermenterPatch, DEFAULT_PATCH } from '../models/FermenterPatch';

const AUTHOR = 'Sourdaw';

function fermenterDevice(name: string, overrides: Partial<FermenterPatch> = {}): DevicePreset {
    const patch = { ...DEFAULT_PATCH, ...overrides, name };
    const parameterValues: Record<string, number> = {};
    for (const [key, value] of Object.entries(patch)) {
        if (key === 'version' || key === 'name') continue;
        if (key === 'macros') {
            const macros = value as number[];
            macros.forEach((v, i) => { parameterValues[`macro${i}`] = v; });
        } else {
            parameterValues[key] = value as number;
        }
    }
    return { type: 'fermenter', name, parameterValues };
}

export const FERMENTER_PRESETS: SoundPreset[] = [
    {
        id: 'fermenter-init',
        name: 'Fermenter — Init',
        category: 'synth',
        subcategory: 'fermenter',
        description: 'Clean starting point — sawtooth through low-pass filter with gentle reverb',
        trackKind: 'midi',
        devices: [fermenterDevice('Fermenter Init')],
        tags: ['fermenter', 'init', 'default', 'clean'],
        author: AUTHOR,
        isFactory: true,
    },
    {
        id: 'fermenter-warm-pad',
        name: 'Fermenter — Warm Pad',
        category: 'pad',
        subcategory: 'fermenter',
        description: 'Slow-attack filtered pad with lush reverb — great for ambient textures',
        trackKind: 'midi',
        devices: [fermenterDevice('Warm Pad', {
            oscWaveform: 1,
            oscLevel: 0.7,
            unisonVoices: 4,
            unisonDetune: 25,
            unisonSpread: 0.9,
            filterCutoff: 2000,
            filterResonance: 1.5,
            ampAttack: 0.8,
            ampDecay: 0.5,
            ampSustain: 0.9,
            ampRelease: 2.0,
            filterAttack: 1.0,
            filterDecay: 0.8,
            filterSustain: 0.3,
            filterRelease: 1.5,
            filterEnvAmount: 0.6,
            reverbMix: 0.55,
            reverbDecay: 0.8,
            lfoRate: 0.3,
            lfoPitchAmount: 0.02,
            chorusMix: 0.3,
            chorusDepth: 0.5,
        })],
        tags: ['fermenter', 'pad', 'warm', 'ambient', 'lush', 'unison'],
        author: AUTHOR,
        isFactory: true,
    },
    {
        id: 'fermenter-acid-bass',
        name: 'Fermenter — Acid Bass',
        category: 'bass',
        subcategory: 'fermenter',
        description: 'Resonant squelchy bass — classic acid house character',
        trackKind: 'midi',
        devices: [fermenterDevice('Acid Bass', {
            oscEngine: 1, // VA for that analog character
            oscWaveform: 2,
            oscLevel: 0.9,
            filterCutoff: 600,
            filterResonance: 8.0,
            filterDrive: 3.0,
            filterMode: 0,
            ampAttack: 0.005,
            ampDecay: 0.15,
            ampSustain: 0.0,
            ampRelease: 0.08,
            filterAttack: 0.005,
            filterDecay: 0.2,
            filterSustain: 0.0,
            filterRelease: 0.1,
            filterEnvAmount: 0.9,
            reverbMix: 0.05,
            portamentoTime: 0.05,
            portamentoMode: 1,
        })],
        tags: ['fermenter', 'bass', 'acid', '303', 'squelch', 'analog'],
        author: AUTHOR,
        isFactory: true,
    },
    {
        id: 'fermenter-pluck-lead',
        name: 'Fermenter — Pluck Lead',
        category: 'lead',
        subcategory: 'fermenter',
        description: 'Snappy pluck with filter envelope — cuts through any mix',
        trackKind: 'midi',
        devices: [fermenterDevice('Pluck Lead', {
            oscWaveform: 1,
            oscLevel: 0.85,
            filterCutoff: 3000,
            filterResonance: 2.0,
            ampAttack: 0.003,
            ampDecay: 0.25,
            ampSustain: 0.3,
            ampRelease: 0.2,
            filterAttack: 0.001,
            filterDecay: 0.15,
            filterSustain: 0.1,
            filterRelease: 0.15,
            filterEnvAmount: 0.7,
            reverbMix: 0.25,
            reverbDecay: 0.4,
            delayMix: 0.2,
            delayTime: 250,
            delayFeedback: 0.3,
        })],
        tags: ['fermenter', 'lead', 'pluck', 'sharp'],
        author: AUTHOR,
        isFactory: true,
    },
    {
        id: 'fermenter-sub-bass',
        name: 'Fermenter — Sub Bass',
        category: 'bass',
        subcategory: 'fermenter',
        description: 'Pure sine sub with tight envelope — solid low end foundation',
        trackKind: 'midi',
        devices: [fermenterDevice('Sub Bass', {
            oscWaveform: 0,
            oscLevel: 1.0,
            filterCutoff: 500,
            filterResonance: 0.7,
            ampAttack: 0.005,
            ampDecay: 0.8,
            ampSustain: 0.0,
            ampRelease: 0.15,
            filterEnvAmount: 0.0,
            reverbMix: 0.0,
        })],
        tags: ['fermenter', 'bass', 'sub', 'deep', '808'],
        author: AUTHOR,
        isFactory: true,
    },
    {
        id: 'fermenter-glass-keys',
        name: 'Fermenter — Glass Keys',
        category: 'keys',
        subcategory: 'fermenter',
        description: 'Crystalline tone with bright attack and shimmering reverb',
        trackKind: 'midi',
        devices: [fermenterDevice('Glass Keys', {
            oscWaveform: 3,
            oscLevel: 0.75,
            filterCutoff: 8000,
            filterResonance: 1.2,
            ampAttack: 0.002,
            ampDecay: 0.6,
            ampSustain: 0.2,
            ampRelease: 0.8,
            filterAttack: 0.001,
            filterDecay: 0.4,
            filterSustain: 0.1,
            filterRelease: 0.6,
            filterEnvAmount: 0.3,
            reverbMix: 0.4,
            reverbDecay: 0.65,
            chorusMix: 0.15,
        })],
        tags: ['fermenter', 'keys', 'glass', 'crystal', 'bell'],
        author: AUTHOR,
        isFactory: true,
    },
    {
        id: 'fermenter-dark-drone',
        name: 'Fermenter — Dark Drone',
        category: 'pad',
        subcategory: 'fermenter',
        description: 'Low rumbling drone with slow LFO movement — cinematic atmosphere',
        trackKind: 'midi',
        devices: [fermenterDevice('Dark Drone', {
            oscWaveform: 1,
            oscLevel: 0.6,
            unisonVoices: 6,
            unisonDetune: 40,
            unisonSpread: 1.0,
            noiseLevel: 0.08,
            noiseColor: 2, // brown
            filterCutoff: 800,
            filterResonance: 3.0,
            filterDrive: 1.5,
            filterMode: 0,
            ampAttack: 2.0,
            ampDecay: 1.0,
            ampSustain: 1.0,
            ampRelease: 3.0,
            filterAttack: 3.0,
            filterDecay: 2.0,
            filterSustain: 0.5,
            filterRelease: 2.0,
            filterEnvAmount: 0.3,
            lfoRate: 0.1,
            lfoPitchAmount: 0.05,
            lfoFilterAmount: 0.3,
            reverbMix: 0.7,
            reverbDecay: 0.9,
        })],
        tags: ['fermenter', 'pad', 'drone', 'dark', 'cinematic', 'ambient'],
        author: AUTHOR,
        isFactory: true,
    },
    {
        id: 'fermenter-bright-lead',
        name: 'Fermenter — Bright Lead',
        category: 'lead',
        subcategory: 'fermenter',
        description: 'Aggressive square lead with high resonance — stands out in dense mixes',
        trackKind: 'midi',
        devices: [fermenterDevice('Bright Lead', {
            oscEngine: 1, // VA
            oscWaveform: 2,
            oscLevel: 0.8,
            filterCutoff: 6000,
            filterResonance: 4.0,
            filterDrive: 2.0,
            ampAttack: 0.01,
            ampDecay: 0.3,
            ampSustain: 0.8,
            ampRelease: 0.15,
            filterAttack: 0.01,
            filterDecay: 0.2,
            filterSustain: 0.6,
            filterRelease: 0.1,
            filterEnvAmount: 0.4,
            reverbMix: 0.15,
            reverbDecay: 0.3,
            portamentoTime: 0.03,
        })],
        tags: ['fermenter', 'lead', 'bright', 'aggressive', 'analog'],
        author: AUTHOR,
        isFactory: true,
    },
    {
        id: 'fermenter-supersaw',
        name: 'Fermenter — Supersaw',
        category: 'synth',
        subcategory: 'fermenter',
        description: 'Thick detuned supersaw — the quintessential trance/EDM sound',
        trackKind: 'midi',
        devices: [fermenterDevice('Supersaw', {
            oscWaveform: 1,
            oscLevel: 0.75,
            unisonVoices: 8,
            unisonDetune: 30,
            unisonSpread: 0.85,
            filterCutoff: 4000,
            filterResonance: 1.2,
            ampAttack: 0.01,
            ampDecay: 0.5,
            ampSustain: 0.6,
            ampRelease: 0.4,
            filterAttack: 0.01,
            filterDecay: 0.3,
            filterSustain: 0.4,
            filterRelease: 0.3,
            filterEnvAmount: 0.5,
            reverbMix: 0.3,
            reverbDecay: 0.6,
            chorusMix: 0.1,
        })],
        tags: ['fermenter', 'synth', 'supersaw', 'trance', 'edm', 'unison'],
        author: AUTHOR,
        isFactory: true,
    },
    {
        id: 'fermenter-analog-brass',
        name: 'Fermenter — Analog Brass',
        category: 'synth',
        subcategory: 'fermenter',
        description: 'Fat brass stab with filter punch — retro synth brass',
        trackKind: 'midi',
        devices: [fermenterDevice('Analog Brass', {
            oscEngine: 1, // VA
            oscWaveform: 1,
            oscLevel: 0.85,
            unisonVoices: 3,
            unisonDetune: 12,
            unisonSpread: 0.5,
            filterCutoff: 800,
            filterResonance: 2.5,
            filterDrive: 1.0,
            ampAttack: 0.05,
            ampDecay: 0.3,
            ampSustain: 0.6,
            ampRelease: 0.2,
            filterAttack: 0.02,
            filterDecay: 0.25,
            filterSustain: 0.3,
            filterRelease: 0.15,
            filterEnvAmount: 0.8,
            reverbMix: 0.15,
        })],
        tags: ['fermenter', 'synth', 'brass', 'analog', 'stab'],
        author: AUTHOR,
        isFactory: true,
    },
    {
        id: 'fermenter-ethereal-pad',
        name: 'Fermenter — Ethereal Pad',
        category: 'pad',
        subcategory: 'fermenter',
        description: 'Dreamy high-pass filtered pad with chorus and long reverb',
        trackKind: 'midi',
        devices: [fermenterDevice('Ethereal Pad', {
            oscWaveform: 3, // triangle
            oscLevel: 0.6,
            unisonVoices: 5,
            unisonDetune: 20,
            unisonSpread: 1.0,
            noiseLevel: 0.04,
            filterMode: 1, // HP
            filterCutoff: 300,
            filterResonance: 1.5,
            ampAttack: 1.5,
            ampDecay: 0.5,
            ampSustain: 0.8,
            ampRelease: 3.0,
            filterAttack: 2.0,
            filterDecay: 1.0,
            filterSustain: 0.4,
            filterRelease: 2.0,
            filterEnvAmount: -0.3,
            lfoRate: 0.2,
            lfoFilterAmount: 0.2,
            reverbMix: 0.65,
            reverbDecay: 0.85,
            chorusMix: 0.35,
            chorusDepth: 0.6,
            chorusRate: 0.8,
        })],
        tags: ['fermenter', 'pad', 'ethereal', 'dreamy', 'ambient'],
        author: AUTHOR,
        isFactory: true,
    },
    {
        id: 'fermenter-dirty-bass',
        name: 'Fermenter — Dirty Bass',
        category: 'bass',
        subcategory: 'fermenter',
        description: 'Overdriven bass with noise grit — for aggressive productions',
        trackKind: 'midi',
        devices: [fermenterDevice('Dirty Bass', {
            oscEngine: 1,
            oscWaveform: 2,
            oscLevel: 0.9,
            noiseLevel: 0.1,
            noiseColor: 0, // white
            filterCutoff: 1200,
            filterResonance: 3.0,
            filterDrive: 5.0,
            ampAttack: 0.003,
            ampDecay: 0.3,
            ampSustain: 0.4,
            ampRelease: 0.1,
            filterAttack: 0.003,
            filterDecay: 0.15,
            filterSustain: 0.2,
            filterRelease: 0.1,
            filterEnvAmount: 0.7,
            reverbMix: 0.05,
        })],
        tags: ['fermenter', 'bass', 'dirty', 'distorted', 'aggressive'],
        author: AUTHOR,
        isFactory: true,
    },
];
