#!/usr/bin/env node

import { writeFileSync, existsSync, mkdirSync } from 'fs';
import { join } from 'path';
import { spawnSync } from 'child_process';
import { getRepoRoot } from './git.ts';
import { red, cyan, bold, dim, green, yellow } from './colors.ts';

function run() {
    let repoRoot;
    try {
        repoRoot = getRepoRoot();
    } catch (e) {
        console.error(red('Error: Not inside a git repository.'));
        process.exit(1);
    }

    console.log(cyan(`\nOrchestrating Automated Release...\n`));

    // Get the last tag
    const tagRes = spawnSync('git', ['describe', '--tags', '--abbrev=0'], { cwd: repoRoot, encoding: 'utf8' });
    const lastTag = tagRes.status === 0 ? tagRes.stdout.trim() : null;

    let logArgs = ['log', '--pretty=format:%h - %s'];
    if (lastTag) {
        console.log(dim(`Found previous tag: ${lastTag}`));
        logArgs.push(`${lastTag}..HEAD`);
    } else {
        console.log(dim(`No previous tags found. Generating from beginning of history.`));
    }

    const logRes = spawnSync('git', logArgs, { cwd: repoRoot, encoding: 'utf8' });
    if (logRes.status !== 0) {
        console.error(red(`Failed to read git log.`));
        process.exit(1);
    }

    const commits = logRes.stdout.trim().split('\n').filter(Boolean);
    if (commits.length === 0) {
        console.log(yellow(`No new commits since ${lastTag}. Nothing to release.`));
        process.exit(0);
    }

    console.log(green(`✓ Analyzed ${commits.length} commits.`));

    const releaseDir = join(repoRoot, '.agents', 'releases');
    if (!existsSync(releaseDir)) mkdirSync(releaseDir, { recursive: true });

    // Determine version bump heuristically
    let bump = 'patch';
    if (commits.some(c => c.toLowerCase().includes('breaking') || c.toLowerCase().includes('major'))) {
        bump = 'major';
    } else if (commits.some(c => c.toLowerCase().includes('feat:') || c.toLowerCase().includes('feature'))) {
        bump = 'minor';
    }

    // Mock calculating the new version
    let currentVer = lastTag ? lastTag.replace('v', '') : '0.0.0';
    const parts = currentVer.split('.').map(Number);
    if (bump === 'major') { parts[0]++; parts[1] = 0; parts[2] = 0; }
    else if (bump === 'minor') { parts[1]++; parts[2] = 0; }
    else { parts[2]++; }
    const nextVer = `v${parts.join('.')}`;

    const releaseNotes = `# Release Notes: ${nextVer}

## Summary
Auto-generated release based on ${commits.length} commits since ${lastTag || 'initial commit'}.
Type of bump: **${bump.toUpperCase()}**

## Changelog

${commits.map(c => `- ${c}`).join('\n')}

---
*Generated by Swarm Evolution V5 Release Orchestrator*
`;

    const notePath = join(releaseDir, `release-${nextVer}.md`);
    writeFileSync(notePath, releaseNotes, 'utf8');

    console.log(green(`\n✓ Release drafted: `) + dim(notePath));
    console.log(yellow(`\nReview the draft notes. If approved, run:`));
    console.log(dim(`git tag ${nextVer}`));
    console.log(dim(`git push origin ${nextVer}`));
    console.log('');
}

if (import.meta.url === `file://${process.argv[1]}`) {
    run();
}
