export const FERMENTER_DSP_PARAM_OVERRIDES: Record<string, string> = {
    filterCutoff: 'cutoff',
    filterResonance: 'resonance',
    filterEnvAmount: 'mod_env_to_filter',
    lfoPitchAmount: 'mod_lfo_to_pitch',
    oscDrift: 'drift',
    oscEngine: 'engine',
    portamentoTime: 'portamento',
};

export const FERMENTER_DSP_PARAM_IDS = [
    'active_layer',
    'additive_inharm',
    'additive_odd',
    'additive_partials',
    'additive_tilt',
    'amp_attack',
    'amp_decay',
    'amp_release',
    'amp_sustain',
    'audio_mod_depth',
    'audio_mod_rate',
    'audio_mod_target',
    'chaos_amount',
    'chaos_speed',
    'chorus_depth',
    'chorus_mix',
    'chorus_rate',
    'comp_attack',
    'comp_mix',
    'comp_ratio',
    'comp_release',
    'comp_threshold',
    'cutoff',
    'delay_feedback',
    'delay_mix',
    'delay_time',
    'dist_drive',
    'dist_mix',
    'dist_tone',
    'drift',
    'engine',
    'eq_high_freq',
    'eq_high_gain',
    'eq_high_q',
    'eq_low_freq',
    'eq_low_gain',
    'eq_low_q',
    'eq_mid_freq',
    'eq_mid_gain',
    'eq_mid_q',
    'filter_drive',
    'filter_attack',
    'filter_decay',
    'filter_keytrack',
    'filter_mode',
    'filter_model',
    'filter_release',
    'filter_sustain',
    'fm_algorithm',
    'fm_feedback',
    'fm_level1',
    'fm_level2',
    'fm_level3',
    'fm_level4',
    'fm_mod_amount',
    'fm_ratio1',
    'fm_ratio2',
    'fm_ratio3',
    'fm_ratio4',
    'grain_density',
    'grain_pan_spread',
    'grain_pitch_var',
    'grain_position',
    'grain_size',
    'grain_spray',
    'ks_brightness',
    'ks_damping',
    'layer_level',
    'layer_pan',
    'lfo_filter_amount',
    'lfo_rate',
    'lfo_shape',
    'master_gain',
    'mod_env_to_filter',
    'mod_lfo_to_pitch',
    'mseg_to_filter',
    'noise_color',
    'noise_level',
    'num_layers',
    'osc_coarse',
    'osc_fine',
    'osc_level',
    'osc_waveform',
    'phaser_depth',
    'phaser_mix',
    'phaser_rate',
    'portamento',
    'portamento_mode',
    'pulse_width',
    'resonance',
    'reverb_decay',
    'reverb_mix',
    'reverb_type',
    'sampler_end',
    'sampler_mode',
    'sampler_start',
    'seq_rate',
    'seq_to_pitch',
    'stereo_width',
    'unison_detune',
    'unison_spread',
    'unison_voices',
    'voice_drive',
    'warp_amount',
    'warp_mode',
] as const;
