import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';

import { describe, expect, it } from 'vitest';

import { evidenceManifestSource } from '../../../scripts/agent-campaign/evidenceContract';
import { validateEvidenceManifest } from '../../../scripts/agent-campaign/evidenceManifest';
import { generateEvidenceManifest } from '../../../scripts/agent-campaign/generateEvidenceManifest';

const manifestPath = resolve(process.cwd(), 'evidence/agent-campaign/manifest.json');
const manifestSource = readFileSync(manifestPath, 'utf8');
type Manifest = typeof evidenceManifestSource;
type Mutation = (draft: Manifest) => void;

function mutate(apply: Mutation): string {
    const draft = structuredClone(evidenceManifestSource);
    apply(draft);
    return `${JSON.stringify(draft)}\n`;
}

const failures: ReadonlyArray<readonly [string, Mutation]> = [
    ['unknown root', (draft) => Object.assign(draft, { unknown: true })],
    ['gate omission', (draft) => draft.inventories.gates.entries.shift()],
    ['result omission', (draft) => draft.inventories.results.entries.shift()],
    ['result pairing', (draft) => (draft.inventories.results.entries[0]!.gateOrSuiteId = 'AC-002')],
    ['redaction omission', (draft) => draft.redaction.patternsScanned.pop()],
    ['redaction type', (draft) => Object.assign(draft.redaction, { retentionDurationDays: '30' })],
    ['capability authority', (draft) => (draft.capabilities[0]!.ownerTask = '')],
    ['provider promotion', (draft) => (draft.capabilities[3]!.status = 'admitted')],
    ['provider route confusion', (draft) => (draft.capabilities[3]!.platform = 'browser')],
    ['environment range', (draft) => (draft.environment.displayRefreshHz = 0)],
    ['model digest', (draft) => Object.assign(draft.environment, { modelArtifacts: [{ id: 'model', sha256: 'bad' }] })],
    ['threshold binding', (draft) => draft.inventories.gates.entries[53]!.thresholds.pop()],
    ['reversion threshold', (draft) => (draft.thresholds.reversionDetection![0] = 'minimum')],
    ['stale threshold', (draft) => (draft.thresholds.staleRevisionDetection![0] = 'minimum')],
    ['lock threshold', (draft) => (draft.thresholds.lockDetection![0] = 'minimum')],
    ['conflict threshold', (draft) => (draft.thresholds.conflictDetection![0] = 'minimum')],
];

describe('agent campaign evidence manifest', () => {
    it('is generated byte-for-byte with complete frozen gate and result rows', () => {
        expect(generateEvidenceManifest()).toBe(manifestSource);
        expect(validateEvidenceManifest(manifestSource)).toEqual([]);
        expect(evidenceManifestSource.inventories.gates.entries).toHaveLength(75);
        expect(evidenceManifestSource.inventories.results.entries).toHaveLength(88);
        expect(evidenceManifestSource.capabilities[3]).toMatchObject({
            id: 'openai-tauri',
            status: 'unsupported',
            platform: 'tauri',
            transport: 'rust-https',
        });
        expect(evidenceManifestSource.thresholds).toMatchObject({
            conflictDetection: ['exact', 1],
            lockDetection: ['exact', 1],
            reversionDetection: ['exact', 1],
            staleRevisionDetection: ['exact', 1],
        });
    });

    it.each(failures)('fails closed on %s', (_name, apply) => {
        expect(validateEvidenceManifest(mutate(apply))).toEqual(['manifest differs from the frozen evidence contract']);
    });
});
