[package]
name = "daw-engine"
version = "0.1.0"
edition = "2021"
description = "Real-time thread, lock-free communication, and graph processing."

[lib]
crate-type = ["rlib"]

[dependencies]
rtrb = "0.3"
cpal = { version = "0.18", features = [] }
daw-dsp = { version = "0.1.0", path = "../daw-dsp" }
triple_buffer = "9.0.0"
