import { buildDevice } from './buildDevice';

import type { Track } from '#/modules/Arrangement/stores';
import type { DeviceSpec } from './buildDevice';

type MasterPreset = 'pop' | 'hiphop' | 'edm' | 'rock' | 'lofi' | 'cinematic' | 'podcast' | 'songwriter' | 'ambient';

const MASTER_CHAIN_PRESETS: Record<MasterPreset, DeviceSpec[]> = {
    pop: [
        {
            type: 'builtin-eq',
            name: 'Master EQ',
            params: {
                'eq-low-gain': 1.5,
                'eq-low-freq': 80,
                'eq-low-q': 0.8,
                'eq-mid-gain': 0.5,
                'eq-mid-freq': 2500,
                'eq-mid-q': 1.0,
                'eq-high-gain': 2.0,
                'eq-high-freq': 12000,
                'eq-high-q': 0.7,
            },
        },
        {
            type: 'gluten',
            name: 'Glue Bus Comp',
            params: {
                topology: 3,
                amount: 45,
                threshold: -14,
                ratio: 2,
                attack: 30,
                release: 180,
                knee: 6,
                makeup: 0,
                mix: 1,
                autoMakeup: 1,
                autoRelease: 1,
            },
        },
        { type: 'proof', name: 'Proof Mastering', params: { input_gain: 0, output_gain: 0, lim_ceiling: -1 } },
        { type: 'builtin-lufs-meter', name: 'LUFS', params: { 'lufs-target': -10 } },
    ],
    hiphop: [
        {
            type: 'builtin-eq',
            name: 'Master EQ',
            params: {
                'eq-low-gain': 2.5,
                'eq-low-freq': 60,
                'eq-low-q': 0.8,
                'eq-mid-gain': -1.0,
                'eq-mid-freq': 500,
                'eq-mid-q': 1.2,
                'eq-high-gain': 1.5,
                'eq-high-freq': 10000,
                'eq-high-q': 0.7,
            },
        },
        {
            type: 'gluten',
            name: 'Trap Glue',
            params: {
                topology: 3,
                amount: 60,
                threshold: -12,
                ratio: 3,
                attack: 20,
                release: 150,
                knee: 6,
                makeup: 0,
                mix: 1,
                autoMakeup: 1,
                autoRelease: 1,
            },
        },
        { type: 'proof', name: 'Proof Mastering', params: { input_gain: 1, output_gain: 0, lim_ceiling: -0.8 } },
        { type: 'builtin-lufs-meter', name: 'LUFS', params: { 'lufs-target': -8 } },
    ],
    edm: [
        {
            type: 'builtin-eq',
            name: 'Master EQ',
            params: {
                'eq-low-gain': 2.0,
                'eq-low-freq': 70,
                'eq-low-q': 0.8,
                'eq-mid-gain': -1.5,
                'eq-mid-freq': 400,
                'eq-mid-q': 1.4,
                'eq-high-gain': 3.0,
                'eq-high-freq': 12000,
                'eq-high-q': 0.7,
            },
        },
        {
            type: 'gluten',
            name: 'EDM Glue',
            params: {
                topology: 3,
                amount: 70,
                threshold: -10,
                ratio: 4,
                attack: 10,
                release: 120,
                knee: 4,
                makeup: 0,
                mix: 1,
                autoMakeup: 1,
                autoRelease: 1,
            },
        },
        {
            type: 'builtin-limiter',
            name: 'Brickwall',
            params: { threshold: -0.3, release: 100, ceiling: -0.3 },
        },
        { type: 'proof', name: 'Proof Mastering', params: { input_gain: 0, output_gain: 0, lim_ceiling: -0.3 } },
        { type: 'builtin-lufs-meter', name: 'LUFS', params: { 'lufs-target': -6 } },
    ],
    rock: [
        {
            type: 'builtin-eq',
            name: 'Master EQ',
            params: {
                'eq-low-gain': 1.8,
                'eq-low-freq': 90,
                'eq-low-q': 0.8,
                'eq-mid-gain': 1.0,
                'eq-mid-freq': 2500,
                'eq-mid-q': 1.0,
                'eq-high-gain': 1.5,
                'eq-high-freq': 10000,
                'eq-high-q': 0.7,
            },
        },
        { type: 'bacteria', name: 'Multiband', params: {} },
        {
            type: 'gluten',
            name: 'Glue Bus Comp',
            params: {
                topology: 3,
                amount: 50,
                threshold: -14,
                ratio: 2.5,
                attack: 25,
                release: 180,
                knee: 6,
                makeup: 0,
                mix: 1,
                autoMakeup: 1,
                autoRelease: 1,
            },
        },
        { type: 'builtin-limiter', name: 'Brickwall', params: { threshold: -0.5, release: 100, ceiling: -0.5 } },
        { type: 'proof', name: 'Proof Mastering', params: { input_gain: 0, output_gain: 0, lim_ceiling: -0.5 } },
        { type: 'builtin-lufs-meter', name: 'LUFS', params: { 'lufs-target': -9 } },
    ],
    lofi: [
        {
            type: 'builtin-eq',
            name: 'Lo-fi EQ',
            params: {
                'eq-low-gain': 2.0,
                'eq-low-freq': 120,
                'eq-low-q': 0.7,
                'eq-mid-gain': -3.0,
                'eq-mid-freq': 3500,
                'eq-mid-q': 1.0,
                'eq-high-gain': -2.0,
                'eq-high-freq': 9000,
                'eq-high-q': 0.7,
            },
        },
        {
            type: 'builtin-bitcrusher',
            name: 'Subtle Crush',
            params: { 'bitcrusher-bits': 12, 'bitcrusher-rate': 0.8, 'bitcrusher-mix': 0.15 },
        },
        {
            type: 'gluten',
            name: 'Warm Glue',
            params: {
                topology: 2,
                amount: 40,
                threshold: -16,
                ratio: 2,
                attack: 40,
                release: 250,
                knee: 10,
                makeup: 0,
                mix: 1,
                autoMakeup: 1,
                autoRelease: 1,
            },
        },
        { type: 'proof', name: 'Proof Warm', params: { input_gain: 0, output_gain: 0, lim_ceiling: -1.5 } },
        { type: 'builtin-lufs-meter', name: 'LUFS', params: { 'lufs-target': -14 } },
    ],
    cinematic: [
        {
            type: 'builtin-eq',
            name: 'Cinema EQ',
            params: {
                'eq-low-gain': 1.0,
                'eq-low-freq': 60,
                'eq-low-q': 0.8,
                'eq-mid-gain': -0.5,
                'eq-mid-freq': 800,
                'eq-mid-q': 1.2,
                'eq-high-gain': 2.0,
                'eq-high-freq': 12000,
                'eq-high-q': 0.6,
            },
        },
        {
            type: 'gluten',
            name: 'Orch Glue',
            params: {
                topology: 1,
                amount: 30,
                threshold: -18,
                ratio: 1.5,
                attack: 50,
                release: 250,
                knee: 10,
                makeup: 0,
                mix: 1,
                autoMakeup: 1,
                autoRelease: 1,
            },
        },
        { type: 'proof', name: 'Proof Mastering', params: { input_gain: 0, output_gain: 0, lim_ceiling: -1.5 } },
        { type: 'builtin-lufs-meter', name: 'LUFS', params: { 'lufs-target': -18 } },
    ],
    podcast: [
        {
            type: 'builtin-eq',
            name: 'Broadcast EQ',
            params: {
                'eq-low-gain': -2.0,
                'eq-low-freq': 80,
                'eq-low-q': 0.8,
                'eq-mid-gain': 2.0,
                'eq-mid-freq': 3000,
                'eq-mid-q': 1.0,
                'eq-high-gain': 1.5,
                'eq-high-freq': 10000,
                'eq-high-q': 0.7,
            },
        },
        {
            type: 'gluten',
            name: 'Voice Glue',
            params: {
                topology: 3,
                amount: 35,
                threshold: -18,
                ratio: 2,
                attack: 20,
                release: 150,
                knee: 6,
                makeup: 0,
                mix: 1,
                autoMakeup: 1,
                autoRelease: 1,
            },
        },
        { type: 'builtin-limiter', name: 'Broadcast Limit', params: { 'lim-threshold': -2, 'lim-release': 100 } },
        { type: 'builtin-lufs-meter', name: 'LUFS', params: { 'lufs-target': -16 } },
    ],
    songwriter: [
        {
            type: 'builtin-eq',
            name: 'Master EQ',
            params: {
                'eq-low-gain': 1.0,
                'eq-low-freq': 100,
                'eq-low-q': 0.8,
                'eq-mid-gain': 0.5,
                'eq-mid-freq': 2000,
                'eq-mid-q': 1.0,
                'eq-high-gain': 1.5,
                'eq-high-freq': 12000,
                'eq-high-q': 0.7,
            },
        },
        {
            type: 'gluten',
            name: 'Gentle Glue',
            params: {
                topology: 1,
                amount: 35,
                threshold: -16,
                ratio: 2,
                attack: 30,
                release: 200,
                knee: 8,
                makeup: 0,
                mix: 1,
                autoMakeup: 1,
                autoRelease: 1,
            },
        },
        { type: 'proof', name: 'Proof Warm', params: { input_gain: 0, output_gain: 0, lim_ceiling: -1 } },
        { type: 'builtin-lufs-meter', name: 'LUFS', params: { 'lufs-target': -14 } },
    ],
    ambient: [
        {
            type: 'builtin-eq',
            name: 'Master EQ',
            params: {
                'eq-low-gain': 0.5,
                'eq-low-freq': 80,
                'eq-low-q': 0.8,
                'eq-mid-gain': -0.5,
                'eq-mid-freq': 600,
                'eq-mid-q': 1.0,
                'eq-high-gain': 2.5,
                'eq-high-freq': 12000,
                'eq-high-q': 0.6,
            },
        },
        {
            type: 'gluten',
            name: 'Soft Glue',
            params: {
                topology: 1,
                amount: 25,
                threshold: -20,
                ratio: 1.5,
                attack: 60,
                release: 300,
                knee: 12,
                makeup: 0,
                mix: 1,
                autoMakeup: 1,
                autoRelease: 1,
            },
        },
        { type: 'proof', name: 'Proof Mastering', params: { input_gain: 0, output_gain: 0, lim_ceiling: -2 } },
        { type: 'builtin-lufs-meter', name: 'LUFS', params: { 'lufs-target': -18 } },
    ],
};

export function setMasterChain(masterTrack: Track, preset: MasterPreset): void {
    const chain = MASTER_CHAIN_PRESETS[preset];
    masterTrack.devices = chain.map(buildDevice);
}
